### ISSUE TITLE
Health Point Reduction

### ISSUE THREAD

**Issue by Drustos** [WarEmu/WarBugs#1007]
While playing as Marauder, sudden health point reduction upon reaching level 14

(HP at 820 max, Wounds at 82)

![grun](https://cloud.githubusercontent.com/assets/13449012/8821917/41943842-302f-11e5-9392-684fb2ddd822.png)

UPDATE: Reaching the next rank seems to have fixed the issue

(HP at 2290 max, wounds at 229)

![moargrun](https://cloud.githubusercontent.com/assets/13449012/8823963/44fe364e-303f-11e5-8884-9bf071bdbb5a.png)

**Comment by Silentguard** [comment]
This is known (or maybe not) bug, happens with mara on some mid levels but you'll be fine after 17 level.

**Comment by ozarmidrashim** [comment]
Fixed

**Comment by xyeppp** [comment]
Still happening despite the fix :^ )

**Comment by Evildoor** [comment]
I'm reopening this issue since people report similar bugs:
https://github.com/WarEmu/WarBugs/issues/1272
https://github.com/WarEmu/WarBugs/issues/1285
https://github.com/WarEmu/WarBugs/issues/1362
All of these have the same pattern "I got problem X on my marauder, oh, i leveled up and everything is fine." Strange thing, it seems only occuring to single class. Tzeentch is bored, i guess...

**Comment by Luth-RoR** [comment]
Is this still an issue?

**Comment by xyeppp** [comment]
Have you got a Logitech mouse?
