### ISSUE TITLE
Extra mastery point at lvl 17

### ISSUE THREAD

**Issue by cupnoodles14** [WarEmu/WarBugs#10106]
Equipping obliterator set gives 2 mastery points instead of 1 at lvl 17 if 3rd set part is equipped while in RVR zone. Probably works with other sets, didn't notice it working on other lvls.

Marauder 17/20, obliterator set. Worked on SW some months ago too, didn't notice on other characters (probably works).

Steps:
(optional) log out with 4 points allocated (no boots equipped - no bonus)
(optional) log in: 4 points still
go to rvr zone and equip 1 part: 6 points allocated

After this equipping/unequipping set will add/subtract 2 mastery points.
You can also respec (80 silver) and train the 5 points ability, which will work (so the bug is not visual though alert text will say 'Your current level is too low to use this ability'.). With some tweaks you probably can end up this way with 1 unallocated point and no need to respec.

**Comment by wdesu** [comment]
Works with sorc and challenger set too.
![slowdive_002](https://user-images.githubusercontent.com/29466521/29003356-f1a18836-7abd-11e7-9b73-dc6365168772.jpg)

**Comment by gebajger** [comment]
I tried this on my sw alt...works perfectly fine, but only at lvl17.
Equipped full challenger in the lake and got 2 points from setbonus, meaning i could get the healdebuff (shadowstring) at lvl 17.
Left the place, did scs (just for testing of course), the ability was there and usable, altho 'reded' out, but it did go off , showed up in combat log, etc , even stayed there after relogging.
Might be something to do with bolster, because after dinging 18, the extra mastery point was gone.

**Comment by Kaelang** [comment]
Should've been fixed on a recent patch. Please re-open if issue persists.
