### ISSUE TITLE
Witch Elf Sacrificial Stab 

### ISSUE THREAD

**Issue by kyranria** [WarEmu/WarBugs#10364]
The Sacrificial Stab healing yourself for all damage that you dealt. But this is not true ingame, the ability heal two / three more than the damage.

https://imgur.com/ItQQHPh

714damage >> 1785 heal

**Comment by Nfkillz** [comment]
Sacrificial Stab hits twice so 357*2=714

**Comment by kyranria** [comment]
https://imgur.com/9xlN9Ed

3 heal: 375 and 714*2

**Comment by Nfkillz** [comment]
man http://take.ms/JgkmB

**Comment by Marawo** [comment]
![jzajza_002](https://user-images.githubusercontent.com/29643742/30243360-bb936d9a-95a7-11e7-8b08-7de35d309ab2.jpg)
![jzajza_003](https://user-images.githubusercontent.com/29643742/30243364-d0148272-95a7-11e7-8b38-914c380a0163.jpg)
![jzajza_005](https://user-images.githubusercontent.com/29643742/30243367-d61d01f8-95a7-11e7-99f4-7a3aecf6a547.jpg)

It is true, the red value "Sacrificial stab hits you for -xxx damage" is added to my current health.
In the endcalculation it heals for about 2.5 times of what it should since 1st strike of SS procs 3 times and 2nd 2 times.
