### ISSUE TITLE
Friend list

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#10386]
Can't remove renamed or deleted players of my friends list. Probably same goes for the Ignored ones as well.

**Comment by Senthoi** [comment]
I have someone on my friends list who has changed their name in game since they were originally added to the friends list. Because of this, it does not show that they are about. I can't remove them as original name comes up with the message that this player does not exist. And if I try to add their new name, it won't let me as I am already friends with this player.

**Comment by MaxHayman** [comment]
This should be working now.
