### ISSUE TITLE
WTF2

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#1038]
http://take.ms/kq5KC

**Comment by xyeppp** [comment]
He just had the buff on from previous scenarios.

**Comment by Nfkillz** [comment]
i know but this buff shouldnt work.

**Comment by M0rf** [comment]
Buffs last the length of the buff and should only disappear after death not when zoning etc, Nothing wrong here.

**Comment by Silentguard** [comment]
Actually every buff should dissapear when its owner leave group. Only effect that persist group leave was WP wounds buff.

**Comment by ozarmidrashim** [comment]
Every buff, or every group buff?

**Comment by Silentguard** [comment]
Every non-self buff that have lim 'group\wb mates only' such as guard, flame shield, frozen touch etc. Moreover on live group buff was not working if buff owner is out of range.

**Comment by magter3001** [comment]
Works correct, nothing to see here.

**Comment by Silentguard** [comment]
Nope. Was added in some early patch to prevent 120 stat or resists buff in low tiers. Tested it on live different ways. Flames of Rhuin with level above tier level cap dont work in rvr lake for example. Only issue that you could exploit on live is tactics boost under apprentice. So no, group limited buffs dont persist party leave.

**Comment by ozarmidrashim** [comment]
Wait, Flames of Rhuin, Flame Shield etc are implemented as Aura buffs, like the WP's?

**Comment by magter3001** [comment]
I'm pretty sure you got WoW and WAR confused. Buffs don't disappear when you die. They persisted through zone changes until their time ended. What did happen though was Mythic lowering the buffs in lower tiers. If a level 20 goes and buffs a level 10, the level 10 will get level 10 buffs.

**Comment by Silentguard** [comment]
No. You always lose buffs and it was on live since start. On death, group leave, wb leave, sc group change. Not sure about zone change.
onPlayerDeath - https://youtu.be/vG5KqnR_guI?t=3m35s

Yeah it keep visual effect of buff but doesnt give you stats, i noticed this while trying to exploit it in low tiers. Have no idea why mythic do this, especially if rvr buff blocks high level effects. Cant say about all effects but am\sham resists and rp runes works aura mode in 1.4.8.

**Comment by Tyramissoux** [comment]
Sorc/BW buffs always stayed active even after your death and after SC leave. 
![keekshirn_019](https://cloud.githubusercontent.com/assets/13544944/9092662/c1b09038-3ba7-11e5-994a-3bca9143398f.jpg) Look at my char frame. Left SC, buffs still there. Screen is from 5th march 2010.

**Comment by ozarmidrashim** [comment]
Unsure of what to do.

**Comment by magter3001** [comment]
I would keep it as it is. I always found that the way WoW did it was stupid, that after every death you always have to reapply buffs. If this changes, zealots and runepriests would have an annoying time always rebuffing people. There is a reason the buff is 60 minutes, it's meant to last that long. Also, if people don't buff, then the team that gets wiped is at a disadvantage because they lost all their buffs and it's uncertain if zealots/rp would rebuff each person individually. Very tedious. The buff is a group buff anyways, it's not like it's a WB wide buff.

**Comment by Silentguard** [comment]
I can post about 20 screenshots with no side\self buffs after sc. I dont insist to copy as it was on live but working off group buffs is obvious exploiting. Common sense is best way before this 'feature' does not become a problem with level cap growth such as t1 chars buffed with Flame of Rhuin boosted with 75% proc chance and double damage.
![kive_013](https://cloud.githubusercontent.com/assets/13031465/9093460/e9fc7caa-3bde-11e5-8b74-b4606d912496.jpg)

**Comment by magter3001** [comment]
If I recall correctly, the 75% chance only effected the sorc, so your argument is invalid. Second, high level players get chickened in T1 if they are in an RvR zone. I also don't think people care enough to have a level 20 BW or Sorc to buff them each time they go play in T1. Too much of a hassle. Though there probably should be a fail safe just in case someone gets the bright idea of doing it. Like not being able to receive a buff if your party member is 10 levels lower than you or just nerfing the flames of rhuin to the T1 version if you buff a T1 player.

**Comment by Silentguard** [comment]
Look, im already exploiting this, but i admit its unfair advantage. So i dont see any sense to keep it. There is only two legit questions "It gives you advantage?" and "Its allowed for everyone?". If you can answer to second one "Sure, everyone can load RP, BW on side account for buffs" i have nothing to say anymore.

**Comment by Nfkillz** [comment]
LOL) look at my screenshot and log. Do you think is it normal that half of damage was dealt by buff of toon  which wasnt on sc? If you think so - ok... I will load RP/BW for buffing because of i dont want that enemy will have adwantage from these buffs.

**Comment by Evildoor** [comment]
Closing since it's not a bug but a balance issue.
