### ISSUE TITLE
Engi spanner swipe being dodged

### ISSUE THREAD

**Issue by grumcajs** [WarEmu/WarBugs#1043]
I have a feeling engi spanner swipe used BS and ranged power to calculate dmg but could be parried like every other melee ability so u could just hit target from back to snare him. Now it seems it can be dodged instead so even when u hit your target from behind he can still avoid it.

Maybe it was same for friction burn but here Im only guessing...

**Comment by ozarmidrashim** [comment]
You can't dodge attacks from behind. Only Disruption is 360 degrees.

Marking as unimportant.

**Comment by Evildoor** [comment]
I don't see any problem here after Azarael's explanation. If it is "Dodge" text instead of "Parry" - i'm not sure if it was "Parry" on live, and even it was i doubt that anyone should bother about it. I can understand people irritated by wrong animations or models (naked Choppa in RVR influence gear, for example. Not an issue anymore with appearance implemented), but this... Closing.
