### ISSUE TITLE
SH pet's bonuses dissapear after crossing zones (i.e. Talabecland to High Pass)

### ISSUE THREAD

**Issue by sofronguy** [WarEmu/WarBugs#10597]
I tested this in Chaos T3 and Elf T3 and it keeps happening on my 40 level squig herder (no bolster). The pet seems to be still controllable but the bonuses for it are not there (verified with .getstats). Also, when you cross the zone, for some reason the game places me 'in combat' status for 4-5 seconds.

First with the pet active before changing zones (.getstats shows the 5% increase in crit as melee crit for some reason)

![snipp_001](https://user-images.githubusercontent.com/30108162/31580245-a6d67d22-b152-11e7-872e-1d5f939eb0b3.jpg)

And then after changing the zone (no more 5 criticalhitrate)

![snipp_003](https://user-images.githubusercontent.com/30108162/31580251-c63483da-b152-11e7-8aed-59de5030d974.jpg)

**Comment by sioding** [comment]
Can you please provide 2 screenshots with the output of the ".getstats"  command? The devs need as much evidence as possible: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)

**Comment by Zealote** [comment]
Wrt pets disappearing at zone boundaries: #10337 #10443

**Comment by bj0rns0der** [comment]
Same happens in Sap/Avelorn. Check armour stat.s

![grichnob_005](https://user-images.githubusercontent.com/5555817/40017072-8f5c1140-57b8-11e8-9ddd-0b082fb386c4.jpg)
![grichnob_004](https://user-images.githubusercontent.com/5555817/40017073-8f7b2d14-57b8-11e8-9b0a-b8ed7c0d8ce0.jpg)

**Comment by Moragor** [comment]
Trying to provide some more info to this problem:
https://youtu.be/LbbN7bLVYWs  A video i captured of the problem.
You can see that on the zone crossing the squig disappears for a second. The cooldown of the active squig is activated and combat state is entered. The pet buff disappears and the color of the squig changes from yellow to orange which usually only happens on a resummon.
After the cooldown is finished a new identical squig can be summoned which normally is not possible since using a squig's skill desummons it and activates the cooldown. See here: https://streamable.com/8olrp
This indicates that the squig is dead after the zone switch, but a phantom reappears. This unfortunately leads to an exploit. The "phantom" squig is mostly functional and can be used in combat, if the squig despawnes due to distance to the SH however the system gets borked. The combo attack "Git Em" which is only usable with an active squig becomes usable without an active squig.
