### ISSUE TITLE
Fated Veil/Fresh Meat/You Gonna eat that?

### ISSUE THREAD

**Issue by Karidoc** [WarEmu/WarBugs#10626]
This item/achievement do not unlock Fated Veil in the Library

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Lheana** [comment]
Are you sure you triggered the correct ToK unlock following instructions of [RoR Wiki](https://wiki.returnofreckoning.com/index.php/You_Going_to_Eat_That%3F)
Verify you have triggered the correct unlock, and talk to the correct vendor in the Library 'Disciple Venomstung'.

**Comment by sioding** [comment]
I did the quality assurance on my own. Works totally fine.

**Comment by Karidoc** [comment]
Anyway you could look into my situation in particular? I followed this
information:

Fated Veil: (5k, 61k) Travel to Praag and make your way down to
Lieberholz's Command Empire Chapter 17 and then move Southwest to the
coordinates given. Enter through the nearby Skaven Tunnels. Slay
enough Warpwind
Gutter Runners, Warpwind Night Runners, and Warpwind Gutter Leaders until
you find one that drops an item called Fresh Meat. After you receive the
item, exit combat and equip this item as it is a Pocket item. Equipping
this item will grant you the tome unlock, "You Going to Eat That?”,
allowing you to claim Fated Veil.

I recieved the "fresh Meat" and equipt and i can not recieve the Title. or
the item "Fated Veil" from the vendor. I have 2 Fresh Meats now since you
sent me this e-mail. Any help would be greatly appreciated.

Thank you for your time!

**Comment by Lheana** [comment]
In which language must I tell it? FOLLOW THE INSTRUCTIONS OF WIKI.

**Comment by Karidoc** [comment]
I did what the Instructions of wiki said. twice over. the in game GM looked
into it and acknowledged it was a problem. an said a reset might fix it.
the reset didn't fix it. I'm not sure why you're being rude.

**Comment by Lheana** [comment]
I am rude because the instructions you put above on your previous comment **IS NOT** the ToK unlock that triggers Fated Veil, which means you **DID NOT** follow the instructions of **RoR Wiki** (that I linked on my first post and I link once again [here](https://wiki.returnofreckoning.com/index.php/You_Going_to_Eat_That%3F)). I am rude because it is a waiste of time if you don't do things right and then report "it does not work!". I tried with several chars, Sioding himself also verified (we triggered the unlock **FOLLOWING ROR WIKI INSTRUCTIONS** then we talk to the correct vendor who sells Fated Veil).
So I repeat it if you have problem following the instructions of **RoR Wiki**: to buy Fated Veil, you have to trigger the ToK unlock You Going to Eat That? clicking on a cauldron in TM (read the wiki for location). Once you have this unlock, talk to the correct vendor ('Mandred Vogt' for Order or 'Disciple Venomstung' for Destruction).

**Comment by Karidoc** [comment]
Got cha, thank you.
