### ISSUE TITLE
Talisman Crafting Breaks Consistently

### ISSUE THREAD

**Issue by wwitunsky** [WarEmu/WarBugs#10665]
I am having an issue where in my crafting bag 2 items keep taking up the same slot. They flash back and forth. This in turn breaks talisman making and forces me to log out. It is very unreliable in putting items in the talisman making window. I am currently running no crafting addons. I have even gone as far as moving everything out of my crafting bag to only have similar results  It will break leaving all items stuck in the crafting phase. You cannot clear and if you can clear it will not take any further items to continues. 

Please direct me to a solutions.

**Comment by oddmage** [comment]
I have the same issue.

**Comment by baroke** [comment]
I had the same issue. For me the issue was caused this way:

In the backpack, Inventory Items tab (the first one, not the Crafting tab), there is a rhombus like symbol at the right side of each bug, which, when hovering your mouse will say "Item Preferences". In that menu, i had enabled for one bag the Crafting->Talisman Making submenu, and on another bag i had the Crafting->Salvaging. 

When i disabled this option on both of these bags the problem disappeared. 
Can you try that?
Hope it helps.

**Comment by wwitunsky** [comment]
Thanks I'll try that
