### ISSUE TITLE
Caledor incorrect out of bounds detection 

### ISSUE THREAD

**Issue by sanscolour** [WarEmu/WarBugs#10747]
At the destruction camp 'Crimson Scar', just outside the camp on the west side you will receive a message saying "The gods are angry that you are trying to leave the world, turn back now!".  After a short time, a player spawned terminate effect will kill you with 30,000 damage.

The out of bounds detection seems to be grossly misplaced here, as I can barely step out of the camp before getting it.

A video is available at https://youtu.be/qGYSNgkOF08 that demonstrates the issue.  Please let me know if there is anything else you need.

**Comment by sioding** [comment]
Thanks for the report. We´ll check that.

**Comment by Natherul** [comment]
Not an issue, its being triggered as we have labeled the fortresses are illegal zones atm and what you are experiencing is due to you entering the fortress zone (which is just west of said camp). Until we decide to lift the flag from fortress zones this will happen.

If you perhaps mean that you spawn on the wrong side of the "barrier" to that zone when killed then DB needs to assign a new spawnpoint
