### ISSUE TITLE
tab targetting still poor 'low priority'

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1079]
I think there is some 'low priorty' need to fix the tab targeting so that is more player friendly and to acquire targets roughly center of the screen area and forward of the players direction

**Comment by ozarmidrashim** [comment]
Please think before you post.

Either the tab targeting priority / handling is intrinsic to the client (which is quite frankly the option that I would put money on) or it's controlled by some obscure piece of information which we don't know how to send to the client.

Either way, it's not getting fixed any time soon. Sorry.

**Comment by gittoaster** [comment]
I no idea if it's client or not.  Why would it be?

**Comment by ozarmidrashim** [comment]
Because it makes absolutely no sense to have an instant response aspect of the UI be sent to the server in order to determine which target should be selected. That would have a response delay equal to your ping. All the client needs to care about is the enemy targets that have been sent to it by the server, and it has its own logic for selecting them.

In short, we can do nothing about it.

**Comment by Radiantknight** [comment]
You can always get nearest target, by pressing 'n'(default setting) and tab it from there(slightly better than just tabbing, still hit-or-miss thing)

**Comment by gittoaster** [comment]
good tip @Radiantknight.  thx

**Comment by xyeppp** [comment]
It always switched through all possible targets when it should've taken your cone field of view/camera angle into account - it was like this on live as well. Just re-configure your binds - I have Caps Lock bound for Nearest Enemy, and tab to cycle with n to go to previous target.

**Comment by ozarmidrashim** [comment]
Closing per xyeppp.
