### ISSUE TITLE
eataine mustering rally point

### ISSUE THREAD

**Issue by vastourl** [WarEmu/WarBugs#10892]
If I try to set my rally point at eataine's mustering warcamp, book of binding is erroneously binded to caledor's conqueror's descent warcamp
![piniaou_000](https://user-images.githubusercontent.com/33893354/33118258-ef3ede94-cf73-11e7-906f-f7525af2437f.jpg)

**Comment by Lheana** [comment]
#10992 
To bind to Eataine, talk to the rally master Adrial Amberstaff

**Comment by ChronoVarience** [comment]
Almost posted this issue again:

I reported this issue to a Gamemaster last week and had my books reset to 0. After some testing it appears that T4 RvR warcamp Rallymasters, Captain Reinold, Corsa Grimhammer, and Aethalas Flowingmain, all bind to the same location in their respective zones:  Empire T4 binds to Praag, Dwarf T4 binds to Black Crag, and Elf T4 binds to Caledor. It's not just me either, I had a guildie test this as well with the same result. Lower tier RvR Rallymasters and PvE Warcamp Rallymasters do not appear to be affected.

Expected behavior and actual behavior:
Expected behavior:  When clicking yes to question "Do you want to bind here?" with one of these three Rallymasters, it is expected that the book will bind to the current location.
Actual behavior:  When clicking yes to question "Do you want to bind here?" with one of these three Rallymasters, the bind location produced is either Praag RvR warcamp, Black Crag RvR warcamp, or Caledor RvR warcamp

Steps to reproduce the problem:
1) Fly to[Chaos Wastes, Reikland, Thunder Mountain, Kadrin Valley, Eataine, Dragonwake] and approach either Captain Reinold, Corsa Grimhammer, or Aethalas Flowingmain, depending upon which pairing.
2) Activate Rallymaster, [Captain Reinold, Corsa Grimhammer, or Aethalas Flowingmain] click "Set Rally Point" and set binding. (observe in chat window)
3) Fly to different location, (anywhere is fine really, but you might want to avoid Black Crag, Caledor, or Praag) and activate Book of Binding.
4) End up in Praag, Caledor, or Black Crag based on which pairing you set you rally point in.

Screenshots/Videos or archive.org evidences:
http://plays.tv/video/5b44e38d340840225d/cw-rvr-rallymaster
http://plays.tv/video/5b44de9773f2bffb46/kv-rvr-rallymaster
http://plays.tv/video/5b44df2bb3804e09dd/eataine-rvr-rallymaster

And also a PvE to demonstrate that they are not affected.
http://plays.tv/video/5b44ddc73dfa944de5/reik-river-pve-rallymaster

Guys, can we get the right NPC's posted out front instead of hidden in tents, or just remove the misbehaving ones, puh-leese!
