### ISSUE TITLE
SH: Expertskrimisher+Shoot Thru Yaa not working

### ISSUE THREAD

**Issue by tr806042** [WarEmu/WarBugs#10986]
Hi,

im not sure if this is an intended change or a bug for SH. But i used to run expertskirmisher+Shoot thru Yaa as aoe build, this was about half a year ago. Now if i try to it sometimes charges in 1sek but only for my char to wait another  sek untill release, makeing it pointless and crippling my rdps aoe potential to 0

**Comment by Haojun-Phalanx** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=24072

[Abilities]

Natherul
- Backend work to allow buffs to change the appearance of items
- Hardcode so that expert skirmisher correctly affects Lileaths arrow or shoot through ya, the client is however hardcoded to change the castbar if out of range but the cast wont go off earlier
- Tactics - Sneaky Stabbin and No Respite will no longer arbitrarily increase Lileaths Arrow or Shoot Through Ya, they will gain the damage increase if their offensive target is within the range parameters

**Comment by sioding** [comment]
Intended - and Thx @Haojun-Phalanx
