### ISSUE TITLE
Guild disappeared with bonus guild 

### ISSUE THREAD

**Issue by GutshotSheerak** [WarEmu/WarBugs#11039]
Created a guild 3 days ago
2nd day guild disappeared, all members guildless
3rd day, we log in and we are in a guild, however this guild is on the opposing faction.  I'm destro and we're in an order guild atm...
My guild's name was "BONE" on destro.  All BONE members are currently sitting in an order guild called "SnD"

**Comment by wargrimnir** [comment]
It's not in the DB. Nothing to do here. Leave your current guilds and make it again.

Usually this happens when people create guilds shortly before the server is restarted, it doesn't save things to the DB instantly. Every couple of minutes. Your characters might have been assigned to a guild, but the guild itself wasn't saved, and that id that you were assigned to got reassigned to them.

**Comment by GutshotSheerak** [comment]
ok cool, that's good to know, thanks for the fast response
