### ISSUE TITLE
SC pop while already inside SC

### ISSUE THREAD

**Issue by baroke** [WarEmu/WarBugs#11088]
I queued for all SCs and i got a pop for Khaine's Embrace a little time after.
I joined the SC normally and started playing.
I didn't do anything weird (like trying to queue for SC again) while playing the SC.
**I got a SC pop at some point, while inside that SC!**
I didn't pressed any of the 3 buttons, the pop timed out on 1 min and didn't got quitter debuf.
The SC ended normally after like 2 mins.

![gogol_003](https://user-images.githubusercontent.com/20115114/34511086-dbe0ed9c-f061-11e7-9a6b-21fd820a0edd.jpg)

**Comment by Natherul** [comment]
where you by any chance in a group before joining said SC?

**Comment by baroke** [comment]
I don't remember.

**Comment by Natherul** [comment]
the best explanation I have (especially since nothing has changed for a long time in regards to SCs and their que) is that you were in a group and your group leader signed up for more scenarios as a party. 

closing this ticket for now, if it happens again and you are sure you are not in a party please reopen this ticket. Ill add to the list to do (low priority) that players in a SC should not be able to be signed up again
