### ISSUE TITLE
away with ye 

### ISSUE THREAD

**Issue by bugreportingisnotworththeeffort** [WarEmu/WarBugs#1124]
Shield wall (100% block) doesn't protect against "away with ye". Not at all.
"away with ye" seems to be unblockable in general.

**Comment by ozarmidrashim** [comment]
Passive-aggressive names now?

Really?

**Comment by bugreportingisnotworththeeffort** [comment]
Since the blackorc kick can be blocked by shield wall the issue is "away with ye". :)
Being passive aggressive because I don't get why the bugtracker is completely unrelated to RoR.

**Comment by ozarmidrashim** [comment]
Yet the RoR devs obviously read and use it, and there's a link to it from the RoR page, so I don't get your point, or how that's related to bug reporting not being worth the effort...

**Comment by bugreportingisnotworththeeffort** [comment]
But creating a completely new account to report sth that is not likely to get fixed is a big effort. ;) I would rather just make a thread on the forums.

**Comment by xyeppp** [comment]
Because it's easier to keep track of bugs this way with labels, which provides for an easier fix and assigning to people responsible for them.
Unless somebody were to create a whole new bugtracker just for RoR, such as https://report.nostalrius.org/plugins/tracker/?tracker=14 (which requires a web developer to do that), then this is most likely the best way for people fixing bugs to keep track of them.

You are helping yourself and the server, why the negative attitude towards it when all bugs get squashed when reported?

**Comment by bugreportingisnotworththeeffort** [comment]
Thank you for the explaination. I am not expecting too much from a game in its alpha, the reason why I am upset is that this "bug" is the most annoying thing when premade fights premade and order has the upper hand without anything destruction can against "away with ye".

**Comment by ozarmidrashim** [comment]
Well it was a two second fix, so it'll be in the next update.

**Comment by bugreportingisnotworththeeffort** [comment]
Thank you. What went wrong? Was it really unblockable/undefendable?

**Comment by ozarmidrashim** [comment]
It didn't have any stat scaling information, so gained no damage bonus and would not have defense checks performed against it.
