### ISSUE TITLE
Scenarios cause system crash

### ISSUE THREAD

**Issue by StuartReid81** [WarEmu/WarBugs#11304]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
When joining scenarios something is causing a crash on my system - it looks like a memory bleed somewhere as the whole system freezes and the audio glitches - the only way to fix is to hold down the power on my system and restart machine.

Steps to reproduce the problem:
This only happen in scenarios - I have turned off all spell effects and camera fade which has reduced the frequency but it still happens - There are occasions when I can make it through a scenario without a crash but I would say it crashes about 80% of the time.

Screenshots/Videos or archive.org evidences:
As the system hangs I have no way to get footage of this - I could record it happening on my phone if it helps?

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Sorry this is nothing for this bugtracker if your complete System crashes while you are entering a scenario.. Please try to get help in the game support part of our forum.

**Comment by StuartReid81** [comment]
Mate it is not while entering a scenario it is at random time in scenarios when in pvp - as in something in the scenario is triggering it (spell effect, bad texture, memory leak) - that is a bug

**Comment by sioding** [comment]
Dude!
If you complete system crash its maybe a bug - but not necessarily the client.  Without any more informations - how shold we be able to reproduce someting? We can´t - so we can not do anything with this report.

**Comment by StuartReid81** [comment]
I am a trainee software developer, I know how hard it is to fix a bug
without being able to recreate it. There must be a way to grab the
exception error that is causing the crash. What debugging tools do you use?
If I ran it in a virtual system would there be a way to see what file is
triggering the crash?

**Comment by wargrimnir** [comment]
You could have some corruption in your client download, download from the torrent, it's probably the best way to get a good version. There's also an endless list of things that we've done to emulate the server that don't match up with what the client expects, that can cause crashing as well, but since we don't have a perfect understanding of the client, a lot of it is guesswork at best to fix and line up properly.

This link may be helpful as well to gain more stability.
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075
