### ISSUE TITLE
[Black ork] Morale skill dissapearance

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#11378]
**Expected behavior and actual behavior:**
Using a black ork, build up morale 1 and use Champion's challenge

**Steps to reproduce the problem:**
Enter pvp combat, build up morale 1 and realize morale 1 skill dissapeared from morale bar

**Screenshots/Videos or archive.org evidences:**
Visual proof of bug in pvp: https://www.youtube.com/watch?v=OP-MpkJFb18

**Notes:**
- I experienced this uncommon bug some time ago and though it was patched away, but today trying to reproduce another morale skill bug [[Camera's bug]](https://github.com/WarEmu/WarBugs/issues/11377), during the same scenario EVEN during the same fight my first morale skill dissapeared and I'm 100% sure it was properly equipped

Thank you for your time

**Comment by Kaelang** [comment]
Unable to replicate this issue and the video link is no longer valid. Haven't heard of any BOrk's saying this is still current in the latest versions of RoR and assume if I was unable to replicate such problem, then it has since been fixed.

Please re-open if this issue remains with a new video link.
