### ISSUE TITLE
Party bug in SC specific to one player

### ISSUE THREAD

**Issue by Vigfuss** [WarEmu/WarBugs#1138]
I'm seeing a problem with group frames, it seems quite specific to one player, but not really sure how to define the problem.

In SC he joins the party, and his character information shows up in the vanilla UI, but not on the enemy group frames. It happens to him at least 2 out of 3 SCs, and it's the same for everyone in our party, he is not showing on their enemy unit frames. Also for him, it looks on enemy as if he is the only member of his party.

So in a way it's a problem with the addon, but there is something else going on in the background that seems like a bug, and it might be affecting other things as well.

**Comment by magter3001** [comment]
This happened to 2 of our tanks the last couple of days. Don't know if it's strictly a tank issue or not, some people get it more than others.

**Comment by Silentguard** [comment]
Invisible player frame happens if you join full sc group. Just in case dont join gr1 or gr2 if you joined sc and dont see players in group formation frame.

**Comment by Vigfuss** [comment]
Good to know, thanks.  I will ask him to join a party first next time and see if it still happens.  Sometimes random people are sneaking into the party before everyone has a group, and he might be trying to join anyways, before moving to another party.

**Comment by Vigfuss** [comment]
I can confirm that this bug is happening to Bozzax with any of his characters almost every SC and he is not joining a full party.

**Comment by bozzax** [comment]
Fix git add on bugs party windows in SC

**Comment by bozzax** [comment]
Even without fix git there is a bug and not only with a full party.

There seems to be another issue possibly due to high latency. If you join a group and another player has joined the same slot milliseconds before you (because of lag/latency it bugs) I think you get the same problem.

Something like
Player A and player B enter SC same second and both joins party 1 with 3 members. 

Player A has less latency and join slot 4. Player B joins slot 5 on server? Or got server respons member 5 and bugged?.

**Comment by Luth-RoR** [comment]
Was fixed a while ago iirc.
