### ISSUE TITLE
Quest: Treasure Under Altdorf

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11402]
The quest book text directs you to travel to the Altdorf slums district, enter the sewers and search for Dolun Hammerson.

The task you are given is "Speak to Grudgekeeper Runepriest".

The map of Altdorf shows three Major Landmarks that are marked as sewers. All appear to be in the slums district. One is directly barricaded. One is inactive. One appears to be inaccessible.

**Comment by Lheana** [comment]
The Sewers are instances that are not available yet.

**Comment by TheBlueCarpetsBand** [comment]
The ,"Treasure Under Altdorf" quest is still broken even after Sewers was implemented:
I did Sewers earlier today, talked to Dolun Hammerson, got credit for the quest only, wasn't able to turn it in to him.
When I returned to Dwarf Tier 2 Ch.6 Murdogh's Hold, the completed quest cannot be returned to the original questgiver NPC, "Alaric Grimstone" either because the NPC still shows a grey quest icon even though the quest is completed and should be turned in to him.
![treasure under altdorf2 1](https://user-images.githubusercontent.com/38879353/43988147-dc72f04c-9d1e-11e8-9cfa-93279f8ee09e.jpg)
![treasure under altdorf](https://user-images.githubusercontent.com/38879353/43988148-df3cdd10-9d1e-11e8-9ec9-accab5ac83d1.jpg)

**Comment by Lheana** [comment]
In fact the real original quest giver is Rolun Hammerson in Dwarf Chapter 5.
The quest finisher will be Dolun Hammerson with next patch.

**Comment by sioding** [comment]
fixed with patch from 14.08.2018
