### ISSUE TITLE
[rvr] wrong name in combat log

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#11452]
Log says that i, a chosen, have slain Blastoise but he's a lvl 40 choppa.
![attilio_038](https://user-images.githubusercontent.com/17765890/37327282-f9539126-2695-11e8-96e7-88c032af8b91.jpg)

**Comment by Kaelang** [comment]
Appreciate this is an old report, however I'm working through a backlog. That being said, it's unclear what you're trying to portray here. There has been a lot of development between the time this bug was listed, and now. Please could you confirm if this issue remains on the current patch, and if so, I'll keep this open.

Thanks.

**Comment by zak68** [comment]
probably something was bugged and seemed that my attacks (Attilio's blast wave) were hitting the choppa (Blastoise) i was guarding, or perhaps that player (Blastoise) was not even online so it seemed that his name was hardcoded somewhere. now i remember asking in /advice why in the combat log the name Blastoise was appearing and someone aswered that it was a bug so i reported it. 
haven't played the chosen for a while but i'll check it out.

**Comment by Kaelang** [comment]
This could be a cache issue - however if you could check this out and further validate that could help. 

Any steps to replicate would also be useful.

Thanks.

**Comment by Kaelang** [comment]
No further information - closed.
