### ISSUE TITLE
Annihiliation (Chaos Epic T4)

### ISSUE THREAD

**Issue by Alfred19** [WarEmu/WarBugs#11466]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*Quest can not be completed

Expected behavior and actual behavior:

Doors should open at completion of Stage 2, critical Mob cant be reached

Steps to reproduce the problem:

Do Reikland PQ "All Kings Men" Cpt.22 - try to reach questobjective

Screenshots/Videos or archive.org evidences:
https://i.imgur.com/Hvh0kAf.jpg
https://user-images.githubusercontent.com/36804013/37184943-d2daa524-2335-11e8-9cb7-0ce67722ff89.JPG

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/37610031-e3f90974-2b9e-11e8-8ebf-633a7b2ca493.png)
Duke Wickham can temporary be found at the ground floor. 
We need to overview the epics to make sure you do not need a warband to get the weapons one the chapther 22 PQs are open.
Until that - fixed with next patch.

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/37731643-07fadbf4-2d43-11e8-8d46-1c4d5f472387.png)

Duke Wickham can temporary be found at the ground floor.
We need to overview the epics to make sure you do not need a warband to get the weapons once the chapter 22 PQs are open.
Until that - fixed with next patch.

**Comment by Alfred19** [comment]
Thank you.
