### ISSUE TITLE
Cannot open loot bags

### ISSUE THREAD

**Issue by Holrun** [WarEmu/WarBugs#11544]
Expected behavior and actual behavior:
I have two loot bags taken from my mailbox that I cannot open. Could you please help me recover what's inside? Thanks.

Screenshots  
![dabigjoe_004](https://user-images.githubusercontent.com/38047020/38262473-93f59fde-376d-11e8-8863-9093ecc8bd36.jpg)
![dabigjoe_005](https://user-images.githubusercontent.com/38047020/38262474-9418833c-376d-11e8-82e4-4fd32e07feba.jpg)

**Comment by Natherul** [comment]
We do not help recover any items from these bags and the issue is caused by winning these bags and letting them sit before taking the items as the server does not save the contents of the bags for restarts. 

This has been an issue for a long time and we will revisit it sometime later but right now its not a priority.

**Comment by Kaelang** [comment]
Bags are able to be opened from the Mailbox now. Please re-open this issue if it's consistent on updated versions of RoR.
