### ISSUE TITLE
Deep Wounds

### ISSUE THREAD

**Issue by knezekj** [WarEmu/WarBugs#1181]
Hi for me is this abillity not functional. It writes that i have too low level to use this abillity, i have it in hotbar but its not usable. Thank you for answer.

**Comment by ozarmidrashim** [comment]
Client display issue.

**Comment by Evildoor** [comment]
Does this skill actually affects the healing? I'm pretty confident that when i used heals with my zealot on debuffed targets during last two days my healing was undiminished...

**Comment by knezekj** [comment]
![snorrri_002](https://cloud.githubusercontent.com/assets/13565283/9555238/1a83ce6a-4dcc-11e5-99d8-f297c93ef2b5.jpg)

**Comment by Evildoor** [comment]
1) These warnings/grey icons/etc happen because of stupid Mythic restrictions which harmed they game even when it was alive. They cannot be fixed because RoR devs have no right to change game client.
2) It was still possible to use the ability despite the warnings.
3) Now the ability was returned back to 9 points, so this is not an issue anymore.
