### ISSUE TITLE
[Ranged classes] Autoattack seems to stop > 95-96 feet.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#11830]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
When making tests with the target dummy in Kadrin Valley, on Engi and SW I noticed that the auto attack of the rdps stops firing at ca. 95 feet and then doesn't can be started till back closer than ca.95 feet after using an ranged attack on the Target.

Gun Turret on Engi, or Scout Stance on SW doesn't change that autoattack range.

I have made a test on an SH too. He also stops to autoattack at around 95-98 feet.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by thorbolt80** [comment]
So if you got turret gun the auto attack should be at maximum range 125 feet?

**Comment by sioding** [comment]
Any proof how it was on AoR ?

**Comment by LestiArdisson** [comment]
@thorbolt80 I made a test with the Gunturret. Your Engineers Auto Attack is not increased with a Gunturret.

**Comment by thorbolt80** [comment]
We test it with Lesti. The auto attack range isn't improve if you put gun turret (maximum range 125 feet) the auto attack start exactly at 100 feet. So unless you want to improve auto attack range to 125 feet if you have a gun turret, (let us know ;) ,you can close this issue one because auto attack start at 100 feet.
