### ISSUE TITLE
To much Exp.

### ISSUE THREAD

**Issue by Laksefisk** [WarEmu/WarBugs#11885]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Was rewarded 199906 exp for killing a Empire helbardier who should have given around 2k

Steps to reproduce the problem:
Killing Empire Helbardiers, dident get it to pop agen.

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/40248295/41375084-48904f9c-6f55-11e8-83a9-325baa104ba3.png)

**Comment by Natherul** [comment]
This can happen under two different circumstances. 

1. You got desynced level and renown from the server and on next gain you gain ridiculous sum of XP and rr to catch up though this is just visual as the client sync up with server again. 

2. The server did something very stupid, but in this case you would not get that amount anyway since the server have fail safes for just this, an you would be notified as such.

Either way, you did not get that amount even if your log stated you did. Thanks for the report though
