### ISSUE TITLE
new squig herder "leap" skill use to enter a keep with inner door still close

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#12025]
Target a player at second floor then use squig leap you are inside the keep with the door still close.

**Comment by Kaelang** [comment]
This report doesn't provide any information as to what keeps, what locations etc. A lot of the maps have invisible walls added since 2018 to today which has stopped a lot of these jumps being possible. 

Please re-open a new report with further information if you are finding these spots in the latest versions.
