### ISSUE TITLE
Squig Herder - Outa my Way makes own pet agro

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#12216]
When Outa my Way is cast own pets starts attacking the squig herder 

Steps to reproduce the problem:
Flag for pvp, summon pet, use outa my way

**Comment by sioding** [comment]
Any screens/video?

**Comment by Culdu** [comment]
![petattack](https://user-images.githubusercontent.com/14928735/44740929-f9d81000-aafb-11e8-9a1b-84f65fff871d.png)

**Comment by Binkies** [comment]
I believe the issue is actually caused by the **'Ere, Squiggy!** Tactic that can be obtained in the _Path of Bouncin'_ Mastery Tree.

I leveled my SH and had been playing him only with the other 2 Mastery Specs, and never saw this happen. After recently swapping to the Bouncin' Spec it started.

To reproduce:

- Obtain and use the **'Ere, Squiggy!** Tactic
- Get hit by any mob
- Pet will eventually start attacking you as well

The Screenshot attached is the combat log from testing this theory by getting hit by a low-level mob.
![petattackbug](https://user-images.githubusercontent.com/45829268/49889856-95be2b00-fe10-11e8-8b22-95fb579ba175.jpg)

**Comment by Natherul** [comment]
was indeed ere squiggy. 

Thanks for excellent information. I have isolated the issue and committed a fix thats pending for the next patch

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
