### ISSUE TITLE
Missing mobs: Saphery Public Quest Trial by fire (Honorable Deceit T3 Dark Elf Epic Quest)

### ISSUE THREAD

**Issue by arialswg** [WarEmu/WarBugs#12294]
Hey.  I know this was logged previously (12212) and it was previously closed saying it was a known issue and to please wait for the next restart of the server.  But it was two weeks ago and I know the server has been restarted since so I'm going to log it again.

Expected behavior and actual behavior: There should be salamanders as well as Impetuous Would-Be Mages for the first stage of the PQ but there are none of the specified mobs when you arrive at the PQ

Steps to reproduce the problem: Just need to go to the PQ to see the mobs are missing

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/43117498/45267410-4c38fb00-b431-11e8-864f-652d5bccd4b3.png)

![image](https://user-images.githubusercontent.com/43117498/45267414-5e1a9e00-b431-11e8-8dc4-363664095df9.png)

![image](https://user-images.githubusercontent.com/43117498/45267418-683c9c80-b431-11e8-81d9-d0d124d3b0b4.png)

**Comment by Lheana** [comment]
What you have to understand is that it's an unconstant issue, that can happen after any server reboot or be fixed with any server reboot. One said to wait for server as it MAY fix it, but it MAY also not fix it as the bug may once again happen.
It's a known issue, and we don't know yet how to fix it.
The only advice we can give you is to check after each server reboot, but we can't promise it will be fixed with a server reboot.
