### ISSUE TITLE
Bathing in Blood tactic not proccing on mobs

### ISSUE THREAD

**Issue by Stinkypants** [WarEmu/WarBugs#1240]
The enchantment shows up on the buff bar when tatic is equipped.  However, no healing proc happens when a killing blow is made.  Only tested on pve mobs so far.

**Comment by Stinkypants** [comment]
Update, tested on mobs some more.  It does work, but some of the time.  My guess is that proc's from buffs that are the killing blow don't register as a kill by you so do not proc the tatic.  <.< let me try without buffs on to see if it's 100% working.  Trying to test in pvp, but it's not optimal and well difficult at best to tell if I actually got a killing blow.

**Comment by Stinkypants** [comment]
I can't figure it out, it doesn't appear to be the proc taking the kill.  I'll do some kills and find killing blow proc/ or not.

**Comment by Stinkypants** [comment]
The closest I can come to any pattern is every other kill.  Perhaps there's an internal timer for the proc.  That was not there on live if that is the case.

**Comment by Stinkypants** [comment]
So all those tests were with the sorcerer.  I just used it with the Black Guard and I go zero tatic proc's on kills.  I was farming champion mobs for salvagable gear.

**Comment by Evildoor** [comment]
The tactic works now, but the amount of health it gives is a bit less than the tooltip states.

**Comment by Zealote** [comment]
Just tried on WE and it doesn't proc when Kiss is killing blow. 

Also, I don't have a clue how it was on live, but it's typed as an enchantment, does that mean the tactic itself can be shattered? :S Seems strange if so.

**Comment by Evildoor** [comment]
The same thing was on live. People were running around with a visible buff, it was possible to remove it with Shatter Enchantment. Dunno if it affected the tactic or not. I do believe that this is another Mythic fail, since i don't see any reason for this tactic to be visible/shatterable. Just another "on kill" tactic for PVE farming, nothing special.
Side note - your words about killing blow with a kiss remind me of another bug report where chosen's aura was preventing EXP/RR/whatever gain if it killed someone. This should be investigated...

**Comment by ozarmidrashim** [comment]
Regarding tactic displaying as "Enchantment": The emulator never gives tactics a type, so even if they are picked up by the client as Enchantments, they won't be shattered serverside.

**Comment by noisestorm** [comment]
+
