### ISSUE TITLE
[KOTBS] Emperor's Champion healing too much

### ISSUE THREAD

**Issue by blechkautz** [WarEmu/WarBugs#12425]
The Morale 2 Emperor's Champion of the Knight heals the user for 2400 hp, while the stats gained are only 160 (like the tooltip and the patchnotes).
![pfosten_011](https://user-images.githubusercontent.com/30760089/46587236-67774480-ca89-11e8-82eb-e2268b8a08dd.jpg)

**Comment by sioding** [comment]
I don´t get the problem. Can you please add more informations?

**Comment by blechkautz** [comment]
HTe morale increases your wounds by 160 and should heal you for 1600 because of that. But it increases your wounds by 160 and heals you for 2400.

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=109&t=28164&hilit=Emperor%27s+Champion

>Knight
- Encouraged Aim is now Overpowering Strike and affects Arcing Swing instead of Press The Attack.
- Emperor's Champion now has a 60 second cooldown, but its duration has been reduced from 30 to 15 seconds and the value of the stats gained has been reduced from 240 to 160 at rank 40.

**Comment by sioding** [comment]
fixed with patch from 14.10.2018
