### ISSUE TITLE
Squid Herder Head Dissapears.

### ISSUE THREAD

**Issue by Huggless** [WarEmu/WarBugs#12566]
When you go into first go into RVR as a squig herder in its squig armor transformation, it transforms you back into a regular squig herder but your head glitches out and vanishes like the head and neck got deleted, all you see is ears and body. only way to fix it is to relog everytime, and sometimes it says your too low to use the transformation even tho your not. if you dont mind fixing it for a lot of people, that would be wonderful :) if you are going to send a token tho, send it to Sensitivetrust :) that is my main character.

**Comment by sioding** [comment]
Can you please add some screenshots?

**Comment by Huggless** [comment]
Yes, i deleted my squig herder because of it but ill take a new picture rn

**Comment by sioding** [comment]
Well - tried my best to reproduce it on the server...
![image](https://user-images.githubusercontent.com/18517842/48313520-feba4500-e5bd-11e8-9741-c1aecd14bdcf.png)

as @Lheana said: seems to be one of the things that are in the client since years but not really reproducable. 

Thanks again for the report. Good luck with the next toon.
