### ISSUE TITLE
WP - Titan's Hammer of Solemnity - no alternate Appearance

### ISSUE THREAD

**Issue by Frostlatte** [WarEmu/WarBugs#12797]
The one handed Hammer of the WP: Titan's Hammer of Solemnity -  cannot change its appearance like the other weapons from the vendor.

![luthmoor_000](https://user-images.githubusercontent.com/9324873/49347554-dfd03f80-f69f-11e8-9568-c219afd0b2fd.jpg)
Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Rydiak** [comment]
I believe it has to do with Titan's Battlehammer of Solemnity being "Main Hand or Off Hand", since all the other 1-hand weapons available to WP appear to be just "Main Hand".

![rydiak_196](https://user-images.githubusercontent.com/15963532/49357035-85c97d00-f693-11e8-9c01-c5b29a95d291.jpg)
![rydiak_197](https://user-images.githubusercontent.com/15963532/49357037-86faaa00-f693-11e8-8323-27b1e99068d3.jpg)

**Comment by Torquemadra** [comment]
that would be it

**Comment by Rydiak** [comment]
Just to add, this likely also affects the 45 SC 1-hander for WP (I believe it is Apostle's Battlehammer of Solemnity) which is also "Main Hand or Off-Hand".

**Comment by Torquemadra** [comment]
I cleaned them all

**Comment by sioding** [comment]
fixed with patch from 08.12.2018

**Comment by Rydiak** [comment]
Any chance of applying this fix to all Warrior Priest scenario 1handers?

**Comment by sioding** [comment]
reopened - will have a look at it @Rydiak

**Comment by NorKalli** [comment]
All 1 handed WP Battlehammers are now main hand only, appearance should new all be swappable.

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
