### ISSUE TITLE
Talisman making requires all slots to be filled

### ISSUE THREAD

**Issue by Luth6409** [WarEmu/WarBugs#1281]
When crafting a talisman you are forced to fill all slots with crafting mats, but iirc it should only force you to fill the "container" and the "fragment" slot.

The other slots should just modify the created talisman (or make it even possible to craft any).

**Comment by Zealote** [comment]
Just to confirm what Luth said: "The top-left square is for your Boxes.  You can’t place anything anywhere else until you have a Box in place.  The top-middle area with the red dot is for your Fragment.  Once you have a Box and a Fragment, you can make a talisman.  The rest of the items are optional to help make the talisman more powerful." (From https://gaarawarrgabs.wordpress.com/2009/11/23/beginners-guide-to-talisman-making , Nov 2009)

[Seems it was changed since if you watch some very old 2008 vids, the 'fuse' button only lit up when you had 2/3 of the other ingredients. That'd explain why I've heard some ppl saying you always needed to fill all slots.]
