### ISSUE TITLE
Problems with ultimate update

### ISSUE THREAD

**Issue by Diablet** [WarEmu/WarBugs#12817]
Hi. Since the last update of the client / updater several things have stopped working: The mouse, a logitech mx revolution, has stopped working the buttons 4 and 5 ... 

To make them work again I have to close the Logitech setpoint or execute the setpoint in administrator mode. 

Apart, the game has stopped sounding in 5.1 multichannel (dolby digital) mode and only sounds in stereo mode. 

These two problems have appeared since the last update. In other games both the mouse and the sound work correctly the buttons and the sound in 5.1...

I hope they solve it as soon as possible or give me a solution to these two problems.

Thanks and regards.

**Comment by sioding** [comment]
Hm kinda strange - i also use the logitech tools and do not need to start them in admin mode to get my other mouse buttons work or anything else. Do you start the launcher in admin mode?

**Comment by Diablet** [comment]
In the game if I run Setpoint in normal mode, the buttons do not work, if I close it and Windows manages it works, if I open the setpoint again in normal mode, it stops working again, if I close it and return it in administrator mode, it works .. In nornal mode they work in any game except with the War. In Windows 10, I have the user account control disabled, so I avoid having to run the programs in administrator mode ... besides, this computer only uses a single account and is an administrator ... And until now there has never been any Permission problem in any application or game. I have uninstalled both the logitech setpoint drivers and the controllers of my Asus Xonar Dgx, cleaned the records with the Trexxy Driver Fushion program and ccleaner, cleaned the logitech and Xonar folders (program files, users and other locations where they are stored) the installation folders) and reinstalled them again with the same results within the War. In other games, both the mouse and the sound card work correctly on the side buttons and 5.1 sound and executing them in normal mode. As I said before, previous to last Saturday's patch worked correctly. It seems as if that update has broken something of the game

**Comment by Diablet** [comment]
Here, one video demostration with the problems.
https://1drv.ms/u/s!AkwfdZKuzirnkBlttUnAUALPoarY

**Comment by sioding** [comment]
I talked to Max about this. The launcher need admin rights since the last update and thats maybe the problem. It´s like the same if you use discord and push-to-talk. Since the launcher update and the admin mode for the launcher i have to start discord also in admin mode to be able to use psuh-to-talk. so using your mouse application in admin mode while the launcher is no also running in admin mode should fix your problem. You wrote it doesn´t - but then we are not able to help. It´s the only report for this. If we have an big issue with that i would face a lot of reports for it - but there is only one. I am really thankful that you gave that much of informations but tight now i have no answer for you how we can halp  with that.

**Comment by notre4ror** [comment]
Hi,
Since this update i have to run several (between 10 and 15) times the launcher, 
maybe the admin rights is messing with the firewalls too? (sometimes takes longer, sometimes takes less time to get the connect button active)

Can I ask, Why I have to run a game with admin rights?
What changed, so now you need to run with admin rights on something what works fine before in user-mode?

Can you make a "Diff" of the related files and see why and when you have changed the permissions needed?
(Maybe someone has run some aplication with admin rights messing without notice the file permisions of the project?)
We are going to be able to run the game without admin rights again or they are here to stay?


Thanks.

**Comment by sioding** [comment]
This isn´t the forum @notre4ror. If you are ingame and got kicked or the client crash i would suggest to use this thread and the tips you get inside: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075

I do understand that you want some clearing on your problems but please do not hijack a report like this. The original reporter came in with a specific question which i have discussed with Max. Your questions are more nonspecific for rights and the launcher. My best guess is to discuss it in the forum. I hope you understand that,

**Comment by notre4ror** [comment]
Hi sioding,
I undestand maybe the second part of my message isn't related to this issue,
but the first part it is.
When you say "It´s the only report for this" maybe for you it is, and i want to clarify/say, i already know people with the same issue, but they don't have time to make reports, (i mean the fact people doesn't make reports doesn't mean there are no issues), so you can add this two more people to the list of players.

**Comment by sioding** [comment]
I will ask Max if he is able to clarify some things in a forum post.

**Comment by notre4ror** [comment]
Thanks.

**Comment by Diablet** [comment]
Thanks.
