### ISSUE TITLE
Items with "unique" 

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#1283]
Items which are listed as "unique" should only allow you to equip one of each of the same item, currently with the new jewelry you can equip all 4 the same.

**Comment by Evildoor** [comment]
Uh, while this was true on live - should it really be fixed? What's the point in restricting players with the jewelry and other things? Also, some scenario weapons (for example, Sentry's Chaosaxe of Brutality) have "unique" stated in their description, which means two of them can't be equipped, which is nonsense.

**Comment by Silentguard** [comment]
Agreed with Evildoor.

**Comment by Nfkillz** [comment]
Agreed with Silentguard

**Comment by Green-Wolf** [comment]
We have to think about this carefully, I agree that it doesn't make sense for the ones you mentioned but is there any very powerful one off items that actually need to be unique. I'm not familiar with enough with WAR at 40 to remember it now but how what about land of the dead jewelry having more than one set? 

If that isnt an issue i'm not experienced enough to say one in WAR but we would want to avoid a situation for example of having an extremely good item that people are only meant to have one of(for balance) and have them stacking it up(Imagine legendary gems from WoW in each gem slot).  

This isnt an issue if you just fix it in the Database, but if it is applied to everything.

**Comment by Thorgatin** [comment]
While the "unique" flag doesn't make sense on the green stuff from the vendors (and other low level jewelry) it is very important on high level items like green-wolf wrote.

Without it, you could just equip the same lodt jewelry four times:
http://werittest4.blogspot.de/2009/06/stuff-to-get-in-land-of-dead.html

And maybe more important, there are also jewelry sets available from PvP tokens that are unique iirc:
http://www.arsenalofwar.com/armor/Order/Skirmisher%20Kit

Without "unique" you could stack for instance only this
http://www.arsenalofwar.com/armor/Order/Warrior's%20Band%20of%20Might
to get huge amounts of weaponskill and you just loose 4% critchance.

As far as i remember the jewelry from the warlord and souvereign sets are also "unique".

**Comment by Evildoor** [comment]
The question is - what items were "meant to have one of(for balance)"? There are some event things (like +18 stat jewelry in RoR), but they don't need to be unique because you can't get two of them (only one quest per character + bind on pickup). PvP jewelry - what's wrong with stacking it? Each part of Skirmisher Kit gives equal amount of stats, so is it really bad to be able to equip, for example, 2 Bands instead of Band + Pin and get 78 WS instead of 39 STR + 39 WS? (btw, all parts of this set have 30+ WS except for Pin, so you won't squeeze too much WS out of it by picking 4 Bands).

**Comment by RoR-Zomega** [comment]
The only issue I see is if the set bonus calculation just counts the number of items in the set equipped rather than the number of unique items in the set equipped, e.g. equipping 3 identical Sovereign jewels doesn't then grant you the 3pc set bonus (with duplicate jewels you can equip 11 pieces of Sovereign armour between the 2 different sets, so you could get a 6pc bonus from one set and a 5pc bonus from another).

If the game already already treats multiple identical jewels as being a single item for set bonuses then this can be ignored - just throwing it out there as a warning :)

**Comment by Evildoor** [comment]
Changelog 12th March 2016

- Items which are marked Unique-Equipped now respect this setting, and only one copy may be equipped at a time.
