### ISSUE TITLE
PQ Mutant Exiles in badlands

### ISSUE THREAD

**Issue by Gwendis** [WarEmu/WarBugs#12881]
Hello,
Bug about Mutant Exiles PQ Destruction Greenskin Chapter 11.
I see there is a Submit about it,
but the PQ works, 
only the influence bar vanish when you enter the area of the PQ, also all the info and stages about the PQ doesnt show.
But the PQ itself works perfect.
Thanks

alexcia

**Comment by sioding** [comment]
Hey - thanks for the report but i don´t get it all. Please add screenshots.

**Comment by Lheana** [comment]
Seems more like an UI issue with influence bar and PQ tracker that don't appear.

**Comment by sioding** [comment]
Seems like a mix of a known issue we can not fix atm and no answer from the reporter. Close

**Comment by KarimaRada** [comment]
Hello @sioding,
you requested screenshots to confirm the issue - please take a look at mine.

![pq2](https://user-images.githubusercontent.com/50321390/57217997-9c427e80-700d-11e9-8e67-69dec46247c6.jpg)
![pq1](https://user-images.githubusercontent.com/50321390/57218003-9fd60580-700d-11e9-89ab-e878ecca0bdb.jpg)

As you can see from the 1st pic., I'm in the PQ area. But neither the stage tracker pops up, nor I can see my influence bar (in the top right corner.) The quest itself seems to be working as the topic starter said since I do gain inf from killing mobs. 
I hope this can be of some help. Thank you for your time.

**Comment by Lheana** [comment]
Issue is on live but not on dev. May be related to map areas.

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
