### ISSUE TITLE
bug with cleansing power tactical

### ISSUE THREAD

**Issue by Oceanman69** [WarEmu/WarBugs#12940]
Expected behavior and actual behavior:

hi,

*Clean your group with "purify" combined with "cleansing power" bugged in rvr and pve aswell.

-First time it happens with a kotbs in rvr, we decide to make some test with my guild in pve.
same thing happened on the south east public quest "defiled anvil"in black crag.
 -We decide to push up further the test without he's auras, without armor special buff, without addons etc ..... etc...... but never works.
-We tried another day with a bright wizard same thing happened.
-Then we start to talk about this problem with other members of our guilds alliances some of the warriors priest report the same bug and said that the only way was to remove cleansing power from their tactical bar.
-Finally i looked for bug report in WarEmu and i found some allready reported but in very specific areas.

-Conclusion: 

-it seems to be bigger than allready reported 
-it happens both rvr and pve
-after our tests and the feedback from multiple warrior priest from our community it seems to be connected to the tactical "cleansing power".

Hope you'll have guys a nice christmas and a happy new year with friends and familly, thanks for your work and make live war again.

Cheers

name in game: Louloute (warrior priest)

**Comment by sioding** [comment]
Thanks for the report and the christmas wishes. I don´t wanna sound rude but for a bug report we need facts not a story - and to make it easier for the devs some screenshots or a video that shows the behaviour. since you found already reported things - please update these reports. A new one - especially this without any precise reproducable informations do not help at all. I hope this was´nt too offensive ... and i wish you a merry cristmas too.
