### ISSUE TITLE
had to change my password and now it says i exceeded login attempts and i'm stuck out of game

### ISSUE THREAD

**Issue by steelfaith** [WarEmu/WarBugs#1297]
how do i get back in?

**Comment by steelfaith** [comment]
i have now managed to login to the forums but cannot login to the game.

**Comment by Evildoor** [comment]
This problem still persists?

**Comment by Evildoor** [comment]
As i've learned, when you change your password it immediately applies to your forum login and with delay (may be pretty long, several hours or even days) to game login. Anyway, from my point of view this is a problem of forum-server interaction rather than RoR bug, so i'm closing this. If the problem still persists, there is a thread (and maybe more than one) on the forum about this.
