### ISSUE TITLE
Squig Herder. Damage per 1 second.

### ISSUE THREAD

**Issue by Tonych1981** [WarEmu/WarBugs#13353]
![default](https://user-images.githubusercontent.com/47569424/52650570-8e43fc80-2efb-11e9-827d-07ff98754f7f.jpg)
As such perhaps, damage from two skills in 1 second. And why is the damage base so high? 932 not critical.
Damage has almost no armor absorption.

**Comment by SecretsOTheP** [comment]
Sneaky Strike:
1) It has a max base ability damage of 375. That's about on par with White Lion's Pack Assault / Coordinated Strike burst, aligns with the 10s cooldown, and has an ability with a whole group attacking. (Melee Squig ability, so mirrors WL in a lot of ways)

Really Bad Gas!:
1) Corporeal, so it won't do any armor absorption.
2) A DoT that ticks every 2s for 6s. I don't believe the DoT applies instantly, so that's why you saw two attacks in the same second. Their GCD was up and thus you were hit 1.5s ago.
