### ISSUE TITLE
[Fortress] damage and bouncing inside the keep

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13530]
Greetings,
last night we defended the MAW.
In the lord room some enemies may inflict damage trought the little jail near the wall, and WL may bounce inside

![puparuolo_143](https://user-images.githubusercontent.com/46483570/53688765-2f7ae180-3d49-11e9-93d3-731d03da6831.jpg)
![puparuolo_142](https://user-images.githubusercontent.com/46483570/53688766-30137800-3d49-11e9-89d4-f202ceff51f2.jpg)

the same bouncing bug happened also in the jail after respawn
![puparuolo_150](https://user-images.githubusercontent.com/46483570/53688769-3f92c100-3d49-11e9-894a-7e38f0535a65.jpg)

cheers!

**Comment by sioding** [comment]
Since we use Game Objects to prevent using this dorr as a normal door - we have to live with the situation as it is atm. It will not be fixed until we either remove the GO´s to let the door being using or been able to edit the fortress walls and remove it. So this gets a close cause its a design decision.
