### ISSUE TITLE
[Crypts and Tunnels] Influence and Event

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#13613]
x2 Event doesn't work with Crypts and Tunnels influence. Chat says 4k but in the ToK it's only 2k.

**Screenshots/Videos or archive.org evidences:**
![wrwer](https://user-images.githubusercontent.com/16005849/54161535-837d7880-4463-11e9-8b60-855e481b9207.PNG)
![daaw](https://user-images.githubusercontent.com/16005849/54161536-84aea580-4463-11e9-83f5-47349e2f9493.PNG)

**Comment by sioding** [comment]
This is working as intended and a design decision.

**Comment by Hargrim** [comment]
Actually, the double influence thing is working - normally without event you get 2x 1000 influence, because there are 2 chapters in both of the dungeons and 2 rally masters, so you can get up to 2 Sentinel Jewels. Here on your screen you get 2x 2000 so it is correctly working. But this is unintended from my design perspective and will be fixed next patch. Thanks a lot for reporting this and let the grind continue!
