### ISSUE TITLE
Goblin Wolf Riders in GS Ch17 aren't "attackable"

### ISSUE THREAD

**Issue by Stebraul** [WarEmu/WarBugs#13703]
**Expected behavior and actual behavior:**
Goblin wolf riders in Greenskin Ch17 PQ don't appear to be attackable, but they are

**Steps to reproduce the problem:**
Look at them, click on them, attempt to attack them

**Comment by Kabucoror** [comment]
I only find them in GS Chapter 6 and they seem fine for me

**Comment by Scophis** [comment]
> Expected behavior and actual behavior:
> Goblin wolf riders in Greenskin Ch17 PQ don't appear to be attackable, but they are
> Steps to reproduce the problem:
> Look at them, click on them, attempt to attack them

Could you specify in which PQ and step those mobs are?

**Comment by Moragor** [comment]
Lets open this up again. It is not a PQ, he's talking about the Bloody Sun Wolf Riders in the area marked in the following map. They are hostile, but attacking them displays the text "Target is not attackable". Since the Bloody Suns are friends, not food I'm sure they shouldn't be attackable. There is no quest that involves killing them, only one [Fightin' Infightin'] that involves using a quest item on one of them. This might have turned him hostile on live, but it's no reason to make them permanently hostile.

![wolf rider](https://user-images.githubusercontent.com/30193675/58548742-357a4480-820a-11e9-8270-a8c637a99564.jpg)
![wolf rider map](https://user-images.githubusercontent.com/30193675/58548745-36ab7180-820a-11e9-85c0-4f9273beabd0.jpg)

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
