### ISSUE TITLE
Initiative 

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#1374]
I believe the stat may be currently bugged. I have been testing the debuffs on it and it seems every 10 points lost grants around 5% to be crit since these debuffs go to 80+ this seems quiet high. 

Thanks to warriorfail for helping me test.

**Comment by Thorgatin** [comment]
You get more from every point invested into initiative, when your have low initiative.
If your initiative is high, you get less from it.

Afaik you can't reach 0% chance to be crit through initiative alone, as you get less and less from it while stacking it.

Iirc a good value to stop stacking initiative is about 10% chance to be crit.
Also: the character window is still not working 100% correctly afaik, so that values might be shown incorrect.

**Comment by Thorgatin** [comment]
http://tools.idrinth.de/tank/?a0l=26&d0l=26&d0a=0&d0pr=0&d0cr=0&d0sr=0&d0er=0&d0i=1000&d0ccr=0&d0bv=0&d0bm=0&d0ws=1&d0pm=0&dN=0

Lvl 26 character with 1000 initiative (absurdly high value) would still have 2,45% chance to be crit.

**Comment by Toldavf** [comment]
just seems a little crazy that one debuff can up your chance to be crit by nearly 40% so I had to report it.

**Comment by Thorgatin** [comment]
On my slayer i have around 20% chance to be crit without any additional initiative jewelry/talis, with fierceness' initiative self debuff up it goes up to 52% chance to be crit. :D

**Comment by Evildoor** [comment]
Since @Thorgatin clarified this problem and no objections are present, i'm closing this issue.
