### ISSUE TITLE
wrong reward in T2 keep gold bag

### ISSUE THREAD

**Issue by Garrthax** [WarEmu/WarBugs#13820]
![ascascasc](https://user-images.githubusercontent.com/49390790/55707613-4a91de80-59e4-11e9-871a-a9e5e2538380.jpg)

Just got gold bag from T2 troll country siege and as WH i got Chosen armor as reward.

**Comment by noazmog** [comment]
Greetings,

I wanted to inform you about an ambivalent bug. This morning, I received a gold bag in my mailbox (thanks to my participation in Thounder Mountains yesturday) with my Shaman (name : Cetelem / Level 17). However, I got «Obliterator Runecuffs» (necessary for Rune Priest whereas I’m a Shaman) instead of «Obliterator Greenbringas». Could you correct this abnormality, please ?
Sincerely,

Cetelem

**Comment by noazmog** [comment]
![bugstuff](https://user-images.githubusercontent.com/49399287/55722637-1aa80280-5a07-11e9-8603-14dcebcf0483.jpg)
Greetings,

I wanted to inform you about an ambivalent bug. This morning, I received a gold bag in my mailbox (thanks to my participation in Thounder Mountains yesturday) with my Shaman (name : Cetelem / Level 17). However, I got «Obliterator Runecuffs» (necessary for Rune Priest whereas I’m a Shaman) instead of «Obliterator Greenbringas». Could you correct this abnormality, please ?

Sincerely,

Cetelem

**Comment by sioding** [comment]
Duplicate of #11739
