### ISSUE TITLE
[Tactic] Aimin' Quickly not working properly

### ISSUE THREAD

**Issue by mursaat1337** [WarEmu/WarBugs#13952]
The tactic for SH Aimin' Quickly reads as "Plink and Poison Arrer now builds up 1 second faster."
The skill Plink is base 2 second cast. This tactic brings it to 1 second but sometimes it does not and I catch myself seeing 2 second cast plinks and I have a screenshot of it slotted and casting plink at 2 seconds.

![aiming quickly bugged](https://user-images.githubusercontent.com/50028473/56826854-385cd080-682b-11e9-95f3-688ce846af56.jpg)

**Comment by zulnam** [comment]
Can confirm the issue is also present for Posion Arrer.

**Comment by grunbag** [comment]
i can't reproduce

**Comment by zulnam** [comment]
After relogging and equipping the skill again I also cannot reproduce it. Went to the trainer to respec the same tree and still CNR.

CNR.

**Comment by grunbag** [comment]
CNR ?

**Comment by zulnam** [comment]
Can Not Reproduce

**Comment by grunbag** [comment]
Ok , i close ticket until we can precisely know how it happened

**Comment by rasmusbh87** [comment]
> Ok , i close ticket until we can precisely know how it happened

I have been able to reproduce this bug, and it is still here. I uploaded a video evidence here:
[](https://www.youtube.com/watch?v=U8k8AsXzSHg&ab_channel=RasmusBrandtHansen)

The bug appears when your Battle Rank changes, it seems. 
And it destroys the desire to run Path of Big Sootin', because you _constantly_ have to manually switch tactics, like I do in the video.

This really needs to be fixed.
