### ISSUE TITLE
Chapter 1 Chaos: PQ Ruinous Powers

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#13991]
**Forum name**

Ototo

**Related Issues**

This still happens:
https://github.com/WarEmu/WarBugs/issues/9108

**Expected behavior and actual behavior:**

The NPCs roaming around give the message shown in the screenshot. They can still be attacked though, so I would consider this a minor annoyance more than a real bug.

**Steps to reproduce the problem:**

Try to attack any of them.

**Screenshots/Videos or archive.org evidences:**

![Naggarythe_005](https://user-images.githubusercontent.com/50114048/57014544-7b8eb900-6c08-11e9-9e9b-40f1b0336878.jpg)

**Comment by Ootootoo** [comment]
Seems to happen in other NPCs that disappear upon quest or PQ reset, like can be seen in this other screenshot from Chapter 7 Dwarf:

![Valaye_000](https://user-images.githubusercontent.com/50114048/57014877-ec82a080-6c09-11e9-941d-09fbf9b20b33.jpg)

**Comment by Lheana** [comment]
Thanks for report, will be fixed with next patch.
Nevertheless:
- First your forum name is not needed
- Second, the report you linked is not related to the same issue, just the same PQ which is different
- Eventually it's **one issue per report**, so for the same kind of issue but about different NPCs/quests/etc, **open one report per issue**

**Comment by Ootootoo** [comment]
I'm sorry, I will keep all that in mind :)

**Comment by sioding** [comment]
fixed with patch from 05.05.2019
