### ISSUE TITLE
Gunbad Mid. Ard to Feed

### ISSUE THREAD

**Issue by DillPickle420** [WarEmu/WarBugs#14048]
After first wipe, boss started with rage.
Buttons were invisible sometimes.
Boss would rage repeatedly even after buttons were clicked on time.

**Comment by NorKalli** [comment]
I did the boss twice in the past 48 hours with no issue, even after wiping several times. Without a video I can't recreate the problem

**Comment by biglimey** [comment]
If your group wipes to Ard Ta Feeda and not everyone in the group dies or zones out, (you can leash him to avoid dying) the boss will be bugged the next time you engage him.  He will not spawn Squigs to chase people and will be permanently enraged.

**Comment by VharneIzor12** [comment]
Had a similar issue happen to day in Gunbad as well. Ard' To Feed's Globs were unattackable, buttons would phase out of existence occasionally. As for raging, I can not attest to to that fact. Was with my same group as posted on my issue I posted as well. This was around 3:30 EST 5/11/2019

**Comment by biglimey** [comment]
Also many other bugs with this fight include, bubbles despawning randomly if people standing near them, tower illuminating, button getting pressed, tower de-illuminating but boss still being enraged, making people think they did the button right but it didn't actually work.  Only way to really tell if boss is enraged is the tank checking his damage intake.  Sometimes you get 2 sets of squigs active at the same time (supposed to be 1 at a time) and sometimes the squig swarm will spawn right ontop of a healer and stunlock kill them to death, especially low armor healers like shaman/zealot.  Everytime you zone in after a wipe to one of these bugs each person has a chance to get zone 0'd which can be infuriating because you can get zone 0'd multiple times in a row zoning in even while dismounted and walking in backwards which is supposed to help reduce the chance.

If you can't fix the zone 0 I reccomend atleast
Portal from Main City to Gunbad that anyone can access or allow scrolls to be purchasable by anyone regardless of guild or guild level.  Not everyone is in a high level guild that does this pve.
Create a portal from Gunbad entrance to Boss zone in location once PQ has been cleared so you don't have to run all the way back down when you get zone 0'd.
Reduce Ard ta Feeda's Enrage damage or duration.

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/13395

**Comment by Estienne1985** [comment]
Have killed Ar'da Feet 20 mins ago with my party. Nedeed only this kill to finish "the threat from Ar'da feet quest" and get finally my red eye chest, so i could wear full red-eye set.
I got no kill counted for my quest, still have 2/3 in my Tome.
Can anyone help with this issue pls?

**Comment by Kaelang** [comment]
> Have killed Ar'da Feet 20 mins ago with my party. Nedeed only this kill to finish "the threat from Ar'da feet quest" and get finally my red eye chest, so i could wear full red-eye set.
> I got no kill counted for my quest, still have 2/3 in my Tome.
> Can anyone help with this issue pls?

This is a live issue - irrelevant to this report. The staff cannot give you the kill credit. Please make sure you are reading the reports before posting. I have deleted your other message on a separate report.

**Comment by Estienne1985** [comment]
Got it,
Ty anyway for the reply

Inviato da iPhone

Il giorno 22 apr 2020, alle ore 13:08, Kaelang <notifications@github.com> ha scritto:

﻿

Have killed Ar'da Feet 20 mins ago with my party. Nedeed only this kill to finish "the threat from Ar'da feet quest" and get finally my red eye chest, so i could wear full red-eye set.
I got no kill counted for my quest, still have 2/3 in my Tome.
Can anyone help with this issue pls?

This is a live issue - irrelevant to this report. The staff cannot give you the kill credit. Please make sure you are reading the reports before posting. I have deleted your other message on a separate report.

**Comment by grunbag** [comment]
fixed recently
