### ISSUE TITLE
White Lion pet skills bug

### ISSUE THREAD

**Issue by Camroin81** [WarEmu/WarBugs#14077]
There are problems with the pet. changing zones or even sometimes in combat the lion disappears or turns off by starting the cooldown to recall it and not allowing to use skills like Leonine Frenzie or Brutal Pounce.
And sometimes it disappears without reason.

**Comment by sioding** [comment]
Are you level 40? Does it happen in T2/T3 zones only ?

**Comment by Camroin81** [comment]
yes im level 40 and it happening in t2/t3 and t4 atm at me

**Comment by Nithryok** [comment]
I recently started playing RoR, I can confirm this bug has been happening at all lvls on my WL. To me it feels aggressive stance has the bug happen less often, but defensive and passive stance have it happen all the time. I believe part of the bug has to do with where you spawn the lion, and where it last entered combat.

If you spawn the lion and run about 3 screens away from where it spawned and tell the pet to attack, it teleports back to where it was when it was spawned and then runs to you. 

If you were in combat and combat ended and you move about a screens distance and issue attack command, the lion goes back to where it last entered combat and then runs to you.

Once you enter combat and use the lion skills there are no issues, but if your character leaves combat the above bug then happens again.

This bug also happens if you summon your lion and then mount and ride off, when entering combat the lion teleports back to where you mounted.

IMO there is some desync between where the lion shows it is on the screen and where the game thinks the lion is. I believe it is not following the player all the time, even though it looks like it is on screen.

I would be happy to provide any more answers to help fix this issue as it makes me feel my WL is useless.

**Comment by stortzm** [comment]
I'd like to add that I've seen this bug happen with the squig too.
This has also been mentioned here: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=31698&start=30#p359008
It happens fast so I don't have a screenshot of it.
This is the behavior I've seen:
 

> If you were in combat and combat ended and you move about a screens distance and issue attack command, the lion goes back to where it last entered combat and then runs to you.
