### ISSUE TITLE
Kotbs Aura Now Our Chanse! activating from 2nd and 4rth morales.

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#14117]
![0now our chanse](https://user-images.githubusercontent.com/18173840/57973866-0c5ee600-79b8-11e9-958f-5f80ee0dd543.jpg)
It's activating on destro players in mass rvr fights from 2nd and 4rth aoe morales like from engies or shwarrios on 5 seconds without reason. Sometimes it have not 25% description in tooltip but 50%.

**Comment by sioding** [comment]
Well - read it more than 3 times and don't get it. Please try again.

**Comment by Lefze** [comment]
Pretty simple, the right side debuff he has- Now's Our Chance!, isn't supposed to be there unless he is within 30ft of a Knight of the Blazing Sun. It's also not supposed to have a timer on it in the first place. The bug here is that the debuff is present in the first place, presumably applied by the SW morale he has ticking on him. Only really unclear part here is if it's a visual bug, a different debuff just applying the wrong debuff visually or if his outgoing healing is indeed reduced by 25%.

**Comment by grunbag** [comment]
please explain which morale triggered uit lefze, it will save a lot of time

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
