### ISSUE TITLE
[WP] Apostle's Tome of Reverence possibly wrong stats 

### ISSUE THREAD

**Issue by ilferro** [WarEmu/WarBugs#14131]
I fully understand that the new equipment should not be too strong compared to the previous one but here we are exaggerating
![asd](https://user-images.githubusercontent.com/16581052/57988823-e2c6bd00-7a92-11e9-88fa-9341a0e8650e.jpg)

**Comment by CrimsonFenris** [comment]
AP per second is totally useless for Salvation WP, for who those items are meant for. 
Please revisit those stats (lower in new version instead of being 20% more, as lv item is suggesting), and useful bonus instead of PA/sec (really anything beside offensive stats will be good, like magic resistance, initiative, crit reduction, toughness... Literally anything). ;)

Besides, no proc on any of those weapons make them sub-par from subjugator (wich are really good for WP).

**Comment by wargrimnir** [comment]
AP shouldn't be on healing gear for WP/Dok, will address

**Comment by wargrimnir** [comment]
Replaced Dok/WP heal spec weapons with 3 Morale Regen instead of AP
Updated two Ironbreaker weapons set incorrectly

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
