### ISSUE TITLE
[Bastion Stairs] Gahvloth Darkrage Enrage.

### ISSUE THREAD

**Issue by Nefarian78** [WarEmu/WarBugs#14293]
**Expected behavior and actual behavior:**

Boss should enrage when pulled too far from spawn or when his pet dies. Currently, the boss enrages for no reason whatsoever and at random. Me and my group found no way to beat the boss as the enrage could happen even only a couple of seconds into the fight, forcing us to skip the boss.

**Steps to reproduce the problem:**

Just engage the boss. We tried a few times and it always happens at a certain point

**Testing Screenshots/Videos/Evidences (always needed):**

I didn't take any evidence as the problem can be reproduced very easily and happens every fight from the looks of it

**Comment by grunbag** [comment]
I will move boss  bit more close to the middle of the room . Try to tank him on the east side for now

**Comment by flannelok** [comment]
Actualy its mechanic - you can keep dog to far and you cant kill him couse he enrage. You can't pull him out of room. The problem is in his spawned aoe. We tryed to pull him out and kite around the room, when the tank stank in 2-3 aoe shit its oneshoting. And you realy can cover aoe all the time cause its fade sway but actually you get dmg(probably some visual bug.)

**Comment by grunbag** [comment]
Fixed already
