### ISSUE TITLE
Ironbreaker Runic Shield issue 

### ISSUE THREAD

**Issue by Coeno1979** [WarEmu/WarBugs#1430]
As the tooltip says, this skill has to absorb "magical damage". This includes spells and melee damage (for example, Chosen ravage). Only if you are hit by a spell, your grudges increase. Instead of that, Runic Shield only absorbs spells now. This was tested in the original WAR.

**Comment by M0rf** [comment]
It should absorb only spells, skills like ravage are melle skills and work off str not int which is why runic shield should not absorb them.

**Comment by ozarmidrashim** [comment]
Affirm, RoR implementation does not use a magical flag on damage - anything that scales with Intelligence is considered magic. Otherwise you'd have the strange situation in which attacks that are not magical but deal a non-standard damagetype (Ravage, Ensorcelled Blow, Festering and Poison Arrers, etc) are punished as both physical and magical attacks.

**Comment by Coeno1979** [comment]
I appreciate your opinions about this skills, but the fact is this: in previous WAR, Runic Shield used to absorb all magical damage, certain melee attacks included. Unfortunately, i didnt take screeshots from this combats, but i think all ironbreakers can confirm this. Runic shield used to absorb ravages in Mythic Game. And i know its not the final truth, but, according to Hammer wiki and other databases, magical damage includes certain melee damage, like chosen attacks. And the tooltip says that absorbs magical damage

**Comment by Evildoor** [comment]
@Coeno1979 provided a video:https://www.youtube.com/watch?v=jMMscxnij1M
3:40-3:42 is an moment of interest, according to him. You can read his full post in https://github.com/WarEmu/WarBugs/issues/1471

**Comment by Coeno1979** [comment]
Please, remove the "Dubious" tag and look at the demonstration video above.

**Comment by Tesq** [comment]
should work that way, i remember i got my ravage absorb, also those skills that absorb physic damage (dok/wp moral 3) didn't  block skill like ravage.

**Comment by Zealote** [comment]
I don't know how it was on live but since *magical* defences (i.e. resists) are used to defend against magic dmg physical attacks, it seems reasonable that other defence modifiers should work the same way, whether they're absorbs or % reductions (e.g. BO's Savin' me hide, that ability they get later on that reduces target's physical dmg, BG's magical dmg reduction tac, etc etc), or whatever else.

It also seems to make sense that there'd be 4 types of dmg: melee physical, ranged physical, melee magical, ranged magical, first two reduced by armour, other two by respective resistance.
-----
Just to check, does Azarael still receive notifications about closed threads?

**Comment by Coeno1979** [comment]
Runick Shield is broken at this time. I tested this in duels. But i dont know if Azarael saw my demostration. We need to fix this.

**Comment by Luth-RoR** [comment]
Is this still an issue?

**Comment by Zealote** [comment]
Just for reference, this forum thread's relevant, and might be a good place for any discussion/debate if necessary: https://www.returnofreckoning.com/forum/viewtopic.php?f=74&t=14562

Obv only Azarael can comment on the actual code, but I imagine this is similar to the general bug with dots and dmg modifiers, in that it's being deferred as it'll require a general re-work of the way stuff's calculated. I.e., as mentioned above, there'll need to be some way of flagging non-int-based magic dmg attacks as doing "magical dmg".

One other point, as I said in that thread: I'd assume (haven't tested it) this is more general than just IB's Runic Shield. E.g. BG's Malekith's Bulwark/BO's Savin' Me Hide presumably don't affect dmg from engis/SMs etc.

**Comment by Torquemadra** [comment]
To note, Runic shield also absorbed red soul on live.
