### ISSUE TITLE
[Bastion Stair][Influence Reward][Bloodlord Tome / WP] wrong proc on healer book

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#14323]
Hey,

despite the Bloodlord set is an off set, there is a book for healer (yay!). Unfortunately, it has the +dmg/-heal proc on the book, which looks like the proc for the dmg weapons. I think this should be an another proc for this book. :)

![book](https://user-images.githubusercontent.com/23266079/58764013-a69b5e00-8562-11e9-9cb6-462044738e04.png)

**Comment by dalen** [comment]
Same applies for the DoK chalice

**Comment by CrimsonFenris** [comment]
Had same thought, +%damage on tome serves no purpose at all, like was the previous +AP on SC purple tome...

**Comment by NorKalli** [comment]
Considering just removing books and chalices altogether. will revisit

**Comment by dalen** [comment]
Can't this be changed to +5% healing, but same reduction of armor and toughness as weapons?

**Comment by CrimsonFenris** [comment]
Would love to see original BS tome, but reverted effect : do 5% more healing, but all your damage are 5% less effective. Kind of a no-brainer and not really a malus (since healing WP/DoK wont do damage at all most of the time).
Anyway, any proc or bonus will be far more useful than current ones, tbh (subjugator one is dangerous, counterproductive at best, sentinel ones are useless since there is no healing crit to be on par stat-wise).

Stat-wise, BS tome is pretty good (+init is a good tradeoff from +wounds with usual WP build).

I really hope for a useful proc (Aid X is not OP but at least useful) of a straight increase in healing (with a fitting malus if too powerful), since healing base values are still not very high for both WP and DoK.

Or give it a proc for a slight Righteous Fury regen, like 5% on direct heal to regain 15 RF on 3 seconds, to not make it OP with Onslaught/Vanquisher procs.

**Comment by raptrr** [comment]
As this is not kind of a bug for me I will close this.
