### ISSUE TITLE
[NPC] Lycithas the Harridan Seer

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#14494]
Just noticed that there is unreachable NPC in one of IC banks with quest. It can be seen AT 19,7-38. Looks like it was mistakenly placed in blue bank abyss.
![Veszal_135](https://user-images.githubusercontent.com/42712833/60382849-6fd93a80-9a71-11e9-8ace-6d3ed716bb5a.jpg)
![Veszal_136](https://user-images.githubusercontent.com/42712833/60382850-749dee80-9a71-11e9-9b53-9affc5657ed5.jpg)
![Veszal_137](https://user-images.githubusercontent.com/42712833/60382851-78317580-9a71-11e9-93c2-b0faa3eafd03.jpg)

**Comment by Lheana** [comment]
You see Lycithas on your map because this NPC is under, but there is no problem with that, this NPC is where he is supossed to be. If you wanna talk to Lycithas, use the portal in the middle under the Monolith, as mentioned here https://wiki.returnofreckoning.com/index.php/The_Inevitable_City_Noteworthy_Persons
