### ISSUE TITLE
Bastion Stairs weapon

### ISSUE THREAD

**Issue by IceandFire1985** [WarEmu/WarBugs#14496]
Hey,

After u double inlfu from BS i finnaly get weapon from the dungeon, but saddly i cant equip it. I got full Sentinel set and i can equip Bloodlord, but weapon cant be equip.

**Comment by sioding** [comment]
Thanks for the report but that doesn't help. The name of the weapon? Any screenshot from your Influence .. maybe a bit more than that.

**Comment by Furrikson** [comment]
![BS weapon bug](https://user-images.githubusercontent.com/19292844/60383195-394df080-9a6e-11e9-9004-c792a73c59a2.jpg)

**Comment by Furrikson** [comment]
![Full Wards](https://user-images.githubusercontent.com/19292844/60383217-8631c700-9a6e-11e9-8852-eeafdcee2404.jpg)
As u see i got full Senti, so its not Wards issue

**Comment by Bejkon** [comment]
Had the same problem, couldnt equip the bloodlord wep with Greater Ward which i should, as per the Tool Tip of the weapon.

Just now finished the Bloodlord set(exc. cloak) and thus got the Superior Ward, and that did it, now i can use the wep.

So either the req is wrong in the back end, or the TT is ment to state superior ward instead of greater.

![Bloodlord Weps](https://user-images.githubusercontent.com/35146895/60388692-915c1580-9ab5-11e9-95cb-71b430e8f33c.JPG)

/Bejk

**Comment by IceandFire1985** [comment]
At this point i need another 2 fulls run to finish Bloodlord Set. So... it sucks

**Comment by grunbag** [comment]
Req superior wards , tooltip is wrong

**Comment by Ysaran** [comment]
I'm having same problem with this weapon
![Zputakatarro_027](https://user-images.githubusercontent.com/47554048/60396425-d88fe800-9b41-11e9-9b12-b6725039c7f2.jpg)

**Comment by anarchypark** [comment]
it needs BS ward?
i have equipped weapon without it.
![no_ward](https://user-images.githubusercontent.com/19988772/60402957-c067a980-9bd1-11e9-8141-3cc396acb2ac.jpg)

**Comment by grunbag** [comment]
Fixed for next patch , it will correctly require greater wards

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
