### ISSUE TITLE
2nd simultaneous fort crashed zone/server when 1st fort locked 2nd required pairing for All Zone reset

### ISSUE THREAD

**Issue by detanglerr** [WarEmu/WarBugs#14510]
This actually happened to me twice (how lucky of me) First on Saturday June 29th, then again on June 30th.  1 pairing was locked for Destruction, and the 2 other pairings had simultaneous fort battles.  The other fort was a successful lock for Destruction which then lagged out and crashed the fort zone we were in.  On the Saturday fort we were able to get back into the fort and finish the fight after reforming warbands.  Sunday the entire server crashed - not sure if it was related.  Sorry i don't have screenshots of it all or anything.

**Comment by Natherul** [comment]
We are trying to fix the issue where the entire server crashes due to memory issues. As such we have employed an aggressive GC. This does however mean that in some cases the clients disconnects as they time out as server is busy with the GC.

This is an ongoing issue we are working on and is not directly attached to fortresses apart from that its extra taxing for when the entire campaign resets currently.

**Comment by sioding** [comment]
This is fixed
