### ISSUE TITLE
Couldnt get back in FORT after crash

### ISSUE THREAD

**Issue by Getku** [WarEmu/WarBugs#14588]
I crashed at 12:00 PM Fell Landing fort. We were clearly winning the defence and i had 20-25 kills and flags taken.... I couldnt get back in after crash to fort...

- Lonkero

![Lonkero_003](https://user-images.githubusercontent.com/51135236/61209770-50920c80-a703-11e9-8324-71c0f8980b65.jpg)

**Comment by Getku** [comment]
PS. we won

**Comment by Getku** [comment]
I rolled 1 in bags... didnt get medallions or renown

**Comment by Natherul** [comment]
This is consistent with not having enough contribution. I can say that kills do not currently count for contribution and I wont say the limit on whats needed to hit this. But suffice to say the barrier is very low.

**Comment by Getku** [comment]
I CRASHED IN THE FORT WHERE I WAS FIGHTING ORDER FOR 25 MINS. AFTER I CRASHED I COULDNT GET TO THE FORT BACK !!!!!!!!!!!!!!!!

**Comment by Getku** [comment]
WHY DID YOU CLOSE THIS CASE?

**Comment by wargrimnir** [comment]
If you want answers, and want to avoid problems, change your tone. We're here to work on the game, not personally service you.

**Comment by Getku** [comment]
Well, why would you just close this case without any decent answer? I didnt afk at fort, i fight there fair and with winning attitude. This is not a problem of my contribute being low. Its that i didnt get back to the fort after i crashed there. and when the fort was over i didnt get any REWARDS. This is a BUG in a game. Or is it just normal that if you crash your whole contribution to the game, fort and for your guild is gone? 

I really do love this game, played since live. I know everything isnt done and needs to be fixed, Im okay with that. And if I can accept that, you guys should accept that if game crashes and you have done everything in your power to win fort BUT you dont get rewards iiiiiis kinda messed up!

**Comment by wargrimnir** [comment]
There's also a level of players that will happily exploit any avenue of free or easy rewards. If we could simply implement a forgiving system that assumes the best, we would. However, any time we do, it kills the game because a significant amount of people would rather AFK than engage in gameplay causing imbalances that ruin any semblance of a decent fight. Because of this, contribution based rewards and mechanics are probably the best we can do.  We are extremely confident through personal experience playing with these systems that they do weed out players with the lowest contribution. As you've presented no evidence otherwise, there is nothing in this report of value that we can act on.

**Comment by Getku** [comment]
You do understand that with servers "stable" as these its bit risky. And to that "evidence".... What do you need to take me or any other player seriously or to consider this as a case?

**Comment by Natherul** [comment]
> You do understand that with servers "stable" as these its bit risky. And to that "evidence".... What do you need to take me or any other player seriously or to consider this as a case?

I would recommend lowering your settings, removing ALL addons and delete the cache folder. I run many forts and so far I have only ever had 1 crash in a fort. The crash is not related to the server. 

As for why it was closed is because the only reason someone would not get a reservation back or get any rewards in the end means that the contribution was low, and I cannot go into details on what that limit is or exactly how its gained but fighting in the fort normally should mean that this should not be an issue.

**Comment by Getku** [comment]
Then video records should be fine next time to proof that this was a bug. I even saw you there Natherul in your orc armor and in my opinion you didnt do much as we did with our group "we had full party with healers tanks and me mara with aoe choppa funneling and killing melee dps from postern" buuuuuut i know its not enough evidence.... To the nextime gentlemens

**Comment by Natherul** [comment]
> Then video records should be fine next time to proof that this was a bug. I even saw you there Natherul in your orc armor and in my opinion you didnt do much as we did with our group "we had full party with healers tanks and me mara with aoe choppa funneling and killing melee dps from postern" buuuuuut i know its not enough evidence.... To the nextime gentlemens

Ill add again that kills do not count. Stage 3 has very little gains currently in the form of contribution, thats being added next patch
