### ISSUE TITLE
Cold Ones in Guile's Strenght quest

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14674]
Expected behavior and actual behavior:
The Cold Ones you release in this quest do not move at all, they are supposed to attack the mourning high elfs down the path in front of them.

Steps to reproduce the problem:
Open the gates to complete the quest, they will just sit there inside their fenced area.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_000](https://user-images.githubusercontent.com/53320075/62015768-d6db3380-b184-11e9-8b35-6c73a1969255.jpg)
![Austherus_001](https://user-images.githubusercontent.com/53320075/62015769-d6db3380-b184-11e9-80b7-0d6ca612ecf7.jpg)
![Austherus_002](https://user-images.githubusercontent.com/53320075/62015770-d6db3380-b184-11e9-925d-d667cbe38f6f.jpg)

**Comment by Lheana** [comment]
Okay I will try to make it as clear as possible: Bugtracker is for bugs, which means minor things like Cold Ones that are meant to go out when you open the door are not for BT. Moreover, I have personally corrected and reworked every Dark Elf quest, so it means they all work, but yes some don't work like official yet. We are aware of it, but it's minor and it does not prevent from completing the quest. You must understand RoR is a whole world to rebuild, and workarounds are made because we don't always have the time/features to make it like official.
So please, report only **real bugs** which means only issues that prevent someone from doing something (i.e. completing a quest, killing an NPC, completing a public quest, etc).
