### ISSUE TITLE
Prize of War quest - Kharaidon

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14679]
Expected behavior and actual behavior:
After taking the key and opening the chest, you return and fight Kharaidon. He's supposed to be summoned after the dialogue with the sorceress, but just stays underground. After you hit him, he'll fight normally. He stays in a T pose after dying. He's also always visible in his corner, before and after the quest is complete.

Steps to reproduce the problem:
Getting to that stage in the quest.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_010](https://user-images.githubusercontent.com/53320075/62021123-1cefc180-b19c-11e9-94bb-f99c6a208ea7.jpg)
![Austherus_013](https://user-images.githubusercontent.com/53320075/62021124-1cefc180-b19c-11e9-9369-019232893ff7.jpg)
![Austherus_015](https://user-images.githubusercontent.com/53320075/62021125-1d885800-b19c-11e9-99f2-d1c4ae7243c5.jpg)

**Comment by Lheana** [comment]
Okay I will try to make it as clear as possible: Bugtracker is for bugs, which means minor things like an NPC that is meant to spawn when you accept a quest, are not for BT. Moreover, I have personally corrected and reworked every Dark Elf quest, so it means they all work, but yes some don't work like official yet. We are aware of it, but it's minor and it does not prevent from completing the quest. You must understand RoR is a whole world to rebuild, and workarounds are made because we don't always have the time/features to make it like official.
So please, report only **real bugs** which means only issues that prevent someone from doing something (i.e. completing a quest, killing an NPC, completing a public quest, etc).

**Comment by Austherus** [comment]
Ok I'm sorry Lheana, I never did this before. I was just trying to report as many things as possible because I want to be useful. I'll try to avoid anything that's not completely game breaking for now on.
