### ISSUE TITLE
Chosen spell - Blast Wave 

### ISSUE THREAD

**Issue by moist666** [WarEmu/WarBugs#14713]
Sometimes when using Blast Wave the curse that is supposed to decrease wounds on target actually increases...... very very annoying.

-Moisstt

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by moist666** [comment]
Hello i have a mp4 file but it wont accept format

**Comment by moist666** [comment]
[https://www.dropbox.com/s/wqexx1fyj3omv1a/bug.mp4?dl=0](url)

**Comment by moist666** [comment]
Hello????

**Comment by wargrimnir** [comment]
Not bugged. Next time try to verify with someone in-game that knows what they're doing.

When total HP is lowered, the percentage of HP remaining goes up because they have less total HP. They don't actually gain any HP. Wounds debuffs don't deal damage, they just reduce total HP.

If you're at 600 total HP, and your wounds debuff brings you down to 500 total HP, the health bar would still appear to be at 100%, but you're still missing 100HP.

If you're at 400 out of 600 total HP, and your wounds debuff brings you down to 400 out of 500 total HP, it appears that you've gained HP by percentage. 400 / 600 being 66% and 400 / 500 being 80%.

**Comment by moist666** [comment]
Very sorry about that. Remind me not to smoke weed and report bugs...
