### ISSUE TITLE
Focused Mind

### ISSUE THREAD

**Issue by hoppolek** [WarEmu/WarBugs#1477]
When using focused mind on my bright wizard it says: 2% faster cast time AND 50 % faster cast time. It feels like it's the normal one, so I guess it's a 2% faster cast. I don't know if it happens just sometimes, or since the last patch.

**Comment by Tyramissoux** [comment]
Confirmed. Same effect on sorc. Must have been a smaller change from today. Yesterday it was still working.

**Comment by magter3001** [comment]
I know on my Shaman that it increased my cast time on my abilities by 0.1 second instead of decreasing it by 50%. So my group heal would have a 2.6 second cast time instead of 1.25 that it should be. It's not a UI error either as the target wouldn't be healed until after the 2.6 seconds pass. Same thing on my sorc.
