### ISSUE TITLE
lingering fire and wildfire doesn't crit anymore

### ISSUE THREAD

**Issue by harkerkane** [WarEmu/WarBugs#14854]
bw tactics lingering fire and wildfire were able to make crit damage. Now the two tactics are just doing flat damage 
**Expected behavior and actual behavior:**

those tactics were always able to crit . now lingering fire tic hit at 160 and wildfire  at 256 max damage. 

**Steps to reproduce the problem:**
spec ae with wildfire and lingering fire and spam flame breath and scortched earth on target . the procs should be up in combat log but dont show any crit with full combustion (55% crit)

**Testing Screenshots/Videos/Evidences (always needed):**

![Pyrosius_004](https://user-images.githubusercontent.com/45519748/63679628-c9a47980-c802-11e9-9fc4-9ff5bdd26050.jpg)

the screen shot show the combal log and dpsmeter max damage on those two tactics

**Comment by grunbag** [comment]
Proc or damage triggered by abilities don’t crit since 1.2.0. Here mythic patch note :

Balance Changes:
Abilities which proc or trigger damage will now correctly be based on their respective resistance types will not critically hit and will be mitigated appropriately. Specific abilities for each career affected by this change are noted below.
Items which proc or trigger damage will now correctly be based on their respective resistance types will not critically hit and will be mitigated appropriately.
