### ISSUE TITLE
[Renown Points]Relog Reset

### ISSUE THREAD

**Issue by osium** [WarEmu/WarBugs#1486]
re logging wipes all the renown traits trained and does not return the renown points

**Comment by Evildoor** [comment]
Seems to be visual only.

**Comment by Evildoor** [comment]
Some additional info - server-side handling of renown points is correct as far as i've tested. The problem is that you have to remember which passives have you spent your points on. For example, if you put 4 points into STR (Might 1 + Might 2), then relog, then reach RR 10, you can purchase Might 1 again, Might 2 again and then Might 3, even if the renown training window shows that you don't have enough points.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
