### ISSUE TITLE
Tor Anroc guards

### ISSUE THREAD

**Issue by osium** [WarEmu/WarBugs#1490]
I reported this before but you can still camp right beside the guards with the item and the guards still aggro

**Comment by Evildoor** [comment]
What about https://github.com/WarEmu/WarBugs/issues/1462 ? Or this does not happens all the time?

**Comment by Rilos** [comment]
I had this happen to me today.  Destro picks up the Bauble and run back to their guards for protection, leaving our ranged dps to kill the tank holding it.

**Comment by ozarmidrashim** [comment]
Artifact won't tick if they do this.

**Comment by Tesq** [comment]
they can simply run head and you cannot follow em unless risk to get Knock down in lava or being killed by guards, can we simple have no longer guard hit us, as it was on live. They should kill ppl only that get knock back inside the tunnel. Put em a little back with a lesser range. SC that have  higer pop spot dont have invasive guards EX: gates of ekrund viceversa look at norderwatch.

**Comment by osium** [comment]
the issue is they can hold it just outside range so it ticks then whenever their is a push they run back the guards need to not aggro down from the spawn at all

**Comment by Evildoor** [comment]
I see two problems here:
1) Guards aggro range too big. I agree with Tesq - guards exist to prevent spawn farming (i don't mean what happens now, i mean hypothetical situation with no guards at all and no high ground, when you resurrect and get immediately killed by enemies standing on exact spot of your respawn), which is pretty much impossible on this scenario because of high ground. Therefore, they should be moved further into the tunnel and their aggro radius should be significantly lowered - then they'll do their job of killing people punted into the tunnel and overeager WLs pouncing up there without instagibbing normal players who only want to get the artifact.
2) Ability to take artifact to the spawn - even if 1st problem gets fixed, this would still be possible. #2547 will be used for this.

**Comment by wargrimnir** [comment]
Fixed in the recent patch. The Thing will despawn if you get too close to either spawn point.
