### ISSUE TITLE
[Dwarfs] Echelon Weapon

### ISSUE THREAD

**Issue by joschika77** [WarEmu/WarBugs#1494]
IB can't buy the LvL 25 Echelon Weapon (32.0 DPS) by the vendor in AD. I think that affects all Dwarfs.

Testest with Slayer and IB. Strange!!!

**Comment by Evildoor** [comment]
You mean there is no lvl 25 weapons for IB/Slayer? This is possible, since RVR vendors have these "additional" weapons for lower levels. Let me explain a bit:
1) Each tier has 2 sets of green gear, Militia/Vengeance, Dominion/Conguest, Sentry/Echelon, Martial/Vanguard.
2) Each type of item is tied to a certain level. For example, at level 9 every class can buy a chest of Vengeance.
3) Weapons of Vengeance are tied to level 8. However, there are some "additional" weapons for lvl 4 which are also called "something of Vengeance", have worse stats than lvl 8 ones, but better stats than Militia weapons. These weapons are not for all classes - i'm pretty sure that there is a bow for SW, but no handgun for WH.
4) Lvl 25 Echelon weapons are the same "additional" weapons compared to "real" Echelon weapons which no one can equip since we are restricted by lvl 26.

I've always wondered why Mythic implemented these weapons into game, since they provide advantage to certain classes (not at 40/80 ofc, but still). I have plans to discuss this matter with the dev team, but don't expect much for now.

**Comment by joschika77** [comment]
thx for the response, you have understood me correctly,  Then it's not a bug.

**Comment by Evildoor** [comment]
Fixed in T4 patch.
