### ISSUE TITLE
Appearance Item bug

### ISSUE THREAD

**Issue by Rildetarma** [WarEmu/WarBugs#14986]
I have a rr 80 Engi.  For the wrench option I use the Sniper Spanner of Glory rr 45.  For the appearance I have used the Mallet of the Lady.  This comes from one of the Tier 1 caves.  I have used this appearance from level 8 to the current rr 80.  Today I wanted to check the look of the Tier 1 Hammer of the Decayed.  This is also a Tier 1 cave reward item.  When I attempted to slot the appearance, something went amok.

The appearance would not change and I got a message that items of a different type cannot be changed.  I thought it odd, so I went to reapply the Mallet of the Lady appearance.  It would not change.  I logged out and back in.  The message changed to "The Main Hand slot may never have its appearance customized."  I check with other toons I have, and am able to change their Main Hand item appearance without issue.  I have included a screen shot where the message is shown.  This is the case with any appearance I try to apply for my engi.   I love my Mallet of the Lady appearance and would be a sad panda if suddenly it can not longer be used.  I suspect Elf involvement.  Please help.

![Handcannon_007](https://user-images.githubusercontent.com/15988204/65839623-aa967d00-e2c3-11e9-86ed-679740e0da68.jpg)

**Comment by Kabucoror** [comment]
The problem here is the Spanner you use is right hand only and the Mallet is for both hands - th other Hammer aswell. Maybe the Spanner got a change sometime ago to right hand because engi weapons don't need both hand assignments. So everything is how it should be. 
I'm sorry but you have to search for a new appearance, but thanks for the report anyways.
