### ISSUE TITLE
[Game Mechanic][NPC] 24 Player AoE limit seems to be applied to NPCs

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#15045]
Today we tried to do the CH22 PQs. Reikland (destro) is usually like a stroll in the park, but today was a wipefest. It seems like the NPCs cast their AoE on the whole warband which is disastrous when they use their "Moral". Similar things in Eataine where normal NPCs sometimes kill two+ groups with a cleave.
PnP is experienced in CH22 PQs, we never had this kind of problems before.

**Comment by sioding** [comment]
Talked to the devs for it. This is no "bug". This change is intended and its being heavily monitored - maybe you can not run these PQ´s like you did before and you need to find new ways - or you can use the feedback thread which will be opened the next days to ask for a change. This thin here will be closed for now since its not a bug.
