### ISSUE TITLE
No invander tokens rewarded (this has happened to me many times

### ISSUE THREAD

**Issue by todngo** [WarEmu/WarBugs#15209]
If the in game help doesn't fix one small portion of this issue by rewarding tokens that were repeated & rightfully earned, and it's also not done here, then there's no recourse to players to all?

Playing my 70 Magus (Kharmah) I entered the fort the second it was open, waited until the outer doors were down, fought amongst several warbands to eventually beat the lord, waited until all bags were distributed, got no errors, checked my invader token count and it was the exact same as when I started like has happened many times before. There's no screenshots to give you as there were no error messages. What info are you missing?

**Expected behavior and actual behavior:**
I should have received invader tokens, and did not.  This is the 5th time this has happened.

**Steps to reproduce the problem:**
Participate in a fort seige, kill the lord, receive nothing

**Testing Screenshots/Videos/Evidences (always needed):**
I cannot take a screenshot when there was no in game error message, the tokens simply do not appear in my bag.

**Comment by Natherul** [comment]
the message was seen in the closed topic, reposting it in a new ticket wont make any difference. 

as for

> If the in game help doesn't fix one small portion of this issue by rewarding tokens that were repeated & rightfully earned, and it's also not done here, then there's no recourse to players to all?

The recourse is to fix the issue so it does not happen again. Bugtracker is here to simply find and give as much details about bugs so that we (the devs) can track down what went wrong and why. Needlessly to say anyone can claim anything and there is no logs that we can check to verify as obviously if we had a log then something went right and we could have given the tokens in the first place. And thats not to mention the extra work it would be to verify that something is correct to give said player the missing items, which is extra work with would DEDUCT time from finding and eliminating the issue in the first place.

Now if you want to reply to this then stick to the old one, if more information is added which I can use to find the core issue then it will be reopened.
