### ISSUE TITLE
Removed from fortes due to AFK when not AFK

### ISSUE THREAD

**Issue by pikara** [WarEmu/WarBugs#15426]
At Stonewach fortess. 
On stange 1 i where killing people around who manage pass the block on border (i not even go close border).
Then stange 2 start i got ported out with msg:
"Since you are AFK you have been removed from the fortress"

![Bambykiller_021](https://user-images.githubusercontent.com/19285502/71841100-ed37d480-30be-11ea-88dd-049c25a24e05.jpg)

When i try enter again, it say the same

**Comment by Natherul** [comment]
this is triggered of the afk setting which can be trigged manually using /afk or standing still too long. The check is quite literally if that value is true. Are you sure you did not run as afk on?

**Comment by pikara** [comment]
100% sure, i where active all time. Moving / killing all time, when i got ported, i was on way to my WB to proced enter inside with then. When stage 2 start i get ported

**Comment by bosli42** [comment]
That happened to me a few times too, some months back. If you knew about the /afk command, it is very likely because of that. If you use it to leave a scenario or otherwise, it stays active until you log out or use the command again. Be sure to always use it right again when leaving a scenario with /afk, and it won't happen again, guaranteed. I had to learn "the hard way" too by losing out on a few forts.

**Comment by pikara** [comment]
Yes, think i leave a SC using /afk like 2h before fort to join WB

**Comment by Natherul** [comment]
then it is not an issue, thanks for the report though
