### ISSUE TITLE
New Runefang Mastery level scaling 

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#15483]
Found a bug that allows you to get the full mastery bonus to runefang without maxing out your mastery tree. When training mastery points to Path of Glory one by one the mastery scaling seems to work correctly adding 4 to stats per level. The tactic bugs when you select it and train at the same time as adding the required 11 mastery points to buy the tactic. If you just select runefang when leveling all your points at once and hit the train button the tactic becomes level 40 with the full 160 stat bonus.

![Aedrik_016](https://user-images.githubusercontent.com/16967436/72311106-a7948200-3651-11ea-9fb7-2309dce5a415.jpg)
![Aedrik_017](https://user-images.githubusercontent.com/16967436/72311109-a95e4580-3651-11ea-8d07-80bc8aa03d10.jpg)

**Comment by CrimsonFenris** [comment]
Runefang was giving 240 bonus points before ; now it's 160 with 11 levels in the tree, it seems correct and should give you 240 bonus points with all mastery completed (+20 points per mastery level above).

**Comment by edavoc** [comment]
The scaling is bugged, without even putting the full points in you can get
the max bonus with the min amount to points. Did you even read what I wrote
in in the report?

**Comment by CrimsonFenris** [comment]
I stand corrected ; tactics usually never scale with mastery level. So it's perfectly normal to get the full bonus when buying the tactic with required points, and it means the max bonus and (the min, consequently) is 160 in stats (you dont get the previous 240 bonus).

The "increase" you are seeing is IMO a visual bug, since tactics are usually not meant to scale with mastery level (only skills do, and some tactics may scale with primary stats like STR, ie. Riposte).

**Comment by raptrr** [comment]
Please check with .getstats and provide a screenshot

**Comment by raptrr** [comment]
No further information, closing this issue.
