### ISSUE TITLE
Winning Gold bag for doing nothing. 

### ISSUE THREAD

**Issue by nnnnNATHANnnnn** [WarEmu/WarBugs#15535]
I think I took one step into praag before it locked a few minutes ago, didn't kill anyone, didn't die, didn't stand on a BO for any amount of time, didn't hit the lord, wasn't in a group, didn't even think I left the warcamp, then I went back to IC to respec and I won a gold bag for the lock for no reason. I would like to stress, I barely even remember leaving the wc, I think maybe I stepped out for 1 second. 
![Goremagala_002](https://user-images.githubusercontent.com/56577119/73086893-56bd2e80-3e86-11ea-945a-eac187cb2834.jpg)

**Comment by CrimsonFenris** [comment]
Destro biased (just joking) :p.

Afaik, to get a bag roll you need to assist someone to kill an opponent near a B.O., but maybe contribution system changed since last year.
I got full rp reward for dying when entering a fortress, and spending the whole time in prison. And the exact opposite (near to no rp reward after big fight), so...

**Comment by raptrr** [comment]
Like @CrimsonFenris already said, maybe you were really lucky and assisted somehow
