### ISSUE TITLE
Maw fort defense

### ISSUE THREAD

**Issue by kayfynn** [WarEmu/WarBugs#15622]
Died 4 times as a destro healer at maw fort tonight. Each time I respawned I was ported to destro camp next to city gates in Maw. I was able to walk to fort gate, however it took many attempts to enter the fort grounds as I was ported out. Also, when I died the 4th time the inner gates were down, I did not respawn in jail, but in the maw near city gates (where destro gathers to enter city during city siege).

**Comment by detanglerr** [comment]
Did you enter the fort legitimately?  i.e. you ran into zone, got the "queue notification" window, then got the "you can enter" notification window?  cause i continually ran at the gate on Maw side and was able to get in on destro side by spam clicking on the door as i got ported.  only took a couple tries. not sure if this is because i play on West Coast, and the door click is registered by the server after it tries to port me back.

in any case i didn't get any window notifications on the first time i tried to enter, and did this a couple times to see if it was repeatable (it was).  i got some vanq medals but no invaders on the zone flip.  i'd suggest moving the spot where it queues destro back farther from the door to prevent this from happening.  seemed like a few destro were able to also take advantage of this.

**Comment by raptrr** [comment]
Like @detanglerr mentiend, did you get any notifications from the game?

**Comment by dalen** [comment]
This should be fixed with the patch from 2020-02-15
