### ISSUE TITLE
Nihilist's Witchstaff of Brutality completely misssing

### ISSUE THREAD

**Issue by Bluoki** [WarEmu/WarBugs#1567]
Nihilist's Witchstaff of Brutality is missing from my bag. All 50 of the Scout's emblem's I spent on the staff are not in my bag either although that seems obvious but I now am concerned/annoyed that anything I've earnt could just not be there next time I log in.
I only got the staff last night and now it's just gone. I've checked my Bank and also vender by backs just in case but it's just plain gone. I've tried restarting the game, logging in and out, switching characters and completely closing out of the game and entering again to no avail.
I'm aware that this item most likely won't be reimbursed but it's also leading me to not want to play anymore.
If I could get any help trying to get it back that would be grand because I spent many hours in scenarios earning it. And now I'm level 22 I can't even start again. 
Please help. Thanks - Bluoki (character Destruction - Sorceress Pernicious lvl 22)

**Comment by Reggaewaldo** [comment]
Hi Blukoi, I'm sorry but as of now I can't help you to get the item back BUT, it can be the old bug that things are not syncing correctly. I understand the annoyance and I will look into what can be done.

I see that the server was restarted yesterday (2015-10-01 11:58:57) before you bought the staff.

My plan of action for your ticket would be to wait until a server restart to see if the staff comes back since that was a huge bug in the past, and if that does not solve the issue we would look at an alternative solution. I'm sorry for any inconvenience caused by this.

**Comment by Bluoki** [comment]
yeah still no staff :( very sad panda over here
