### ISSUE TITLE
AoE knocks and AoE morales hit through doors

### ISSUE THREAD

**Issue by Alvanos** [WarEmu/WarBugs#1571]
Well, at least they can hit you through keep gates.

**Comment by Evildoor** [comment]
What about simple aoe abilities?

**Comment by noisestorm** [comment]
Currently AoE LoS is only available for all SCs and Empire pairing. If you find any special issues with AoEs then write where exactly and make some test around it.
When do you people learn, than reports have to be accurate and detailed in order to be useful at all.
If you encounter that issue in lets say Ostland then report it as that. Also mention if you tested different AoEs (lotsa chopping or whatever i care for) and if they did also work or if it really just was the morale...

**Comment by ozarmidrashim** [comment]
Doors of all kinds don't have LOS checks at the moment.

**Comment by Evildoor** [comment]
Closing this since #931 includes this issue.
