### ISSUE TITLE
Infernal wave with tactic - not affected by CD reduction from waagh or Chop fasta

### ISSUE THREAD

**Issue by Troelsnap** [WarEmu/WarBugs#15913]
**Expected behavior and actual behavior:**
Its supposed to drop the CD by 5 sec.

Infernal wave does not work with tactic from destruction tree and waagh / chop fasta.
The ability says it has no cd, and show up like you can see in the video - however you cannot fire the ability at all, until 5 secs later. So the CD reduction does not work on tactic and with an ability by the looks of it.

**Steps to reproduce the problem:**
Respec a sorc to Destruction - get the neverending agony tactic. The ability is now reduced to 5sec - pop waagh with cd reduction by 5 second, or chop fasta from the choppa to reduce reduction of cd's for 5 sec as well. It's the same for both, as shown in the video below.

**Testing Screenshots/Videos/Evidences (always needed):**

https://drive.google.com/file/d/15ZpHbKRRl5RDe-sbXFY-kiuqj2IhW2fy/view?usp=sharing

https://drive.google.com/file/d/1CuGxdqUCzGcZ-FykjEqzIIN5gBSPZcRc/view?usp=sharing -uploaded a zip file, think the quality is reduced by quite a lot when uploaded directly.

**Comment by Vayra** [comment]
It's an intentional change the devs made a while back, IW cannot have its cooldown lowered below 5s. AFAIK it's the only skill in the game they have done this for.

**Comment by Tesq** [comment]
it was infernal wave and rending blade before. rending blade has been reverted indeed infernal wave it still un-effected for some reasons while its perfect mirror on engi can be CD reduced

**Comment by SilverWF** [comment]
Tesq, for real, how you can compare Sorc and Engi?

IW is really OP skill if no CD: 24-targets cap, 100 feet range (with tact) and no CD? You dont even need morales with it - just burn everything on sight.

**Comment by Troelsnap** [comment]
> Tesq, for real, how you can compare Sorc and Engi?
> 
> IW is really OP skill if no CD: 24-targets cap, 100 feet range (with tact) and no CD? You dont even need morales with it - just burn everything on sight.

Yes, and flashfire is totally fine on the BW I forgot, add funnel power to the equation - and you then have why a BW who knows what they are doing are doing 30-50% more dmg than a sorc with perma shatter limbs in an aoe situation. its not like IF wave hits for what 30 or 40% less - but again fiery blast and shattered shadows only does what 40% more dmg than IF - so clearly its IF that melts everything.

**Comment by Tesq** [comment]
Should had say more cross mirror than perfect mirror but point is  engi can have a similar skill with the same aim;  be able to spam a stronger  atk out of cd while sorc dont.

It was not a crytic just an analysis it is like this the whole thing is balanced. Rending blade was reverted as 2h for rvr was overkilled.

**Comment by kalmatar** [comment]
1) either you are trolling (nice name I guess)
2) you probably have missed out a few patch notes, check circa september 2017, BORK was given CD reducer, but it was on purpose prevented from having IW cd reduced to 0 (by any CD reducer; bork+choppa) due to balance reasons. 0s spmmable IW is quite powerful.
3) you are just writing up false information and hoping your class gets buffed, okay I guess. I'd probably play my Sorc more if I could just turn into a lawnmower with 0s cd on my IW and melt anything within 80ft of me.

**Comment by Troelsnap** [comment]
Why would I bother creating a thread - if I were trolling - or aware of their change? Sorcs that are being shattered limbs in an aoe situation, is very limited in what they can actually do - the main dmg has never been from infernal wave, even on live after the changes to SE and SP - where we did have a CD reduction to spam it.

Log in to your sorc, don't spend any point in any tree see the tooltip dmg - and stop accusing anyone for writing up false information. Reality is, infernal wave spam were never the primary dmg dealer - but a filler for when you did not want to drop lower on your SP, ideally only one and DC. 
so stop with the whole "it melts everyone"

Let's counter this to the BW - flashfire, passive dmg from funnel power, FBB - they never have to fill anything as they actually have two more abilities to cope in a proc which has like 95% uptime in an aoe fight, and instacast FBB.

There is a reason a well played BW in the city has a lot higher dmg output than anyone.

**Comment by SilverWF** [comment]
The only thing I could agree here is: if that inability to reduce CD lower than 5 sec was intentional, then it should be mentioned in the tooltip.

> 
> 
> > Tesq, for real, how you can compare Sorc and Engi?
> > IW is really OP skill if no CD: 24-targets cap, 100 feet range (with tact) and no CD? You dont even need morales with it - just burn everything on sight.
> 
> Yes, and flashfire is totally fine on the BW I forgot, add funnel power to the equation - and you then have why a BW who knows what they are doing are doing 30-50% more dmg than a sorc with perma shatter limbs in an aoe situation. its not like IF wave hits for what 30 or 40% less of a proc from flashfire which is up constantly - but again fiery blast and shattered shadows only does what 40% more dmg than IF - so clearly its IF that melts everything.

Then you should speak with good bomb sorcs, like Ithappens about damage output. Because I've met him several times at cities and seems he has no problems with his damage.
Flashfire? 1st it bugs out. 2nd fiery blast requires target to hit and if that target would disrupt/block it - then no damage too. 3rd fiery blast AOE is way lesser than IW

**Comment by Troelsnap** [comment]
> The only thing I could agree here is: if that inability to reduce CD lower than 5 sec was intentional, then it should be mentioned in the tooltip.
> 
> > > Tesq, for real, how you can compare Sorc and Engi?
> > > IW is really OP skill if no CD: 24-targets cap, 100 feet range (with tact) and no CD? You dont even need morales with it - just burn everything on sight.
> > 
> > 
> > Yes, and flashfire is totally fine on the BW I forgot, add funnel power to the equation - and you then have why a BW who knows what they are doing are doing 30-50% more dmg than a sorc with perma shatter limbs in an aoe situation. its not like IF wave hits for what 30 or 40% less of a proc from flashfire which is up constantly - but again fiery blast and shattered shadows only does what 40% more dmg than IF - so clearly its IF that melts everything.
> 
> Then you should speak with good bomb sorcs, like Ithappens about damage output. Because I've met him several times at cities and seems he has no problems with his damage.
> Flashfire? 1st it bugs out. 2nd fiery blast requires target to hit and if that target would disrupt/block it - then no damage too. 3rd fiery blast AOE is way lesser than IW

![Snapsenn_004](https://user-images.githubusercontent.com/18040365/76223561-bba4cc00-621b-11ea-8977-399053da1f2f.jpg)

hits for 31~% less or so. Stop commenting when you do not have your facts straight. So no, it does not hit harder than than FB and SS - which has the same dmg. So again, no IF is not what melts anyone as it's not worth spamming, but needed to weave in for the downtime when bombing - aoeing. 

I've seen that it does bug flashfire, and not always for a negative outcome, even seen it proccing multiple times on Zarbix stream and him using it twice after eachother.

**Comment by BomblingTV** [comment]
Just for context. This intentional change of IF not being able to get affected by cooldown decreasers, was after an organized destro guild used this to melt warbands left right & center by only using IF spam with BO or choppa cooldowndecreasers. Sure it was coordination, but it was also one button spam to wipe enemies.

About the same time of changes, Sorc got M2 mirror of BW to give them something back in return.
Sorc does fall behind in even city instances and cant keep up with funnelpower and Flashfire, however they do have the option to aoe debuff both of their magical damage types from Magus core ability, and Zealot tactic. I personally havnt seen this being used after DPS zealot warband built got nuked by the devs. Maybe this could help the sorcs keeping up, but it is no secret that right now a single supported BW have it dealing more aoe presure than a sorc, having to coordinate and setup several keyroles to reach the BW level.

**Comment by Kabucoror** [comment]
The cooldown of Infernal Wave can't be reduced below 5s, as some other abilities from WP and DoK.

The Bugtracker is no place for discussions. We have a forum for this.
