### ISSUE TITLE
Smoke Screen [detaunt] doesn't remove after death

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#15944]
**Expected behavior and actual behavior:**
expected - detaunt should remove after that player is killed
actual - it doesn't

**Steps to reproduce the problem:**
use detaunt and die before it expires

**Testing Screenshots/Videos/Evidences (always needed):**
![detaunt](https://user-images.githubusercontent.com/7898608/76350032-42af7e00-62c8-11ea-9d42-db7e445df226.png)

**Comment by kalmatar** [comment]
Buffs/debuffs do not "wipe" just because their original source has died. You can see this when you DOT people, and you maybe die, but sometimes the DOTs finish the enemy as well. Just because one person dies, not mean combat is over until last debuffs also run out. Detaunt is just one type of debuff.

**Comment by Kabucoror** [comment]
it is working as intendent
