### ISSUE TITLE
WL Whirling Axe castbar setback too high

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#15966]
The White Lions castbar setback on Whirling Axe and/or Slashing Blade is set way too high. We had a city siege against 5 White Lions, and them jumping in and using Whirling Axe one after another prevented some of our healers entirely from getting any not instant casts done at all to the point where most fights felt unwinnable. Apparantly, some were even hard-interrupted, though that didn't happen to me and I don't know if that was actually caused by the WLs. This combined with the raw power of their AoE thanks to armor ignore makes it much too strong for basically being a 2 button build.

**Comment by kalmatar** [comment]
Their Whirling Axe is more or less exact same mirror as mara Wrecking Ball. And both Mara and WL have access to an AoE interrupt, which is the most likely cause behind you being interrupted. 
What you are describing is not a bug but your view regarding balance. And when it comes to balance between AoE WL and Mara, the first one to be nerfed would be Mara due to their access to aoe AP drain, aoe Init debuff, aoe morale drain, aoe knockdown, aoe disorient.

**Comment by RoR-Zomega** [comment]
Whirling Axe's attack speed combined with it being stacked by many WLs will trigger a lot of setbacks, especially if people are doing fragile single target spells. In addition, chaining Echoing Roar will cause AoE interupts around the WL and pet.

**Comment by grunbag** [comment]
Set back change is common to all abilities . There is nothing more with WA
