### ISSUE TITLE
Gunbad: PQs reset

### ISSUE THREAD

**Issue by stealthc98** [WarEmu/WarBugs#16034]
We completed ALL PQs, and wiped on the main boss.  When we respawn the red barrier at the boss is up, and the whole right side PQs reset.  We also spawned in between the red barrier and the boss barrier.  This has happened twice now.

**Comment by Vayra** [comment]
It happens in mid wing as well. Especially noticeable as if you complete Solithex/Ard Ta Feed, you have to redo the entire wing to do the other.

**Comment by iiiLollo** [comment]
This is the same issue as https://github.com/WarEmu/WarBugs/issues/15918

**Comment by stealthc98** [comment]
On a side note we found a workaround by having a 7the man (alt) hold the instance open while we fight the boss.

**Comment by Vayra** [comment]
Another workaround for mid wing is to not complete the last PQ, and do Solithex first since there is a gap in the barrier allowing you to get to him without completing the PQ. If the PQ boss is spawned, it remains active while killing the boss, allowing you to exit after finishing  Solithex, finish the PQ and kill Ard ta Feed.

**Comment by Hargrim** [comment]
This should no longer happen, please confirm.

**Comment by stealthc98** [comment]
Hasnt happened for the past 2 GB runs.  Not sure if anyone else has a different experience.

**Comment by Kaelang** [comment]
Closed - rework seems to have fixed this issue.
