### ISSUE TITLE
[SW] Lileath's Arrow. Radius

### ISSUE THREAD

**Issue by karrik1978** [WarEmu/WarBugs#16030]
Good afternoon!
We have analyzed the radius of the defeat of the skill Lileath's Arrow. In the presented video, everything is phased analyzed.
https://youtu.be/N5jAAGVDubc
We ask developers to consider the possibility of changing the radius of the defeat of this skill, because currently, the Shadow Warrior is in vain clashes with the main damage skill focused on the area of defeat, is useless.

**Comment by maksshram** [comment]
I fully support this report .

**Comment by RoR-Zomega** [comment]
This is likely going to end up as being treated as a balance suggestion rather than a bug as this how the skill worked on live as well. The skill has almost always operated as a line (or narrow cone) that is slightly wider than the arrow's visual effect rather than a 90 degree cone regardless of how it's worded on the tooltip. The bug would be asking for the tooltip to be clearer on how the ability works.

**Comment by grunbag** [comment]
It’s a line Aoe and not a cone Aoe. The radius is correct and the same as live
