### ISSUE TITLE
Can enter fort without reservation

### ISSUE THREAD

**Issue by Garrthax** [WarEmu/WarBugs#16115]
Last fort i was able to enter without reservation, after doors were down (after flag capture phase) i just tried to enter to get into queue in case someone disconnects (fort was full), but i was free to go in without it.

It was in tonight fort (last one, fel landing, city after that) - did not get message about needed reservation, was not ported out, just nothing. We won, got only 4 medals, so it did not count it as win for me, but i was in roll for bags. I didnt fight in previous zone, so no chance to get contribution or reservation, there was even big group of ppl waiting to enter and 100+ in queue afair.

No screens, sorry, i was at work :-) ... maybe u can find it in logs on char Garrth

**Comment by Garrthax** [comment]
it clearly still works

![image](https://user-images.githubusercontent.com/49390790/80153242-72d38780-85bd-11ea-81d4-8ccc7d4468e4.png)

**Comment by Kaelang** [comment]
It's difficult to replicate considering there's almost 400 people in the queue.

To get this straight - are you saying that if a player is already within the zone, before the zone flips, then they aren't ported out?

I've tried this myself after reading this and was ported out on both occasions so I'm struggling to figure out how to replicate this.

**Comment by Garrthax** [comment]
https://clips.twitch.tv/SillyPlayfulCarabeefANELE

fixxer today got it same, tried to enter, died inside before ported out and it let him stay

**Comment by Garrthax** [comment]
dying before being ported and zero contribution enter works, got it confirmed from guild

**Comment by Kaelang** [comment]
So, player dies within fort zone (before flip). Then releases once the zone has been flipped (i.e. reservations have been sent out). 

Do they release inside the fort and are free to carry on? Is that the suggestion here?

**Comment by Garrthax** [comment]
in countdown before first stage, when its waiting for ppl to enter, char without reservation tries to enter and is killed just behind zone border, he respawn inside keep and can participate without reservation 

(hard to explain, my english is bad)

second is what i described - char with exactly zero contribution in previsous zone is sometimes (50% for me) allowed to enter without being ported out even in fort in progress

**Comment by Kaelang** [comment]
No worries re: English, you're doing fine.

I've just tried what you suggested and was ported straight out into the lobby waiting to get in.

Now, what actually happens, from time to time, is players have enough contribution to receive a 'Reservation Popup' however because they're already in the zone - the popup doesn't actually appear. Because the game thinks that you have made your way in (disregarding the need for the popup).

That being said, players shouldn't be able to get into the zone with 0 contribution, especially when there is a queue of almost 200 players (currently at Fell Landing).

I think there is a problem somewhere here, but it's going to be hard to pin point the actual causation. Especially if you're confident people without any contribution are able to find a way into a fort, and receive rewards from the fort.

I'll forward this report over - thank you for sending this.

**Comment by Garrthax** [comment]
i have entered twice (one reported, one by mistake runned out) without contribution while 150+ were in queue, same confirmed from guild and some friends, who were using this to farm

no pop in uderstandable, no chat message maybe too, weird is, that if fort is defended and "normal" ppl with reservation got 6 medals, buggers got only 4

can by just normal server hamster brainlag, happens in every game

dead without reservation to fort - Fixxer video 6:38:40 https://www.twitch.tv/videos/600271554

**Comment by Vayra** [comment]
It's definitely possible to get in without reservation. Right now in Reikwatch order had equal or higher numbers than destro from the start of the fort. The forts need to aggressively maintain population levels and kick people if it goes above.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15728
