### ISSUE TITLE
Exploit to get into t1 at any level

### ISSUE THREAD

**Issue by idkshaman** [WarEmu/WarBugs#1613]
If you have your book of binding set to anywhere in t1, you can use it to port back to t1 at any level. I've tested this on multiple characters. (I didn't gank or anything but 100% could have!)

**Comment by Evildoor** [comment]
Ahem. Sure, you can do that. You can also travel via flight master. But how can you "100% could have" ganked anyone without getting RVR flagged? (apart from known issues like https://github.com/WarEmu/WarBugs/issues/1603) And RVR flag turns you into chicken if your level is too high.

**Comment by idkshaman** [comment]
I was told it was impossible to get into t1 after level 11 so I thought it was an exploit. Guess not. I didn't check rvr flag. I know there was a lvl 13 shadow warrior ganking in t1 before so there must be some way to do it though.

**Comment by Evildoor** [comment]
You were misinformed. It was always possible to get in T1 with chicken limitation mentioned above. People are doing it all the time to do quests/PVE farming for craft/whatever.
I guess that 13 SW was able to RVR because of https://github.com/WarEmu/WarBugs/issues/1399. That issue is known, so i'm closing this ticket.
