### ISSUE TITLE
shaman "geddoff" ability doesn't work in some circumstances

### ISSUE THREAD

**Issue by idkshaman** [WarEmu/WarBugs#1620]
If the "geddoff" ability is used when there is enough waaagh to either give it a very short cast time or instant cast, the knockback effect doesn't work.

**Comment by idkshaman** [comment]
After some more testing, it seems like if any ability has an instant cast time due to waaagh it doesn't work at all. heals don't heal, knockback doesn't knock back etc etc

**Comment by Evildoor** [comment]
From my experience, healing and damaging abilities do work correctly, but only on server side - for example, if you try to cast a 2s heal with 5 mechanic points, then it immediately heals your target (as it should), but you get a cast bar anyway, which you have to interrupt, which is clunky and annoying. However, this problem is reported, known, but has no solution so far.
Can't test "Geddoff!" for myself because dev server is unavailable to me for now.

**Comment by ozarmidrashim** [comment]
Mechanic appearance on client was fixed in recent patch.

**Comment by ozarmidrashim** [comment]
Played some Shammy to test this and noticed no issues.

**Comment by Evildoor** [comment]
No reports of incorrect "Geddoff!" behavior, closing.
