### ISSUE TITLE
Chapter 22 PQ -No rolls, No bags

### ISSUE THREAD

**Issue by IC2Piggies** [WarEmu/WarBugs#16230]
Yesterday, I joined a 24 man Warband to do Chapter 22 PQ in Reikland. Everything went fine cept in the end,,,,None of us got any rolls or BAGS! I Opted out of gold bags because I was on my Shammie and all I wanted was my Talismans. I didn't get any at all. Please get the bag of talis to me asap.
Thanks Much,
Shamaniganz

**Comment by barfyman92** [comment]
#16231 these are related, I think it's because people wipe out and respawn, completely bugging out their PQ contribution. 

Makes for 0 bags, which is very sad. Happened to me twice at the caledor 22 pq, both times i respawned in nearby pve camp and ran back up to retry boss, and there was no loot to be had for me.

**Comment by Lheana** [comment]
Please don't open 2 issues for the exact same thing. And please provide a description...

**Comment by Kaelang** [comment]
Closing - no further information from OP and already stated that the team doesn't perform item recoveries.
