### ISSUE TITLE
Invader Token + Rollbag

### ISSUE THREAD

**Issue by Tsunade92** [WarEmu/WarBugs#16282]
Hi guys.

I just made the "Shining Way" Defense but didnt get any Tokens or Rollbags.

I saw there were many others peopIe with this issue.
The difference is that i did get a Reservation.

Any clue?

Regards

IG: Tsu

**Comment by Hypina** [comment]
Hello

Im getting the same problem last few days of not getting any bag rolls at all
The roll chest in top right corner didnt even appear while im in the zone at the lock. I have enought contribution for sure because other guild mates that are in the same wb with me and we do all stuff in the zone togetter get it, but not me. Also quest to get the keep also dosnt complete even when i contribute and attack the lord too
Its realy frustrating so please look into this

IG: Hypina

thx

**Comment by Kaelang** [comment]
Did you receive a yellow message in chat, anything about contribution not being calculated? Please supply screenshots if this happens in your upcoming forts.

**Comment by Kaelang** [comment]
Closed. No further information provided.
