### ISSUE TITLE
Shaman - Beastlord Hunting Guide 6th Set Not working

### ISSUE THREAD

**Issue by Scabbyskinz** [WarEmu/WarBugs#16315]
The Shaman - Beastlord Hunting Guide 6th set isn't working as intended, The ability just doesn't trigger at all despite testing various ways for it to happen. The ability just doesn't heal for the health it's supposed too, I'm aware it's a 10% chance but it should still proc at least once right?

**Expected behaviour: "Caretaker - On Hit: 10% chance to heal defensive target for 235 health.**

**Steps to reproduce the problem: Just do the "On Hit" aspect of the shaman 6th set to get a noneffect in play**

**Comment by Kaelang** [comment]
Are you suggesting that this never procs, or when it does the value isn't high enough? Please can you support this report with evidence, a video would be best.

**Comment by Scabbyskinz** [comment]
Hey there mate, I tried the thing again and did a short video, Basically either I'm misunderstanding the "On Hit" effects or the 10% isn't working at the value stated. You'll see in the combat log at the start of this combat sequence (On an attempt before) it EVENTUALLY did proc at some point when I killed a yeti, But on fighting a couple of Sabres it didn't proc once despite being attacked and attacking.
https://youtu.be/A5xeP1sZhRg

**Comment by Kaelang** [comment]
10% is still a relatively low chance, just because something is 10% doesn't necessarily mean it will proc 1/10. A dice is rolled when you receive damage and is individual to that specific action which is where the 10% comes into play. 

Going from the video you uploaded, I can see the ability is proccing - as opposed to your initial report saying that the ability isn't functional. If you believe the % to proc is substantially below 10% I'll re-open this as a query. 

For now however, as your initial report stated the ability does not work, and evidence has been given to suggest it does, I'm going to close this report.

Feel free to reply if you want to get clarity on the proc chance or you're happy with how it is.
