### ISSUE TITLE
stairs bug and bo bug 

### ISSUE THREAD

**Issue by Alby1312** [WarEmu/WarBugs#16337]
Hi there, i found 2 bugs the first one is in the elf keep in dragonwake when you go up the stairs and fall between stairs and wall you will get gliched in the wall and /stuck is not working properly here, another bug in kadrin valley central bo, don t rem the name that one with water around , if you keep jump from stairs to the center bo you will get gliched under the bo happen almost everytime . Is it enough to earn the mount?cheers

**Comment by Kaelang** [comment]
Need screenshots, will be impossible for devs to find the spots you're trying to explain with being able to clearly see them.

**Comment by Alby1312** [comment]
Okay as soon as I can I will open another post with that

**Comment by Kaelang** [comment]
Just edit your original post - no need to make a new one.

**Comment by Alby1312** [comment]
![bug 1](https://user-images.githubusercontent.com/63458229/79076848-b1e91980-7d2f-11ea-927f-78d7b7180ea9.jpg)
this is another bug in city i ve found , when i will have more time i will take screenshots of the others falling into the street into IC city fight

**Comment by Alby1312** [comment]
I’ve found another bug yesterday check my original post . When I will have time I ll go take a screenshot of the others .

**Comment by Alby1312** [comment]
found another big bug in the ironclad map scenario if you jump in a corner you fall down in the map look screenshots

**Comment by Alby1312** [comment]
![Teschiosacro_002](https://user-images.githubusercontent.com/63458229/79899843-eea7c580-843f-11ea-8cc8-47e17ef1565c.jpg)
![Teschiosacro_003](https://user-images.githubusercontent.com/63458229/79899857-f4051000-843f-11ea-906e-917c79fc4513.jpg)
![Teschiosacro_000](https://user-images.githubusercontent.com/63458229/79899865-f8312d80-843f-11ea-8e12-b9d73d360795.jpg)

**Comment by Alby1312** [comment]
is the corner with those 3 barrels if you jump on it you just fall down the map

**Comment by Kaelang** [comment]
Please could you open a separate issue for the spot in The Ironclad Map.

**Comment by Alby1312** [comment]
Done

**Comment by Alby1312** [comment]
Mate do I have any chances to get the special mount for the reports I’ve done ?

**Comment by Kaelang** [comment]
The special mount is given out in extreme circumstances by lead developers who work on game-defining bugs. 

Anyone who asks for a Griffon or Manticore mount will not receive one, regardless of whether the report would otherwise be eligible.

These mounts are given only for serious issues, which are not obvious, and which significantly threaten either the security and stability of the server or its economy. Please don't waste Devs time by creatively spinning minor reports into something that they're not.

We have also decided to open the option to give these mounts to people with a large amount of reports written in a good manner with many details, if this is the case you will be notified and do not need to ask for it.

See: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Alby1312** [comment]
Gotcha thanks for your time
