### ISSUE TITLE
Order got through the barrier at altdorf City siege tonight 

### ISSUE THREAD

**Issue by Chopyaded** [WarEmu/WarBugs#16344]
**Expected behavior and actual behavior:**
The barrier is supposed to be there to stop each of the other sides getting through but didn't 

**Steps to reproduce the problem:**
Get a choppa to use his get to the choppa ability whilst stood next the the barrier on the inside

**Testing Screenshots/Videos/Evidences (always needed):**

So we did a city siege tonight and if a choppa uses his get to the choppa ability he can actually pull the order through the barrier at destructions spawn. I actually used the skill as I was running to go through the barrier and in stage 3 of the city it pulled 2 of the chosen champions through the banner a white lion and a bright wizard who then proceeded to farm us as soon as we respawned. I didn't take any screenshots but I could tell you the names of everyone in my warband who can verify this.

**Comment by Gunlingers** [comment]
So YOU used the Pull, that at this point everyone is well aware, can pull enemys without CC imunity through the barrier. And YOU even mannaged to Pull their 2 DPS CHAMPS right into YOUR spawn,
making it impossible for their Healers to use direct healing Spells.
And now YOU open a Bugtracker, that from it's Headline looks like THEY did anything wrong?
What should they do? Let your WB kill them for free?
The solution for this problem is, that the Classes with Pull Skills simply stop to abuse them.

**Comment by Chopyaded** [comment]
I am not complaining about it I am just making people aware of the bug and stating what happened. I won't report things like this in future if that is the response I get.
