### ISSUE TITLE
Zealot perma silence with 0 aps after casting Mark of the spelldestroyer

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#16645]
If you can Mark of the spelldestroyer you lose all AP and cant do anything. Even logout doesnt work because it says cant log out while casting. It happens the first time in Stonewatch after Shinning way was active too. Had to kill the client because logout not possible and lost fort reservation.
![Knochenfraktur_007](https://user-images.githubusercontent.com/45398873/80925881-c307d200-8d93-11ea-9712-8e12ce22a3ca.jpg)

**Comment by Kaelang** [comment]
Thanks - we know about this issue however I'll keep this report live so other Zealots who may come in wondering what's happening can find this post.

The Zealot /RP Buff ability was the cause of a pretty nasty exploit and was required to be disabled pretty quickly, caused a few issues in doing so. The current workaround is to just not use any of your buffs until the devs can fix the ability and bring it back to normality.

Thanks.

**Comment by ruscur** [comment]
This can happen in ranked SCs, the player does not appear in the scenario info window but the game still starts and I still lose 65 MMR and I'm still salty.

If this turns out to be hard to fix it'd be great to have some kind of detection in ranked so that the game can restart with a new player, like how it works when a player doesn't accept the queue.

**Comment by Kaelang** [comment]
This is effecting Zealots / RP's. The team are aware of the issue.

**Comment by Riggaknocka** [comment]
@Kaelang Thank you and sorry for the duplicate report.
