### ISSUE TITLE
Forts - can attack through walls

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16657]
the keep walls in the Maw (lords room) can be shot, aoe, and targeted through (also pulled through),
here is my BO testing this with an aoe in SS.
![Nooblit_051](https://user-images.githubusercontent.com/44329952/80936522-2e9f6e80-8d97-11ea-9a8a-d009be5fd2d9.jpg)

**Comment by Xicoz** [comment]
also as u can see in chat window, I killed 2 people in 1 hit through a wall as a BO, so pretty big deal lmao

**Comment by igvgithb** [comment]
This also works on destro side in the Maw and the corner of Butcher's pass. I've tested with several chosen abilities and raze and all have gone through. I'm not sure about challenge, since I can't inspect people on the other side to test it out. Dreadful Agony ticks the entire time, Quake always hits the max number of targets, blast wave clips people from time to time.

**Comment by Kaelang** [comment]
This should now be fixed.

**Comment by Garrthax** [comment]
aoed throught maw walls again 
![image](https://user-images.githubusercontent.com/49390790/83834436-9e827b00-a6ee-11ea-9348-6103e466a346.png)

**Comment by XmatXergon** [comment]
https://youtu.be/y6eLjeyApW0
