### ISSUE TITLE
Spider Boss has no lockout.

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#16680]
hello spoke to the gm yesterday*Kaelang*it seems that he is not interested in the problem *

Therefore I post it here and hope that as many as possible use it until the fix Comes..
to farm in gb gems namely solo..!!!!
start right kill the shaman mop and ignore the spider..run back over the bridge and everything is already left .. you can start again..!
for someone who has time can farm something together

14/5000

it is possible

**Comment by Kaelang** [comment]
Hi - me again.

I didn't say I wasn't interested, you just provided no information as to how to replicate this without having to lock people out each time - which is an intended mechanic of a dungeon lockout. If people are getting locked out, to kill mobs to drop items, then it's working, no?

Also - soloing dungeon mobs in Gunbad? Not confident that's a thing.

All this being said - I mentioned I'd pass this over, and I'll do so - if you can provide me some more information, mainly a video of this being done in action so I can understand what your perspective of this is.

Thanks.

**Comment by noobwarrior** [comment]
kill the trash mop and hope that the armor gem drops ..
was in there for 30 min unfortunately no luck and no desire but for players who bring more patience with them a lucrative offer

**Comment by Kaelang** [comment]
Killing the boss in the hope of getting loot is the whole point of dungeon running... I'm confused as to how this is a problem? Please can you record a video of this happening to highlight the concern you have.

Thanks.

**Comment by SilverWF** [comment]
Well, I think, he said, that one solo player can run to some wing, fast kill some mob champ, then run back to respawn point, forcing other monsters to avoid and reset, then return back, attack and fast kill another one, then rush back back to spawn etc.

**Comment by RoR-Zomega** [comment]
I don't quite understand the gibberish of Noobwarrior, but the current issue with the gem farm is this: the spider hero boss that drops the gems has no lockout timer. These gems can sell up to 1.6k gold if the right one drops (Equisite Gunbad Diamond), or still hundreds of gold if some of the less-better ones drop.

Usually for bosses that drop such good items there is a lockout timer on the boss so you can't roll on the loot with the same character more than once every X days. Because there is no lockout, once the boss is killed you can leave the instance, reform the party, everyone goes back into a fresh new Gunbad and kill it again. A boss with a chance to drop a 1.6k gold ring can be farmed every 10-15 minutes with a good group with at most needing to swap out one person to force a fresh instance (that person can then be replaced with the original character once people are in the fresh instance).

Is it really intended that this one lucritive boss can be farmed while everything else has lockout timers?

This was possible before the Gunbad rework btw and is unrelated. The spider boss has always been missing the lockout timer that is on other sub-bosses.
