### ISSUE TITLE
Zealot Tactic

### ISSUE THREAD

**Issue by Critos** [WarEmu/WarBugs#1676]
So, Tzeentch's Grip is painted red because "this ability is not usable at your current level'.
http://i.imgur.com/MTo6PUA.jpg
Also, is the proc chance a correct? It procs like 3 times in a row and 15 casts without proc.

**Comment by Evildoor** [comment]
Mastery abilities/tactics had the same problem on live if you had mastery from 40\50\60\70 RR because of Mythic putting unnecessary checks into game client and forgetting about them when they doubled the renown cap. Therefore, i doubt that we can do anything here since it's hardcoded into the client. But it works anyway, right?
I don't see anything wrong with proc rate you're talking about. 18 tests is not enough to make a conclusion.

**Comment by ozarmidrashim** [comment]
Client problem, can't fix.
