### ISSUE TITLE
Being in fort without reservations

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16761]
To get into fort without reservation is very simple and exploitable, you just go to the fort right before it spawns and just sit inside inner/outer, ive tested this twice so far. You will not get contribution, or end rewards, but you will boost the numbers of your faction in fort and make it a lot easier to defend or attack. I believe a lot of people are using this and that is why you're seeing so much "I did not receive contribution at fort, I didn't get any rewards" or why the numbers at forts seem to be off, is by people getting in via this method, accidental or not. In the SS you can see it shows something like "you did not receive enough contribution for reservation, you have been kicked from fort etc." but it doesn't do so cause I was here before fort started, but if I leave and come back, it doesn't let me in.
![Dracula_057](https://user-images.githubusercontent.com/44329952/81513108-84ba6780-92eb-11ea-9ee2-74f357d29472.jpg)

**Comment by Xicoz** [comment]
just recreated again in an attacking fort 
![Dracula_058](https://user-images.githubusercontent.com/44329952/81513808-a407c380-92f0-11ea-8d13-064b4e92908f.jpg)

**Comment by Kaelang** [comment]
Tried this myself on multiple occasions and was always ported - did you contribute in the zone beforehand?

**Comment by RoR-Zomega** [comment]
I managed to do this today in Shining Way. Zero contribution in Eataine other than a 5 vs 1 killing of a Slayer hiding in the BO near the zone border between Eataine and Shining Way. I literally just ran from the warcamp to the fort zone and arrived 30 seconds before the zone was due to flip. I expected to be ported out and put in a queue but instead it let me stay in and participate in the fortress. I didn't get any rewards for doing so other than renown earned from kills (no renown/tokens/etc from winning the fortress).

This was on a rank 32 Squig Herder.

**Comment by Xicoz** [comment]
a little bit, but nowhere near enough to get a reservation (also no message about a reservation), as well as when I died in fort, I was ported to an island to the south and couldn't get back in again. 

![Dracula_059](https://user-images.githubusercontent.com/44329952/81518610-3bc2dd00-9304-11ea-8412-e6089bd6d22b.jpg)

**Comment by RoR-Zomega** [comment]
Just happened now in Fell Landing. System message saying I had no contrib and would be teleported out but I have not been teleported out and can participate in the fort def.

![image](https://user-images.githubusercontent.com/60266177/81542594-d35c1600-936c-11ea-98a6-0a74650f83ee.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15728
