### ISSUE TITLE
[Skill] Word of Pain remove detaunt when cast

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1681]
Word of Pain remove detaunt when cast not when give dmg

**Comment by ozarmidrashim** [comment]
This isn't easy to change. I was told that DoTs counted as an attack upon application. Not quite sure why you should be able to stack up damage while having a detaunt up either...

**Comment by MKorin** [comment]
till tick its only debuff

**Comment by magter3001** [comment]
If that's the case, then all DoTs would be able to bypass detaunt for 3 seconds (as it takes 3 seconds before the first tick arives). I don't think that's a bug.

**Comment by Evildoor** [comment]
If DoTs will remove detaunt on damage instead of on application, it would be pretty much impossible to use detaunt as a class with DoTs in situations when the tide of battle changes and you need to detaunt a target which you were attacking before, since it will have your DoTs still ticking. Therefore, current mechanic is correct, IMO, and should be left that way.

**Comment by MKorin** [comment]
It seems logical.
