### ISSUE TITLE
infinite t1 emblems

### ISSUE THREAD

**Issue by thullonse** [WarEmu/WarBugs#1688]
![darude_001](https://cloud.githubusercontent.com/assets/14988273/10563298/4479b88e-7585-11e5-982e-b99ed5a77bc8.jpg)
you can buy literally infinite amounts of t1 emblems gonna delete mine later on but please do something about this exploit

**Comment by Evildoor** [comment]
#809. Bug is known, and i've already asked the devs to take a look at it. According to the forum, i'm not the only one who've done that, so no need to create more duplicates of the problem reports. Unless, of course, if you've got those medallions (not emblems, right?) from some source different from #809. If yes, say so, otherwise i'm closing this.
