### ISSUE TITLE
[Tactic] Long-Held Grudge replacing tactic in 1st slot

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#16894]
After relog on my IB and after some time playing (I can't find an exact reason why and how) my first tactic slot are being replaced with Long-Held Grudge tactic. I do not know exactly how to reproduce this problem, but it happens 100% chance after logging on IB and spending like 2-3 minutes online

**Comment by Kabucoror** [comment]
happens to my IB as well, still no idea what it causes

**Comment by Kaelang** [comment]
Been running around on an IB since this report came up and my tactics have held in place. (re-logged twice) Could this be somewhat related to https://github.com/WarEmu/WarBugs/issues/15857 or is this exclusive to the Long-Held Grudge tactic?

Do you have this tactic equipped, and then it swaps place? Or will it simply replace any Tactics that you use in that first slot?

**Comment by Tamtam-RoR** [comment]
It happens to me also ingame when:
- I have 4 tactics equipped
- I have equipment giving %block 

When I try to change or take out the equipment with %block, the long-held grudge tactic appears on 1st slot and other tactics are shifted on the right.

**Comment by Sandskid** [comment]
> 
> 
> Been running around on an IB since this report came up and my tactics have held in place. (re-logged twice) Could this be somewhat related to #15857 or is this exclusive to the Long-Held Grudge tactic?
> 
> Do you have this tactic equipped, and then it swaps place? Or will it simply replace any Tactics that you use in that first slot?

It simply replaces any tactics that I use in the first slot. It happens 100% of the time when I change weapons or shields, mb it's also caused my something else.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/12902
