### ISSUE TITLE
Non PVP Flagged in RvR/Scens

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#1698]
Yesterday noticed a few Order players in RvR zones and in Scenarios being Non PVP flagged, but they could still attack us. I made some screenshots in case needed. But won't post them here, don't want to do any namecalling. Don't know if this is a bug or an exploit. Just give a shout if you want the screenshots.

**Comment by Tyramissoux** [comment]
Have this on my order chars quite often when joining a SC. As soon as I cast a heal on someone, I suddenly hear the "flagged" sound.

**Comment by Tiggonos** [comment]
same in orvr and on destro side.

**Comment by Tesq** [comment]
some ppl deliberatly stay un-flag in sc to preven being attacked trying to cap flags

**Comment by Naos7** [comment]
I wanted to post a bug report for this issue with disappearing RVR Flag at anytime and anywhere (even in scenarios), but you did it before. I wanted to tell that I have this problem a lot, even when I enter in scenarios flag rvr doesn't pop himself, I made 1 scenario, I will never do it again until this bug will be fixed, don't want that other team flames on me because I just forget to manually retag RVR flag.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
