### ISSUE TITLE
Marshthum Bladestoppa not BoP

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1703]
The Marshthum Bladestoppa off-hand weapon for the Black Orc/Choppa is not BoP, this way they can't be used for appearance and sold on the AH. It also has a bugged +99% block rate which should be a 99 block rate, for regular shields.

**Comment by sullemunk** [comment]
it's not marked as a sheild so it doesn't block anny attacks

**Comment by Evildoor** [comment]
#907 
FYI, current appearance system has a method of bypassing lack of "Alt. appearance available" (one of the reasons why i like this system over original).

**Comment by Ryanfawkez** [comment]
Evildoor, mind explaining to us how exactly we can avoid the lack of "Alt. appearance available"? My guildies and me have been heavily struggling with having nice looking stuff we can't apply due to lack of BoP, teach us your secrets :D

**Comment by Evildoor** [comment]
You can bypass some of the restrictions by swapping items before hitting "Yes" on confirmation window. I.E, it is possible to do something like this: you have sword A, which is Main Hand without Alternate Appearance Available and sword B, which is Main Hand/Off Hand (different type, so it will not allow you to use it even with AAA) without AAA. All you need is to get sword C and sword D, both of which are the same type (both Main Hand or both Main Hand/Off Hand) and have AAA (vendor things like Militia do fine for this). Then you equip sword C and apply sword D's appearance to it, but DO NOT press the confirmation button on the message. Then, while the message still hangs, you should do two things:
1) Equip sword A instead of sword C.
2) Move sword D elsewhere in your bag and put sword B in the place where D was.
Then you can click "Yes" and you'll have sword B appearance applied to sword A. This can be used to fool around, for example, applying Book Of Binding or potion or mount appearance to an item makes it invisible.

**Comment by Ryanfawkez** [comment]
You are legendary. Just putting that out there. <3
