### ISSUE TITLE
[Exploit] Order can get to the Destro part of the Maw

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#17089]
Well, just watch video :)
Pretty sure, the same is possible solo as Engineer or in party with friend who will sacrifice himself to the guard.
You **can't** enter to the IC there.
Not sure which profit you could get there - maybe kill some afkers only.

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.youtube.com/watch?v=VByZxiz-5N8

**Comment by Tazo83** [comment]
10 more guarded needed for that cave :D

**Comment by valkeera** [comment]
I wouldn't call this an "exploit", because Reikwald is the same - even worse, since the PvE route to Altdorf on Order side (east) is completely unguarded (except for a few bears which don't really count), and it's possible for a destro character to get to the Reikwald order side behind the fort without any opposition at all. That destro guard on the CW/Maw side is there more likely because there is a chaos chapter camp nearby, rather than protecting the backway to the IC.

**Comment by SilverWF** [comment]
Yes, like that
https://www.youtube.com/watch?v=KntEQHoxGJU

**Comment by Rockalypse** [comment]
Reaching gates when no siege going is fine, that route in reikland lets you access fort though and now is blocked.
