### ISSUE TITLE
Influence on Sigmar Crypts & Tunnels

### ISSUE THREAD

**Issue by jlpdiez** [WarEmu/WarBugs#17091]
The chat says you get 2k influence when killing bosses on those instances but the Tome reflects only 1k per boss. This means it's much harder to get Sentinel influence that Bloodlord one.

This run is from yesterday but it has happened every single time.
![WAR-64 2020-06-09 20-20-32](https://user-images.githubusercontent.com/3782057/84335510-4d163800-ab95-11ea-8c42-61ce5593008f.png)
![WAR-64 2020-06-09 20-47-42](https://user-images.githubusercontent.com/3782057/84335575-7040e780-ab95-11ea-8baf-cf81b4a98f08.png)
![WAR-64 2020-06-09 21-46-44](https://user-images.githubusercontent.com/3782057/84335580-733bd800-ab95-11ea-80bd-f8a624fbd77d.png)
![WAR-64 2020-06-09 22-04-17](https://user-images.githubusercontent.com/3782057/84335585-7636c880-ab95-11ea-99c7-a7002bf487df.png)

**Comment by SilverWF** [comment]
Same happens in the every dungeon: Gunbad, Bastion Stair, BB&BE (for Destro)
Chat shows double renown gain, while actual gain is lower in 2 times.

**Comment by crazyturkme** [comment]
Nothing is wrong. It gives 1k to bb 1k to be inf bar. Same for order you will get 1k inf for crypt 1k for tunnels inf bar. 

Everything works well.

**Comment by Lheana** [comment]
It's just visual. As crazyturkme said, for the city dungeons, you get 2 ticks cause there are influence bars for 2 dungeons (crypts/tunnels for order and BE/BB for destruction). Concerning Bastion Stair and Mount Gunbad, that's simply because there is in real one bar for each faction, and even if you can not see the one of the opposite faction, you still get influence for the influence of the opposite faction as these dungeons are common to both order and destro.
So this issue is related to #10445
