### ISSUE TITLE
Auto or cruise control experience

### ISSUE THREAD

**Issue by imneo58** [WarEmu/WarBugs#1716]
Level 26 White Lion is sitting in Ulfenwyr Public Quest in Norsca afk while his lion kills continuously. I searched to see where to report this on the regular forum and ended up here. Is this acceptable or just something that isn't being reported? If this is the wrong avenue to take please point me in the right direction. I was told GM then told no GMs online don't handle this so I'm doing the circuit trying to find the answer. Thank you in advance.

**Comment by Evildoor** [comment]
Uh, bugtracker is a place for bugs, and killing mobs using some 3rd party software while afking is not a bug. I think it should be PMed to Game Master, but since you say that you've heard this as well as the opposite, i'll leave this ticket open for now so that some GM/dev could see it and clarify things.

**Comment by imneo58** [comment]
I understand it's not a bug. I don't know the proper avenue for reporting it. I will close this. Sorry.
