### ISSUE TITLE
WE Bloodlust costing ability bug

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#1717]
For each blood lust you have, it's suppose to reduce the cost of your blood lust finisher ability by 20% but it doesn't.

Nvm, just a UI error

**Comment by Evildoor** [comment]
This issue can prevent you from attacking on low AP, because client checks for AP cost. For example, if you have 100 AP left and 5 Bloodlust, Puncture costs 35 AP but really uses 0, so you still have 100 AP after using it. However, if you only have 20 AP, the game will not allow you to use Puncture because client thinks that it costs AP. This issue was even worse when stealth abilities visually increased AP costs by 50% instead of reducing them. So, while it is somewhat hard to run into problems with this (or notice them if you do), it is still a bug which should be fixed.
Same for WH, ofc.

**Comment by noisestorm** [comment]
+
