### ISSUE TITLE
Sometimes it stops working collecting seeds and planting

### ISSUE THREAD

**Issue by Olovo-ru** [WarEmu/WarBugs#1721]
Sometimes it stops working collecting seeds and planting
video: https://yadi.sk/i/5pAjsr0pjyLJa

**Comment by mursie** [comment]
I use miracle grow remix addon and this problem occurs if I try to quickly replant all four open cultivation spots to quickly.  BAsically, the cultivation plots need to be pressed one at a time with care to wait until it fully accepts commands before going to next plot.  

DOing this will ensure a much higher rate of plots actually not getting bugged out.

WIth that said, when server lag is really really bad, i find that cultivation will still bug out and not be responsive.  

The worst part is - the only solution is a relog which causes you to lose all planting in the four plots you had done.

**Comment by Blubberino** [comment]
What is very strange that some people only have this bug once every week or so but others have it several times a day which is super annoying. 
So for my character it worked perfectly fine till I reached cultivating lvl 200 and then it started to bug often. At first I also used miracle grow and i diddn't have any bug outs whatsoever but now they occur almost every hour. I even disabled miracle grow again but it still seems to bug alot.

Did you make any progress on this issu?
+ Can you change the issu name to something with culticating because I also started an issu and closed it again after I found this one over an other issu.

**Comment by Blubberino** [comment]
Something as usefull as .unlock for crafting would be nice
