### ISSUE TITLE
Account still frozen.

### ISSUE THREAD

**Issue by punakone** [WarEmu/WarBugs#1724]
In every login it only says "invalid username/password" it started yesterday so I changed my password. This all happened after the DDos attack. Now I'm able to login to the website normally and I have made a new account on top of it all because it works so as works my brothers accounts and there isn't any issue with the launcher or the game but I think that after the attack it bugged out or is missing something from the armory I still see my chars intact my main shaman Dizlyk whom I got the 210 medallion apostles staff even right before the attack wich is the least of the concernes bu still I hope there is somekind on an fix to this because I'am starting to lose hope that all of my chars were now completely wiped/lost I hope I won't need to say goodbyes to my 18 mara and 11-12 sh.

**Comment by Evildoor** [comment]
Password change applies to forum immediately, but takes several hours (sometimes days) to apply to the game itself.

**Comment by milosxe** [comment]
Here's the official word from RoR team on that and similar issues:
"The forums are broken. Registration and emails are included in that. If you don't get an email during registration, it's probably not going to show up until after these problems end. We're not approving accounts manually.
Despite the website being rekt, the game is online and playable, at least we got that going for us. So that's nice."

**Comment by Evildoor** [comment]
Aha. So it's forum problems on top of general long time of password change. Okay, i'm closing this, since issue it is known issue with forum, and not with the game.
