### ISSUE TITLE
Convert Recruit's Emblems

### ISSUE THREAD

**Issue by Alex40k** [WarEmu/WarBugs#1727]
Hello. Can y fix this item or make it able to get recruit's emblems after 12 lvl? There are many wepons which looks so nice. But I can't get them my charecters too hight.  <a target="_blank" href="http://radikal.ru/big/fe9d3643217746d2a74e3fff6dffd6ab"><img src="http://s40.radikal.ru/i089/1510/a3/5d67bd94c545.jpg" ></a>

**Comment by magter3001** [comment]
The satchel of recruit's emblems (25) also doesn't work.

**Comment by Evildoor** [comment]
And satchel to convert Soldier emblems into Scout ones is missing altogether. (Or not implemented yet, ofc)

**Comment by TaeBal** [comment]
I got same problem "Satchel of Recruit's Emblems" not work 
i have 2 bag and need 50 recruit emblem :)

**Comment by Evildoor** [comment]
Satchels work now, but their description says "Control-right click" while they work on simple right click. Also, they go to main backpack instead of currency. Possibly because of this, a satchel which my WH had in currency pack is now bugged and cannot be used/moved/deleted. New ones function properly (with nuances stated above).

**Comment by genisaurus** [comment]
Fixed some time ago.
