### ISSUE TITLE
[WH WE] when buffed by Feinted Positioning you can sneer target in any side

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#1741]

**Comment by Evildoor** [comment]
Uh, is this wrong? Snap Shot/Throwing Dagger (if you are talking about this skill) description says "deal damage, snare if behind", Torment/AW description says "deal damage, ignore armor if behind" and FP affects it - why shouldn't it affect Shot/Dagger then?

**Comment by Nfkillz** [comment]
on live FP applies only on Torment/AW and knockdowns

**Comment by Evildoor** [comment]
IIRC, at least it also affected Flanking. Ok then, let's see what Aza says/does about this.

**Comment by magter3001** [comment]
You have to waste Feinted Positioning though, which is on a 60 second cooldown, in order to snare people from ranged. Also the dagger throw/snap shot cannot be used at melee range, only at above melee range. I see no problem with the way it performs now and if I recall correctly, used to perform this way on live as well at one point in time.
