### ISSUE TITLE
[Quest] Innocence Challenged, Destruction @The Blighted Isle

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#1744]
Hello,

I have killed all the wolves in the red area indicated by the quest. I get no Dreamshade Meat to drop.
I am getting so many of these bugs (see the other bug reports) I fear it's my character that is broken :(

**Comment by Evildoor** [comment]
I don't think your character is the problem. Tons of broken quests are logical since game priority is PVP. BTW, can you please check for existing tickets (if they are present, of course) for the problems you report and comment them instead of opening new ones - unfortunately, github has no feature to merge issues together.

**Comment by dfumagalli** [comment]
Sure, but Github does not have a great search function to help me avoid duplicating issues as well :(

By the way, I think the reason why there are a number of bugged quests is simply because I am basically doing them alone for hours and hours. That is, there's simply too few people doing the Elf chapters to catch the bugs with the same effectiveness we may achieve on other racial pairs.

Finally, I had proof it's not "about my character" because I have done a number of quests requiring a quest item to drop and they do drop it. I'd say 70% quests work, 30% don't.

**Comment by Meralors** [comment]
This quest isnt fixed yet, the item doesnt exist in db.

**Comment by Ryanfawkez** [comment]
Added the quest item on unused ID 53380 - item is now dropped by Dreamshade Wolves.
Fixed in next patch.
