### ISSUE TITLE
Solo ranked shadow warrior classification bug

### ISSUE THREAD

**Issue by pkfsa** [WarEmu/WarBugs#17683]
I just played a game as a dps shaman with a choppa, 1 ranged 1 melee against a white lion and a shadow warrior. The shadow warrior has crosscut and the melee kd, playing in assault stance most of the game. I assume not taking shadowstep classifies you as a "ranged" shadow warrior allowing you to abuse the system.

**Comment by Keula** [comment]
Yea I had the same happen yesterday and they were even using a a strength pot. Ppl in my sc were also saying he actually was using shadowstep, but i can't confirm since i wasn't paying attention to that. If had to guess they probably have their renown not specced in melee crit/strenght and maybe even some ranged crit so the system thinks they are ranged. You can argue No Respite tactic on ranged sw but anything other than that should be classified as melee.

**Comment by pkfsa** [comment]
yea I'm not sure how they programmed it but its being abused at the moment.
