### ISSUE TITLE
Reckless Gamble,Hurtin Time

### ISSUE THREAD

**Issue by geezereur** [WarEmu/WarBugs#1796]
Hurtin' Time and Reckless Gamble's self dmg used to trigger of ability activation and not numbers of targets it hit.

Example: On liver server it would do self dmg on time, despite hitting 3 targets with AoE. Here it does self dmg 3 times, if AoE hits 3 targets on one ability activation.

**Comment by Evildoor** [comment]
Someone does not knows how to use the bugtracker? Fine, let me explain. First of all, there is a search function - before posting anything, use it to avoid duplicating known issues. In this case, #1199 is an issue about Reckless Gamble. You ignored that and created #1776 - i posted #1199 number there and closed it. Now you create another ticket about the same issue, which is pointless. Instead of doing so, you should understand, why exactly was your #1776 ticket closed (duplicate issue in this case). If you, for some reason, disagree with the ticket being closed, comment the closed ticket and elaborate your position like "i think this ticket should not be closed because A and B and C". The fact that the ticket was closed does not means that it vanishes from the world - it does not, we are reading all the new comments.
