### ISSUE TITLE
Lion's Roar Not Working as Intended

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#17991]
![lr](https://user-images.githubusercontent.com/23129933/97217773-d0e55f80-17d8-11eb-8a84-e7cab2ad3460.png)

Lion's Roar is one of the WL's pet ability when you switch to "Train to Threaten", currently it's working as regular taunt for the pet but on tooltip, it should work as "challange". 

without lion's roar
![Choppapullop_018](https://user-images.githubusercontent.com/23129933/97218499-d42d1b00-17d9-11eb-8ee6-79be94e388f0.jpg)

with lion's roar
![Choppapullop_019](https://user-images.githubusercontent.com/23129933/97218552-e27b3700-17d9-11eb-91bf-ce415a34aa5d.jpg)

**Comment by CrimsonFenris** [comment]
Oh thanks for pointing this out, I wondered why this stance (I use it all the time) had damage increaser instead of intended effect (challenge to protect you).

Never thought about checking the lion's debuff... now I understand better.

Actually it's not a bad thing to have this effect since the pet is very efficient in this stance (+30% damage + Axeman-centered build is doing better damage output than Trained to Kill + Guardian, even without offensive added stats).

As a sidenote, it could be good to check tooltip value for other skills from this training, like "Shred" ; both damage component (displayed 333 in tooltip, only 308 inflicted) and armor debuff one (-24 armor doesnt looks like either useful nor accurate/intended), and "Leg Tear" inflicting about +34% more damage than tooltip, maybe it's a DoT and miscalculated ?

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17986
