### ISSUE TITLE
Morales can be used without Morale cost

### ISSUE THREAD

**Issue by DanskuL** [WarEmu/WarBugs#1803]
Using a M1 when you gain enough for morale for M2 doesn't reset the morale bar (it does trigger CD on the M1), I.E you can use 2 morales right after each other same with M2 -> M3 jump.

**Comment by Evildoor** [comment]
Just tested, morale bar was properly reset. I remember situations in combat when i pressed M1, it got on CD (i don't know if the effect triggered or not, because seeing the cd with full morale bar immediately lead to thoughts like "damn, buggy game wasted my morale") and morale bar was not reset, but it seems that there is some kind of condition for that. More information is required.

**Comment by Morksezstop** [comment]
that happens often on healers core moral 1. The heal got like 1 sec delay and if the target die within that delay the moral got cd but the bar doesnt reset cos you really didnt used it. That was on live as well. So at least for healers it is common and normal situation

**Comment by Tesq** [comment]
it happen in lag situation it's a client bug, it happen also for all the other normal skill, when lag, cd skill get used even if they dont hit or consume ap, they just go in CD hence why moral bar didn't reset cos morale gauge isd handle by server nor from client.

**Comment by Evildoor** [comment]
Well, according to @Morksezstop and @Tesq it's a client problem, so we cannot fix it. Closing.
