### ISSUE TITLE
BW instant kill?

### ISSUE THREAD

**Issue by dharissa123** [WarEmu/WarBugs#18102]
Issues should be unique. Check if someone else reported
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.
-->

![Dharissa_000](https://user-images.githubusercontent.com/74745658/99739780-85526880-2a9b-11eb-9020-b2276ea2ddbf.jpg)

**Comment by Tesq** [comment]
there is no timestamp in chat hard they can do anything with this

**Comment by M0rw47h** [comment]
It took BW at least 6,2 second to prepare the burst on you, damage was hiting at least in two turns (since both Boiling Blood and Slow Boil explode after 5s, so there was GCD between them), and you weren't guarded nor had resist buff... What is surprising, you're surprised about it while playing Sorc.

**Comment by cimator** [comment]
looks like a classic BW rotation. Im curious how you arent aware of this as sorc, you can do the same.

**Comment by dharissa123** [comment]
my mistake was not to have timestamp.   This whole ordeal took less than a sec that I couldn't even turn around or  fire my heal pots.  That was to my surprising.
