### ISSUE TITLE
scenario weapons

### ISSUE THREAD

**Issue by vithoria** [WarEmu/WarBugs#1814]
some scenario wepons, have cahnged career's like deciple of khaine sword, say's it now fit for iron breaker

**Comment by Alteren** [comment]
![capture](https://cloud.githubusercontent.com/assets/13026327/11042048/dafa45e4-86c9-11e5-8f61-13279cf81716.JPG)

**Comment by Meralors** [comment]
I fixed Apostle's Xiphos of Cruelty and its now a DoK weapon. Will be fixed on live with next update.
Please post the full name of any other weapon that might be broke ;)

**Comment by sullemunk** [comment]
Nihilist's Focus of Cruelty has also been labeld as Ironbreaker

**Comment by Meralors** [comment]
Nihilist's Focus of Cruelty and Nihilist's Skinflayer of Cruelty fixed

**Comment by Evildoor** [comment]
Sentry's Stabba Of Cruelty
Sentry's Chaosaxe of Cruelty
Sentry's Crusher of Cruelty
Sentry's Painblade of Cruelty
Sentry's Stiletto of Cruelty
Sentry's Bigloppa of Cruelty
Nihilist's Blasta of Cruelty
Sentry's Direblade of Cruelty
Sentry's Ninestaff of Cruelty
Sentry's Glaive of Cruelty
Sentry's Witchstaff of Cruelty
Sentry's Shoota of Cruelty
Sentry's Herald of Cruelty
Sentry's Aspis of Cruelty
Apostle's Chalice of Cruelty
P.S. @Meralors, have you added "Career: DoK" restriction to Xiphos? If yes, i do believe that it's not needed since all these weapons have no career restriction, only race and type. I know that this does not changes much since its stats make it a bad choice for BG, and nobody else can use it besides DoK and BG, but still...

**Comment by Meralors** [comment]
I added no career restriction, you are right they are restricted by race and type. I'll fix all that list and let you know when I'm done

**Comment by laattori** [comment]
Apostle's Xiphos of Cruelty is broken again.

![ironbreaker](https://cloud.githubusercontent.com/assets/15817706/11120220/081a6cb8-8957-11e5-9b13-0f9558ddf231.jpg)

**Comment by Evildoor** [comment]
Xiphos is not the only one item. To me it looks more like "nothing was fixed yet on live because there was no DB pull" rather than "everything is broken again".

**Comment by laattori** [comment]
Ah my bad. I have been playing as melee lately and never noticed this until today.
