### ISSUE TITLE
AH - Item listing and search problems

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#1821]
Hello,

I just noticed that in the last few weeks I see only items under LVL 20 in AH no matter what I select.
If I click on the AH and I don't change any filters (everything is on default) then I click on search. It will search all items. I click on the level coloumn to put the items in row by lvl. I check the highest lvl items and I see items only up to lvl 19.
I checked the filters again and everything is on defult. I checked AH with other character and even after PC restart, but it's the same.

However if I want to search for an specific item, which is above lvl 19, then I type in its name. It finds the searched items and list them out. So all the items are there, but I don't see part of them (which are above lvl 19.

Have anyone ever had the same? What is the problem and how can I solve it?

THX!

**Comment by gabor128** [comment]
I got it. This game cannot list huge amount of items. So it must be limit by e.g. lvl. 
It caused me some problems, because if the search does not list all the items, then maybe I can buy only the more expensive one. 
If the search cannot list all the items a warning sign should be appear to notify and asking you to narrow your search. It should be very important!

**Comment by Luth-RoR** [comment]
Client restriction; it only returns the first few hundred items. Was like this on the mythic server too.
There is a white message in the chatlog.
