### ISSUE TITLE
Blood of the Black Cairn Scenario Bug

### ISSUE THREAD

**Issue by Vizio101** [WarEmu/WarBugs#18218]
The scenario only let 2-3 people out of 12 out of the spawn area.  All three exits are red and not allowing anyone out and of course we then got removed from scenario and received the quitter debuff.

![Zanshin_000](https://user-images.githubusercontent.com/66458029/102644599-ea8a8f80-4115-11eb-9c2f-ad5e486c26fd.jpg)
![Zanshin_001](https://user-images.githubusercontent.com/66458029/102644608-ef4f4380-4115-11eb-8d9a-19ec059a44aa.jpg)
![Zanshin_002](https://user-images.githubusercontent.com/66458029/102644618-f24a3400-4115-11eb-97c5-c0c208fb79e4.jpg)

**Comment by Kaelang** [comment]
Does this happen everytime? Or a one-off situation?

**Comment by Vizio101** [comment]
Happened every time.  When I posted this it was my second time after quitter debuff wore off.  The people you see in the screenshot also talked about it happening every time.

**Comment by tlitschye** [comment]
No need for a confirmation request this stuff happens all the time, in eternal citadel, in praag, in blood of the black crain.
Sometimes a /rel fixes it but not always.
This kind of stuff started to happen when the PQ klicking bug was "fixed"
Since then something with the "clicking" mechanic is broken.
