### ISSUE TITLE
Chaos Spawn on the loose

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#1835]
The level 41 Hero Chaos spawn is not locked in the cart where he supposed to be. He appears to be in the cart, however when you attempt to run by him, he comes out of the cart and one shots you. 

This mob would randomly be freed from said cart and roam the city until killed but until that point, he would be locked in the cart. 

The mob is located at 24133, 41000 and attached is a screenshot.
![moondogg_004](https://cloud.githubusercontent.com/assets/15387904/11211974/215d33a6-8d01-11e5-8228-89bc1af2e2f6.jpg)

**Comment by Evildoor** [comment]
I suggest removing it for now. BTW, there is a way to get pass it (wait until some npc spawns nearby and distracts it).

**Comment by Abolition** [comment]
I remember when it would "break free" as a random event in the IC from time to time. It'd rampage through the middle of the Apex area and everyone would have to band together to kill it. It was great fun.
Obviously, given we are all low levels, this makes it rather... interesting at the moment.

**Comment by Meralors** [comment]
Removed it from city ( couldnt change it to passive mobs since it's spawned in other place in the game ).
Live with next npc db pull ;)

**Comment by Hauclir** [comment]
![map of inevitable city](https://cloud.githubusercontent.com/assets/7598530/11264865/4c1cd6f4-8e4c-11e5-943f-f512c9bdf403.jpg)
That monster is part of a secret PQ in the inevitable city called Chaos Unleashed, There was only one stage and 1 objective in that PQ and that was to kill that Chaos Spawn.
![hauclir_103](https://cloud.githubusercontent.com/assets/7598530/11265332/590b89b0-8e50-11e5-9e3b-9a8a800e41e2.jpg)
You trigger that PQ by clicking on this skull in that same alley way that it is in. I remember setting that monster loose on the live server on the inhabitants and watching the weak run for their life and the strong fighting it for dear life since the monster does not have a distance reset it can go anywhere in the city and kill. P.S. the smart players would lure it to a stronger friendly npc that can kill it when they cannot kill it themselves in this case they lured it to 
![hauclir_102](https://cloud.githubusercontent.com/assets/7598530/11265205/3f0dbe4e-8e4f-11e5-95f1-18c4d6ad0f15.jpg)
Engra Deathsword a level 47 LORD friendly npc
