### ISSUE TITLE
Neverending agony tactic

### ISSUE THREAD

**Issue by fornicator** [WarEmu/WarBugs#1837]
Says it's for level 29, but is active on my sorc "nutzap" right now.  Roughly no cd on pit of shades if cast continuously.  Tactic appears red on tactic bar, but is active.

**Comment by Evildoor** [comment]
And what's the problem here?
1) With addition of 40rr it is possible to get tactics like this one. Unless it's active by itself, without speccing for it?
2) Tactics saying that they are for lvl 29 and shown in red are known. This is client limitation, nothing can be done about it. Mechanically they work, so it is just a visual issue.
3) "Roughly no cd on pit of shades" - and? It's exactly what tactic is supposed to do (apart from affecting IW) - reduce PoS CD from 20 to 10, with PoS having 10 seconds channel time.

**Comment by ozarmidrashim** [comment]
Not a bug, or at least not one we can fix.
