### ISSUE TITLE
[Quest] Tipping the Scales

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#1838]
Tipping the Scales is picked up from an NPC in the Shadowlands Oath's End Warcamp. The requirement is to travel to the Ostland Raven's Edge Warcamp and talk to "Soiyvk" Stormwing. However, the NPC in the Raven's Edge Warcamp is "Sojyvk" Stormwing and the quest doesn't recognize the difference.

Attached are two different screenshots showing the NPC and the requirement.
![moondogg_005](https://cloud.githubusercontent.com/assets/15387904/11243337/76e0fd06-8dd5-11e5-8f70-e91332d7f1c4.jpg)
![moondogg_006](https://cloud.githubusercontent.com/assets/15387904/11243338/76eb5e22-8dd5-11e5-81aa-25f1202d3af5.jpg)

**Comment by Hauclir** [comment]
![hauclir_101](https://cloud.githubusercontent.com/assets/7598530/11249109/e3a4bca8-8dd9-11e5-890d-010b70008bd2.jpg)
That is because there is another Sojyvk Stormwing in the Ostland warcamp a level 19 Chosen champion and the quest register for him  to complete. Although there is only suppose to be 1 Sojyvk Stormwing, I do not know who is suppose to be the real Sojyvk Stormwing, the Marauder or the Chosen...

**Comment by Evildoor** [comment]
IIRC, Chosen does not accepts quest either.

**Comment by moondoggcavalier** [comment]
I was able to complete the quest by speaking to the Chosen

**Comment by Meralors** [comment]
Quest's npc where actually messed up. The correct npc you have to talk to for quest turn in is now (and should have been) Sojyvk Stormwing - the marauder looking one.
Quest fixed, live with next quest db pull, cheers.
