### ISSUE TITLE
Stomp Da Yard : bugged

### ISSUE THREAD

**Issue by badoglio170389** [WarEmu/WarBugs#18675]
it appened to me already plenty of times in these few days so maybe it is a bug and not a case, each time i try to use choppa m4 "Stomp Da Yard" it goes in cd and its not used - using the ability trigger the visual effect of the ability but not the ability itself, as u can see from the screenshot i have the morale in cd with m4 charged

![bugm4](https://user-images.githubusercontent.com/72200276/111717674-d5c6b080-8858-11eb-90cf-6e838a068345.png)

**Comment by lilimx** [comment]
Hey,

I need a bit more information, atleast I need your combat log to see if you even hit the enemy with your M4. A small clip would be awesome.
I've tried to reproduce it but it works on my Choppa on the IC dummies/trainings construct.
Maybe add a small liste where have you tried it. It could be a LOS issue or a delay issue due to the connection.

**Comment by badoglio170389** [comment]
bug solved with some patch probably, it's working fine since some weeks
