### ISSUE TITLE
Gork sez Stop

### ISSUE THREAD

**Issue by Chummi** [WarEmu/WarBugs#1879]
doesn't stop when you stop running. it lasts the full duration of 30 sec.

**Comment by ozarmidrashim** [comment]
GSS has a duration of 2 seconds...

**Comment by Morksezstop** [comment]
it got durataion of 1 min if the person that got it doesnt stop for 2 sec.

**Comment by Tidybraveguinea** [comment]
I think the skill stops when you run and damages you when you stand. But I'm not sure. Sometimes running removes it, sometimes not.

**Comment by Morksezstop** [comment]
no. the skill is runing 1 min if you dont stop moving, if you do stop for 2 sec it stop working. So it could go from 2 sec to 1 mins depends of the target decision to move or to stop for 2 sec

**Comment by Tidybraveguinea** [comment]
well, I was 1 vs 1 against a shaman. I'm completely aware of that morale and how it works, so when he throwed it I -immediately- froze in place. The morale continued ticking and killed me.

**Comment by Gobtar** [comment]
just to clarify, the ability has a 2 second duration that will reapply itself if the target is moving when GSS expires. GSS is a movement barb for the purposes of damage, not a DoT.

**Comment by Grywwy** [comment]
Sometimes GSS doesnt even get removed when the traget stops for 10 secs and sometimes it only tics 2 secs even if the targed is moving....

Something is definetly wrong with this ability

**Comment by Morksezstop** [comment]
yes, sometimes it stop working without enemy stop moving. May be bunny hopping is preventing the reset of the timer

need some testing, btw here you can see how it is ticking if target dont stop \and the ridicules kotbs shatter...\
<a href='http://postimage.org/' target='_blank'><img src='http://s16.postimg.org/tu7f84m05/GSS.jpg' border='0' alt="GSS" /></a><br /><a target='_blank' href='http://postimage.org/'>online photo sharing</a><br /><br />

**Comment by Lheana** [comment]
A bug I could see with Gork sez Stop is that it's stopping when the enemy is snared. And for example, it stops when the enemy is under ~7% his wounds cause he is automatically snared.

**Comment by Lheana** [comment]
Another bug concerning this morale is it does not do any damage if the enemy does not move. But it should hurt during 2 seconds then restart until the enemy stops moving during 2 seconds.

**Comment by Luth-RoR** [comment]
Can we bring some clarification to this report? Is this still a problem?

**Comment by Lheana** [comment]
There are still some bugs with Gork sez Stop : first it does not do any damage if the enemy does not run, while it should hurt during 2 sec then stop if the enemy does not run, or hurt again for 2 sec if he runs. The second bug is it stops when the player is low life, because of the natural snare when life is low ; the game must consider the player as not moving in this case, that's why it stops.

**Comment by notre4ror** [comment]
Tested yesterday. If the target don't move don't do damage, if moves only do the half of the damage that is 150 each second instead of 300 (tooltip says 600  over 2 sev that is 300 for one sec).

**Comment by Lheana** [comment]
I think the damages are correct because on official, as a level 40 rr 100, the Gork Sez Stop hit ~170 damages per tick.
[Video](https://www.youtube.com/watch?v=aG3Sx8079wM&t=1s) see at 1:46. But on official in real the Gork lasted for 3 sec (if the enemy does not move at all), and not 2 sec as on tooltip.
