### ISSUE TITLE
Is Greyseer Quol'tik supposed to hit this hard???

### ISSUE THREAD

**Issue by kekkers119** [WarEmu/WarBugs#18875]
**Expected behavior and actual behavior:**
Is Greyseer Quol'tik supposed to hit this hard? previously he was enraged the entire fight and was hitting this hard however this supposedly got fixed. We wiped first attempt because healer had to go afk right as I started the fight. TBH we ALMOST solo healed it and it didn't seem he was hitting this hard but I didn't check combat logs. Every attempt after he's hitting me for 6k+

**Steps to reproduce the problem:**
We attempted it like 4 more times.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/42598271/115503096-e3020100-a243-11eb-925d-92559e9a18c7.png)

**Comment by CrimsonFenris** [comment]
This boss hit for unusually high dmg since recently yes. It used to have a big burst every 20-30s, but it's about half-HP on our party, not 6+k on tanks (and certainly not 15k total wich is insane, oneshotting everyone except tanks.

Biggest issue now is that most of hits looks so high damage that they are basically undefendable (and I run this boss with a SM with 75+ % constant parry, 100% with 2H channel. Still getting hit 90% of the time without parry, guard included).

I also suspect some bosses in Bastion (the one with napalm and skulls to place) getting too much damage from their buff, since it's really hard to do even with 2 Xguarded tanks, plus skulls mechanic sometimes broken, but it's another matter.

**Comment by kekkers119** [comment]
This issue seems to have been fixed however I have noticed that if you wipe one him and try again this problem actually rears it's ugly head again.
