### ISSUE TITLE
Zealot: Winds of Insanity (ability) knockback/knockdown bugs

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#1893]
One, maybe two bugs with this ability:

1) Against players: the knock-back isn't triggering. Tested with/against 2 willing Order characters in a controlled environemnt. One if them *might* have been punted a tiny distance on the first tick but that could've been lag (800 players...). No knock-back on any of the other ticks.

2) Against NPCs: it is granting the immunity timer. I'm not sure if this is intentional and/or matches Mythic's AoR or not.

**Comment by ozarmidrashim** [comment]
1) WoI was missing its knockback power. Fixed.

2) is not an issue. WoI states in the tooltip that it, like all knockbacks employed against mobs, changes into a 3 second KD. This KD grants Unstoppable, as it should - otherwise you would be able to permanently KD NPCs by using knockbacks against them.
