### ISSUE TITLE
quest "Welcome Back : Brotherhood"

### ISSUE THREAD

**Issue by Locnars** [WarEmu/WarBugs#19003]
Quest requires you to collect cannonballs in the gates of Ekrund, when you interact with the "Crate of Cannonballs" the crate begins to float but you won't get credit for clicking the quest item.

Destro side.
![image](https://user-images.githubusercontent.com/84420575/118728623-cce06400-b834-11eb-8713-d91bd5d11c8c.png)
![image](https://user-images.githubusercontent.com/84420575/118728645-d4a00880-b834-11eb-884a-a4528523a9d9.png)
![image](https://user-images.githubusercontent.com/84420575/118728709-eb465f80-b834-11eb-83a8-da4dfb79d1c1.png)

**Comment by Rubyeclipse-war** [comment]
Thank you for letting us know. This is an old ticket, but I just wanted to quickly confirm why you were having this issue:

![image](https://user-images.githubusercontent.com/60584990/189552587-32e051e3-a55c-4e6a-a495-249ede1f1b55.png)

Both Order and Destruction have similar quests here, but with different objects to find. Order interacts with the Crate of Cannonballs, which you mentioned above, and this is why your quest wouldn't complete. Destro needs to interact with the "cannonballs" located on the Destruction side of the Gate, which will complete this quest. 

Because this could be confusing for newer players, I've gone ahead and updated the text on this quest to clearly tell players not to interact with the crate of cannonballs but instead to find the loose cannonballs instead. On the next patch, Destruction players should see this new text:

![image](https://user-images.githubusercontent.com/60584990/189553017-ad8edcb1-1bd1-4c71-b926-f338569fb5e6.png)

Thanks again for the ticket and hope this will be helpful for others going forward!

**Comment by lilimx** [comment]
Fixed with patch [14/09/2022]
