### ISSUE TITLE
REALM IS FULL

### ISSUE THREAD

**Issue by Doctorek** [WarEmu/WarBugs#1902]
Hi !!!
There is so many players ... i know that !
But this is a server bug I think or ... so many bloody afkers. 
Can you check it? 
PS. Good job boyz and girlz.

**Comment by Evildoor** [comment]
Clarification - according to the forums, something is wrong with server population checks (for example, player logs off and can still see their character as "online") which leads to server being shown as full, while in reality it is not.

**Comment by mursie** [comment]
This is a big issue.  The server has basically been a ghost town since Sunday at 5pm Central Standard time due to this bug.  It shows that 800+ ppl are online and the "realm is full" to most ppl logging in.  Yet, in reality the server has probably less than 25 ppl in it.  No one can join it because of the "full" error.

**Comment by Tiggonos** [comment]
fixed as of 25.11.
