### ISSUE TITLE
Order tryhard losers sat in our new spawn to kill us in city 

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#19100]
![image](https://user-images.githubusercontent.com/37393516/121133804-c70ceb80-c800-11eb-85b4-70a95463cc46.png)
![image](https://user-images.githubusercontent.com/37393516/121134026-f3c10300-c800-11eb-9d76-dabaa2da40fa.png)
![image](https://user-images.githubusercontent.com/37393516/121134091-01768880-c801-11eb-855a-0f204e607e6c.png)
This order premade purposefully delayed their city queue to match vs a solo queue pug group then proceeds to move to our new spawn room inside the citadel before the stage ends so they can aoe the air we recall into for 3 mins. fix this exploit and punish these players.

**Comment by maxonian** [comment]
I was there too and have a bit different take on it, but since the issue is the same, I'll post here.

First off, by the looks of it we had 6 + 6 + soloers vs 6 + 6 + soloers, so all fair there.  I dont share "premade vs soloers WTF GAME?!" sentiment.

With that said, I've personally seen how order guys deliberately went into palace right before stage 2 closure. Meaning this "farm at port" thingie wasnt a mistake or accident.

I dont want any action taken against the order players that were part of this. Both Rolgrom and Dansari already have pretty shit reputation on the server. But that is of course up to GMs to decide.

Needless to say this "infiltrate enemy spawn and farm" has been executed by both factions many times now. Maybe its time for this to be gone? I mean you, the devs, patch out any bugs that allow players to get into enemy warcamps in the rvr lakes with fervor. I believe the stuff we are discussing is just the same - essentially people are able to get inside the 'safe haven' of opposing faction.

![WAR-64 2021-06-08 09-24-46 c](https://user-images.githubusercontent.com/74731579/121138557-803ee600-c840-11eb-97fb-d72e132da15c.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. 
Please don't use the bug tracker to name and shame. 
If you see a player-behaviour issue, please contanct a GM. 
If you want to report a bug, please write it in a matter-of-fact manner.
