### ISSUE TITLE
Can't log destro or order characters

### ISSUE THREAD

**Issue by grotsaidstop** [WarEmu/WarBugs#1911]
Hi!

I was on a destro character (black guard here) when i was disconected from the server. After a restart of the launcher, i tried to log my Black Guard but nothing happened.
I returned on the main charcter page and can't switch on the others characters or swich on Order page.

I restart the launcher, i test an other try with the Black Guard, nothing happen, but i succes to switch on Order page and succes to log an Oder character.

Just to test for an eventual report, i disconnect my Order character and try to log a Destro one, but nothing happen. I quit, and launch again after 1h, Order side is fine, but not Destro.

I know that a friend have the same problem but he can't log his Order charcater, but his Destro one is ok.

Hope i help you!

**Comment by Tesq** [comment]
this problem is related to char only, there are 2 issue

1- the char block seems happen after disconnection/crash
2-you can log with other char and this is wrong cos the game should check the account and not the single character, when 1 of your char log all the others must be offline.

-> you should implement an account check to avoid this kind of problem maybe

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker.
