### ISSUE TITLE
Disconnect during Maw fort sometimes teleports you into mountains around/behind IC gate

### ISSUE THREAD

**Issue by grant-musick** [WarEmu/WarBugs#19132]
On both Order and Destruction getting a disconnect during a fort defense then reconnecting sometimes teleports you into the barren mountains behind the IC gates. If you are lucky you have a path back down to the gate to re-enter. If not, you get stuck in terrain and have to port out.

**Comment by lilimx** [comment]
Hey,

do you have any screenhots of your destination?

**Comment by BomblingTV** [comment]
Hello, this issue is mostly happening from my experience to players who have "effects turned on" (based on my own experience where i rarely crash during the Disconnect wave" during fortresses. And the only thing i can think of i do differently is that i dont have effects on.

Im reaching out to some of the known Warbandbuilders who take part of fortresses, and ask for some screenshots they might have of this issue. ill return when i have more information.

For now i am hearing this often happening in The Maw Empire. Norther mountains.
Reikwald, spawning on the roof of a house.
Some reports of Fell Landing.

https://media.discordapp.net/attachments/412718019425337366/853333623020191794/unknown.png?width=1202&height=676
https://media.discordapp.net/attachments/412718019425337366/853333697510899752/unknown.png?width=1202&height=676
https://media.discordapp.net/attachments/412718019425337366/853334387962019880/unknown.png?width=1202&height=676
https://media.discordapp.net/attachments/412718019425337366/853334412098535444/unknown.png?width=1202&height=676

**Comment by indal-andal** [comment]
fell landing 
[https://i.imgur.com/KNoaxxN.png](url)

It also happens when you are in fort -reservation-  and relog during stage1 (5min)

**Comment by BomblingTV** [comment]
Screenshot of the Fell landing DC-respawn location:
https://media.discordapp.net/attachments/808501351356039228/854471397971066910/unknown.png?width=856&height=482

**Comment by Lheana** [comment]
This should have been fixed several patches ago.
