### ISSUE TITLE
Duraz Dok, Greenskin Chapter 21 Hard PQ, missing 1 cannon stage 1

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#19327]
**Expected behavior and actual behavior:**

Stage 1 requires that you destroy 7 cannons in addigion to 85 dwarves. Only 6 cannons are available. Perhaps one is underground somewhere, as I saw with another PQ?

**Steps to reproduce the problem:**

Kill all the cannons you can find. There are 6, not 7.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

which one did you miss, because I count 7 cannons:

2 on this wall:
![grafik](https://user-images.githubusercontent.com/23266079/126109022-2949c2f5-f36d-4c95-a048-85aa85bb497b.png)

2 on the other wall:
![grafik](https://user-images.githubusercontent.com/23266079/126109055-8f26a341-f541-48fa-8b4d-ea13d837e225.png)

1 in the middle of the PQ next to the big statue:
![grafik](https://user-images.githubusercontent.com/23266079/126109106-0afa1fa7-3e9b-4551-8ead-8dfa143849ac.png)

1 next to the door:
![grafik](https://user-images.githubusercontent.com/23266079/126109139-a66021c8-fd1a-45a1-b1fa-2e0d286e258b.png)

1 inside the tower:
![grafik](https://user-images.githubusercontent.com/23266079/126109166-31fc82de-f000-4091-b03f-e6242a91e6f8.png)

**Comment by lilimx** [comment]
Hey,

Im going to close this ticket now due to no feedback.
