### ISSUE TITLE
EAX

### ISSUE THREAD

**Issue by Fritomaster** [WarEmu/WarBugs#19324]
Is there any way to enable EAX on the ROR client? Even with a older card doesn't allow you to use it. 

Thanks again!

**Comment by lilimx** [comment]
Hey,

thank you for your ticket, but it's actual no bug. If you want to know more about RoR and EAX, please open a thread on the forum.

Nevertheless here are a few information, maybe you haven't checked them yet.
"These games support EAX 4.0 if audio hardware with an OpenAL-supporting driver is present. Because hardware acceleration for DirectSound and DirectSound3D was dropped in Windows Vista,[1] OpenAL will likely become more important for game developers who wish to use EAX in their games. According to Creative's OpenAL 1.1 specification, EAX should be considered deprecated as a developer interface. New development should use OpenAL's EFX interface, which covers all the EAX functionality and is more tightly coupled with the overall OpenAL framework."

Please note, that windows you cant enable EAX since vista.. its not supported.

**Comment by Fritomaster** [comment]
> Hey,
> 
> thank you for your ticket, but it's actual no bug. If you want to know more about RoR and EAX, please open a thread on the forum.
> 
> Nevertheless here are a few information, maybe you haven't checked them yet.
> "These games support EAX 4.0 if audio hardware with an OpenAL-supporting driver is present. Because hardware acceleration for DirectSound and DirectSound3D was dropped in Windows Vista,[1] OpenAL will likely become more important for game developers who wish to use EAX in their games. According to Creative's OpenAL 1.1 specification, EAX should be considered deprecated as a developer interface. New development should use OpenAL's EFX interface, which covers all the EAX functionality and is more tightly coupled with the overall OpenAL framework."
> 
> Please note, that windows you cant enable EAX since vista.. its not supported.
> 
> Edit: ah, forgot to add this one...maybe it's helpful:
> https://gamefaqs.gamespot.com/boards/520538-warhammer-online-age-of-reckoning/45511540
> https://gamefaqs.gamespot.com/boards/520538-warhammer-online-age-of-reckoning/45499819

Ya I did find that but Alchemy released a program to enable it back on older games in up to windows 10.
Just wasn't sure if it was hard coded in to be disabled. I appreciate the help tho thank you.
