### ISSUE TITLE
debolster effect

### ISSUE THREAD

**Issue by fizzlepwn** [WarEmu/WarBugs#19359]
I joined a scenario in tier 1 but when I leveled in the scenario I debolstered while I was in the scenario. Fix please

**Comment by lilimx** [comment]
Hey,

thanks for your report. However you are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide;

* Expected behaviour and actual behaviour
* Steps to reproduce the problem
* Testing Screenshots/Videos/Evidences (always needed)

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now.
