### ISSUE TITLE
RVR ticks

### ISSUE THREAD

**Issue by Freddan2** [WarEmu/WarBugs#19353]
played too many hours rvr today and i dont get the rvr tick or medallions at all even tho i have high participation in zones.

**Comment by lilimx** [comment]
Hey,

Thanks for your report. However you are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide;

* Expected behaviour and actual behaviour
* Steps to reproduce the problem
* Testing Screenshots/Videos/Evidences (always needed)
