### ISSUE TITLE
BO. Cant hit me ability bugged

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#1936]
Cant hit me. Channel and moving at 60% speed. Block increased by 50%. When blocking attacker takes 222 dmg. Its bugged Both in PvE and PvP attacker only take 1 dmg.

**Comment by nelsonus** [comment]
Additionally, this ability sometimes hits the user instead of the attacker. Unable to find exact trigger, but sometimes can be triggered when defensive target is the black orc. Seems to happen when being damaged by many abilities at once.

**Comment by nelsonus** [comment]
Update: Further research found that the damage to the user is being done because guard damage. If the user takes un-blocked/avoided damage from guard, then "Can't Hit Me" damages him as the attacker. This makes this ability a lot less usable, and may end up costing the black orc more health than he's saving by blocking.
