### ISSUE TITLE
Bugs with dead, invenory and all panel

### ISSUE THREAD

**Issue by susaninf** [WarEmu/WarBugs#19437]
hi, I ran into such a problem.
After the relog of the game, the character is considered dead (the health bar is at zero). The character is not visible in the guild window (although others see me in the window and I am online). The "exit the game" or "change the character" button does not work - it is written in the chat that the character is dead. Costume jewelry disappeared from the inventory. The bags are empty - there is not a single item, medals and medallions are also missing.. The hotkey bars are empty. The character himself can move and move around the zones, moves to other zones using the quick move option.
A non-character cannot interact with the world.
Re-entering the game, reinstalling, restarting the computer, the /real command does not help, what should I do?

![1](https://user-images.githubusercontent.com/90922392/133820807-7b0d2e20-008e-4db3-a5fb-69c5781827dd.png)
![2](https://user-images.githubusercontent.com/90922392/133820811-be9eb9d7-ef61-4083-95ca-7d05f3b1a367.png)

**Comment by xpander69** [comment]
Ask a GM (type .gm) in game to reset your char position. might help or try /stuck twice.
if not that server restart for new patch could help also.

**Comment by susaninf** [comment]
not work
and my chat message is doubled
![1](https://user-images.githubusercontent.com/90922392/133906117-820552dc-2ad5-4b40-a5e2-85abcae8d196.png)

**Comment by susaninf** [comment]
ask question to GM (Grumlok), but he say cant help me

**Comment by lilimx** [comment]
Hey,

maybe your addons are outdated as well....I would recommend to join the RoR discord so we can take a look at your files and stuff.
link to the RoR discord: https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=22044

**Comment by lilimx** [comment]
Note:

So I checked his files. They are all fine, He also tried several things that also mentioned in his first post.
There are no addons or addon setup related issues that cause the problem.

**Comment by susaninf** [comment]
I will add: the display of things on other characters disappears
![2](https://user-images.githubusercontent.com/90922392/133921694-9c360401-ab80-46b8-b198-53aa4b2bd2d1.png)

**Comment by susaninf** [comment]
and in the scenarios, the character cannot join the group, the script does not see him

**Comment by Zomega-WAR** [comment]
Wargrimnir (lead GM) can usually fix this if you send him a message on discord. Still needs to be investigated in general as how characters get stuck in this state, but he seems to have the power / magic button to properly log out your character from everything which seems to fix it.

**Comment by susaninf** [comment]
his help did not lead to a result, so I will just keep a diary of mistakes until I get tired and I will not stop playing this =)

the character does not get exp and renown in the scenarios and for raising supplies

**Comment by susaninf** [comment]
the auction has stopped working on the account (on all characters), messages are duplicated in the chat on other characters as well

**Comment by susaninf** [comment]
when re-entering, the profession of one character (for example, alchemy) is superimposed on another (for the second, salvaging)

**Comment by susaninf** [comment]
anybody help me?!

**Comment by whitelionWL** [comment]
Hello I was about to make a new bug report but saw this and I have the exact same issue, every time I log into my slayer he is dead, on my screen I am moving around normally, but to others I appear dead, I can be revived, and then I have to reslot all my skills and tactics, but I get no loot, all of my currency and crafting items are gone too, and upon the next login he will be dead again, in this state I can move without being attacked or attack others, can go into destro warcamps etc. 
![image](https://user-images.githubusercontent.com/58403430/134707116-09a8d922-57eb-4c51-8a2e-c126dd18cad4.png)
Here I am outside IC gate

**Comment by susaninf** [comment]
the problem is the same, only heller or fast travel can revive the character. but experience and renown can only be obtained for killing pvp or mobs, the rest is not available (supplies, fort, scenario)
the auction will also not work (it does not work for all characters)

**Comment by lilimx** [comment]
Hey,

can you both say when exactly the issue occures the first time (before a certain patch or something)?

**Comment by susaninf** [comment]
the problem occurred immediately after the death of the elves in t2 2 weeks ago

**Comment by whitelionWL** [comment]
For me it was 21st (Tuesday) at around 9pm, the rvr zone was averlorn, completely fine before I went into the SC, once I loaded into it is when the problem hit, I wasn't in any group, saw no other groups, scenario summary window empty, left the SC, dead when the load screen finished, no skills, no tactics, no currency, no craft items (normal inventory is still there.)

**Comment by Tesq** [comment]
i saw these player so the bug is not visual and not show on their part of the client only

**Comment by NeedEvenMoreDakka** [comment]
Unfortunately I ran into the same issue as the OP.

Joined a scenario (Reikland Hills) when the party frames bugged out. Deemed it a visual bug, so I finished the scenario normally, continued playing for another ~15 minutes (not sure whether my bags were already empty) before I realized I wouldn't get any reknown. Went for the wc and logged my character out and back in and that's where the shitfest began.

Symptoms are the exact same as the OP described it. Additionally I get an exception thrown in my chat which reads as following:

> FormatException was thrown from ThrowOverflowOrFormatException.

![ElaniaBUGGED](https://user-images.githubusercontent.com/73796736/147737233-09e31356-ecd8-444e-b321-dce56c86913a.jpg)

**Comment by NeedEvenMoreDakka** [comment]
Update on my side:

Got the advice to use /stuck twice to unfuck the char. Asked guild members to rezz me because in my semi-dead state I couldn't use /stuck. Ironically they reported that I was actually dead on their screen.

After using /stuck I was ported back to the Blighted Isle, got a very,long loading screen and now I'm thrown back to the lobby anytime I want to log in on this char.

Other characters can still be accessed without any trouble though. It's just the witch elf, that is bugged,

**Comment by NeedEvenMoreDakka** [comment]
Another update:

I frequently log in on my bugged char in order to check if it's still bugged. Last time something interesting happened, as I got the notification that my expedition resources expired. This is interesting because all of my bags actually seemed empty (even the one with the currencies), yet apparently my items are still there, they are just not being displayed / fetched from the database correctly?!

![ElaniaResourcesExpired](https://user-images.githubusercontent.com/73796736/148037154-9daeea70-0940-43a6-982c-a153c8e97ee9.png)

Hope this helps narrowing down the issue!

**Comment by QuickerBen** [comment]
Hi all, I have a related issue to what people have been talking about here.  For me it did not involve a scenario at all, I was getting some lag while playing in orvr and noticed a weird error I have not seen before.  After that error my character was not gaining renown from kills, so I restarted the game to see if it would fix it and when I logged back in I got the error I was dead with no option to respawn although I could walk around the world.  This happened to me on January 5th at 9:25 pm server time.

I took this screenshot of the error before I was "dead".
![Tornado_004](https://user-images.githubusercontent.com/97256921/148452429-7685f085-1c9d-4b7b-971e-3ff4550f38ea.jpg)

Here was about 25 mins later where now I was "dead" after relogging hoping to fix the lack of renown gain from kills. 
![Tornado_005](https://user-images.githubusercontent.com/97256921/148452940-e55c2ea8-ce9b-47fa-b8ae-1571382680b9.jpg)

After reading this thread I logged in again took one more screenshot of my inventory, like the others most of it is missing but for me the first pouch was unaffected though everything else appears missing including the currency, crafting and quest items tabs.
![Tornado_006](https://user-images.githubusercontent.com/97256921/148453536-321b9e3a-f4e3-41bb-bc05-4b087c3a19dd.jpg)

So for others contacting a GM did not help?  I guess I'll stop playing see if its fixed in a few months or something...

**Comment by QuickerBen** [comment]
I have an update; today the server was down for a few hours and after it came back online, the patch notes said "- We have today migrated Martyrs Square to a new server." so I loaded the game and tried to log into my Bright Wizard again.  He now loaded in alive and it looks like his inventory is no longer empty as well.  I also was able to change zones, do scenarios and earn renown and experience in them.

I don't know if the bug has been squashed server-wide or if just that I am freed from it, it might be worth checking any characters previously affected by this.
