### ISSUE TITLE
Winds impervious quest reflection not working for unlock when clicked upon also close quarters/doombolt not working

### ISSUE THREAD

**Issue by zarrathos** [WarEmu/WarBugs#19471]
Hello,
Winds impervious quest/ reflection (the one in Cinderfall) not working for unlock when clicked upon also close quarters/doombolt not working correctly. Same casting time when armed and standng right beside enemy.
Thanks guys.

**Comment by lilimx** [comment]
Hey,

thanks for your report. However you are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)
- Additional, please only one issue per ticket.

Please open a new ticket with all required information. You can find two guides that will help you here:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
