### ISSUE TITLE
Hunter Vale last boss another (brand new) bug

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#19484]
So, we all know HV is bugfest - was since the initial release. And especially last boss fight.
But today we faced something new.

We reduced boss HP to 80% - 1st potals phase started. We completed it with no efforts.
Then we lowered boss HP to 60% - 2nd portals phase started. BUT! When we "killed" 2nd portal it resets his HP and 2nd portal phase was started all over again. We killed it and fight was continued.
Boss came out, but when he should be transformed 1st time he stuck at place for a few seconds we ain't clicked at any animal around (they are not visible due old engine which is unable to show so many objects on the screen) and then boss appeared in the center of the room in the lion form **and** with FULL HP!
We started to hit him and guess what? WHOLE fight resets: at 80% 1st portals, at 60% - 2nd portals etc.
_No one used any kind of controls on the boss_

**Expected behavior and actual behavior:**
Expected: no bugs
Actual: there is tons of

**Steps to reproduce the problem:**
Play HV.

**Testing Screenshots/Videos/Evidences (always needed):**
I didn't recorded or made screenshots.

**Comment by Zomega-WAR** [comment]
Can confirm there's a bug where the Kurnous resets to 100% mid-fight during/after portal stage 2. Had it happen in two runs now. In the second run the bug was triggered due to wiping.

1) Kurnous 100% - 80%
2) Portals stage 1 (no adds)
3) Kurnous 80% - 60%
4) Portals stage 2 (adds)
-- Wipe Here, Fly Back on Eagles --

5) Kurnous back to 100%, first portal stage in process (no adds) but is still applying the hex to people
6) Kurnous 100% to 80%
7) Portal stage again with no adds (can't remember if hex was being applied)
8) Kurnous 80% to 60%
9) Portal stage 2 with adds, all worked fine

**Comment by MaxHayman** [comment]
This should be fixed. If not please reopen.
