### ISSUE TITLE
Dark Elf Chapter 18

### ISSUE THREAD

**Issue by jhamm-13** [WarEmu/WarBugs#19545]
**Expected behavior and actual behavior:**
Killing/Completing directed objects on Isle of the Dead should grant INF.  It stops at a specific point.

**Steps to reproduce the problem:**
Travel to isle of the Dead, select any of the PQs and kill a listed object.  No award of INF, can loot NPC respawns, PQ will advance, just no INF

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/93090688/138603192-b9a6d08d-0250-4041-b1f1-9642f324cc4c.png)

After completing PQ
![image](https://user-images.githubusercontent.com/93090688/138603902-d4611af1-3fc2-45eb-a731-27d32a7492f0.png)

**Comment by Lheana** [comment]
As you can read on the right page, PQs of the Isle of the Dead are not bound to the Dark Elf Chapter 18, but 17, so that's totally normal that you don't get influence for Chapter 18 when you complete PQs in the Isle of the Dead.
Complete the PQs mentioned on the right page and you'll get influence for Chapter 18.
