### ISSUE TITLE
Leather Mask of the Gobbo Gone

### ISSUE THREAD

**Issue by Sixmoons48** [WarEmu/WarBugs#19540]
This happened last halloween event, the old "Leather Mask of the Gobbo" is gone from the inventories of the characters that had it.  It was fixed shortly after, i didnt expect it to happen again this halloween.
![image](https://user-images.githubusercontent.com/21229715/138510657-903e5ed3-ab70-423b-b4d0-9ddcb7d7393b.png)

**Comment by Kaelang** [comment]
Checked this in DB and looks to be working correctly. The Mask decays into another Mask (without magical properties) after a set period of time.

If this was 'fixed' as you said then I'd presume this was looked at and confirmed to be working.

If you think there's still a problem here please re-open this ticket because this doesn't look like a bug anymore.
