### ISSUE TITLE
Gunbad boss Kill Wight Lord Solithex

### ISSUE THREAD

**Issue by Evilchosen** [WarEmu/WarBugs#19595]
Gunbad boss Kill Wight Lord Solithex  Piller keep sponingand adds can kill the piller will just pop up 2 sec later again

**Comment by lilimx** [comment]
Hey,

thanks for your report. However you are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Ecilchosen** [comment]
Evilchosen is the name   and ill didit on evilviking

Den mån 15 nov. 2021 kl 20:42 skrev lilimx ***@***.***>:

**Comment by lilimx** [comment]
Hey,

please read again what I've wrote. Did you do more tries? Any screenshots? Maybe someone who was in your group can wrote more about it?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
