### ISSUE TITLE
Can not equip "Tears of Isha" - get error messerge

### ISSUE THREAD

**Issue by MannyKarlavera** [WarEmu/WarBugs#19654]
Hiya, just dinged lvl 85 but when i try to equip the elf blindfold "Tears of Isha" i get an error messege: "Cannot equip an item that is stacked. Please report this to the bugtracker."

Tried both r-click and drag and drop to both character and apperance. 
 
Tried to relog after ding, but no luck.

Kind regards

**Comment by CrimsonFenris** [comment]
Youhave to use the bottom right slot in the "dye items" interface (speaking to any merchant), and let this item slide into the special slot.

It's not appearance item like others (it has no specific slot since its meant to be combined to any other head appearance).

Anyway, an explanation could be good to add in the tooltips... ;)

**Comment by MannyKarlavera** [comment]
Sweet, thx a bunch!


Sent with a Spark

**Comment by lilimx** [comment]
Fixed with Patch 19/12/2021
