### ISSUE TITLE
[WH] snap shot is undefendable

### ISSUE THREAD

**Issue by coltylul** [WarEmu/WarBugs#19723]
WE have same i think. Same problem that posted here before and fixed, but now actual again.

**Comment by lilimx** [comment]
Hey,

thanks for your report. However you are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by coltylul** [comment]
same as
https://github.com/WarEmu/WarBugs/issues/19297
https://youtu.be/U4JdjoVBVpI

**Comment by lilimx** [comment]
dublicate / related to #19297
related to #13435
