### ISSUE TITLE
Skill not showing?

### ISSUE THREAD

**Issue by afonu** [WarEmu/WarBugs#19744]
My white lion spends specialization skill points, but no skills appear to be used? Why is this?

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by lilimx** [comment]
I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
