### ISSUE TITLE
Ironbreakers able to block attacks (punt) while knocked down

### ISSUE THREAD

**Issue by wghtopside** [WarEmu/WarBugs#19757]
At first I thought it was a networking issue. Like if I knock IB down and try punt right away, maybe it was too early to register that he is KD'ed or whatever the issue is. But I have a 5s KD and I waited 3s and had 2s of KD still remaining and IB still blocks punt while knocked down (even from behind) each time I try to do it. So many times now it's not coincidental. And it seems to happen only against IB.

**Comment by bloodmasked** [comment]
everyone can block/parry/dodge/disrupt while knockdowned

**Comment by lilimx** [comment]
Hey,

the fact that being knocked down does not reduce avoidance in RoR. In other words, hitting a knocked down player does not make your attacks undefendable. Its purely positional.

If you are still the opinion there is a bug, I leave this ticket open for the next 14 days, so you can bring some evidences.

**Comment by wghtopside** [comment]
I believe I explained already that standing behind him does not help, Or
which position do I have to take to make my attacks undefendable?


пн, 24 янв. 2022 г. в 23:58, lilimx ***@***.***>:

**Comment by Bejkon** [comment]
@wghtopside 

Me and Lil'MX, took the time to test this specific case, BG vs IB.

The IB ran Oathstone just to make sure we didnt just get lucky while hitting it in its back.

Outcome:
The knocked target could still avoid attacks/punts/whatever from the front.
The target could not block or otherwise avoid attacks from the back, no matter if CCd or not.

I was 99% sure this was what we were to find, and now im 100%. That goes for you aswell unless you have a clip from a test of your own showing otherwise. If you want to have help creating said clip just hit me up ingame, name is Oathmeal. That way i could get to see the backblock in action.

My guess is the client-server-client conection doesnt 100% agree on positioning, or isnt fast enough. In combat its common for people to whine about "facekicks" or being blocked/parried from what seemed to be a clear flanking position, happens to me on the daily. Its also the reason you can see SH/SW/Stealthers selfpunt in one direction and then teleport somewhere else. Just lag, not a bug and nothing easily fixed.

And for your question "which position do I have to take to make my attacks undefendable?":
The Back. The back is the answer. I belive its 180deg, but it could possibly be 270, i cannot recall.


/Bejk
