### ISSUE TITLE
Close Quarters (BW) Tactic not working

### ISSUE THREAD

**Issue by nightmora** [WarEmu/WarBugs#19764]
Hi and sorry my english

Close quarter tactic fail more than 60% times.

Thanks

**Comment by nightmora** [comment]
When relog works fine.
After SC or RVR works wrong

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by nightmora** [comment]
**Close Quarters tactic equiped**
- Expected behaviour: fireball cast time 1,5 sec on target at 20ft or less
- Actual behaviour: fireball cast time 3 sec on target at 20ft or less

**Steps to reproduce the problem**

- Login > Check if close quarters tactic is equiped > Do one scenario > Try the close quarters tactic on target dummy or a enemy 
- if you relog then tactic works fine

**Testing Screenshots**
Screenshots after doing one scenario.
Fireball cast time is 3 sec.

![Chispita_002](https://user-images.githubusercontent.com/7690485/151159049-273bbc25-d0a5-4173-8100-34d449a4c25a.jpg)
![Chispita_005](https://user-images.githubusercontent.com/7690485/151159117-f80c988d-e379-47c5-8188-d4296812d057.jpg)


Thanks

**Comment by lilimx** [comment]
Hey,

we did some tests, but we are not able to reproduce it. Are we missing something?
Maybe your tactics or your equip? Maybe it's because you are not lvl 40?

**Comment by lilimx** [comment]
Hey,

we did some tests, but we are not able to reproduce it. Are we missing something?
Maybe your tactics or your equip? Maybe it's because you are not lvl 40?

**Comment by nightmora** [comment]
Hi.

I'm sure close qurters tactic was on.

Maybe it's because you are not lvl 40?
Maybe ....... I will hit lvl 40 on a few days. Then i will write if the issue continue or not.

Thanks

**Comment by xpander69** [comment]
Should be working fine. feel free to add new info here if the problem is still there for you.

**Comment by nightmora** [comment]
works fine!!!

Thanks
