### ISSUE TITLE
Cant add dyes or talismans to my characters

### ISSUE THREAD

**Issue by Scardith** [WarEmu/WarBugs#19827]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Scardith** [comment]
Hello,
I been trying to add talismans and dyes to my characters. but it wont let me for any of them. Please help. sucks to play when i cant even edit my characters

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Scardith** [comment]
it has been fixed
