### ISSUE TITLE
Drop invisibility

### ISSUE THREAD

**Issue by mrgreeny23** [WarEmu/WarBugs#19841]
when taking any damage, the invisibility disappears on my wh

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by SecretsOTheP** [comment]
This is being addressed internally.
