### ISSUE TITLE
Twitch Mount Icon tooltip wrong.

### ISSUE THREAD

**Issue by AkameSins** [WarEmu/WarBugs#19925]
Icon buff for Twitch mount is wrong ? It says 60% while mount is 65%.

[https://prnt.sc/ms_Hijq9YmHf](url)

**Comment by lilimx** [comment]
Hey,

65% any confirmation about that? Because all mounts over 59% starts to glitch.

**Comment by Zomega-WAR** [comment]
This is because the item itself displays the uncapped speed (65%), but when you use it the player buff says 60% due to the cap.

![image](https://user-images.githubusercontent.com/60266177/158277624-6ad2eb2a-3958-4049-9d49-a744fe0a3ba2.png)

![image](https://user-images.githubusercontent.com/60266177/158277664-1c93e389-c6f0-478d-8834-dc83aa4bb3ff.png)

I think the only mount this really affected before was the bugfinder's Manticore which says 70% on the item but actually grants a 60% speed bonus.

**Comment by lilimx** [comment]
Aaah!

**Comment by GamesBondd** [comment]
Fixed
