### ISSUE TITLE
gold disappeared

### ISSUE THREAD

**Issue by lothra** [WarEmu/WarBugs#20021]
good mornning. i had transferred money from my characters to my white lion and with the crash server my 210 gold disappeared . thank you.
my toon in game : wl ilwyn

**Comment by lilimx** [comment]
Hey,

sorry, but we don't do any refunds:

**Nothing that you earn on this server is guaranteed.**

_While we strive to minimize issues, the fact remains that you, and all of us, play on a development server and represent if not the first, then the second line of testing. This means that the playerbase are occasionally exposed to destructive bugs. Accordingly, we guarantee nothing. We reserve the right to wipe any type of progress should the need arise, and we have a general policy of not restoring losses that occur due to issues, as our primary mission is to restore the game._

source: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=16391

**Comment by lothra** [comment]
ok thank you
