### ISSUE TITLE
Fierce Might isnt as fixed as u claimed

### ISSUE THREAD

**Issue by ravezaar** [WarEmu/WarBugs#20040]
Ok so Secrets said they patched Fierce Might live, and as a Slayer main who also hate bugs and abused stuff ingame went to test it. Tested as before with a DoT called Onslaught (we all know this aoe DoT) Normal ticks seems fine even under 1k HP wich I was at this test but well Crits displayed the warning indicator and these numbers still seems very high.

https://imgur.com/a/htxpB6n

plz confirm if its still bugged wich I assume it is with 1300+ ticks on an AoE Dot

**Comment by lilimx** [comment]
Hey,

Yeah, Secrets hopped off the team (I don't know for how long).

**Comment by lilimx** [comment]
Related to #19893

**Comment by Grock-r** [comment]
I did a quick test as well and indeed there's no change, it behaves like it always did.

Bejkon explained well what happens, but to add: 
- Reapplying the DoT resets the effect so you can't stack it, it depends only on your current HP and the number of the damage tick in the current dot application.
- It doesn't affect channeled attacks (RoA/Retrib) and doesn't affect ID either coz its considered a direct attack.

Honestly havent heard of anyone trying to make use of it until this month, its not very practical outside of duelling or city champ stage and the abilities that can benefit from it are kinda meh

**Comment by lilimx** [comment]
Hey,

I did some things and hope someone is going to check where the fix stuck in the pipe.

**Comment by Paurax** [comment]
https://streamable.com/dk975g

**Comment by Undrsiege** [comment]
Sad this is allowed to be exploited..

**Comment by Zomega-WAR** [comment]
> 

Do you know if reapplying the DoT allows for a 4th even higher tick? Usually the DoT ticks for 3 times over 9 seconds, but if it uses the new DoT time extension thing which the majority of DoTs do, then reapplying it between two ticks would cause the reapplied version to have 4 ticks and a slightly longer duration. If the damage increases per-tick, then adding a 4th tick would let the final damage scale even higher.

As the skill has a 10s CD it would need to be combined with some form of CD reduction (Short Temper tactic or a Swordmaster's Whispering Winds ability), otherwise you can't reapply the DoT before it runs out.

**Comment by Zomega-WAR** [comment]
> Reapplying the DoT resets the effect so you can't stack it, it depends only on your current HP and the number of the damage tick in the current dot application.

Do you know if reapplying the DoT allows for a 4th even higher tick? Usually the DoT ticks for 3 times over 9 seconds, but if it uses the new DoT time extension thing which the majority of DoTs do, then reapplying it between two ticks would cause the reapplied version to have 4 ticks and a slightly longer duration. If the damage increases per-tick, then adding a 4th tick would let the final damage scale even higher.

As the skill has a 10s CD it would need to be combined with some form of CD reduction (Short Temper tactic or a Swordmaster's Whispering Winds ability), otherwise you can't reapply the DoT before it runs out.

**Comment by Paurax** [comment]
> > Reapplying the DoT resets the effect so you can't stack it, it depends only on your current HP and the number of the damage tick in the current dot application.
> 
> Do you know if reapplying the DoT allows for a 4th even higher tick? Usually the DoT ticks for 3 times over 9 seconds, but if it uses the new DoT time extension thing which the majority of DoTs do, then reapplying it between two ticks would cause the reapplied version to have 4 ticks and a slightly longer duration. If the damage increases per-tick, then adding a 4th tick would let the final damage scale even higher.
> 
> As the skill has a 10s CD it would need to be combined with some form of CD reduction (Short Temper tactic or a Swordmaster's Whispering Winds ability), otherwise you can't reapply the DoT before it runs out.

Look https://streamable.com/dk975g

**Comment by lilimx** [comment]
Hey,

guys, I know the topic is hot. But this is not a forum. Please talk about that on our forum or on Discord.

**Comment by ravezaar** [comment]
yea all I want to see here is a Solution and hopefully it will come, clearly this bug hasnt affected Des ingame domination.

**Comment by Grock-r** [comment]
> Do you know if reapplying the DoT allows for a 4th even higher tick? Usually the DoT ticks for 3 times over 9 seconds, but if it uses the new DoT time extension thing which the majority of DoTs do, then reapplying it between two ticks would cause the reapplied version to have 4 ticks and a slightly longer duration. If the damage increases per-tick, then adding a 4th tick would let the final damage scale even higher.

So i tested for this and it seems neither Cleft in Twain nor Onslaught work with this dot mechanic: the duration stays the same, number of ticks stays the same and the crit damage /w FM stays the same on all ticks as well, i suppose this is because both abilities have "instant" tick on application so they are excluded from reapplying dot mechanic.
Screenshots:
Cleft in Twain regular: 
![asd](https://i.imgur.com/EFyLwX2.jpg)

The only ability that works with this is Relentless Strike and indeed it does get 4th tick and does slightly more crit damage on it.

p.s. If anyone has any genuine videos (or at least scoreboard screenshots) of the use of this bug in actual gameplay im very curious to look at it, send me a dm on forums or on Bitterstone discord :P Its been known for years and as far as im aware nobody did anything with it lol

**Comment by ravezaar** [comment]
tbh I never ever use Fierce might so I only tested it when I heard of the bug. In Wb I run PfM and PT, adn for Solo I never touch FM cause there is always better ones

**Comment by Paurax** [comment]
> > Do you know if reapplying the DoT allows for a 4th even higher tick? Usually the DoT ticks for 3 times over 9 seconds, but if it uses the new DoT time extension thing which the majority of DoTs do, then reapplying it between two ticks would cause the reapplied version to have 4 ticks and a slightly longer duration. If the damage increases per-tick, then adding a 4th tick would let the final damage scale even higher.
> 
> So i tested for this and it seems neither Cleft in Twain nor Onslaught work with this dot mechanic: the duration stays the same, number of ticks stays the same and the crit damage /w FM stays the same on all ticks as well, i suppose this is because both abilities have "instant" tick on application so they are excluded from reapplying dot mechanic. Screenshots: ![asd](https://camo.githubusercontent.com/3b9113c742a825eb848f9b60c21878103a45f5c779b34747b3be9e1d84871ef6/68747470733a2f2f692e696d6775722e636f6d2f4546794c7758322e6a7067)
> 
> The only ability that works with this is Relentless Strike and indeed it does get 4th tick and does slightly more crit damage on it.
> 
> p.s. If anyone has any genuine videos (or at least scoreboard screenshots) of the use of this bug in actual gameplay im very curious to look at it, send me a dm on forums or on Bitterstone discord :P Its been known for years and as far as im aware nobody did anything with it lol

video here : ======> is not hard look and open your eyes...   https://streamable.com/dk975g

**Comment by lilimx** [comment]
Hey,

guys....I've already written here. Please discuss this on our forums or on discord.

**Comment by lilimx** [comment]
fixed with patch 30/04/2022
