### ISSUE TITLE
Issue with Renown gear merchant in Inevitable city

### ISSUE THREAD

**Issue by Goontrain** [WarEmu/WarBugs#20085]
I was browsing upcoming gear the level 34 to 39 renown gear merchant in inevitable city on my level 31 black orc. Character name Poolboy. I had 522 war crests. All of a sudden my inventory was spammed with disciple of khaine shields that were level 29. These weren't even in the list of gear because I'm a black orc. They also are the wrong level bracket for this vendor. My war crests were also spent in the process. I lost approximately 300 war crests. I would like the shields gone and my war crests back please

**Comment by Goontrain** [comment]
![Poolboy_003](https://user-images.githubusercontent.com/80876753/167373534-ae5ae65c-8a32-4732-ac0a-ad6d645254b8.jpg)
![Poolboy_004](https://user-images.githubusercontent.com/80876753/167373540-38d69918-da4f-478e-928c-e156d3230a39.jpg)

**Comment by Goontrain** [comment]
You can see in the above pictures my warcrests have indeed been taken, and the random DOK shields in my inventory which i shouldnt even be able to purchase

**Comment by lilimx** [comment]
Hey,

uhm I thought about a picture of the vendor window.

Additional I have to say, that there is no refund:

**Nothing that you earn on this server is guaranteed.**

_While we strive to minimize issues, the fact remains that you, and all of us, play on a development server and represent if not the first, then the second line of testing. This means that the playerbase are occasionally exposed to destructive bugs. Accordingly, we guarantee nothing. We reserve the right to wipe any type of progress should the need arise, and we have a general policy of not restoring losses that occur due to issues, as our primary mission is to restore the game._

source: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=16391

**Comment by Goontrain** [comment]
Ok no problems, im done playing then
