### ISSUE TITLE
Hello, I found a bug when using some tactics, supported skills are disabled.

### ISSUE THREAD

**Issue by Khorni** [WarEmu/WarBugs#20121]
Hello, I found a bug when using some tactics, supported skills are disabled. The Stay Focused type of Kotbs is disabled with the Focused Mending tactic. Wl also disables Trained To Hunt when using the Pack Hunting tactic.

Character Ppopps (Kotbs 39lvl)

**Comment by lilimx** [comment]
Hey,

please one issue per ticket. The Stay Focus // Focused Mending is already known: #20058 and #13368

Additional we always need more information to reproduce the issue:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
