### ISSUE TITLE
Morrslieb Missing After Strictures of Morr Quest Completion

### ISSUE THREAD

**Issue by Emissaryx** [WarEmu/WarBugs#20184]
Completed Morr main questline chat box said received Morrslieb but did not

Exactly that, I completed quest and did not receive the Morrslieb, chat box said I did but nothing in any of my bags, restarted, cycled list on and off still nothing. 

![Emissary_015](https://user-images.githubusercontent.com/107319355/173198605-d0276044-4fcf-48ad-9a24-7d36e6c1638c.jpg)

**Comment by Emissaryx** [comment]
![Emissary_017](https://user-images.githubusercontent.com/107319355/173198652-871332f6-871c-4eb2-8033-be2b4e9cdc6d.jpg)

**Comment by Demonthyr** [comment]
Hello there,
As i have the exact same issue : 

- Character concerned : Kanzen
- What happened : finished the quest, received the cape but not the token despite the log.

- More information : i have this bug since long, and still have it on all my currencies
- When i receive war crest for exemple, i see the log but nothing in my main bag
- I need to take war crest from my devices bag->move it into my main bag->to see the total of war crest incremented
- For the present ticket, as i had initialy 0 previous Morrslieb in my devices bag, i wasnt able to do this manipulation
- As a result as in the exact same situation as described by Emissaryx
- (If needed i'll open other ticket to be more precise)

**Comment by lilimx** [comment]
Hey,

The Morrslieb Crest from the Quest isn't a currency...it's an Event Slot Item
The Event currency is called: Morrslieb Coin

**Comment by Demonthyr** [comment]
Hi lilimx, for my case i'm speaking of the currency , so the Morsslieb Coin

**Comment by lilimx** [comment]
Hey,

but if it's regarding the coin thing. It could be also a broken patch (so try a fresh install)...
otherwise, open a new ticket please :D

**Comment by Demonthyr** [comment]
Hey there, it is ok about the Morsslieb Crest, I'm creating other ticket about my main issue. I had the matter with the Morsslieb Coin but was saved by a relog. See you on other ticket ;)

**Comment by MaxHayman** [comment]
Sounds like this should be closed. Please reopen if not.
