### ISSUE TITLE
Engineer grenade ranges smaller than the tooltip says

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#20277]
In Altdorf outside of the guild hall, if you put a land mine at the feet of the construct, the land mine explodes hitting 2 target dummies on each side. (5 total targets, the construct, and 2 on each side). Land Mine has a 30 foot range.

If you throw Acid bomb, an AOE DoT with a 20 foot radius at the constrcut, you will get damage from 1 dummy on each side, a total of 3 targets in total.

If you throw any direct damage AOE grenade, Flashbang or Firenomb, each with the same 20 foot range, it only hits the construct, it does damage to 1 target, no target dummy next to the construct is affected by this 20 foot AOE attack.

No radius tactic (extra powder) was equipped or even specced. I'd do more testing on other abilities etc but we all know I'm posting this for posterity. (nothing will happen).

**Comment by Zomega-WAR** [comment]
And you were doing so well until the last couple of sentences.

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
