### ISSUE TITLE
Hunter's Vale - Gate of Nature's Raging Javelin - high damage

### ISSUE THREAD

**Issue by martialiss** [WarEmu/WarBugs#20294]
**Expected behavior and actual behavior:**
Final boss ability: Gate of Nature's Raging Javelin (Phase 2), the spears (aoe) should not be able to kill the players within 2-3 seconds (1 second = spear dmg x spear puddles). Unable to outheal the incoming damage.

**Steps to reproduce the problem:**
Encounter the final boss.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/75132461/182874044-f3a3b838-7851-478d-8725-28b875737e1f.png)

**Comment by xaunik** [comment]
in fact many bosses seem to have no internal CD on abilities, this is happening in Bastion as well

**Comment by MaxHayman** [comment]
Is this new from the last patch?

**Comment by lleri** [comment]
Yes, this is new, starting today.

**Comment by xaunik** [comment]
the Lightning boss in Bastion (who you interrupt when he rears up) would immediately rear up again rather than again 15s later
the left wing, penultimate boss in Bastion (dmg on heals, never use HoTs) stomps much more often than normal
last boss middle wing Bastion punted people on one side, turned around and punted the people on the other

the Javelin Deluge in Hunters Vale is like the extinction event meteor bombardment that killed the dinosaurs, so much so that you can't evade them (they are also hitting MUCH harder)

I didn't dare enter CnT

and yes, started today, yesterday none of this happened

**Comment by xaunik** [comment]
I didn't catch the timestamps in the screen grab but they were about 1-2 secs apart - way too much to heal through

![image](https://user-images.githubusercontent.com/16874366/182958202-8eaa733e-7a28-4c10-8902-f1fcbfc589db.png)
