### ISSUE TITLE
Quest bug: Barring the way (Caledor)

### ISSUE THREAD

**Issue by Kostoglod** [WarEmu/WarBugs#20348]
Good day! This quest not working. Quest demands to help 2 npc. Both of them have to give you quests to finish. When i finished quest for one npc(dwarf) it was good. When i started next part of the quest (help human) i got 0/0 of completed objects. I abandoned quest and get a new one. Now i have both next quests completed and i cant finish this quest chain. Fix pls or help! Important thing: all 3 npc located in 2 different places.

**Comment by Kostoglod** [comment]
![1Wbp8lwuw8w](https://user-images.githubusercontent.com/111536343/185488075-6b12d3ed-efb9-42b5-8d7f-fe47eb75903e.jpg)

**Comment by Rubyeclipse-war** [comment]
@Kostoglod Thanks for letting us know! The Empire quest in this chain was broken and has now been fixed. Fix will go live in the next patch.

Because you've already earned quest completion for these old versions, the fix won't automatically update for you. If a kind GM is able to reset your quest credit, you should be able to properly complete these. 

For GM team (Quest IDs):
36126
36127

**Comment by lilimx** [comment]
Fixed with patch [14/09/2022]
