### ISSUE TITLE
Cant receive mail.

### ISSUE THREAD

**Issue by glukadin** [WarEmu/WarBugs#20350]
**Expected behavior and actual behavior:**
Having icon on minimap telling me i got 2 mail, from RVR i guess.
But when i check it on post office, there is none.

Expected behavior: have mail in the box when indicator telling that there is one (or many).
Actual behavior: There is indicator, but no mail in the mailbox.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![InkedWAR-64_2022-08-19_00-20-14_LI](https://user-images.githubusercontent.com/111539722/185501596-bfd57232-fc36-4045-8d01-43e5bd77d629.jpg)

**Comment by xpander69** [comment]
Nothing in auction tab either? Could just be a visual bug though, does it still stay there after relog?

**Comment by glukadin** [comment]
auction tab empty as well. its gone away after long (12h+) relog. but was there after fast relogs.

**Comment by MaxHayman** [comment]
Theres is not much I can do with no information such as character name.

**Comment by martialiss** [comment]
Hi all

I can confirm the bug and specify a bit more as far as possible.

- [ ✓ ] With my character it was the same, I was in the open rvr and have received through participation bags.
- [ ✓ ] These bags were sent by mail.
- [ ✓ ] The icon for "new mail" has been active since (no bags in the others tabs too). 
- [ ] unfortunately i can't find it and thus can't open it.
character name: _Manei_

- [ ] Now i have logged in once on another character of the same account. and look and behold, here i find the bags in the mailbox.
this character name: _Kodiak_

Maybe this helps a little bit with the troubleshooting.

Best regards
Martin

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
