### ISSUE TITLE
my life gauge doesn't match the actual life gauge ingame

### ISSUE THREAD

**Issue by evilgobo** [WarEmu/WarBugs#20378]
-->
![Relife_868 xxx](https://user-images.githubusercontent.com/110903588/187181463-1c058308-9e67-4848-8aa2-ae90d5bb2d4b.jpg)
gave it a try.. i only have 4.5k life..
there must have gone wrong something

**Comment by lilimx** [comment]
Hey,

please check your stats with .getstats
The paperdoll doesn't display properly.

**Comment by Zomega-WAR** [comment]
Going to take a bet that you equipped items directly from the bank instead of from your back-pack? That causes your real stats to bug out (and the health bar is using the real stats, as is .getstats) while the character sheet looks fine.

[The big bast](https://github.com/WarEmu/WarBugs/issues/19729) is likely the culrpit unless something new broke.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
