### ISSUE TITLE
Black Guard Elite Training

### ISSUE THREAD

**Issue by bulgy70** [WarEmu/WarBugs#20408]
This has been going on for a few weeks now, 1st time i been able to get a video of it. As you can see in the video, i have the Elite Training buff and the knight was still able to punt me. As i have said this has been going on for a few weeks. **This has not been a one off**

https://medal.tv/games/warhammer-age-of-reckoning/clips/AxHKwXpNkF1u9/d1337cRzpBP1?invite=cr-MSx6VGMsOTUxNzQ3MTYs

**Comment by bulgy70** [comment]
2nd video showing a wl's pet doing damage and elite trianing not parrying the attacks. 

https://medal.tv/games/warhammer-age-of-reckoning/clips/AS9vKFGxwMNPb/d1337ofrYOEn?invite=cr-MSwwOG8sOTUxNzQ3MTYs

Can we please have a fix for this

**Comment by FIxxerIrongorge** [comment]
On video number one the Knight punt was on your side.. you can only parry from the front.
On Video number two you have a shield. Block takes priority over parry so if you block you cant parry as well. On top of that the damage u receive IF I seen it correctly u turn your back to the pet and it did a dot on you that's the damage you see. all other attacks were blocked or parried.. It seem that the skill works as intended - IF you want to check it again remove shield, face enemy, remove all gear and Renown on parry.

**Comment by wargrimnir** [comment]
This is working as intended. Fixxer is correct in his assessment.

**Comment by bulgy70** [comment]
So maybe update the tool tip on this and say only works for great weapon, as it does not work when carrying a shield.

**Comment by bulgy70** [comment]
I will do the testing again for you, and i will post a video again for you when i have time. there are also other abilities on the BG which needs looking at. The feeding on weakness does not always get a cool down and also Brutal Smash does not always get a cool down. i will start new topic's for them.

**Comment by wargrimnir** [comment]
You're not doing it _for me_, you're doing it for yourself. The video shows it working as intended. 

Parry is positional. The knight ran to your side and hit your rear 180.
If your character is hit in the rear 180, then you will never parry or block because there isn't a chance to. 

Parry comes after block. If you have sword and shield you will see block if it blocks and parry if it doesn't block. Even if your parry is at 100%. This doesn't mean your parry is broken, block comes first.
Damage over time is not parried, only the initial application is possible. You can't parry bleeding from a wound.
For whatever reason you decided in your "testing" to turn around and let the lion hit your back, it inflicted a dot. You were taking 6 points of dot damage that _cannot be parried_.

Please try to have some fundamental understanding of game systems before you repeatedly insist on calling out bugs. Otherwise you waste our time and annoy us. 

I hope you enjoyed your moment of excruciatingly specific attention to be told you're wrong several times.

**Comment by bulgy70** [comment]
Wargrimnir, i been away from the game for 3 years, and yes i have forgottern a lot of things about the game. and you know what, i am always happy to learn, always happy for people to point things out to me. I don't get upset over it. I am just happy to know that it is not broken.
