### ISSUE TITLE
[Guild] Unwillingly transferred into "Forces od Order"

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#20406]
As I logged in after the recent patch I noticed that I was put into the "Forces of Order" starter guild, without leaving my guild BeneTleilax before.
The overview states that I joined 2 month ago. 
I actually was in this guild back then, but was kicked at lvl 19 a few days later. (Due to a bug or lvl-cap of guild?)

![Loarelle_025](https://user-images.githubusercontent.com/40274248/189486556-767a3164-0471-4282-9cad-de528b66ed2e.jpg)

**Comment by MaxHayman** [comment]
This was part of this weeks patch.

Players who were in "The Forces of Order" will find themselves part of the guild once again after this patch. You will now be able to leave and continue your WAAAGH!

This was caused by a problem which caused people to not properly leave the guild. So we have fixed the issue and people can now leave.

**Comment by Scophis** [comment]
> This was part of this weeks patch.
> 
> Players who were in "The Forces of Order" will find themselves part of the guild once again after this patch. You will now be able to leave and continue your WAAAGH!
> 
> This was caused by a problem which caused people to not properly leave the guild. So we have fixed the issue and people can now leave.

But why was I pulled out of my new guild for this?
