### ISSUE TITLE
Warrior Priest - Greave of Sigmar

### ISSUE THREAD

**Issue by ThePollie** [WarEmu/WarBugs#2041]
Tactic, Path of Grace - Greave of Sigmar seems to be having a conflict with the Knight of the Blazing Sun's battle shouts. Stand Strong! and Press the Attack!, toughness and strength aura buffs respectively, appear to be preventing Greave of Sigmar's bonus to strength and toughness when Sigmar's Fist is used.

**Comment by Morksezstop** [comment]
becouse buffs doesnt stack and appeare only the higher ones. The question is are auras' buffs higher than sigmars fist buffs?

**Comment by ThePollie** [comment]
Stand Strong! provided roughly eight more toughness, but Press the Attack! was about twelve less strength.

**Comment by ozarmidrashim** [comment]
Not a bug. All of the mentioned buffs are standard buffs, and the highest value is used.

**Comment by Evildoor** [comment]
While i agree that this issue is not a bug and it was this way on live, it once again makes me wonder, with what part of the body Mythic were thinking sometimes... Wild Gambit gives Slayer 120 STR and WS (at level 40), stacks with everything because it's a tactic. Runefang buffs 3 of KotBS' stats by 240, stacks with everything because it's a tactic. Greave of Sigmar adds 120 TOU buff/debuff and 120 STR debuff to Sigmar's Fist, is a tactic... But is treated like a simple buff/debuff. Only because Fist already buffs STR by 120? Really?
Well, i hope that at some point in the future we'll take a look at stats buffing/debuffing in general, but it will be complex and laborious work, so it's a story for another time. For now - this issue is not a bug, as stated by comments above.
