### ISSUE TITLE
[Items] Strength replaced with Ballistics Skill on several Renown Swordmaster 1-Handers

### ISSUE THREAD

**Issue by deepruntramp** [WarEmu/WarBugs#2043]
A stat (I believe Strength) has been replaced with Ballistics Skill on several Swordmaster 1-Handed Swords.  Most of these appear to be on renown vendors.

Examples:

Sniper's Falcata of Merit
Sentry's Falcata of Merit
Echelon Falcata

**Comment by ozarmidrashim** [comment]
Falcatas are Shadow Warrior offhands.

**Comment by deepruntramp** [comment]
Then perhaps the issue is that Falcatas are appearing for Swordmasters and are wieldable
 in the main hand.  Screenshot at the T1 vendor:

![masterblader_000](https://cloud.githubusercontent.com/assets/13120213/11462577/5035c28c-96e4-11e5-9a5b-205c97280e07.jpg)

**Comment by Evildoor** [comment]
Here we go...
1) Falcatas of Merit/etc are SC weapons. They are intended for SW, and they were this way on live. They are wieldable by you because they are just "swords for high elves". Sure, we can add "SW" restriction, but why should we bother? The same happens with other classes - BG can wield healing blades intended for DoK, so what? Just don't use them.
2) Echelon Falcata and other similar - this was changed in this patch. And i especially pointed out about SMs:
[*][661] Fixed weapons from PVP vendors to have stats useful to phys RDPS. List of affected items:
Engineer: Spanner of Vengeance, Spanner of Dominion, Spanner of Conguest, Echelon Spanner, Martial Spanner.
Shadow Warrior: Falcata of Vengeance, Falcata of Dominion, Falcata of Conguest (added to vendor in Altdorf), Sentry Falcata, Echelon Falcata, Martial Falcata.
NOTE: SW swords can be used by Swordmasters, so those of them who used Falcatas will have to change their weapons.
Squig Herder: Stabba of Vengeance, Stabba of Dominion, Stabba of Conguest, Sentry Stabba, Echelon Stabba, Martial Stabba.
The same logic applies here - Falcatas are intended for SW, Blades are indended for SMs. Before the patch, there were no swords with BAL from vendors, so SW were handicapped.
