### ISSUE TITLE
Stunty Noggin unable to be applied to offhand items.

### ISSUE THREAD

**Issue by Orlock13** [WarEmu/WarBugs#20431]
Stunty Noggin not able to be applied to offhand items

**Comment by lilimx** [comment]
Hey,

do you mean as an appearance?

**Comment by Orlock13** [comment]
Correct. It can be applied to main hand appearance (appears in offhand grip like a weapon so can have a shield on arm and holding the helm with main hand empty). It will not apply to offhand shield on BO, Dok, or Chosen as appearance. You are able to equip it, but not change appearance.

**Comment by Rubyeclipse-war** [comment]
Hi there - I have some updates for you on this one!

First, for shields, the dev team decided in the past not to allow swords or similar offensive items to be skinned over shields, as players might use this to manipulate others or hide the fact that they're using a shield. Following that, in this case, we aren't able to allow this item to become a shield skin, as it's currently set to be an offensive weapon skin. 

That said... after looking into this item, we now have some bug fixes / improvements for it coming up! Here's what you'll see in the next patch:

- The Stunty Noggin for Destro and Goreksson's Brutebashin' Ring for Order will now properly appear in your main hand when used or skinned, instead of your off-hand.

- You can now skin the Stunty Noggin and Goreksson's Brutebashin' Ring onto both your main and off-hand items, provided the off-hand is not a shield.

Thanks Max and Eka for their help digging into this one today. Fix coming up with next patch!

**Comment by lilimx** [comment]
fixed with patch 08/10/2022
