### ISSUE TITLE
Sentry's Orcsplitter of Reverence 

### ISSUE THREAD

**Issue by Grundim9** [WarEmu/WarBugs#20455]
I was just going to buy this Axe and instinctively gone to lower rank vendor and bought titan's orcsplitter just to realize when u wanna upgrade Axe u upgrade it to hammer and when u have a hammer u upgrade it to axe.  Tbh Im a bit confused.
![image](https://user-images.githubusercontent.com/114528878/192887733-bbb24c11-857c-4d4f-9004-ec1a5c8bca08.png)

**Comment by Grundim9** [comment]
Just checked other races and thats the only case of those two weapons. Others works like it should sword upgrades to better sword hammer to stronger hammer and axe to nicer axe.

**Comment by Rubyeclipse-war** [comment]
Thank you - just looked into this, here's the latest on it:

- In order to fix this, I had to create two brand new items, as just swapping the stats so this makes sense would end up changing the items for everyone who already owns one of these. So, anyone who currently owns one of these upgraded weps won't be impacted by the upcoming change.

- After the next patch, these items will now upgrade Axe into Stronger Axe and Hammer into Stronger Hammer. The new Axe will inherit the offensive stats and the new Hammer will inherit the defensive stats. So, if you were intending to swap your offensive axe for a defensive hammer, please do so now as you won't be able to anymore soon.

Thanks @Grundim9  for letting us know of this, and as of the next patch, this should be fixed and the new items listed at the bottom of the vendor, putting this in line with all the other classes!

**Comment by lilimx** [comment]
Fixed with patch 01/10/2022
