### ISSUE TITLE
Black Guard Feeding of Weakness

### ISSUE THREAD

**Issue by bulgy70** [WarEmu/WarBugs#20491]
Black Guard Feeding of Weakness is giving back - damage, in stead of "Your Feeding On Weakness heals you for"

![fow_01](https://user-images.githubusercontent.com/44948480/196646852-03c3c6ba-4435-48f5-8d5b-bf303f7ca233.jpg)

Also tested on Training Construct
![fow_02](https://user-images.githubusercontent.com/44948480/196649115-bce1695c-65e8-422b-a363-7652146ee3d6.jpg)

**Comment by lilimx** [comment]
Hey,

tried to reproduce it but it worked out on my end. I think it's related to this issue: #20289

**Comment by bosli42** [comment]
Every lifetap damages you for a negative value to circumvent healdebuffs, so this is working as intended.

**Comment by bulgy70** [comment]
> Every lifetap damages you for a negative value to circumvent healdebuffs, so this is working as intended.

No one said that it was not working as intended, what i said was it should be saying " Your Feeding On Weakness heals you for "

**Comment by bosli42** [comment]
> > Every lifetap damages you for a negative value to circumvent healdebuffs, so this is working as intended.
> 
> No one said that it was not working as intended, what i said was it should be saying " Your Feeding On Weakness heals you for "

The combat text log is a direct translation of the code, so for it to say "heals you" it would either need to be converted from lifetap to direct heal, which would make it affected by healdebuffs, or the translation of lifetaps would need to be changed.

The way it appears in combat log is a definite way for players to know if an ability providing a heal is considered lifetap or heal = interference with healdebuffs (or buffs), so it actually gives us more information the way it is handled currently.
This is helpful because you need a fair amount of game knowledge what skills are considered a lifetap, generally if it has a base value of healing it counts as a healing ability.

Take AM's EoV for example, the skill itself is a healing ability, because it has a base healing attached, so it also has a (tho low) willpower PSM as well as an intelligence PSM and crits with healcrit. But if you slot the tactic that removes base heal and increases "lifetap", it turns into a proper lifetap, losing the willpower PSM and crits with magiccrit.
