### ISSUE TITLE
Acid bomb (engineer)

### ISSUE THREAD

**Issue by darkt1981** [WarEmu/WarBugs#20492]
Engineer Acid bomb can be stacked to 5x on 1 person bringing the corp reduction down to 1795, thats more then even the cap,
sounds a bit broken to me.

havent tested it it can go be on 5x seeing by then ytouyr dead anyway.. lol

**Comment by lilimx** [comment]
Hey,

Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
