### ISSUE TITLE
Living Snot

### ISSUE THREAD

**Issue by IC2Piggies** [WarEmu/WarBugs#20523]
Living Snot in CW is bugged. Spinning around in a circle NOT taking any damage. Please fix this so we can do our QUEST! thank you.

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Rydiak** [comment]
I can't make video, but I can confirm this.  Living Snot simply spins around in circles and repeatedly resets back to 100% now.  He is effectively unkillable.

**Comment by lilimx** [comment]
Ah yeah, it's a dublicate....that part with "spings around in circles" was a bit confusing.

dublicate #20521
