### ISSUE TITLE
problem with equip

### ISSUE THREAD

**Issue by padrepergola** [WarEmu/WarBugs#20553]
Every boots i equip it doesnt show on my character
![Trespolo_001](https://user-images.githubusercontent.com/118435075/202444686-c78eac15-86f5-4bdf-9bbf-3eb5631e48e4.jpg)

**Comment by b00nation** [comment]
try to reload your client or use /rel

**Comment by padrepergola** [comment]
> try to reload your client or use /rel

it doesnt work

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
