### ISSUE TITLE
Loosing buff potion after switching Blessing for WH

### ISSUE THREAD

**Issue by Zaaaaap88** [WarEmu/WarBugs#20586]
When im casting blessed bullets of purity my pots disappering (seems they where checked) and only my str pot is reapply and the armor pot is vanishing.

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (use .getstats)
- check if your buffs are back after a /rel or you've changed the zone

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by CrimsonFenris** [comment]
Got this bug too, it often happens when you use default UI, where buff icons are duplicating and/or overlapping. Check with a .getstat your armor value, before and after the bug, to see if it changed or not.

I strongly suggest you to use Pure addon wich totally eliminate UI icons issues.
