### ISSUE TITLE
Shrapnel Arrer Is Not Ailment

### ISSUE THREAD

**Issue by Manatikik** [WarEmu/WarBugs#20604]
Shrapnel Arrer's debuff is not an Ailment so can not be used to trigger Rotten Arrer for the heal debuff. This is an oversight/bug

Squig Herder

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

**Comment by lilimx** [comment]
accidentally closed it

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
