### ISSUE TITLE
squig melee 2 branch

### ISSUE THREAD

**Issue by Dugaros** [WarEmu/WarBugs#20619]
Greetings, I am playing for the shepherd of squigs in the 2nd development branch and I have a mistake when using all tactics from this branch at once. being in armor , when I summon squig , I am thrown out of armor .
when he drank the potion for 60 minutes and jumped into the squig armor and then back into his normal appearance, the effect of the potion disappears

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Your current lvl // rr rank
- Testing Screenshots/Videos/Evidences (always needed)
- only one issue per ticket

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Ruin-84** [comment]
This bug i related to Sneaky Git Tactic. when you have it Equipped, every time you summon pet you are kicked out of Squig armor. 
So if your pet dies and you: 
- resumon it **you will be kicked out of Squig armor**
- detonate pet and instantly resumon another one **you will be kicked out of Squig armor**
- consume pet to heal wounds and instantly resumon other one **you will be kicked out of Squig armor** 

I don't know anything about the potion problem.

**Comment by lilimx** [comment]
Hey,

so it's an already reported issue. Im going to close this one.
