### ISSUE TITLE
Shadow Prowler/Incognito are casted they can't be cancelled until their cd is finished

### ISSUE THREAD

**Issue by Onlyendari** [WarEmu/WarBugs#20657]
As title says stealth can't be canceled at any time like it used to, now stuck in stealth for the full 30 seconds and with the recast starting upon leaving stealth a miscast will cost you a full minute.

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

**Comment by zipherus** [comment]
I don't know how we're supposed to show proof of this when the max file size is 10MB. Videos recorded at even low quality are much larger than that.

Expected behavior: Once stealth is active, it should be able to be cancelled at any time.
Actual behavior: Once stealth is active, it cannot be cancelled until after the 30s CD has finished.
Screenshots/Video: No screenshot will show this as it is dynamic. Recorded multiple videos at lowest quality and framerate but still far too large to attach.

**Comment by zipherus** [comment]
How was my prior comment spam? I was confirming bug and providing information in format requested. How are we supposed to provide videos? Do we need to record on Youtube and link it or something?

**Comment by Onlyendari** [comment]
This problem happens in all game modes at all times and on both order and destro with either stealth class. The way stealth used to work was you could cancel stealth at any time after casting and then the recast timer would start, that is not possible now.

https://user-images.githubusercontent.com/95725837/212496293-dfaf9772-58e9-4407-9b04-1c04c3f5a6b1.mp4


https://user-images.githubusercontent.com/95725837/212496303-3a8a08e2-32d9-4ccf-b601-0b37150881f9.mp4

**Comment by lilimx** [comment]
Ah! Sorry now I get what you mean...

yeah this issue was already reported here: #20302
