### ISSUE TITLE
Potent Draught of Recovery with 30sec Timer

### ISSUE THREAD

**Issue by holywochos** [WarEmu/WarBugs#20660]
The "Potent Draught of Recovery" Potion from Vendor "Venel"(Ruin Armor Quartermaster)
has a 30 sec Timer which starts after buying the Potions.
After having Potions for 30secs in your Inventory they decay.

**Steps to reproduce the problem:**
go there and buy it xD

**Testing Screenshots/Videos/Evidences (always needed):**

![Potent Draught of Recovery](https://user-images.githubusercontent.com/122727776/212539721-49f8d8f8-db88-4997-9871-9bc2aed193c4.jpg)

![Venel](https://user-images.githubusercontent.com/122727776/212539725-d1984d2b-9c71-4f8d-9462-6731fabe9316.jpg)

**Comment by lilimx** [comment]
Note: it doesn't disapear. But it's still a bug.

![image](https://user-images.githubusercontent.com/23266079/212546907-7ee6f8ff-51b3-4422-a10c-707c19d06f38.png)

**Comment by holywochos** [comment]
They decay!
![20sec](https://user-images.githubusercontent.com/122727776/212558884-6071409c-de32-4f1b-9c46-0d47eec7ee5a.jpg)
![7sec](https://user-images.githubusercontent.com/122727776/212558888-3e687e21-24cd-4358-9fbc-0d3ab4524701.jpg)
![2sec](https://user-images.githubusercontent.com/122727776/212558893-4d0ca053-f8be-4c81-a9e7-3addbb85a8a1.jpg)
![gone](https://user-images.githubusercontent.com/122727776/212558898-b479ca62-dca5-4a41-8aac-bb06670783f8.jpg)

**Comment by Rubyeclipse-war** [comment]
Thanks for this ticket. First, the good news: 

These potions don't truly expire (that's just the term we have to use in-game) - they're actually converting into the same HP pots that stack properly with your other crafted pots. So you haven't lost any pots, they've just joined any existing stacks you had in your inventory. 

Second, in order to help with any confusion like this down the road, we've updated *all* of the potions in the merchant to properly stack now the moment you purchase them. Going forward, you shouldn't see any decay timer on them. As part of this update, the potions will now appear at the bottom of the vendor list following the next patch. 

Thank you!

**Comment by lilimx** [comment]
Fixed with Patch 20/01/2023
