### ISSUE TITLE
I can't equip other weapons

### ISSUE THREAD

**Issue by samuelalpha86** [WarEmu/WarBugs#20694]
I've started playing as a Dwarf Ironbreaker and after equipping the Honored Mallet I'm unable to equip a new weapon in that hand.

**Comment by Rydiak** [comment]
Are you able to unequip Honored Mallet and then equip another weapon?

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Tested it and it works as intended.....what's the other weapon you tried to equip?

**Comment by samuelalpha86** [comment]
I can only unequip it but I can't equip any other weapon.

**Comment by samuelalpha86** [comment]
Pilfered Trollsplitter and Timeworn Waraxe.

**Comment by lilimx** [comment]
Hey,

does the issue still persis?
