### ISSUE TITLE
It Ain't Bad in Da Gudlands Quest Bug

### ISSUE THREAD

**Issue by radchu** [WarEmu/WarBugs#20704]
**Expected behavior and actual behavior:**
To finish the quest you need to kill 12 enemy players at Karagaz BO. 
Today I had few solo fights at this BO and none of my kills counted for quest.

**Steps to reproduce the problem:**
As destro kill order player at the Karagaz BO.

**Testing Screenshots/Videos/Evidences (always needed):**
none :(

**Comment by Rubyeclipse-war** [comment]
We have a temporary fix in place for this now, which will go live in the next update. Will likely update this further for a more solid fix after some testing tomorrow!

**Comment by Rubyeclipse-war** [comment]
OK, all fixed up. We've made some changes to this quest after reviewing it:

- Due to the difficulty in getting kills at this BO versus the Order equivalent (Bugman's brewery, which is a much more active area for fighting), the quest itself has been updated. Now you'll need to get 20 kills, but you can get them anywhere in the Badlands. 

This change should make the quest much more workable for Destruction and will go live in the next patch. Thanks!

**Comment by lilimx** [comment]
Fixed with patch 24/02/2023
