### ISSUE TITLE
[Hunter's Vale] Vines Door is bugged and dogs infinite spawn

### ISSUE THREAD

**Issue by steoptus** [WarEmu/WarBugs#20722]
![image](https://user-images.githubusercontent.com/51764381/218594407-ba43c8ea-d918-4b3a-879d-3d2826400523.png)

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- What happend during the way to the door?
- Did you kill all bosses?
- any wipes?

**Comment by steoptus** [comment]
- During the way, after the long tree trunk, an infinity of white dogs spawn and the door could not be destroyed since it was already "dead"
- All Boss before, I think, it was my first Hunter's Vale
- No Wipe

**Comment by steoptus** [comment]
I just did a test right now, the Vines door is bugged again, I think it's always bug. Wipe or not wipe

**Comment by Zappira** [comment]
We had the same issue, 2 days in a row.
We did the first 3 bosses as usual, killed them all, no members of the party died.

When the Tree-Bridge was created, we moved over as usual, sas Kurnos in his white-elk-form, saw him move through the vines. when we approached the vines, member of my team said he hit them, but instead of opening like they are supposed to, they remained closed and the vines dead. 
infininte dog spawns are normal here afaik.

only thing that appeared to be different was: at third boss theres 4 dryads that u have to kill to activate the boss. The 4 dryads seem to have re-appeared while the boss fight, so we could kill them again.

![grafik](https://user-images.githubusercontent.com/125561622/219352119-4ec54c72-8d82-4c5d-b46b-b1ec7f6d8d0a.png)

**Comment by Masterrar** [comment]
The error is relevant, 2-3 times in a row the error has already occurred. Restarting the dungeon didn't help.

**Comment by Rubyeclipse-war** [comment]
Fix for this is now baked in for the next patch. Should work properly, but let us know if there are any other issues. Thank you!

**Comment by lilimx** [comment]
fixed with patch 17/03/2023
