### ISSUE TITLE
KOTBs tactic bugged: Biting Blade

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#20733]
**Expected behavior and actual behavior:**
Biting Blade doesn't pop after a critical hit

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

I tested the tactic on the dev server and it works as intended

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
