### ISSUE TITLE
Stupid Sexy Chosens are back - Rare Fortune Carapace has a bugged appearance

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20788]
**Expected behavior and actual behavior:**

Expected: Stupid Chosens
Actual: Stupid Sexy Chosens

The Rare Fortune Carapace's appearance is bugged and now it looks like the Chosen is wearing nothing at all... nothing at all...

**Steps to reproduce the problem:**

Set the appearance slot of a chest piece on the Chosen to the Rare Fortune Carapace.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/60266177/224448417-0c908fde-81cb-4ff3-95fa-8ccc60402535.png)

**Comment by Rubyeclipse-war** [comment]
Sexy Chosens will be reverted back to Regular Normal Chosens in either tomorrow's patch or the patch after - fix is now on dev. Thank you for the report!

**Comment by lilimx** [comment]
fixed with patch 17/03/2023

**Comment by Endtimer** [comment]
I am ressurecting this bug since the appearence is fixed, since Chosens do not appear naked any more, but it is not as it used to be. To be more specific Chosen's Rare Fortune Carapace appeared just like Martial Carapace of the Survivalist and also had the same item icon. To my knowledge if now used for appearence it looks like Onslaught Carapace, which also has the same item icon. 
Best regards,
Endtimer

**Comment by lilimx** [comment]
Please open a new ticket. This issue has been solved.
