### ISSUE TITLE
WP Tactic

### ISSUE THREAD

**Issue by DiamSarbal** [WarEmu/WarBugs#20816]
Hello. The character is a Warrior Priest. AoE Detaunt tactic doesn't work (I tested it on 03/28/2023)

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Rydiak** [comment]
I just tested it and it works fine.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
(And I think it works, according to Rydiak)
