### ISSUE TITLE
War Bellow bug for Black Orcs

### ISSUE THREAD

**Issue by Nicetomeatcha** [WarEmu/WarBugs#20825]
Any time you put gear on or take it off, Da Greenest will turn on, it will not use ap, or go on cool down, it still works as the bellow should, just not at the players command.

cheers, thank you for all yall do,byebye

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Valterius87** [comment]
Leaving a comment here to confirm that this bug also applies to Swordmaster Phantom's Blade. It activates itself when zoning into different places, slotting certain tactics, and equipping certain gear. Possibly related to this BO bug.

**Comment by lilimx** [comment]
@Valterius87 Then it belongs to its own ticket pls.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences
