### ISSUE TITLE
A drop of influence modified to obtain

### ISSUE THREAD

**Issue by Cyprien-nguyen-van-vien** [WarEmu/WarBugs#20833]
**Expected behavior and actual behavior:**

Recovery of a weapon of influence from bbbe.

**Steps to reproduce the problem:**

Clicked on the weapon of bbbe already recovered on one of the two pnj or we recover the rewards

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by lilimx** [comment]
okay...after I found the actual ticket I don't get it.

**Comment by lilimx** [comment]
Hey,
I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
