### ISSUE TITLE
Wurrzag Ud Ura Zahuhu not showing Eastern Wyvern Hunt event earnings (reopened)

### ISSUE THREAD

**Issue by pthiel168** [WarEmu/WarBugs#20844]
I had opened case # 20843 and received the reply that to get the event earnings I needed to complete a quest taken from 'Wurzzag's ssistant'. I do not see any quest in my quest log to match this data, see quest log below. If I am mistaken and one of these quests is the one refered to - please point it out,

Many thanks

![image](https://user-images.githubusercontent.com/8930990/231774142-fd526f7e-d119-4f39-8654-aecc7e1eb99a.png)

**Comment by ekalime** [comment]
I apologize for not being clear. You already completed his quest which is what is blocking the herald. His quest existed to prevent the herald from being blocked by players who do not want to do quests. By finishing that quest you unlocked two quests which unfortunately block the herald function. 

Solution: Return to Wurrzag. Take his quests (Way of the WAAAGH, and The Once and Future Git if I recall) and complete the first step of each (you do not need to complete all of The Once and Future Git because it is long). This requires only 5 minutes of your time by travelling to the lower deeps by way of the mine junction room. If you do not know how to get to the lower deeps ask in advice chat. The two NPCs to complete these quests are straight from the portal in the lower deeps. It is not far.

**Comment by pthiel168** [comment]
Thank you very much











---- On Fri, 14 Apr 2023 01:22:02 -0400 ekalime ***@***.***> wrote ---





I apologize for not being clear. You already completed his quest which is what is blocking the herald. His quest existed to prevent the herald from being blocked by players who do not want to do quests. By finishing that quest you unlocked two quests which unfortunately block the herald function.

Solution: Return to Wurrzag. Take his quests (Way of the WAAAGH, and The Once and Future Git if I recall) and complete the first step of each (you do not need to complete all of The Once and Future Git because it is long). This requires only 5 minutes of your time by travelling to the lower deeps by way of the mine junction room. If you do not know how to get to the lower deeps ask in advice chat. The two NPCs to complete these quests are straight from the portal in the lower deeps. It is not far.
