### ISSUE TITLE
Da Greenest Auto-Enabling

### ISSUE THREAD

**Issue by ApthNZ** [WarEmu/WarBugs#20951]
**Expected behavior and actual behavior:**

- Playing Black Orc
- Using Da Toughest
- Every time I load into and out of a scenario it automatically switches to Da Greenest
- Was doing this even before the level where I had Da Greenest as an ability I could use
- Now that I'm the level where Da Greenest is actually available, when I enter or leave a scenario, both Da Greenest and Da Toughest are active on my ability bar, but only Da Greenest is actually active
- Expect Da Toughest to stay active without Da Greenest automatically enabling itself when I don't want it to

**Steps to reproduce the problem:**

- Play Black Orc
- Use Da Toughest
- Load into a scenario
- It automatically switches to Da Greenest
- Manually switch to Da Toughest
- Leave the scenario
- It automatically switches to Da Greenest

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot from 2023-06-04 14-39-01](https://github.com/WarEmu/WarBugs/assets/24648796/bbab2ccc-a7df-4b79-8747-23bc6eee4b59)

![Screenshot from 2023-06-04 14-38-57](https://github.com/WarEmu/WarBugs/assets/24648796/32dc25a7-35f1-499b-8772-d608cb1f673a)

**Comment by bosli42** [comment]
This is the temporary fix to prevent stacking the DoT + HoT tactics on the buff as extra (+2 tactics) and only happens like that because you are mid tier and constantly bolster and debolster. Once you hit 40, it will only switch to healing stance when you change something on gear, tactics or build.
Probably have to wait until new system for a "proper" fix.

**Comment by ApthNZ** [comment]
All good :)
