### ISSUE TITLE
Attacks from behind (WH)

### ISSUE THREAD

**Issue by Talissera** [WarEmu/WarBugs#2206]
I apologize, if such tread exists..
So there is a problem with WH position and openers, finishers and Torment skill. Too often when I hunt squig herder and chase him, he run directly from me and I shoot him in back, there is no snare.
When I use torment on mara or sorc, my crits are 200-300 (31 lvl, 820 str) from behind.. There is too little chance that mara has overcap of toughness. Last tick of BAL smth like 600 (in sorc).
Sometimes in 1v1 I cant use finisher although from behind or from side (same with knockback), angle is to small.

Guild WHs have the same problems.

I would like to ask to check positioning, armor ignore, BAL ticks.

If there is necessity of screenshots, I can make it.

**Comment by Evildoor** [comment]
Nothing doing, it was discussed already (see #2004 and #2013, for example) - lag + imperfect client-server interaction, and it happened even on live. If your client thinks (and shows you) that you are behind your target, server might think otherwise, and vice versa. If there will be something we can do with it, we will do so, but for now nothing can be improved in this regard.
