### ISSUE TITLE
T1 lock after Nordland

### ISSUE THREAD

**Issue by Talissera** [WarEmu/WarBugs#2354]
As you know, when one of the sides lock all BOs, side should win Nordland scenario before lock. Nordland applies to t1 location but after winning, participators don't earn exp/ren/infl.

Some people say that on live locs are connected, and participators earn all staff.

Does it real to connect them?

**Comment by Evildoor** [comment]
IIRC, on live old lock system (like in T1 in RoR) rewarded players doing scenarios related to the zone (for example, Empire vs Chaos lock rewarded those playing Nordenwatch and other EvC scenarios, since they were needed for a lock), and new lock system (like in T2-T3 in RoR) had nothing to do with scenarios at all.
