### ISSUE TITLE
nasty bug joining party/scenario command .unlock doesnt work

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2415]
Check the video...it says party is full but it actually isnt...and it doesnt let me join the party.
I tried .unlock command but that didnt work either.
I cant join scenarios too.

https://www.youtube.com/watch?v=zUb9LC7h5Vg&feature=youtu.be

P.s Is there any similar problem? After .unlock i press to join the party again and it says in chat:
You have left the party.
The part if full.
WTF

**Comment by noisestorm** [comment]
the .unlock command is just used if someone is stuck with a bugged in-fight flag. Your problems looks like you were joining a SC while you were in a warband and caused it to bug out, because warband member are not supposed to be able to queue up for SCs. So if youre queued up and join a WB then you will also cause the whole warband to completely bug-out once you join the SC...

Since i assume that the warband as well as th SC parties will be reviewed somewhen soon_TM, i can just say so far that this will be looked at and the only thing you can do is to completely shut down your warhammer and restart it.

**Comment by Evildoor** [comment]
#1138 and #1505 come to my mind, do they describe this problem? Sorry, cannot watch the video right now, so i may be wrong.

**Comment by Stefanosgr18** [comment]
@noisestorm Oh thats sad :( But good to know how to avoid it.
@Evildoor No problem the #1138 actually happened to me 5 minutes ago.#1505 is similar to #1138 but none of them are related to mine problem/bug above. 
Thanks guys.

**Comment by Evildoor** [comment]
#2603
