### ISSUE TITLE
Encroaching darkness QUEST Very low reward. 

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2468]
This quests gives very very low item reward in compare of the Xp it offers...and wrong item for Archmage(dwarf boots)**At least wrong visually for the boots**
![123](https://cloud.githubusercontent.com/assets/16375224/11993753/5b423d2e-aa3d-11e5-92ee-3f4e751f41e2.jpg)

**Comment by Evildoor** [comment]
Correlation between quest XP and quality of reward? Something new to me. Find proof that reward was different on live.
Not all armor icons correspond to the actual armor look.

**Comment by Stefanosgr18** [comment]
I cant find it but im pretty sure that there were more OP items as rewards...these are damn low.

**Comment by noisestorm** [comment]
https://github.com/WarEmu/WarBugs/issues/2471

**Comment by gittoaster** [comment]
I agree with the concern of this general issue - item too low for quest rewards.
I also don't think it maybe bug related - but something to do later by some dev member who has time to go through all quest rewards and give a 'pass over'. 

But, I think the Bug here (and in my own case points) that no quest item should be of 'common' rarity - this would easily make a broad improvement across the board.
I don't remember getting 'common' rewards from quests - these grey items are typically only found from trash mobs loot tables.

**Comment by Evildoor** [comment]
"Later" for this kind of problems will come in a very, very, veeeeeery distant future. Therefore, cluttering bugtracker with such things will make more harm than help.
