### ISSUE TITLE
Prt Screen  

### ISSUE THREAD

**Issue by zibiman** [WarEmu/WarBugs#2487]
Prt Screen for screen shots dont have cooldown and some use that to lag other player on PvP or RvR normaly it must have 10 sec cooldown

**Comment by Evildoor** [comment]
Client-side operation affects other players? Proof?

**Comment by zibiman** [comment]
yesterday i had that on PvP and on warhammer official Server they maket 10 sec pecause players usingt to lag the other player

**Comment by Evildoor** [comment]
I'll ask again - proof? You had lags in PVP, how exactly do you know what caused them?

**Comment by Thorgatin** [comment]
Iirc button mashing print screen to cause lags on other clients was a myth that was told my many players back in those days, but it was never proven.

**Comment by HtGeist** [comment]
Workied in Dark Age of Camelot mashing your print screen would make your char ghost forward in your running direction and 5 sec later you would rubberband back to where you pressed screenshot and have opportunity to run away opposite direction,or nuke em down if a spellcaster. its also a Mtyhic game.

**Comment by Evildoor** [comment]
I'm closing this highly dubious report until some serious evidence (like detailed video demonstrating the aspects of this "bug abuse" from PoV of both abuser and other players, not a statement "i heard that this is how it works") is provided to answer the following questions (and maybe some more):
1) How exactly a client-sided action such as taking a screenshot affects server and other players which have nothing to do with it?
2) Ok, let's say that somehow it does. Then how is it possible that such action affects server and other players more than the abuser himself? (otherwise the possibility of using this to one's advantage is questionable) 
P.S. Yes, i've read HtGeist's comment, it sounds plausible, but that's just a description of a situation, not an explanation of its mechanism. And it has no proof. And the situation described is not in WAR.
