### ISSUE TITLE
Merchant doesnt sell anything

### ISSUE THREAD

**Issue by RoRWp** [WarEmu/WarBugs#2522]
![foniasgr_000](https://cloud.githubusercontent.com/assets/16444872/12010254/c69744e0-aca7-11e5-899d-3b3eb041e893.jpg)

**Comment by RoRWp** [comment]
![foniasgr_000](https://cloud.githubusercontent.com/assets/16444872/12010273/4ea7b568-aca8-11e5-877e-ae9b355c757f.jpg)
![foniasgr_001](https://cloud.githubusercontent.com/assets/16444872/12010274/4eab1294-aca8-11e5-9677-f99443e44fb5.jpg)
All merchants inside Altdorf Library.

**Comment by Evildoor** [comment]
Stefanogsr, i asked you to stop posting, and you said you'll comply, but instead you create a new account on github and continue?

**Comment by RoRWp** [comment]
I want to post again...but serious bugs.May i ask why you closed this?

**Comment by noisestorm** [comment]
May I ask why you make a second account to report stuff that is not necessary to report in the first place. This is nothing _serious_ and you were already friendly told to stop reporting stuff that is currently neither relevant nor fixable without certain sources.

**Comment by Evildoor** [comment]
What you want and what you don't want does not concerns me. I politely asked you to stop using the bugtracker, but instead of complying or at least trying to reason with me (or any other member of the staff) you tried to trick us by making a second account. Therefore, i consider myself free to explain nothing to you. Stop using the bugtracker.

**Comment by RoRWp** [comment]
There is so much flame...ok i will stop...
