### ISSUE TITLE
Mourkain Temple / Tor Anroc bauble can be taken to spawn

### ISSUE THREAD

**Issue by Sabacik** [WarEmu/WarBugs#2547]
On Mourkain Temple SC you can take scoring bauble to spawn point.

If you bring it close enough by climbing up a hill you can pick it up from the spawn and spend all SC in the spawn point with other side not being able to hit you or take it back. If you die in the spawn just re-spawn and collect it again as it does not reset.

**Comment by Evildoor** [comment]
Changing the name because Tor Anroc has the same issue (see #1490 for more info). 
Implemented mechanism of the artifact giving no points near spawn does not helps. People are still taking it there, for various reasons - maybe they don't know about the mechanism, maybe they want to deny their opponents a fast victory, this does not matters. 

Fact is - if someone manages to get the artifact to the spawn, there is little that can be done, since it requires them to die, and then either the artifact must reach the time limit and respawn (and if the player wants to keep the artefact then they'll just respawn and take it again, even worse if several of them want to do it) or some other defender must take the artifact, jump down and let themselves be killed to give the artifact to the attackers (this is noble, but does not looks like a good solution for the problem).

Therefore, i think that some additional mechanism should be implemented. Dunno, maybe taking the artifact to the spawn should trigger it's respawn in the middle of the map.

**Comment by wargrimnir** [comment]
This will despawn if the player is too close to either entry area now.
