### ISSUE TITLE
WL - Axe toss crit + cause Jagged Edge

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2554]
I noticed that WL Axetoss can crit (and the value was fairly high too)
And was possible to proc a Jagged edge that way.

**Comment by gittoaster** [comment]
No procs are on axe toss.

**Comment by noisestorm** [comment]
*Wrong*. Best example was Marauder back on live having his mutation procc from axes. Which was removed here, but then brought back. even covenants or flames of rhuin procc from axes and always did.

And as you already saw, axes also can Crit, because theyre just normal abilities like all others too. Hence they can proc it. Unless you get some footage from live that shows me someone flotted with JaggedEdge and critting with an axe and NOt proccing it, this will remain most likely like it currently is.
