### ISSUE TITLE
skaventide event reward 

### ISSUE THREAD

**Issue by Kouba85** [WarEmu/WarBugs#2643]
Hallo Hunting dog have bad model but i think you are making very good job with ROR so if he will look like this it doesn´t matter. Because the game is greatest mmorpg ever.
![snorrri_016](https://cloud.githubusercontent.com/assets/15944509/12079329/f3fe6688-b234-11e5-96ed-eee7bcd28724.jpg)

**Comment by Ryanfawkez** [comment]
I'm not sure if this problem is occurring only on your end or not, because my mount looks completely normal. Looks to me your graphics card drivers are malfunctioning, which tends to happen in this game due to its poor graphics optimisation. Bugs like this occurred on live a lot, and were very sporadically seen, and usually related to a client-side issue with AMD cards.

**Comment by Ryanfawkez** [comment]
Also, the pet name is only parsed in strings. This seems related to an earlier pet bug we had; in which Landmines and Daemonic Infestations showed up in the same bugged fashion, right after the Skaventide event was released. Perhaps it's a similar issue?

**Comment by Kouba85** [comment]
So after some relogs pet looks normal with texture etc. But sometimes is not moving just sit on ground. And have bad position because is not neer charecter but stand in center of character.

**Comment by DanaBloodkiss** [comment]
This problem is on your side. NPC pathing is already reported. Closed.

**Comment by Kouba85** [comment]
i am not sure if it is on my side because when i relog sometimes is dog without texture and sometimes with.
