### ISSUE TITLE
No stabilizers from butchering?

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#2727]
It seems like I can't find any stabilizers for the apothecary skill when butchering animals. I remember it used to drop from most, if not all, kinds of butchered mobs but now I can't find any mobs that give you stabilizers. I know there are such stabilizers like Primal Zoic Gore in the game since I just got one as a loot item from a rank 1 Pub Rat (and the Primal Zoic Gore was for apothecary skill level 25) on a character that does not have butchering.
Maybe I just haven't found the right mobs to butcher yet but it is a little bit of an issue if you can't make potions without the cultivation skill on at least one character that provides you with stabilizers or buying it from the auction house.

**Comment by bwdaWAR** [comment]
According to [this](http://warhammeronline.wikia.com/wiki/Butchering_monster_reference_list) stabilizers are supposed to drop from all monsters. While I can't confirm this is true, I can confirm they do drop. I've got several of them while butchering boars, bears, wolves and hounds in Talabecland with Destruction, and one just now from a Savage Goarhide Boar in chapter 11 when I tested it.
But I will admit that the droprate seems very low for Butchering to be an option on its own rather than supplementing Cultivating, especially with high rank main ingredients. You pretty much need stabilizers from Cultivating.

**Comment by Halhammer** [comment]
Stabilizers do drop, extenders are missing tho (at least I havent seen any)

**Comment by killingjack** [comment]
The drop rate of stabilizers from butchering on this server is a small fraction of what it was on live.

My personal impression is that it dropped from approximately 50% (it was certainly high enough to the point of not being a limiting factor) to less than 5% (I have so far leveled multiple characters to butchering 100+ before giving up and the most I have gotten is 8).

It would not surprise me in the least if they simply, inadvertently dropped a 0 from the stabilizer drop rate.

**Comment by Squea** [comment]
Mob: Wild Razorswine
Zone: Norsca
Level: 5-6

The swine in Norsca drop gore stabilizers at a decent rate.  If you need a mob loot table to go off of use these.

**Comment by nalgol** [comment]
i added a fix on dev server butchering has a 50 % chance to drop additional stabilizer on all creatures
