### ISSUE TITLE
[WP] Cleanse tactic

### ISSUE THREAD

**Issue by Antismar** [WarEmu/WarBugs#2768]
When you slot cleanse tactic you can not cleanse allies outside your group.
Unslotting it lets you cleanse any ally you want.

On live with cleanse tactic you were cleansing target (any ally) + whole group.

**Comment by Landaren** [comment]
Sense we have someone looking at this anyway...

I noticed on my DoK I just have a target that has a cleanse able debuff on them in order to fire off the cleanse.

On my WP I am able to use cleanse any time on myself removing debuffs from the group regardless of conditions. I know on live WP cleanse worked that way.

So I guess what I'm saying is, efficient patching is not working like cleansing power.

**Comment by ozarmidrashim** [comment]
https://github.com/WarEmu/WarBugs/issues/2026

**Comment by Tiggonos** [comment]
The tooltip clearly states "Purify will ALSO cleanse your entire group". So it should cleanse on hex from your target and one hex from each of your group. it should not cleanse more then 1 hex though. The adition of that supports the behaviour of cleaning 1 hex from your target AND 1 from each member in your group.

**Comment by Luth-RoR** [comment]
Fixed https://github.com/WarEmu/WarBugs/issues/2026
