### ISSUE TITLE
[SH] Run Away ability without squig

### ISSUE THREAD

**Issue by grotsaidstop** [WarEmu/WarBugs#2775]
The Run Away Ability need a pet to be cast. But when I use Farty Squig or Tastes Like Chicken (so i loose my squig) I can use the Run Away ability without squig during the next 9 sec. But nowhere it's written that i can do that, a good advantage for my favorit creature, but not in the rules.

**Comment by Zealote** [comment]
You can currently use Run Away! without a squig present, and not just after using Farty Squig/Tastes Like Chicken. The skill icon is greyed out and it says 'Requires an Active Pet' but ability still activates.

**Comment by Zealote** [comment]
It's caused by the squig disappearing at zone boundaries. I assume it's something like the client knowing that the squig's gone and so greying out ability and giving 'Requires pet' message, but it's not really dead so you're still able to use Run Away! Sounds like Schrödinger's squig to me.

![runaway](https://cloud.githubusercontent.com/assets/10598420/26325579/5e18f9a6-3f2f-11e7-9307-1e2c3d2646b1.png)
