### ISSUE TITLE
Brigand Matchlock stats 

### ISSUE THREAD

**Issue by Senss** [WarEmu/WarBugs#2797]
Hello can you fix the brigand matchlock stats please ?
it should not be +28 ballistic skill for witch hunter ... :)

thanks

**Comment by Senss** [comment]
"Brigand's Matchlock"

**Comment by Meralors** [comment]
http://www.warbits.com/gold-items-6518-Brigands-Matchlock.html

It used to be that way.

**Comment by magicthighs** [comment]
Even if just before the official servers closed the stats on this gun were +28 ballistic and +21 wounds, making it so now would make it a useless weapon, since WHs don't need ballistic skill anymore for their ranged finishers, and haven't since before patch 1.2.1.

Found patch notes here: http://www.ign.com/boards/threads/warhammer-online-patch-notes-big-additions.179285930/
Search for "Ballistics Skill has been removed from all Witch Hunter items".

**Comment by ozarmidrashim** [comment]
Reopening this because Witch Hunter items should not have Ballistic Skill anymore, no matter what old live databases report.

**Comment by Senss** [comment]
Fury with brigand doesnt have this problem -_-

**Comment by Styrkarr** [comment]
Fixed in the next patch.

Brigand's Matchlock stats are now :
+28 Strength
+21 Wounds
+3 AP regen
