### ISSUE TITLE
Party icons distant even if players are close by

### ISSUE THREAD

**Issue by Fikatind** [WarEmu/WarBugs#32]
After making a party group members are distant, even if they stay close to ech other

**Comment by Tiredofpickingnames** [comment]
Please reopen this ticket.  I am seeing many cases where party and warband members are listed as "Distant" even when they are standing right next to me.  That makes it very hard to heal them when clicking on their names in the warband windows due to incorrectly getting the message that they are too far away to target.  Trying to click on a moving player icon is much harder and should not be necessary for nearby players in my warband.

This problem seems to occur at random with no way to reproduce it.  I have also seen a couple of cases where the problem suddenly corrects itself and player info in the warband windows starts displaying correctly again.  Client and server are out of sync?

This ticket was originally listed as "Minor" but it is a major problem for healers.

**Comment by Tiredofpickingnames** [comment]
Here is a screenshot showing a party member right next to me who shows as "Distant".

![grimseer_000](https://user-images.githubusercontent.com/44715297/48414883-da737b00-e719-11e8-842d-5468d512ddde.jpg)
