### ISSUE TITLE
Quest Item and Rewards not showing up.

### ISSUE THREAD

**Issue by Reorgael** [WarEmu/WarBugs#364]
So at the beginning of Norsca for Destruction player you recieve a quest called "The Heart of Battle". It asks you to use an item called "Ancestral Bane". Upon getting the quest said Item doesn't show up in you inventory, so you are unable to complete the quest

In regards to quest rewards there is a quest in the area above that requires you to kill a Bright Wizard Acolyte. I did this and went back to the quest giver, handed it in but it did not show up in my inventory.

**Comment by milosxe** [comment]
The Heart of Battle quest works fine since the Quest Item inventory tab is operational. You can pick up the quest item, it shows up in your inventory and you can finish the quest.

Second quest still has some issues, cause quest rewards are a bit broken.
It's more detailed in this report https://github.com/WarEmu/WarBugs/issues/1388 so I'm closing this one.
