### ISSUE TITLE
[ToK] Death Shroud Cape

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#3809]
wiki says you need 5 Broken Wight Blade in order to buy the cape. I was able to acquire the blades but can't seem to buy the cape.

**Comment by Torquemadra** [comment]
I believe you had to click the 5 blades in your backpack which made them vanish and gave you the unlock needed to buy the cape, same as some of the unlocks needed for the great oathstones.

**Comment by TaeBal** [comment]
i have same problem i got 5 Broken Wight Blade but cant unlock "Broken Men, Broken Blades"
and cant buy "Death Shroud Cape" click the blade is not work

**Comment by Hauclir** [comment]
I assume the unlock achievement works now for this cape since I just saw someone in game with the cape. I haven't tried the unlock achievement to confirm that it is working.
![hauclir_008](https://cloud.githubusercontent.com/assets/7598530/15164763/c2c3480e-16c5-11e6-9973-edfcdb36fd53.jpg)
![hauclir_009](https://cloud.githubusercontent.com/assets/7598530/15164764/c4e465fa-16c5-11e6-9331-ba7117e02f49.jpg)

**Comment by Yellowpillow** [comment]
this unlock was fixed

**Comment by Luth-RoR** [comment]
Thanks.
