### ISSUE TITLE
Rain of Fire stacking 

### ISSUE THREAD

**Issue by Dreamhousee** [WarEmu/WarBugs#3816]
If multiple Rain of Fire's are put down on the same spot one of the Rain Of Fire's don't register any damage, this is not a visual bug.

**Comment by Evildoor** [comment]
"In 1.2.1 we will be adjusting GTAoE spells so that the damage will not stack with somebody being effected by the same spell. For example using the same 3 Bright Wizards the damage would be allocated until every target was hit one time by Rain of Fire."
Seems like a correct behavior if i understand your report correctly.

**Comment by Tiggonos** [comment]
jepp gtaoe are not supposed to stack.

**Comment by ozarmidrashim** [comment]
I find this report highly suspicious.
