### ISSUE TITLE
Runepriest: Oath Rune not refreshable

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#3880]
Cannot refresh a previously casted Oath Rune on party members, even though I was the one buffing them. Only refreshing on oneself.

**Comment by vove-RoR** [comment]
Did you check #2729 ?

**Comment by Pumatouch** [comment]
Didn't find it on search but yea did now. Not sure if joining warband and SC is the cause BUT one shouldn't queue SC and join a warband at the same time, due to other issues with bugging the warband. No clue if they are related.

**Comment by vove-RoR** [comment]
In my opinion they are related because joining sc while in a wb as you noticed bugs the party and it seems that it treats you like a member of a different party even though you are in the warband. You can rebuff yourself (as you are the member of your party) but you cannot buff other people as after leaving a scenario it seems you are assigned to the a different group and it doesn't reassign you to your party after leaving. Was that how it happened in your case? You joined a scenario while being in a warband?

It's not only with warband, in normal 6m party as well. I think what happens is we get stuck with the sc group even after finishing the match, that's why you can cast the buff only on yourself- you are the only member of that party in range. Would have to check in a party of 3 ppl from which 2 join sc and one waits. I wonder if it would bug for both party members or only for the one that didn't join the match.

**Comment by Pumatouch** [comment]
Well, knowing about the bugged warband I wouldn't join SC first now would I :) I can't speak for the others, however there was one guy that did leave and go on an alt to join SC, and then return later for lair boss kill. I read about the possibility of "remnant" SC queues when logging to other characters, think this might be it?

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
