### ISSUE TITLE
SM Potent Enchantment not cleansable

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#3927]
I tried it a couple times and I'm fairly sure that the SM Potent Enchantment Hex Debuff is not cleansable.
Don't really see it that often so it's difficult to confirm for me.

**Comment by taccr** [comment]
Can confirm now, definitely not cleansable. Not even passively via group cleanse. Cleanse lightens up but it won't fire.

**Comment by Torquemadra** [comment]
Its a tactic "buff" that puts a damaging effect on your attacks, same as ensorcelled agony, guilty soul and a myriad of other tactics. Its an extension not a hex, ailment or curse.

**Comment by Evildoor** [comment]
Tooltip on an enemy says "Hex", so i think it should be cleansable. Ensorcelled Agony, for example, shows "Damaging".

**Comment by Torquemadra** [comment]
Potent enchantments, like ensorcelled agony and guilty soul tooltips have it listed as a "buff" like all tactics, as in they "buff" the ability they are working off extending it to something more. I would suggest that the damage type is wrongly attached otherwise this would be a significant downside to extension tactics over self buff ones like dirty tricks.

**Comment by taccr** [comment]
This logic doesn't apply to tactics in general, otherwise should CS also be damaging and not a curse.

Either way the tactic is currently bugged in conjunction with cleanse. Make it cleansable or change the damage type so it doesn't lighten up.

**Comment by Torquemadra** [comment]
Point. Though its a tactic extending a mechanic, it is, like CS, potentially extending every attack ability and therefore possibly outside the normal balance parameters of the other tactics I mentioned which are all single target.
