### ISSUE TITLE
There are two bugs that I know of

### ISSUE THREAD

**Issue by dadlyj** [WarEmu/WarBugs#4027]
1,Guild connections list bug

All 40 people who have joined a Guild accurately when
After that, the user is
The list seems to only your own Guild connections
May decrease by 39 people
41 people gets to work

2.magus - path of daemonology 

rank 4 moral - firewyrm of tzeentch 
not work.

**Comment by noisestorm** [comment]
1 report per problem please. especially when they are completely unrelated to each other. Edit this post here with whatever Guild issue you have and explain it a bit better if possible. 

@Firewyrm: that was left out for the moment since it is somewhat hard to fix from what i've heard. So no need to make a new topic for that - problem is known basically

**Comment by Evildoor** [comment]
No explanation, closing.
