### ISSUE TITLE
Group buffs not working in PVE/RVR parties

### ISSUE THREAD

**Issue by Karast** [WarEmu/WarBugs#4044]
The runepriest runes, group only buffs no longer function in groups since the patch hotfix.

**Comment by ozarmidrashim** [comment]
Tested and is working fine...

**Comment by Karast** [comment]
it doesn't work when group in RvR or PvE, it does work in scenario and
warband.

**Comment by ozarmidrashim** [comment]
Okay I think we have a misunderstanding here.

Because of some stupid bug or lack of understanding we have in the group code, the group buff abilities are greyed out when in a regular group in the open world, but they still work.

Accordingly, I'm removing my assignment from this issue and I will require someone to post video proof that attempting to cast a RP or Zealot group buff on a group member in the open world does not work.

**Comment by Luth-RoR** [comment]
No evidence/response -> closed.
