### ISSUE TITLE
Problem T2 keep guard on Top of keep

### ISSUE THREAD

**Issue by Tyrean** [WarEmu/WarBugs#4084]
There is a problem when we are attacking keep Mandred and now Barak Var when the warband going on lord room some guard on top third floor move down to lord room and kill some of us . 

We are on Barak Var now and guard on top killing me when im inside lord room again.

**Comment by Sakhou** [comment]
hello ! 

I up this topic. When we are on the right corner of Mandred'skeep, we take aggro of npc lvl 40 on top.

Screen
<a href='http://postimg.org/image/947w1t7n9/' target='_blank'><img src='http://s2.postimg.org/947w1t7n9/Morzog_0011.jpg' border='0' alt="Morzog 0011" /></a>.

**Comment by Sakhou** [comment]
I update this topic because orders use this bug for farm the influence and it is not fair!

**Comment by Evildoor** [comment]
Read the rules of the bugtracker.

**Comment by Torquemadra** [comment]
fixed next

**Comment by Blaqwar** [comment]
May I ask what happened to this fix, I wasn't able to find anything about an attempted fix in the patch notes. The merchants in the mentioned two keeps still aggro through the floor (as soon as you step on the stairs pretty much) and one shot anyone attempting to clear the upper floors after the lord is pulled.

I was under the impression that (similar to T4) the vendors on the top floor aren't supposed to provide a safe haven to the defenders. At least not more than normal NPCs of the tier-appropriate level would. There's a similar problem in T3.

**Comment by Luth-RoR** [comment]
>through the floor (as soon as you step on the stairs pretty much) and one shot anyone attempting to clear the upper floors after the lord is pulled.

The original report was about the issue that guards always aggroed as soon as people enter the lord room to kill the keep lord, not about killing people on the upper floor; Afaik any complete/real fix for NPCs aggro-ing through walls can only be applied, when the new instance tool is done.

**Comment by Blaqwar** [comment]
I see some confusion about this issue since there seem to be 2 of them. One is guards aggroing from upper floors down to the bottom floor and the second is merchants from the top-most floor aggroing in the lord room (2nd floor). You're talking about the former, I'm talking about the latter. I'm honestly confused about whether this exact bug report (#4084) is about the former or the latter, I may have made a mistake in posting in this issue rather than in one of the ones below.

But I am certain these issues ( #4354, #4328, #4337) are all the same bug. Again to reiterate, lvl 40/41 vendors from the third floor (top of the keep) teleporting through the ceiling and killing anyone in the lord room (second floor) with one attack.

Furthermore, Torquemadra's bugfix from 17.02.2016 (https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=11644) referenced this bug entry (#4354), which clearly is the one I'm trying to get attention to right now. Which also makes me think that either the bug fix didn't work or that it somehow didn't make it onto live.

I understand that the core of all these guard aggro issues cannot be adressed right now. But it doesn't make sense to diminish the already not healthy T2 and T3 by ignoring the issue and having unacessible areas in the keep that provide a safe haven for the defenders and discourage players from assaulting keeps. (For example not being able to fight the keep lord in his room means that the attackers are open to siege weaponry and RDPS attacks from unreachable areas of the 3rd floor).

I suggest changing the levels of the vendors on top of the keep if that is possible. That way they can be dealt with the same way players deal with buggy guards teleporting through the keep floors by either killing them, once you can access that floor, or ignoring them and healing through the damage.

**Comment by Blaqwar** [comment]
![blaq_004](https://cloud.githubusercontent.com/assets/5108812/18812675/041da452-82dc-11e6-9e00-0e87c50e528d.jpg)
