### ISSUE TITLE
Birds Of A Feather Title Unlock

### ISSUE THREAD

**Issue by MalakarSW** [WarEmu/WarBugs#4106]
Birds Of A Feather ( http://warhammeronline.wikia.com/wiki/Birds_of_a_Feather ) is an unlock for Eagles in the ToK Bestiary that rewards you with "The Vigilant" title when a Giant Eagle Feather drops from the eagles in Ellyrion. However the item doesn't seem to work when you right click it. 
![malathorn_007](https://cloud.githubusercontent.com/assets/16929056/12662278/4a725d00-c5ed-11e5-91f0-611506d62291.jpg)

**Comment by CaptainoftheHarem** [comment]
I killed Treeman Dregenis and got the title and unlock for The Vale-Walker (I did it as a Zealot so I don't know if that had an impact)

**Comment by MalakarSW** [comment]
Confirmed. Killing him unlocks the title. Guess the wiki was wrong. Still the Eagle Feather thing is a problem.

**Comment by Ryanfawkez** [comment]
Cannot fix ToK unlocks related to item interaction yet.

**Comment by Lheana** [comment]
I killed more than 170 Ellyrian Eagles without looting "Great Eagle Feather".

**Comment by Lheana** [comment]
Ellyrian Eagles still don't drop 'Great Eagle Feather', and should be fixable now.

**Comment by Lheana** [comment]
Fixed: Killing 'Ellyrian Eagle' will now trigger the unlock. They will drop 'Great Eagle Feather', a pocket item, that triggers the associated title.

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Lheana [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UBHOYAXJIDCQBZICLAAPDMKAGOOVIFLCRBCIKG5BB6IMV5O5CV7GBNVABNGEZQMDUC3NIIMIOKIQVFEO5FFM3GXBEGADN3AWUBY4QM3IWFGSBABKSEFIAHMAHIACMAAMAADAALAFGYKQC5IBGUANYZEVG2OBLFMCQQAIAAEA======@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Mon, 12 Jun 2017 10:13:23 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.26]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp j78si539941ywg.370 - gsmtp:
    retry timeout exceeded
