### ISSUE TITLE
Unusual Cultivation Skill Bug

### ISSUE THREAD

**Issue by andreiiftemi** [WarEmu/WarBugs#4118]
Yesterday around 6 p.m GTM+2 I opened my launcher, entered my account, started the game and logged in with my sorceress Sisu and tryed to cultivate lvl 75 seeds in my addon window(i have lvl 93). It was bugged so I supposed it is the normal bug which can be fixed with a simple relog, but it didn't worked. I opened my cultivation window, nothing different, I disabled my addon, still bugged.  Then restarted my game, still not working, I couldn't plant any seed. I made a new profile, still the same.
Today I reinstalled my game and it's still not working. I can't even plant lvl 1 seeds, it's like the mother of cultivation bugs.
How can I fix this bug without ".respec gathering" (supposing a restart would fix it).

**Comment by Kouba85** [comment]
The same with tallisman making with my char Kouba Black Orc

**Comment by nalgol** [comment]
dont use addons with crafting they where build for a 100% working crafting system but since we got no packet logs for crafting the current system is as mutch as i could get to work theres missing stuff like crafting time that totaly fucksup the addons and since we got no logs no clue how mythic send those

after server restart everything should work again though since none of the crafting progress is saved

**Comment by Evildoor** [comment]
This problem still persists?

**Comment by Kouba85** [comment]
For me everything ok

**Comment by imneo58** [comment]
I experienced something similar.
I had 4 seeds cultivating and opened the Apothecary window to make a potion. Inserted Bloated Spumepetal(75),2 Pristine Arboreal Resins (200),and 1 Angry Marsh Root (175)
and got the following message in a shout/tell after the following combine.

"An Error in the crafting system occured if the problem is repeatable please report it shouts:"
![ulksmash_003](https://cloud.githubusercontent.com/assets/14805388/15033043/87c8c348-122c-11e6-9b74-c253c06f80d5.jpg)
