### ISSUE TITLE
order warriorpriest skill "Supplication" bug

### ISSUE THREAD

**Issue by johnbolt** [WarEmu/WarBugs#4132]
warriorpriest no friendly target use skill supplication, and cleaning debuff.

but destro khain not use Patch Wonds no friendly target.

**Comment by ozarmidrashim** [comment]
...

1) You're talking about Purify and Patch Wounds with the Cleansing Power and Efficient Patching tactics slotted, not Supplication
2) This is intentional and how it worked on the live server
3) The forum rules forbid posting on the bugtracker if your command of English is as basic as this and if you are not capable of correctly identifying the problem.
