### ISSUE TITLE
Cant use the "Book of Binding" in chicken form

### ISSUE THREAD

**Issue by Pogolove** [WarEmu/WarBugs#4208]

**Comment by ozarmidrashim** [comment]
How is this a bug??

**Comment by Evildoor** [comment]
Actually, it was possible to do so on live, IIRC. And on live it was quite helpful sometimes, because i remember getting in some weird place in Greenskin T2, which was a pretty large PVE location but counted as RVR for some reason. I was lucky that the book worked in chicken form, otherwise i would have been forced to run a pretty long distance (without mount) to get either to flightmaster or some place where RVR status was not applied.
However, i'm not sure if we should bother fixing this here, because we have /stuck, and because situations like i've described should be fixed by removing incorrect RVR areas, not by changing this.
