### ISSUE TITLE
Machine Gun Turret Upgrade

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4236]
This Upgrade(Ability) can be used in Scenarios for free even in Rank 1...but you have to be 17  to unlock it.
![toufekiaaaa_054](https://cloud.githubusercontent.com/assets/16864486/12831051/02e99fe4-cb9b-11e5-8485-f7252f1a8180.jpg)
![toufekiaaaa_055](https://cloud.githubusercontent.com/assets/16864486/12831050/02e8a0d0-cb9b-11e5-8311-1ba336e745ef.jpg)

**Comment by Torquemadra** [comment]
To clarify, those abilities are not trainable, they are inherited by the summon appropriate to its level so while bolstered they are gaining abilities higher than the players level but appropriate for the bolstered area.

Note engineer turrets will never have machine gun working in t1 due to this, only t2.
