### ISSUE TITLE
Rift exploit by Engineers??

### ISSUE THREAD

**Issue by dviella** [WarEmu/WarBugs#4369]
Hi.
Is rifting players by using the magnet link into a tree an exploit? Some engies are repetably exploiting the fact that after the rift INTO a tree (Battle for Praag scenario) players cant move and dieing instantly.

![lobotomy_004](https://cloud.githubusercontent.com/assets/17257697/13058120/4a56cbfc-d421-11e5-9cc3-57a87208f381.jpg)
![lobotomy_005](https://cloud.githubusercontent.com/assets/17257697/13058125/4f3ba688-d421-11e5-9e2d-c7db3b52ae18.jpg)

**Comment by ozarmidrashim** [comment]
It's abuse. GMs are clear to ban for this.

**Comment by ropuch** [comment]
Being stuck in textures in "rift path" looks like a bug :)

**Comment by Vancerus** [comment]
you know that you die instantly because of the 5 engie premade and you can not move because of coordinated knock down and stagger...not because of a bug or exploit. 
the trees are only used as shield against range LOS, otherwise they would die easily. 
that is the next level of the "these engies are multiboxing" chant  in every bg, which they are beeing called free by the GMs who checked that. 

Cheers, 
Vance

**Comment by ropuch** [comment]
I'm used to rift + stagger (both realms), this is something different. And you're actualyy stuck in the tree texture so, yea, exploit as hell. Nice try, though.

**Comment by Vancerus** [comment]
So, because you are not the OP, i am guessing you have experienced the same issue in some way. I am just curious how you know that you are stuck in the tree if "you are dying instantly" as OP stated.
As for my own experience, i have not one time NOT been able to move out of objects, after beeing rifted into them. A video would have been better on how they are actually stuck. Maybe i myself can provide one in the future about this to solve the mystery.

So long,
Cheers,
Vance

**Comment by Luth-RoR** [comment]
Environment collision/LoS is active; if this is still possible, it's high likely a client restriction
