### ISSUE TITLE
Character bugged, "Selunae" Bright Wizzard

### ISSUE THREAD

**Issue by Krysstar** [WarEmu/WarBugs#4424]
Hello, i require an intervention on my Warhammer RoR charcter : Selunae.
I can log it, move with but the character always is considered as dead. The skill book is empty and i can not have any interaction with others players or play.

My apologizes for my bad english.

Thanks for future support.

**Comment by Jojo1337** [comment]
You had the trophy 'Red skull ribbon' equipped?
There are reports from other players with the same issues since the latest patch who had this trophy equipped, which is now gone from the slot and also cannot be bought from the merchant any more.
It is the trophy on the bottom right here: http://i.imgur.com/HSAndBb.jpg

**Comment by TaeBal** [comment]
Yeah same here every "Red skull ribbon" equipped players got same problem since latest patch

**Comment by Krysstar** [comment]
The red Skull is not Equipped but in my bank at altdorf.

**Comment by Jojo1337** [comment]
my character with this problem got fixed.
