### ISSUE TITLE
[Crafting] Blue Toughness talis from purple mats on critical success

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#4501]
mats was 175 lvl purple, total power was 39-44(41 prolly) and on critical success I get Potent talisman of the Protector (blue) +20 for  36lvl

**Comment by Paninii** [comment]
i can confirm this bug since Tier 4 came out.  I am hoping not to get criticals or special moments on my 175 purple fragments as it will give me a worse talisman then a non-crit (non crit would give 22 stat)

something i just crafted - a blue 175 Ball fragment.  It critted and gave me a level 36 +16 ball tali.  Where a non crit would have given me a +18 Ball tali.

**Comment by Abolition** [comment]
This also happens on green levels fragments of lv 200. It "crit" and made a WHITE lv 36 talisman.
