### ISSUE TITLE
[Witch Elf] Death Reaper

### ISSUE THREAD

**Issue by Luranni** [WarEmu/WarBugs#4505]
On live this morale was 32 I believe, and also states it as 32 in RoR.  However I'm at 35 now and it still cannot be trained.

**Comment by Lileldys** [comment]
It was switched for the morale 2"Web of Shadows" with the lvl32 update, where every class got morale2. The morale 2 would've been at r36 on live.

**Comment by Chummi** [comment]
Pretty sure that this was a bug on live.
Class specific morale 2 were always granted at lvl 32 on any other class.
The exact equal counterparts for Web of Shadows (Flying Axe, Reversal of Fortune and Great Fang which can be found on White Lion, Witch Hunter and Marauder) are available at rank 32. 

Class specific Morale 3 is always granted at rank 36.

I don't see how this morale is by any means stronger than a **50% crit **buff for your group. DR's damage is usually used for morale dumping and its damage is equal to SN. 

Besides granting the WE the possibility to have a defensive morale 1 (Confusing Movements) and a damage morale 2 for its group play it has no impact. 50% crit on the other hand is insanely strong in both ways offensive and defensive.

**Comment by Chummi** [comment]
Pretty sure that this was a bug on live.
Class specific morale 3 were always granted at lvl 36 on any other class.
The equal - defensive - counterpart for DR (Witchfinders Protection which can be found on the WH) is available at rank 32.

Class specific Morale 2 is always granted at rank 32.

There is nothing which would justify giving WE access to a **50% crit buff** for its group before the counterpart is available. 50% crit is huge. Especially since the WE has already the highest ST pressure in the game. Her morales should be available at the same level as the one of other classes. No need for a unnecessary benefit. 

I see that one as a bug fix not as a current bug.

**Comment by Luranni** [comment]
I don't mind either way as long as it's fair for all, with most m3's also on 36 it would make sense to keep them all on a level.  In which case, it's a tooltip fix required and nothing important.

**Comment by ozarmidrashim** [comment]
Bug fix.

Career builder will send the updated rank requirements in next patch.
