### ISSUE TITLE
"Marked" - none usable item

### ISSUE THREAD

**Issue by DizzyUA** [WarEmu/WarBugs#46]
quest item "Crawling Doll"  not usable, so quest cannot be ended.
![dizzy_002](https://cloud.githubusercontent.com/assets/7514926/2908193/e4f6885c-d624-11e3-844c-5dec993f8d0b.jpg)

**Comment by Evildoor** [comment]
You can return to Surtsen and finish the quest now.

**Comment by RoR-Zomega** [comment]
Not sure if this should be closed or not. The fix means that rather than using the doll you instead talk to Sursten. However, the result of talking to Sursten is that you then get a new quest... to talk to Sursten (which originally would've been generated by using the doll). This part of the quest chain has become nonsensical due to the work-around.

**Comment by Evildoor** [comment]
IIRC, some quest mechanics are not implemented yet, and "use item" is one of them. So yes, for now it is nonsensical.
