### ISSUE TITLE
Zone 0

### ISSUE THREAD

**Issue by Thorrik** [WarEmu/WarBugs#4677]
Hi, I'm in the Zone 0, and I try to unlock my character, and restart the game but I'm locked in this area. 
My character name is Thorryk.

**Comment by Thorrik** [comment]
And my account name is corentin.bolou27@gmail.com

**Comment by Evildoor** [comment]
Read the rules of the bugtracker.

**Comment by Thorrik** [comment]
I did it but I don't see the problem with my request

**Comment by Evildoor** [comment]
Point 3. Do not post well-known issues that are within the realm of game / technical support.

Do not post problems related ONLY to you if the general existence of the problem is already known, such as missing items or inability to get into the game. These issues are solved on the forum (for example, trouble with the launcher), in game by GMs (**if your character is stuck somewhere and conventional methods like /stuck twice do not help**) or not solved at all (missing items – we are trying to fix the causes of items disappearing, but we will not reimburse items to individual players because we cannot check the veracity of the report).

**Comment by Thorrik** [comment]
Ok I know what you mean sorry for the desagrement.
