### ISSUE TITLE
Enfeebling strike bug

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#4742]
Hello today i experience bug with this skill. Result was killed in 1 second.
![bug photo](https://cloud.githubusercontent.com/assets/12202629/13550514/c05d7c0e-e373-11e5-9771-73410bf47205.jpg)

**Comment by diablight** [comment]
#4318 bugtracker. I already have posted this bug. It was me who hit you and i cannot tell how this happened

**Comment by Evildoor** [comment]
Hmmm. Diablight, so when you posted #4318, you had a similar bug with numerous instances of the same small damage in one second? Because your words in it:

> enfeebling strike has hit the enemy suddenly with all the damage within the same second

led me to a different conclusion.
Anyway, we'll use this report for this issue since it has a screen which clearly indicates that this problem is different from #2645.

**Comment by diablight** [comment]
Yea this was what i ment. My english is not so good. I use google translator (sorry :( )
