### ISSUE TITLE
Devastator Boots / Gloves Not BOE

### ISSUE THREAD

**Issue by davidchicheung** [WarEmu/WarBugs#4763]
I am a SW and our group got a pair of white lion boots to drop. They say BOP and are not tradable as shown in the screenshot attached.
![meepie_002](https://cloud.githubusercontent.com/assets/699806/13555618/2992e6f4-e37a-11e5-8cd3-7ce7c8707ae8.jpg)

**Comment by Ryanfawkez** [comment]
Tried putting them on the Auction House? Should be possible.

**Comment by davidchicheung** [comment]
That is correct, can be sold through AH. Will close ticket.

**Comment by Soulwhisper** [comment]
So we can trade/mail but only sell them on AH.

**Comment by Soulwhisper** [comment]
**The gloves and boots from these sets have been made Bind on Equip, and are now salvageable. Their rarities have been adjusted accordingly.**
We should be able to trade/mail them too if they are Bind on Equip.Currently we can only sell them on AH.

**Comment by Tiggonos** [comment]
im confused so its intended it isnt tradeable via mail/direct ??

**Comment by Ryanfawkez** [comment]
There is a bug with Bind on Equip items. They tend to falsely flag themselves to Bound to Player, while this should only occur when you equip them. Due to a wrong byte in the BoE handling code, it makes them untradable through direct trade, yet they can still be put on the Auction House, and be mailed through a work-around by quickly right-clicking a tradable item as you drag your BoE item to it.

**Comment by Tiggonos** [comment]
thx!
