### ISSUE TITLE
[Crafting] Seeds mapped to wrong stats (or might just be addon)

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#4771]
I'm sure I'm not the only one to have noticed, but I couldn't find an outstanding issue log.

Note, this could possibly just be hardcoded mapping in an addon that is no longer up to date rather than a DB issue. Still, worth making sure it's not the DB.

I think it's EZCraftX that shows the additional info in the mouse over target display, but three seeds are coming up differently to how they should/used to.

- Gumpleaf (Willpower) says "Grows Intelligence"
- Beardweed (Strength) says "Grows Willpower"
- Smedleycap (Intelligence) says nothing

The same (mis)information appears in the Motion ingredients picker, but this could be pulling info from the other addon.

Let me know if you need screenshots.

**Comment by taccr** [comment]
Couple things wrong here:

a.) Obviously addon related problem. Does not belong here. If you don't see any errors WITHOUT addons then it's highly unlike that your problem is related to the server.

b.) Wrong addon:
ezcraftx>grep -ir "grow" *
<No result>

c.) You are most likely using an old version of craftinfotooltip. Check the forums for an updated version. The extended tooltips work fine for me.

**Comment by Damiel126** [comment]
Great. Thanks. Will check it out. If yours works fine then it's obviously not the DB.

Only logged because I had no way of knowing whether it was the addon spewing out incorrect info, or whether it was merely exposing that info from the DB.
