### ISSUE TITLE
Tracer rounds on engi

### ISSUE THREAD

**Issue by pigbearman101** [WarEmu/WarBugs#4836]
with the tracer rounds trait, it gives 15% crit chance when within 20 feet, but as long as your turret is alive it does not matter how far away you are from it, you get the extra crit chance as long the turret it alive.

**Comment by Evildoor** [comment]
In character sheet? Or in .getstats too?

**Comment by pigbearman101** [comment]
in character sheet, did not know about get stats until now, but in getstats it does not show any change, meaning the tactic does not provide any bonus to range crit chance. It showed 0% chance with no turret, 0% with turret built and 0% with turret 60 some feet away

**Comment by Evildoor** [comment]
No ranged crit, ok. And no general crit either? (They are different, see #1994, for example)

**Comment by pigbearman101** [comment]
ok so the tactic gives general crit, which i cant seem to find in the .getstats dialog

**Comment by Evildoor** [comment]
I don't know for sure if it should be general or ranged crit. But you are saying that .getstats does not differs at all, right?

**Comment by Evildoor** [comment]
Ow. #2050.

**Comment by pigbearman101** [comment]
but does that mean that the crit chance it there?

**Comment by Evildoor** [comment]
I cannot tell, since the most reliable source of this information is .getstats, and in this case it is disabled, while @ozarmidrashim stated in #2050 that he implemented this tactic (so it should be working).

You can perform a test with some kind of tracking addon (Enemy, for example) to measure crit on mobs, and post results here.
