### ISSUE TITLE
silent crash

### ISSUE THREAD

**Issue by Natherul** [WarEmu/WarBugs#4898]
as discussed http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=12069

Game will sometimes crash silently (no errors or anything).

If there is any way to log this to provide more information please do tell me so I can help you track this nasty one down

**Comment by Natherul** [comment]
I have at this point given up on keep assaults or defends with many players as then I WILL crash at least within 5 min it seems, especially in a WB.

**Comment by nalgol** [comment]
could need a packet log of the crash
you can dl the packetlogger here https://mega.nz/#!VYhSwaIR extract it to the war folder and start PacketLogger.exe while in game and wait for a crash ( this could create a huge file if it takes a while)
i would only need like the 30 last packets so go into the log folder open the packet last packet log file and copy out the last 30 packets

**Comment by Natherul** [comment]
I need a decryption key to download that file, PM me it and I will download it and get some logs for you :P

**Comment by nalgol** [comment]
wops 
https://mega.nz/#!VYhSwaIR!4ryqd0RkZFgfQ_DP_w9YcJMXRGxhBlTrgL9jRuPf5IE
here it is with key

**Comment by Natherul** [comment]
[sniff_h19m49.txt](https://github.com/WarEmu/WarBugs/files/191035/sniff_h19m49.txt)

Here is todays crash log, I will upload whenever I get crashes :P

**Comment by nalgol** [comment]
hmm cant find anything unusual keep them comming maybe even make them a bit longer with almost no filters in theres alot of spam going on between the server and the client but any of those packets could cause the crash

**Comment by Natherul** [comment]
[sniff_h19m24.txt](https://github.com/WarEmu/WarBugs/files/192197/sniff_h19m24.txt)
Crash now as server just came online, not cropping anything with the file this time, its all there :D

**Comment by Natherul** [comment]
[sniff_h19m42.txt](https://github.com/WarEmu/WarBugs/files/192221/sniff_h19m42.txt)
Another one, perhaps the last for today, this one was a bit different however as it was giving me a windows error sound, no message however.... Same thing now, uploading  entire file

**Comment by Natherul** [comment]
as a reference my system is: 
intel i7 6700K @ 4.0Ghz
16GB RAM DDR4
2x NVIDIA 970 GTX
Game installed on a WD black edition 1TB HDD

All this on a 200/100 mb/s fiber line and running freedome VPN

Just thought Id post that as well if by any chance it affects just people with similar hardware

**Comment by ozarmidrashim** [comment]
Thanks, gonna look through these shortly!

**Comment by Natherul** [comment]
anytime mate, always at your service if you need it :D

**Comment by Natherul** [comment]
[sniff_h20m18.txt](https://github.com/WarEmu/WarBugs/files/198352/sniff_h20m18.txt)
Another crash-log, however I had to crop this one as it was too big.... .P

**Comment by Natherul** [comment]
[sniff_h23m58.txt](https://github.com/WarEmu/WarBugs/files/201056/sniff_h23m58.txt)
tried to move to another disk as well, SSD this time but as I tabbed out to reply to something in the IRC the game just silently stopped.... -.-

**Comment by Natherul** [comment]
[sniff_h19m28.txt](https://github.com/WarEmu/WarBugs/files/201462/sniff_h19m28.txt)
Another crash

**Comment by bwdaWAR** [comment]
[sniff_h22m59cut.txt](https://github.com/WarEmu/WarBugs/files/203533/sniff_h22m59cut.txt)
The last 100kb of a log with a crash that wiped a whole warband, in Passwatch.

**Comment by bwdaWAR** [comment]
Here are a few more Open RvR crash logs. My old computer can't really handle the PacketLogger and I get extremely low FPS in big fights, so some of them may be because of that. But a few of them were mass crashes, as far as I can tell anyways. Most of them happened while defending keeps.
[sniff_h15m33cut.txt](https://github.com/WarEmu/WarBugs/files/205186/sniff_h15m33cut.txt)
[sniff_h16m37cut.txt](https://github.com/WarEmu/WarBugs/files/205187/sniff_h16m37cut.txt)
[sniff_h17m23cut.txt](https://github.com/WarEmu/WarBugs/files/205188/sniff_h17m23cut.txt)
[sniff_h18m10cut.txt](https://github.com/WarEmu/WarBugs/files/205189/sniff_h18m10cut.txt)
[sniff_h18m19cut.txt](https://github.com/WarEmu/WarBugs/files/205190/sniff_h18m19cut.txt)
[sniff_h18m36cut.txt](https://github.com/WarEmu/WarBugs/files/205192/sniff_h18m36cut.txt)
[sniff_h18m54cut.txt](https://github.com/WarEmu/WarBugs/files/205193/sniff_h18m54cut.txt)
I'll add a note to the last two, since I noticed a few large packets just before the crash while editing. The second crash happened just a minute or two after the first (and restarting, relogging and joining a WB), so the cause may be related.
[sniff_h19m56cut.txt](https://github.com/WarEmu/WarBugs/files/205198/sniff_h19m56cut.txt)
[sniff_h21m09cut.txt](https://github.com/WarEmu/WarBugs/files/205200/sniff_h21m09cut.txt)

**Comment by Natherul** [comment]
seems this issue has been somewhat solved for me suddenly (dont know if it was an update for the server, OS, driver or something else), running with ooh, shiny will crash even more frequently now BUT running on fastest framerate has allowed me to play over an hour now with no crashes at all in heavy ORVR fights.
