### ISSUE TITLE
[Core] Deatunt stacks with guard to 75%

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#4943]
Totaly game breaking bug. On live was no stacking effects with same damage direction. Only stackable combination was strongest outgoing debuff + strongest incoming buff. Distracting bellow Tank M3 + guard for example.

On live detaunt has higher prority before guard. Means detaunted target hit over detaunt and dont trigger guard.

**Comment by Nfkillz** [comment]
i confirm

**Comment by Silentguard** [comment]
Confirmation of what?

75% dmg mitiagation.
![pobrila_002](https://cloud.githubusercontent.com/assets/13031465/13782687/173db8f4-eb03-11e5-9e74-82cabd38fb0b.jpg)

**Comment by Evildoor** [comment]
Confirmation of how it was on live.

**Comment by bloodi** [comment]
I am farily certain that detaunt and guard never stacked on live.

**Comment by Silentguard** [comment]
https://www.youtube.com/watch?v=eKDSbxSA20o

5:09
Chasing for AM. Double guarded. No detaunt. Average dmg 400-600.

5:19
AM is kd. Average dmg same.

5:21
AM using detaunt. Double guarded. Average dmg same.

**Comment by Silentguard** [comment]
Moreover all this stacks with challenge!

Pounce damage: 457 crit

Guard+Detaunt+Challenge
Pounce damage: 87 crit!

![tashkent_001](https://cloud.githubusercontent.com/assets/13031465/13785176/6cb1413e-eb0d-11e5-83e1-6331f8be0f9b.jpg)

**Comment by Thorgatin** [comment]
Guard and detaunt never stacked on live.
Was the actual HP loss checked (WSCT and/or healthbar)?
The combat log was buggy/showing wrong values a while ago (when people reported that armor pen from WS is not working, but it did).

**Comment by Silentguard** [comment]
Not a visual bug. Just outhealed all wl dmg with single hot of dps dok.

**Comment by Blubberino** [comment]
I did stack in the beginning causing enemies to only take 1 dmg however im not really sure they changed it to additive stacking or no stacking at all.

**Comment by Gobtar** [comment]
Guard and Challange should stack stack, but from what I remember on live, guard and detaunt didn't. When we ran Double doks, our tanks never had to run over to guard the healer cause they had their AoE detaunt, and it's commonly known "you don't need a guard if you detaunt" as they didn't stack.That video seems to set the tone of this discussion though.

**Comment by Blubberino** [comment]
That would be strange if they treated two similar skills different. So it's either multiplicative or the highest debuff counts not one thing is like that and an other is like that.
+ Those I remember things doesn't count because when I told my guild here (who played on live) that detaunt and guard don't stack they were surprised too.
For the video 400-600 dmg average is quite a big difference how are you going to tell that it's not working since 450 is exactly the number multiplicative dmg reduction would give you.

All I know is that they changed guard + detaunt to not stack additive because people then only got 1 dmg which is op

**Comment by Blubberino** [comment]
That would be strange if they treated two similar skills different. So it's either multiplicative or the highest debuff counts not one thing is like that and an other is like that.

Those I remember things doesn't count because when I told my guild here (who played on live) that detaunt and guard don't stack some were surprised too. For the video 400-600 dmg average is quite a big difference how are you going to tell that it's not working since 450 is exactly the number multiplicative dmg reduction would give you.
All I know is that they changed guard + detaunt to not stack additive because people then only got 1 dmg which is op

**Comment by ozarmidrashim** [comment]
Ordering problem.

**Comment by Morksezstop** [comment]
just to add that greenskins tactic "wazad behind you" is exeption from that rule since on live it tend to stack with detaunts and guard
