### ISSUE TITLE
Ghrond's Xiphos #4935

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#5027]
Gives an wrong fragment. Added the info + pic in the old ticket.

**Comment by Evildoor** [comment]
Really? You know that you can and should comment existing ticket, you do so, but you open a new one to tell us that you did so? Go and read the rules. And while you are at it, read the part about losing items.

**Comment by Blubberino** [comment]
Well I saw that we shoudn't open the same ticket again and that you guys look over tickets but this one was closed and as such I was unsure if you read closed tickets or not.
To the lost items it wasn't in the Game Server Rules and after reading it again it's mentioned with one word in How to report a bug I've seen that now but I'm sorry but who reads rules so precisely as if they are going to write an exam about them. "Still my fault though"

Then I took a look at the threads in the forum they are always about "Well I lost my item somehow" and then the answer to that is that you guys don't replace lost items, I understand that but my item isn't lost I salvaged it to get the a high fragment and because of the bug (which I nicely reported) I got something of lower value. You guys doesn't replace lost items because you don't get why (or even if) they are lost here I offered you the reseason (atleast I think that is why you don't replace items).
I mean why should I report this kind of bugs then anyway it certainly doesn't affect me after I lost my item while testing the issue.

**Comment by Evildoor** [comment]
> I was unsure if you read closed tickets or not

Point 2 of the rules:
A closed report means only one thing – the devs consider the report either to be fixed or false. this does not means that the report was consumed by Chaos and lost forever. If you have something to say about a closed report, comment on it, we'll take a look and reopen it if needed. Do not create duplicate reports stating "I created / noticed report ABC, and it got closed, but the problem is still here because X and Y".

> To the lost items it wasn't in the Game Server Rules and after reading it again it's mentioned with one word in How to report a bug I've seen that now but I'm sorry but who reads rules so precisely as if they are going to write an exam about them.

Ok, then i'll clarify. Bug tracker is a place where you can report bugs, so that in the future these bugs do not occur again - not the place to get help with something. If your personal problem is solved by the way - good. If not - tough luck, but this is alpha.

> You guys doesn't replace lost items because you don't get why (or even if) they are lost here I offered you the reseason (atleast I think that is why you don't replace items).

We do not return items because we have no means to check if there was an item loss or not. I don't see any difference in your case.

> I mean why should I report this kind of bugs then anyway it certainly doesn't affect me after I used my item while testing the issue.
> 
> I know you guys do this for free and I shouldn't whine about an lost item but I think other people will think the same and then just don't report such things I mean I most certaintly wasn't the first person who salvaged this item I just was the first one who botherd writing about it.
> 

Players should report bugs for the same reason why are we working on this project - to bring the WAR back. And that's the main goal of RoR in it's current state. The fact that they can play their favorite game again is a byproduct.
