### ISSUE TITLE
Mounts Can't Turn Around Itself Smoothly

### ISSUE THREAD

**Issue by BrokenDiamond** [WarEmu/WarBugs#5064]
When you turning your mount, it can't turn around itself with move it's legs, it's legs giving much noise. And it's not aesthetic. Can developers fix it please? Not so big deal but not beautiful also. :)

**Comment by ozarmidrashim** [comment]
No, we can't fix client issues. Please don't report client side issues here.

**Comment by BrokenDiamond** [comment]
Why you can't? You can't change codes? :/

**Comment by Evildoor** [comment]
We can easily change the server, since it was made pretty much from scratch, but original WAR client is being used, and changing it is very problematic.

**Comment by BrokenDiamond** [comment]
What do ya meant by "change the server?"

**Comment by Evildoor** [comment]
The game consists of two parts, server and client. Implementing changes to first is easy, to second is not. This issue is client-related.
I suggest you to spend some time learning the ropes, about client/server difference, WAR, RoR, their difference, goal of RoR, etc, etc. We have no time or resources to teach everyone the basics. No offence, just a friendly advice.

**Comment by BrokenDiamond** [comment]
Hard but it can doable, right?
