### ISSUE TITLE
Banning Because Of Ban Evading

### ISSUE THREAD

**Issue by BrokenDiamond** [WarEmu/WarBugs#5074]
My account has been permanently banned because of ban evading. WTF is that? Are you fucking a joke?

**Comment by Evildoor** [comment]
Wrong place for complaining. Read
http://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=2485

**Comment by BrokenDiamond** [comment]
I didn't broke the rules. That is just my one account and the reason is "ban evaind." WTF?

**Comment by Evildoor** [comment]
Again, wrong place. This is place for bugs. From the rules:

Process for Appealing Staff Actions

If you wish to appeal an action made by a member of staff which you believe to have been made in error, you should first PM the GM who applied the action. If you do not know who applied the action, or if the issue is not resolved to your satisfaction, you must email sigmarpriest@returnofreckoning.com or PM SigmarPriest on the forum.

**Comment by BrokenDiamond** [comment]
Sorry but I can't post on the forum because of ban.

**Comment by Evildoor** [comment]
Emailing is banned too? Or what?

**Comment by BrokenDiamond** [comment]
No. I didn't meant that. Just I didn't know which e-mail address should I send e-mail.
