### ISSUE TITLE
Restarting the game when you are dead

### ISSUE THREAD

**Issue by wizzypooh** [WarEmu/WarBugs#519]
I don't feel like looking through all 13 pages, but when i die i quit the game and log back in, i am at the spot i died and full HP like i never died at all. I'll keep using this untill it's patched, but figure i would post about it so it can get patched.

**Comment by Evildoor** [comment]
I'm not sure, but wasn't this the same on live?

**Comment by Tiggonos** [comment]
on live it revived you too but in the Warcamp not in middle of the battle ...

**Comment by Evildoor** [comment]
If i understand correctly, this is a different issue. In ORVR you were revived in WC because you were always moved to WC if you logged out/went to SC/whatever near objectives (sorry, can't remember about doing it in RVR zone far from keeps/flags). Similar mechanism was implemented to move you to Altdorf/IC from LoTD if it was unavailable. In PVE you were revived on spot.
Long story short - this happens because #879 is not fixed yet, not because overall respawn on the spot mechanic is wrong.

**Comment by Evildoor** [comment]
Closing, since nobody challenged the statement that it was this way on live.
