### ISSUE TITLE
Damage over time and Heal over time

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#523]
After last patch the Dots and Hots take between 2-3 secs to apply. That is from cast until first tick hits. Tested on shaman. Both Dot and hot.

**Comment by ozarmidrashim** [comment]
Intentional.

**Comment by AlistaireCrowley** [comment]
Ok. Always thought dots hit 1st tick on instant.

**Comment by AlistaireCrowley** [comment]
Been talking in /advice. Seems I stand corrected. Its the mob behaviour that is wrong not the dot ticks. Mob should aggro when dot is applied. 
So u guys are correct. My apologies

**Comment by M0rf** [comment]
I was about to post a bug on dots and hots but as this is already here i will add to it. 
Hots and dots should tick 2 secs after cast and every 2 secs after the first tick, you can see it was like this by watching some old war vids on youtube and as a bright wizard where ignite ticks only 3 times instead of the 4 it should.
