### ISSUE TITLE
Things I have noticed.

### ISSUE THREAD

**Issue by bender072** [WarEmu/WarBugs#528]
When I receive potions they do not work or have any stats, and a potion during combat would be nice. 

There is a quest in the 3rd Ork questing area that is missing it's coding, and it says to contact and admin for that.
there are quite a few quests that require a sync example, When you kill the Gors, and pike Braeman's head another quest is suppose to pop up instantly from piking his head and continue with another piking quest but it doesn't do that so the quest is incompletable. Same with marked only when you right click the doll the quest doesn't complete or start a new one.

Also the bolster to 10 is suppose to be 15, but my main complaint about it is when you die with bolster you revert back to your original level thus making you weaker for pvp combat, and bolster doesn't help you kill the npcs near the flag points.

These are the main bugs that concern me most every thing els is null and void to me.

**Comment by Thorgatin** [comment]
- potions are not implemented yet
- some quests still don't work yet, especially if you have to interact with objects to fulfil the quest
- level cap is 10, there is no bolster to 15
- there is an issue atm, that all permanent buffs are removed if you die (including the bolster buff)

Please open always one bugreport for every single bug, so the devs can close the report after the bug is fixed. There is also a search function on github/the forum, all these issues are more or less already known.
