### ISSUE TITLE
choppa auto-facing

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#529]
Choppa's do not auto face target like other classes. as a keyboard turner noob its pretty painful to play a choppa.

**Comment by Thorgatin** [comment]
Every range attack uses auto-facing atm. Tested with bw, sw and slayer "throw axe".

**Comment by M0rf** [comment]
Im not sure i explained it correctly as #77 raises the issue with all classes, this is ONLY choppa problem that NO other classes have to deal with. i will do my best to explain it again, this is easily noticeable if you try any other melle class then try a choppa .
Every melle class you are able to attack your target with what appears like a 180 degree angle, so if your target is slightly to the left or right of where you are facing you will still be able to attack, now with the choppa u have to directly face your target in order to attack.
Hope this clarifies it and if u need any help to understand my poorly explained issue pm me.

**Comment by Thorgatin** [comment]
I just made a choppa to test it: 
for melee abilitys it seems that you need to have your target in a ~ 135 degree in front of you. If you use a melee ability, while the target is in this frontal attack cone, your character will automaticaly turn to him. Tested on a new choppa and with my knight.

Hint: The frontal alignment on the choppa idle animation is the direction the head points not the position the legs may suggest:
![choppaw](https://cloud.githubusercontent.com/assets/8567481/5680686/0079c676-9811-11e4-97fb-908c45b5e1e9.png)
![choppar](https://cloud.githubusercontent.com/assets/8567481/5680688/058dfe2a-9811-11e4-944d-b8eaf47a82de.png)

Nevertheless all range attacks have autofacing on 360 degree. 
Atm range attacks are also bugged so that you can fire on targets in your back while on the move. 
I think the attack cone for range attacks on the move (or in general) on the original server was 180 degrees. RDPS had to strafe kite to hit enemys following them:
https://www.youtube.com/watch?feature=player_detailpage&v=FLTfMjv7Bl4#t=285 (unfortunately it's mostly just another "festerbomb" video...)

Tip: I would hardly recommend to learn mouseturning if you want to pvp, as everyone turning with a mouse will have a big advantage. Auto-facing also should not work if you move and unless you don't cast a non-instant ability as a rangedps, it will not be of much use in pvp.

**Comment by M0rf** [comment]
Not sure if after your testing you are confirming this bug and i thankyou for taking time to test it.
what i will say is, it is very noticeable in pvp, every other melle i have played on this server it appears to have 180 degree or 135 degree like u said when attacking someone infront, playing a choppa it is very noticeable that something is not quite right.
Cheers for the tip and yes while it is a disadvantage i am not new to pvp, infact it made me a better kiter on my shaman Morfee.

**Comment by gittoaster** [comment]
Same thing for BW

**Comment by Evildoor** [comment]
Seems to be fixed, played both choppa and other mdps for a long time, had no problems bashing things without anything like "with the choppa u have to directly face your target in order to attack". https://github.com/WarEmu/WarBugs/issues/77 was also closed, so i'm closing this. Please, comment here and say so if i'm wrong and there is any persisting problem.
