### ISSUE TITLE
DCs at SCs

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#5296]
Hey since some days i get discountect sometimes every SCs (it don't care what class i play) but my internt is fine! Also the Tier don't care. I think it is a bug maybe.
Ty Elvo :)

**Comment by letumexordo** [comment]
And I can't entering into the game, when I click "PLAY" game loading but then I'm going into character selection screen and then I can't even click that button. And @Evildoor said me "read Github rules." That should be kind of joke.

**Comment by Evildoor** [comment]
@Zaccar20 - is there any error messages, or the game just closes?
@letumexordo - this report has nothing to do with your problem.

**Comment by Zaccar20** [comment]
Just getting back to Server-couse Screen sometimes i Need to restart the game to can rejoin the server

**Comment by Zaccar20** [comment]
I noticed it also happend at open RvR sometimes (without a mass dc) most of the time i have to restart luncher to fix the problem

**Comment by letumexordo** [comment]
@Evildoor I didn't said this report have do anything with my problem. Just I'm saying I have similiar problem but you said I should read rules. lol.

**Comment by Evildoor** [comment]
@letumexordo - first of all, i told you "If you don't understand the reason why i've told you to read the rules - say so. But in the proper place, not here.", why are you answering me here instead of #5291?

> Just I'm saying I have similiar problem but you said I should read rules. And yes, I didn't understand the reason why you've told me to read the rules.

Point 3. "Do not post problems related ONLY to you if the general existence of the problem is already known, such as missing items or inability to get into the game." And  
http://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=12841

confirms my suspicions - there is some kind of problem with your Witch Hunter which must be solved individually. I don't know, maybe he/she has a bugged item in inventory or something.

Also, i'd like to draw your attention to point 7. Bugtracker is a place for helping devs make the game better, not to solve your problems (even if reporting bugs serves both purposes sometimes). Things like

> What the hell is wrong with your servers?!
> And @Evildoor said me "read Github rules." That should be kind of joke.

do not belong here.

**Comment by letumexordo** [comment]
I told you already I could not find where I read the rules so why are you saying that what you said already at this case? lol. And why should answering you there #5291?

What the hell is that? Why would I post problems which is not about only me? lol. Of course I gonna report bugs which is related to me. Sorry but I'm not bugfinder or it is not my job. I don't have to report bugs which isn't only related me. I prefer to report bugs which is related only me. Sometimes you report bugs for looking for a resolve by help from developers, not just being report this bug do you know?

No, it is not about bugged inventory item in my opinion. But I don't know where issue is. So, when server resetted I'll be able to entering into the game with my Witch Hunter. I'll be waiting until then.

Sorry but I don't care about helping to developers. I care about my issues getting solve.

**Comment by Luth-RoR** [comment]
Is this still a problem?
