### ISSUE TITLE
Floating Goblin Player

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5316]
Hi all,

this guy here just flew around for a minute or two and killed me from out of the air. There was no way to kill him at all.

Is that a bug or exploit?
![anthyr_096](https://cloud.githubusercontent.com/assets/17605387/14474525/d7669a00-00fd-11e6-88a1-f764ac845c74.jpg)

**Comment by Luth-RoR** [comment]
Could be either 
a) the "hovering" bug that happens from time2time (players look like the fly around); that one happened on the mythic server too sometimes
b) some guy hacking

In case of a) it's a bug that can't be high likely fixed atm, cause probably client side.
In case of b) better ask for GM help ingame next time instead of a bug report (.gmlist shows a list of all GMs that are active atm in the game).
Setting the client modification milestone.
