### ISSUE TITLE
Cheap RvR influence

### ISSUE THREAD

**Issue by GloomySam** [WarEmu/WarBugs#5389]
Not just Influence, actually - all three types of rewards.
Sometimes if a player happens to be in a locked RvR lake the moment it resets, they will receive 600 points of influence 1500 rp and whole lotta exp, as if they partook in locking it. They need to be of an adequate level for the tier for that to happen, and it doesn't happen every time, but it does, allowing some to rank up get their rewards sooner than others.

**Comment by Yellowpillow** [comment]
That was on life like this, you can have revards for locking zone even if you not into RvR zone. I think it was done on purpose, so that people are not directly involved in the battle to feel part of the war. For example, when the lock requires points from finishing PQs.
Not so often people not involved in any gameplay receive any rewards, but it happened sometimes. Not big deal for times, when zone captures happens not so fast.

**Comment by GloomySam** [comment]
No, YellowPillow, you are thinking of another thing.
I do remember receiving lock rewards while unflagged and in PvE on live.
I am talking about receiving exp,inf,renown for nothing - the zone unlocks and I receive rewards, while literally NOTHING happened for them to come. This is obviously an unintended thing. You just come to an area 29 minutes after it was locked, stand around doing nothing, and BAM - 24k experience, 1,5к renown, 600 influence for free.
