### ISSUE TITLE
Scrubby Thief's Nettle Special Moment granting Smoking Pyre Ivy

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#5402]
Special moments on a Scrubby Thief's Nettle (Ballistics 175) is not granting a ballistics 200. Instead I've just got a Smoking Pyre Ivy (Molotov 1). Twice.

**Comment by Malvius** [comment]
It seems the ID that should have been for ballistics 200 ingredient (I only mean that it is the next ID incrementally after the 175 ingredient, and for all 15 other ingredients and seeds the 9 levels (1-200) have sequential IDs) is the first in the sequence of the 9 levels for the molotov ingredient.
For the record, here are all the related IDs:
Ballistic (ingredient): 83852 (1) - 83859 (175) and currently 84543 (200)
Molotov (ingredient): 83860 (1) - 83868 (200)
Ballistic (seed): 84353 (1) - 84361 (200)
Molotov (seed): 84054 (1) - 84062 (200)
Either have the special moment for ballistic 175 seed produce 84543 or bump up the whole molotov ingredient IDs by 1 (from what little I could tell by testing ingame the ID 84063 does not refer to an item, quest or skill, but whether that means it's available is just guesswork on my part) or to another range entirely and turn 83860 into the ballistics 200 ingredient. I'm assuming this latter solution, while being clean, is probably too much hassle since it would affect player inventories, banks, guild vaults and maybe other stuff too, requiring those to be "adjusted".
Sorry for the wall of text, I just wanted to post the IDs here for convenience since I had them in front of me anyway. I will wait for this to be fixed before I put up my CraftData.lua on forums in which I've corrected/added all the remaining IDs that weren't working for MiracleGrow (it'll be CraftValueTip 1.5.4).

**Comment by Kalidore** [comment]
This issue still needs to be addressed.

**Comment by rngvp** [comment]
This is still an issue. Just critted 2 Molotov items.  Also, for the record the Molotov item would not give a seed when trying to break it down.  It has the tool tip ctrl + right click but nothing happens.  Is there a way to get lvl 200 BS seeds?
