### ISSUE TITLE
 Knockbacks/Kicks interrupt casts twice

### ISSUE THREAD

**Issue by tutti13** [WarEmu/WarBugs#5472]
When kicked/knocked back, you get interrupted when you are kicked AND when you land on the ground again.

IIRC, the kick on live only interrupted you when being kicked, NOT when landing again.

Old one was closed for no reason. Behavior is still wrong and weird compared to live. Landing on the ground after a kick DID NOT interrupt casts. Only the kick itself did interrupt. therefore, starting any cast while still in air will lead to both a loss of GCD and AP. This cannot be wanted, can it?

Old one: https://github.com/WarEmu/WarBugs/issues/2359

**Comment by ozarmidrashim** [comment]
Bugtracker rules:

2. Verify that it's not been posted before.

You can search the bugtracker for keywords in order to verify that the bug you're posting wasn't already reported. Please do so to avoid creating work for the bugtracker's managers.

A closed report means only one thing – the devs consider the report either to be fixed or false. this does not means that the report was consumed by Chaos and lost forever. If you have something to say about a closed report, comment on it, we'll take a look and reopen it if needed. Do not create duplicate reports stating "I created / noticed report ABC, and it got closed, but the problem is still here because X and Y".
