### ISSUE TITLE
[Quest] Ghrond's Sacristy bugged for me

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#5506]
I have this quest bugged, the npc don't give me the quest, and no quest taken on the quest log.
I have this quest bugged since the past two weeks (jeje, two weeks....sorry ;) ).
I don't have any problems with my other chars, only with my zealot (notredame). can you fix me on the db, please?
Ty.

**Comment by Evildoor** [comment]
Wrong place. Read the rules of the bugtracker.

**Comment by notre4ror** [comment]
Sorry, but yesterday i ask a GM and he told me to put this BT report because "the GM doesn't work with quest, only devs works in quest, so put your BT report" (almost textual words)

**Comment by Evildoor** [comment]
Ok then, i'll talk with the team and we'll see what we can do.

**Comment by notre4ror** [comment]
Thanks.

**Comment by Evildoor** [comment]
We had a discussion and, unfortunately, it seems that we can't help you. The problem is, solving your issue requires someone with access to the database of the live server. This can't be done by a GM or a DB developer, it has to be one of the core devs - and i hope you understand that they have tons of work already, so bothering them even more just to solve the problem with a single quest (which will become obsolete as you move to next tiers) of a single character does not looks rational. My apologies, but that's how it is.
