### ISSUE TITLE
[Graphical Glitch] Female SM with Shield drawn

### ISSUE THREAD

**Issue by Thraksy** [WarEmu/WarBugs#558]
I noticed a graphical error with my female swordmaster's eyes when her shield is drawn

Shield stowed - no error
![wareyeglitch1](https://cloud.githubusercontent.com/assets/10601115/5804197/12aa2732-9fd2-11e4-848f-6360d3d7cdb7.png)

Shield drawn - eye glitched
![wareyeglitch2](https://cloud.githubusercontent.com/assets/10601115/5804212/346b1930-9fd2-11e4-819d-5cdb1e8e52b9.png)

**Comment by ozarmidrashim** [comment]
Happens to mine as well, and with a twohander out, one of the eyes contracts. I doubt there's anything that can be done about it because it's a skinning / animation issue.

**Comment by Elvenalthur** [comment]
I also experienced this on official server. It's a very minor mistake they made, but I don't think it's so dire that we need to fix it :smile:

**Comment by Meenexx** [comment]
Even if it is close i have a idea. I don't know if it is possible. It is not possible to use animation of dark elfe black guard. They have pretty much the same animation. And black guard do not have that issue. It look like a little problem but it affect a high elf. The race feature is the beauty and grandeur. If that bug was on Ork,it just look like normal because ork is ugly by nature.
