### ISSUE TITLE
Mirelen's Lost Shadowlands (Order) Quest Bugged

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5582]
This quest is bugged (again I think, from the forum posts). The quest is to kill 20 Uthorin Seekers and collect a scroll from them. You get 20+ copies of the item parchment filling up your quest inventory, but the quest does not ever tick off "Find scroll". There is no interact-able scroll in the area either.

**Comment by Ryanfawkez** [comment]
You need to use the gameobject "Scroll" in order to progress.

**Comment by Milord9** [comment]
Same problem and can't solve it : every Uthorin seeker gives us 1 scroll stocking in the quest items inventory, but it s impossible to tick the "find scroll" line. And the item "parchment" is unusable, can't click on it.

**Comment by Jsnen** [comment]
This quest appear to still be undoable - if there is supposed to be a scroll world object or something we need to interact with, could somebody verify that this object is reachable and visible and in the area? Because there does not seem to be anything, nor is anything dropping from mobs in the area.

**Comment by thorbolt80** [comment]
Confirm. There is no interact-able scroll in the area either and can't use the scroll given by uthorin.

**Comment by thorbolt80** [comment]
![thorbolt_090](https://user-images.githubusercontent.com/16274785/35191679-55f78fb4-fe81-11e7-900a-ce519f1ec3fb.jpg)

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
