### ISSUE TITLE
[Client] [Utorrent] Missing files 1week after DL

### ISSUE THREAD

**Issue by Chaoslan** [WarEmu/WarBugs#572]
I downloaded the client via Utorrent 1 week ago. The game is Playable. 
This morning, Utorrent wasn't sharing the Files.  I checked files via Utorrent and the rep was'nt complete so no shareable.

I'm redownloading It But mabye there an update of the torrent file that hadn't been done. Hope it can help ;-)

**Comment by Elvenalthur** [comment]
You're probably playing the game with the game files still in the torrent shared folder? The files will be altered from original torrent files because A: The RoR launcher alters a couple of key data files in order to log onto our server. B: Your personal user files of characters are saved there. So uTorrent won't see it as exact copy :)

The bug repository is for bug reports related to the emulator i.e server, so this shouldn't be reported here. The forum would of been better place to post it.

I hope this answered your questions, and you can close this.

**Comment by Chaoslan** [comment]
...ouppssss...Thx u've totally answer ;-)
