### ISSUE TITLE
Catapults on Gates of Ekrund isn't working

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5766]
Gates of Ekrund contains 2 catapults, they should throw players at the middle of Ekrund gates. Right now they unactive and uninteractable.
![arena_066](https://cloud.githubusercontent.com/assets/18102127/15118784/bcd2b512-161e-11e6-8b75-ca639cd2700b.jpg)

**Comment by Evildoor** [comment]
That was possible on live?

**Comment by Yellowpillow** [comment]
yes, after using (cast about 5-10 sec.) it throw you on middle of gate near central flag, by script i suppose. but very few people actually know it because usually people run forward from WC and sometimes use right stairs. And catapults placed far and throw you in a middle of gates, and also cast time not let people who play in group to stay together, so even those who knowed about this feature not often used it.

**Comment by Evildoor** [comment]
> after using (cast about 5-10 sec.) it throw you on middle of gate near central flag. You fly there by script and catapult just perform simple animation of throwing nothing

I can imagine this myself. What i'm interested in is if this really was possible. I doubt it, because order has no catapults on their side (don't tell me that you were supposed to load yourself into a dwarven cannon). Also, IIRC, catapults in Greenskin T1 PVE (which actually launched you onto walls) are world objects, while catapults on GoE are just decorations and you cannot interact with them.

So, proof.

**Comment by Yellowpillow** [comment]
Order don't have those because it wasn't conceived by mythic as a part of solid gameplay. It is more like easter egg, it is not so usefull because of a reasons i mantioned before. Also order not have alternative because catapulting yourself onto the wall is orkish thing, like in cinematic trailer.
I'm afraid i have no proofs, newer imagine on life it might be necessary.

**Comment by Evildoor** [comment]
Closing then. I understand this point

> I'm afraid i have no proofs, newer imagine on life it might be necessary

since i've run into it myself on several occasions, but this does not changes the fact that without proof we'll not change most things. And in this particular case i'm not sure if the catapults should be fixed even if someone brings proof. They can still affect balance between factions, long cast times and other stuff notwithstanding. Not to mention that we don't have catapulting implemented yet.
