### ISSUE TITLE
Loudmouth BO Tactic

### ISSUE THREAD

**Issue by Shadowgurke** [WarEmu/WarBugs#5769]
Let me preface this by saying I have no idea how that tactic worked on live.

The tactic states that Warbellows deal X damage to your offensive target. Which for my understanding is the enemy you have targeted at that time. However the tactic actually damages the target that the warbellow triggered on

**Comment by ozarmidrashim** [comment]
If you don't know how it worked on live, can you ask the forum first instead of creating a report?

**Comment by Shadowgurke** [comment]
Linking the thread here

https://www.returnofreckoning.com/forum/viewtopic.php?f=71&t=13581

Is this enough proof to warrant a change?

**Comment by Luth-RoR** [comment]
As the choppa and slayer abilities "bring it on" and "retribution" were fixed in one of the later patches to only proc against melee damage, it's probably save to assume that melee classes generally don't have access to easily available powerful range attacks from a balancing perspective + there were still bugs in 1.4.8.

Report can be reopened with evidence.
