### ISSUE TITLE
Local Beliefs - Empire CH19 Quest

### ISSUE THREAD

**Issue by player1137** [WarEmu/WarBugs#5814]
Quest objective:
0/1 Slain Bear examined. 

There is no way in which a player can interact with this mob. It's immune to player attacks, however other NPCs are able to damage and kill it.

**Comment by pixie126** [comment]
Confirmed. Not interactable.

![xramoth_014](https://cloud.githubusercontent.com/assets/15041016/15995441/0214e2ee-30e1-11e6-950c-e70537c3f6ae.jpg)

**Comment by Gakvar** [comment]
Double checked. Slain Bears not interactible, not killable. Quest cannot be completed.

**Comment by lennip** [comment]
Triple checked. Not only are slain bears not interactible with, but some of them are displaying wrong, as they appear alive instead of dead.

![piratelemmy_002](https://cloud.githubusercontent.com/assets/2891053/20062636/b67203b0-a504-11e6-8b06-c2edfd172d3e.jpg)

Also, there is a cave nearby where the "bear shrine" referred to in the quest description is, but clicking on it doesn't do anything. I think the shrine is supposed to be the actual quest-completing object. 
![piratelemmy_003](https://cloud.githubusercontent.com/assets/2891053/20062706/f321fd4c-a504-11e6-9b96-a6a742c06a2e.jpg)

**Comment by lennip** [comment]
Update: OK so I found this link: [http://marrek.blog113.fc2.com/blog-entry-897.html](http://marrek.blog113.fc2.com/blog-entry-897.html) that describes the quest chain. 
Apparently examining the Bear should trigger a new quest to kill some mob named Utlag, who should give the player an item when killed (Utlag Bear Slayer's Liver), and then the Liver should be brought to the Bear Shrine in the cave.

**Comment by NorKalli** [comment]
quest is long since completable
