### ISSUE TITLE
Terrible Embrace pulls through walls.

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#5828]
Terrible Embrace can pull people through walls if you line of sight after they've started to cast.
Seems like no LoS check at the end of cast.

**Comment by ozarmidrashim** [comment]
Collision is not active in T4 zones

**Comment by Troelsnap** [comment]
Not sure if it goes to the same bug - but engineers and magus have done the same since the fix of pulling through walls. If you were in LoS on cast you would get pulled though the object. On TE you have a small window where you can LoS as the cast gets disrupted if you are not more than half way through the cast.
