### ISSUE TITLE
[chosen] touch of palsy

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#5910]
damage tick happen even if the target don't move.

same on door but less frequently

**Comment by noisestorm** [comment]
To add to this, the Raw damage of its running dot is 4x higher than it states in the tooltip. (Tooltip ~70 , raw damage hitting for around 300 with very low str)

**Comment by Tesq** [comment]
there is a problem with icon maybe the damage of the direct hit change if i lower strenght, but the dot tick value remain the same; it's either a icon problem client side or tickt that had contribuition from strengh

i had focus offensive and 700 strengh anyway.

**Comment by Scrilian** [comment]
The raw part is kinda absurd, hitting harder than Ravage. Tested vs decently geared r40 dps 2h chosen, no taunt.
![2](https://cloud.githubusercontent.com/assets/16498708/15276422/55ef6e40-1af0-11e6-8325-dc862838f62d.jpg)
![1](https://cloud.githubusercontent.com/assets/16498708/15276423/55f138ce-1af0-11e6-9244-22912985eef9.jpg)

**Comment by Tesq** [comment]
the point is my touch said tick damages = 103

dosent matter if i increase stre or not, with around 700 str i had 149 melee bonsu damage

so 249 damage x tick then you can add taunt or focus offensive if all of this is allow to stack then damage get huge in no time.

**Comment by noisestorm** [comment]
the deal is that this skill still hits 4x harder than the opener of a WH/WE (and i am running 900+ str atm) so your argument should apply to my skill as well. the tooltip value of my sudden accusation goes from 109 with str tactic down to 108 (!) with 160 str less. And the actual damage of this spell in fact is exactly what the tooltip states. not like touch of palsy that hits for 3-4x its value.

**Comment by Tesq** [comment]
ye as i said maybe there is something wrong with contribution from str, after the tooltip it get contribuition again and wep dps again, anyway fix pending.

**Comment by Waffulz3178** [comment]
sorry to tack this on late but figured I would just in case. I don't know the exact circumstances this has been tested on but food for thought.

Is it ticking higher because testing might be being done with Toughness aura to already increase the dmg it is doin (since toughness aura reduces toughness of enemies around) and also running resistance aura which since touch of palsy does spirit dmg it will hit harder when enemies spirit resistance is reduced and a STR aura which would increase the DMG even further? I am not sure exactly how much of an effect all of those things would have but i know the toughness aura and resistance aura would make the ability hit much harder than it would actually be displayed on the tooltip.

**Comment by noisestorm** [comment]
So much non-wisdom. The tooltip damage of a skill no matter what it is is always the maximum achievable damage of said spell without having a crit on it. If touch of palsy or punishing blow (ib counterpart) state that the dot deals 100-120 dmg in the tooltip, then this spell CANNOT (or should not) exceed those 100-120 damage in any way unless you use taunt, or other direct damage modifiers. There is no reason to discuss any theories or whatever around why the damage is so high, because it simply should not be possible anyways. Your average enemy has 40-50% spirit resi. testing this without aura should now give out ticks of 50 or 60 dmg per second (on no toughness). The damage in fact is though 3 times as high as it should be as one can see if you count the 259(-95) together and see that the damage is just around 3x of its tooltip value. so here we have 350points of _RAW_ dmg instead of ~110 which the tooltip gives us. Even with the 30% dmg buff from taunt this value is not anywhere near where it should be.

**Comment by Waffulz3178** [comment]
No need to insult I meant no offense by my post just wasn't sure if that had been taken into consideration. Thanks for the breakdown though, always happy to be more informed :)
