### ISSUE TITLE
Declare Anathema/Agile Escape inmunity

### ISSUE THREAD

**Issue by chaoself** [WarEmu/WarBugs#5914]
It used to be 10 seconds on live instead the 30 that gives actually, making it almost useless to re opener as it was intended.

**Comment by Evildoor** [comment]
Proof.

**Comment by Dirksolomon** [comment]
Hello, I was quite intrigued about this too and I just did a bit of video spying. Here on this timestamp AE will be used, it will show up the timer on the addon top of the WL. Quite blurry but if you look frame by frame it is 2 digits and letter s, then after a second it turns into one digit countdown.
[https://youtu.be/39Z8o5eT2Zo?t=513](url)

**Comment by Tesq** [comment]
8:00 slow at hal speed you will see at 720p 10 sec clearly

https://www.youtube.com/watch?v=6gdhaTzpg74

**Comment by noisestorm** [comment]
Adding to this: Those spells should be undefendable. Right now they can be parried/blocked to prevent your selfkick, which is incorrect. CC immunity only prevents the stagger, but the selfkick still goes off.

Add #2: The spell had a short delay, that allowed you to reposition yourself shrotly before the selfkick. The issue on live was, that you were seen flying in direction X, but popped up in a position in direction Y, which was somewhat unfair, since there was no way to predict your direction. The short timer for repositioning would nonetheless be a very strongly needed QoL fix if there was a way to avoid the buggy position visuals with it.

**Comment by Torquemadra** [comment]
The pause and "repositioning" causes the client thinks you went one way when in actuality you went another as it makes assumptions based of the initial activation. This is a cause and effect of a client shortcoming and not one we can resolve, certainly not until we have the ability to update everyones client. 

Its completely unnecessary as a QoL as WH/WEs are not a weak class and neither should they be able to punt themselves back after being punted as they could do on live.

**Comment by ozarmidrashim** [comment]
Agile Escape / Declare Anathema will not be allowed to reposition on RoR.

"You leap backwards from your target"

These skills will, in future builds, get their punt direction when the cast completes, and punt in that direction when the effect begins.

**Comment by noisestorm** [comment]
@ozarmidrashim did you look at it being undefendable as well?
