### ISSUE TITLE
[Ability] Zealot Warp Reality doing wrong damage type

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#5966]
While testing the tactic sweeping disgorgement (which debuffs armor and corporeal resistance), I noted that the damage on warp reality wasn't increasing, while my autoattack damage and Scourge (tooltip corporeal damage) were getting increased damage. Warp Reality is also supposed to be corporeal resistance (according to the tooltip)

**Comment by CaptainoftheHarem** [comment]
I just did one more test and it does get affected, but only if it is cast after the buffed daemonic spittle is cast (there is no effect on an existing dot), so this does state that it is doing the right damage type.

**Comment by Morksezstop** [comment]
that change from live was intentional. at RoR dot dmg checks at initial cast not at each tick. If u get boiling blood on you and afterward detaunt the BW u still got the full dmg of BB, while all dots and hits from BW afterward got detaunted /even if he cast the BB while got 1 sec of detaunt and BB pop when there is no detaunt you get only half of the damage/

**Comment by Evildoor** [comment]
Morksezstop is correct.
