### ISSUE TITLE
dwarf tier quest reward 

### ISSUE THREAD

**Issue by lilsabin** [WarEmu/WarBugs#6051]
hi , it s me again , i am questing in dwarf tier 1 (of course) and i have noticed that the quests (all of them) rewards for turning in are all the same , a pair of gloves (12 armor) and a potion (22 action point) . Maybe you could take a look into it . :)

**Comment by Evildoor** [comment]
Exact quest names. Information how it was on live.

**Comment by lilsabin** [comment]
i dont know how it was in live (but i dont think rewarding the same item for 4-5 quest is normal) , and unfortunately i dont remember the quests name , cause i did 4 of them then i came here to report , it s dwarf t1 in the begining where there is the redhammer in with the railroad in ekrund , sorry

**Comment by Evildoor** [comment]
I agree that it's obvious that many quest rewards are broken, but to make them correct and fair we have to options:
1) Find info how it was on live and fix them accordingly.
2) Decide for ourselves what rewards should be given.
Second option requires lots of time and effort which we can't spare right now since we have more important things to do. So, if you have info on wikis or something like that about quest rewards for particular quests on live - post them. Otherwise - do not report such things.
