### ISSUE TITLE
level capped renown causes massive lag

### ISSUE THREAD

**Issue by Aleteh** [WarEmu/WarBugs#6114]
If you are level 10 with RR10 (99%) you get massive lag spikes everytime you get renown

It probably has something to do with the lag spikes you get, when you level up in either career rank or renown rank.

**Comment by Soulwhisper** [comment]
Loading stuff from HDD i think.An SSD would eliminate that brief pause if im not mistaken.

**Comment by Aleteh** [comment]
I dont see how that is the cause.

**Comment by Evildoor** [comment]
I'd like to get confirmation of this, because this does not happens to me, and i've not seen other mentions of such problem. I've not tested this at exactly level 10, but on many other levels (1-4, 19 to name a few) capped renown only causes visual bugs with "you've got 423532342384 renown" messages. So either there is something special about RR 10 or this problem has some additional conditions.

**Comment by Aleteh** [comment]
It might only happen in scenarios, but i had a guildy having the same problem.

**Comment by Evildoor** [comment]
No confirmation, closing.
