### ISSUE TITLE
tome: flamer

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6172]
i was trying to unlock bestiary->demons of tzeentch->flamer so i tried the following
http://warhammeronline.wikia.com/wiki/Hot_Deal
and indeed, in choas wastes and at the given loc i was able to find Soulflame but it seems to be the wrong one; looked high and low, tried interacting with flamer mobs in proximity, but the other spawn seems to be vacant. so, should i, as Torquemadra says, "try harder" or something is really missing ?

**Comment by Meralors** [comment]
Soulflame does exist in 2 spawn and award the correct tome unlock. You may have to try harder :)

**Comment by Lheana** [comment]
Soulflame in Chaos Wastes (48k 6.6k) correctly triggers his unlock and his associated title. Nevertheless the alternative for Order is not working: should loot a 'Mote of Change' killing 'Kruk'tar the Drunken' in Nordland (19k 40.9k). Then Order chars should give it to Aialye Lynsellia at High Elf Chapter 16 in Eataine.
'Kruk'tar the Drunken' does not drop 'Mote of Change'. Killing him does not provide the unlock/title. Talking to Aialye Lynsellia neither provides the unlock.

**Comment by Lheana** [comment]
Fixed: Killing 'Kruk'tar the Drunken' will provide the unlock. He will drop the 'Mote of Change', pocket item, for the associated title.

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Lheana [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UBTJACKAAVGQCLCUQBYIYMFNQFWACWBDUUQLDHXVW2Q7GTMUFRVJJRGAICQPNZJOAAKAAOQBDUCDZ6GGCBBKAVOMFWYI4JCFSDFEQU4IICAAWBCDAAD4ADXABHQAGYAB4AFWBSPBIC6MBLGASWMYJJI4CWISTIICQAAIA=@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Mon, 12 Jun 2017 10:49:50 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.26]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp w124si2271148ybc.337 - gsmtp:
    retry timeout exceeded
