### ISSUE TITLE
To many quest

### ISSUE THREAD

**Issue by Areanda** [WarEmu/WarBugs#6178]
put a maximum to the amount of quest that can be taken alot people take to many quest and in doing so they bug there character out resulting in getting kicked back from the loading screen to the character screen.

**Comment by LordMort** [comment]
Hi there,

I'm experiencing the same issue apparently.
When trying to log in with one of my characters, in difference to all my other characters, I continuously get dropped back from the loading screen to the selection screen, or the game crashes directly to the desktop.

So far I have tried all the suggestions given on both the forums, as well as here on github. This means the 2x /stuck within 5 seconds when the loading screen appears, as well as the .u commmand, and the /reloadui command. Every time the game was closed before restarting it for another try. Also the option of terminating the game process through the Task Manager has been unsuccesfully tried.

Upon comparing for diffrences between my characters, I had to come to the conclusion that the only real "major" difference between my characters appears to be the number of active quests. While most of my characters have a maximum of 14 quests, the character I am experiencing log-in issues with has 260+ quests (still) active.

My question concerning this issue is this: is there a way that a player could abandon all quests for a character, even if that player is unable to log-in with that character? I know that this would mean that all progress for active quests would be lost, and that the quests would have to be accepted again at a later time in-game?

Thanks in advance for any reply.

**Comment by Areanda** [comment]
yes there is a way just look on forum of ror or ask there.

**Comment by LordMort** [comment]
Hi Areanda,

thanks for your reply.
I assume that you are talking about this solution:
https://returnofreckoning.com/forum/viewtopic.php?f=4&t=8904&p=95047&hilit=too+many+quests+active#p95047
Unfortunately for me it didn't work. That's the reason for my earlier post.
