### ISSUE TITLE
[title] Fearlss

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#6301]
Should be granted when you enter in th cave located at 48k, 44k

**Comment by Evildoor** [comment]
#5578

**Comment by joneswaronline** [comment]
I believe the problem is thus:

When entering Amund's Barrow the game is not recognizing it as a separate location. Traveling around Amund's Barrow your location changes according to where on the world map you are. The picture I attached shows that at the entrance to Amund's Barrow the game is recognizing the area as Hunter's Road.
![graved_007](https://cloud.githubusercontent.com/assets/19896303/16283751/973c143c-387a-11e6-8bbf-2254ad912ec7.jpg)
