### ISSUE TITLE
T1 ORvR Rewards Bugged

### ISSUE THREAD

**Issue by zyidgaming** [WarEmu/WarBugs#6435]
The T1 ORvR Rally Master's choices are completely blank, as in no boxes or any gear of any kind appears. I have unlocked all chapters leading up to the current ORvR in the tome of knowledge and it is still bugged.

**Comment by Evildoor** [comment]
> I have unlocked all chapters leading up to the current ORvR in the tome of knowledge

But orvr page itself refuses to unlock, right?

**Comment by Vandorkholme** [comment]
I can confirm, you can gain influence within the lake but in the tome & when you go to the rally master there are no rewards, only blank boxes.

http://i.imgur.com/CWdbJOe.jpg

**Comment by kuldian** [comment]
I can confirm this as well. Also, not only is this relevant in T1, it is also relavent in T2 and T3 (and possibly T4, I'm not that high level yet)

I believe the problem lies with not being able to unlock the warcamp entries in the tome of knowledge. It worked flawlessly up until about a week ago but something was changed that screwed it up somehow.

**Comment by Evildoor** [comment]
#6320 then.
