### ISSUE TITLE
Getting influence in T1

### ISSUE THREAD

**Issue by ThunderMjolnir** [WarEmu/WarBugs#6451]
Getting Influence
At Tier 1 zones we cannot getting any influences from Battlefield Objectives anymore. I asked for it to a developer and he said it applied for Tier 4 zones and accidentally applied Tier 1 zones too. Please fix it. We can't getting influence rewards without killing players from enemy realms. People can getting those either chatting or they have to wait long time for sometimes catching players from enemy realms especially when they checking for lair bosses at lairs.

Influence Bar
We can't see influence bar at some zones. And we seeing Chapter bar inside Warcamp, we should see RvR Influence Bar in my opinion.

Elf Zone's Influence
We cannot see about Elf Zone's influence anymore at Tome of Knowledge and rewards at Rally Master.

P.S. When you get your first influence either Influence Bar is showing up, High Elf Storyline adding at Tome of Knowledge and influence rewards adding at Rally Master. Until you get your first influence none showing up nor adding at anywhere. So you can fix those issue by looking on that detail.

Rally Master
Rally Masters doesn't have their relevant mark onto their head and not even name. So we know they are near to the Healer but sometimes we getting hard time while trying to find them. Thanks for fixing issues already!

**Comment by Evildoor** [comment]
1) One report per problem.
2) 3 and 4 were already reported elsewhere. I'm not sure whether point 2 is a general problem or should be reported individually for each zone.
3) This report will be used for as a report for its point 1.

**Comment by ThunderMjolnir** [comment]
Why while those problems are relevant with each other? lol. I thought it is better to report those relevant problems at same topic. Sorry.

**Comment by Evildoor** [comment]
The only relevant thing among them is that they have something to do with influence. First problem is about a dev's mistake, which has clear way of fixing by reverting that change, other have no known fixes for now. I can name some more differences, but the result is - it's highly probable that these problems will be solved separately (and probably by different people), that's why they need separate reports. 
Multiple problems can have one report, but then they have to be directly connected (Landmine throws exception, Rain of Fire throws the same exception) or very similar (items with wrong stats in a single chapter, two mirrored abilities have the same problem).

**Comment by ThunderMjolnir** [comment]
Of course. So that is the point. That is why I gathered them in same topic. That makes no sense. If these problems will be solved separately and by different people those different people can read those problems here. I don't mind.

**Comment by Evildoor** [comment]
Reading is not the only thing done with reports. They also have to be closed/discussed/reopened/etc. In single report devs (and players responding to them) will have to write "problem number X: i did this and that and now it has to be ..." every time. Both in this report and in other ones where this one has to be mentioned. That's a lot of unnecessary work which will also complicate navigation between reports.

**Comment by ThunderMjolnir** [comment]
So they can discussing about those here too. And until all problems will be fixed no close then there won't be any problem at this case.

**Comment by Evildoor** [comment]
Ahem. So, let me get this straight. We have two options:
1) You create 1 report for 4 problems which are barely related. This requires every dev/player who says something here add "i'm talking about problem number X" each time they are saying something. Same goes for every other report where one of these problems are mentioned. This also requires me to change the name of the report depending on the situation, otherwise it will be vague "issue about influence" which makes search harder. This also makes labeling this report more complex.
2) You create 4 reports for these 4 problems. This requires you (and only you) to click a bit more buttons, and make it only once.
And you believe that second option is better?

**Comment by ThunderMjolnir** [comment]
1) Why would have to talking about issues? Their job is fixing issues not talking about those, so they should fix rather talking about those. And if they gonna talking about issues yeah they should add "I'm talking about problem number X." 

2) No it isn't problem for me. I just thought it would be provide more clear forum to post relevant issues at 1 topic. Otherwise it is not problem for me create 4 topics. lol. No I'm believing that first option is better.

**Comment by Evildoor** [comment]
> Why would have to talking about issues? Their job is fixing issues not talking about those, so they should fix rather talking about those.

There are some situations where initial description of the problem is not enough. And i really don't understand why should i be explaining things as obvious as this one.

> I just thought it would be provide more clear forum to post relevant issues at 1 topic.

I understand this point, usually it's valid. But in this particular case the problems are barely related, so they need separate reports (and they have, since 3 and 4 were already reported).

> No I'm believing that first option is better.

Then use it in the future, unless problems are

> directly connected (Landmine throws exception, Rain of Fire throws the same exception) or very similar (items with wrong stats in a single chapter, two mirrored abilities have the same problem).

**Comment by ThunderMjolnir** [comment]
What kind of situations there which is requires talking? There is no obvious thing at this case in my opinion.

No problem you also can edit my first post if those are already reported and unnecessary.

But you saying I shouldn't use it 1st option as I understand.I don't got your quoted saying btw.

And could you tell me how could you quote my sayings?

**Comment by Evildoor** [comment]
> What kind of situations there which is requires talking? There is no obvious thing at this case in my opinion.

Obvious thing to me is the fact that problems may require discussion. I don't know exactly what could be discussed (but i may hazard a guess or two since i have some knowledge about how things work out there), but i know that saying "hah, these problems are so trivial that there is nothing to talk about, we should just fix them" would be premature.

> No problem you also can edit my first post if those are already reported and unnecessary.

I know.

> But you saying I shouldn't use it 1st option as I understand.I don't got your quoted saying btw.

You should not use 1st option when the problems are only slightly relevant, like here - as i already said, only similar thing about them is that all of them have something to do with influence. This is not enough - otherwise, following this logic, we should dump like hundred more issues into this report since they are also related to influence in some way. I doubt that anyone would be able to use this report afterwards to keep track of things fixed and broken. My quoted saying describes examples of the problems which have enough in common to be reported together.

> And could you tell me how could you quote my sayings?

Copy/paste a text into response form. Then select it and press "Insert a quote" button.

**Comment by Luth-RoR** [comment]
Point 1: https://github.com/WarEmu/WarBugs/issues/4915

**Comment by Luth-RoR** [comment]
The other points: as evildoor stated.
