### ISSUE TITLE
Interups on Knockback

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#6504]
On live a knockback or a pull never caused the ability to stop building neither was it impossible to start a new cast while on the fly. This is the reason why knockbacks and pulls are so strong here on ror. 

This change here on ror is also the cause why moral 2 (50% faster casting + imunity to anything) is getting interupted by kicks. The ability never had to prevent interups from kicks because kicks never interupted anyway on live.

https://www.youtube.com/watch?v=TJYFl3F11Mg 

Skip to 7.15 for several casts after kick and mid air.

**Comment by Londo001** [comment]
I believe you are correct, only abilities that explicitly stated in a tooltip that they will interrupt would stop channels and cast timers.

**Comment by noisestorm** [comment]
I can just judge from my experience back then but all groupheals got interrupted as i got kicked. On the other hand i definitely know that the "ismoving" check on live was extremely bad and you could start running while your casts werent even finished. You were basically able to cast Healing Energy on the move (like it is on RoR now), if you staarted moving after 0.1 sec after the cast begin. Also in this video the second cast is not while being kicked, but being pulled by the Eyes which most likely doesnt even count as movement at all. Not sure if i'd count that as proof tbh, allthough i have to admit im biased in this topic since kicks are imo supposed to set you as moving

**Comment by Londo001** [comment]
Group heals and big heals are "fragile" and are setback/interrupted by dd damage.

**Comment by Blubberino** [comment]
Well he for sure starts a casts while being kicked and than starts another one while being pulled.

**Comment by noisestorm** [comment]
Setback =/= interrupt. Also those are only worded on the single heals - not the group heals.

**Comment by Londo001** [comment]
I am 100% certain channels were not interrupted by knockback/falling on live.

**Comment by Vayra** [comment]
I don't remember if you got interrupted or not by being KB'd, but you could definitely start a new cast while in the air without it being interrupted.

**Comment by Blubberino** [comment]
https://www.youtube.com/watch?v=NprJWU_i4xw

17.58 dok starts and compleats a grp heal mid air

**Comment by Evildoor** [comment]
Sigh. #1450 & #1528 (these should have been a single ticket, but chaos interfered). Long story short: knockbacks interrupted on live, both channels and cast spells.
Casting in mid air: #2359.

**Comment by Blubberino** [comment]
Okay posted the video in the other thread

**Comment by noisestorm** [comment]
>

https://www.youtube.com/watch?v=NprJWU_i4xw

17.58 dok starts and compleats a grp heal mid air

a) that is a 0.5 sec single targte heal 
b) like i said you could even cats 1.0 sec casts on the move since the games movement check was shit.
