### ISSUE TITLE
Warped Flesh does not trigger

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#656]
Warped flesh does not activate. I tested the empire version, I think its called Emperor's Ward? And it works if when you equip it, you get the auto attack animation and sound, otherwise it's not going to work. So swapping tactics around to try and get it equipped is a smart move any new scenario etc. But Warped doesnt work at all.

**Comment by Evildoor** [comment]
Warped Flesh works, but it absorbs damage from a single attack instead of creating absorb shield like Empire version. Here are discussion and dev answer about this:
http://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=1189&start=410
I think this difference comes from Mythic's different wordings of the tooltips:
Warped Flesh: Any time you are attacked, there is a 25% chance that you will absorb up to 141 damage. 3 second cooldown.
Emperor's Ward: Any time you are attacked, there is a 25% chance that you will become protected by a magical barrier for up to 10 seconds which will absorb up to 141 damage. 3 second cooldown.
