### ISSUE TITLE
White Lion Tactic Tearing Blade

### ISSUE THREAD

**Issue by SirBattosai** [WarEmu/WarBugs#6610]
Hey there!
The White Lion Tactic Tearing Blade is dealing its damage over the course of 9 seconds instead of 3.

![battosai_040](https://cloud.githubusercontent.com/assets/16100206/15747799/ac08bbc0-28dc-11e6-845f-baa1db9db2ab.jpg)
![battosai_039](https://cloud.githubusercontent.com/assets/16100206/15747798/ac005a48-28dc-11e6-81ef-2e59409627e3.jpg)

**Comment by Chummi** [comment]
there is a second thing which seems to be wrong with this tactic. it refreshs itself which makes no sense to me due to its 100% trigger chance on both SB and SC. since there is no initial damage tick you will never get all dot ticks e.g. the full damage when spamming SB - and that's what you do in aoe pve :P - hence why i think it shouldnt refresh itself.
