### ISSUE TITLE
ToK : Title Spite Splitter

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6664]
Title Unlock: The Spite Splitter
Notes: "Looking for Shinnies" Kill Dark Sprites at this location (Blighted Isles, 54k 53k for a Shining RIng. Looting the item grants the title unlock. (Low drop rate)

The ring almost always drop, but doesn't give the title.

**Comment by Ryanfawkez** [comment]
Ring's now a pocket item you'll have to wear for the title. Unlock is added to killing Dark Sprites.

**Comment by Lheana** [comment]
There is an error : it's not Dark Sprites, but Dark Spites.

**Comment by Lheana** [comment]
Dark Sprites will no longer trigger the unlock; Dark Spites will trigger it.
Added the unlock on "Shadow Spites" for Destruction task.

**Comment by Lheana** [comment]
Completly fixed: Shadow Spites will now drop Shining Ring for the title.

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Lheana [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAIZEA3ICGPYIDSTFACNSVRAATVYAMYZDBLOQHMRQDHIUCGS6FLV4ANAZNWVDMECCGMTUTT4RKY5YG6EF7B2USCYQOHQZTE44EKWBAOMSJYE3FYDBAALARBQAB6AB3QATYADMAA6AC3AZX2MBPGAVTAJLGM4Y6EUKJCRACAIAAEA======@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 08:13:24 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp t95si1478716ybi.466 - gsmtp:
    retry timeout exceeded
