### ISSUE TITLE
SILENCING THE CANNONS quest

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6676]
Issues:
- put 2-3 more cannons to kill
- quest has the same name but requires to kill hellmagus', hellfangs and hellservants and has same rewards. Please put mobs closer to the cannons, From cannon point of view they are too far away.

**Comment by Ryanfawkez** [comment]
Or, how about you go down there and kill the mobs yourself? You don't need to use the cannons for it, as it is proving to be very ineffective.

**Comment by StaH84** [comment]
Of course I can, just I remember it was possible on live.

**Comment by Ryanfawkez** [comment]
A part of the issue is related to NPC distance rendering range. There are actually three cannons down there as it was on live, but only two are visible from the hill. I could perhaps move one cannon a bit closer to make it fair, and reduce the amounts of cannons required to be killed to one. This also covers the lack of NPCs visible at range for the secondary quest.

Another issue is the overal lack of mobs in the area. Even on live it took long to kill all the mobs required, be it in close quarter combat or at range. With the influx of new players wanting to do this quest now, I see the issue in its entirety and could apply some fixes for the next patch. I'm sad to say it's a bit low priority, though.

**Comment by StaH84** [comment]
Thank You for detailed info.

**Comment by sioding** [comment]
Checked that Quest - works fine - and its like Ryan said - if too many new players are in that area you just need to wait.
