### ISSUE TITLE
Lissariel's Glade PQ Troll Country

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6956]
No-one interacts with the old one.
**Stage 1** - Works fine with wood logs.
**Stage 2** - Works fine killing dryads but in this stage it spawns Deeproot TOO who is meant for Stage 3.
**Stage 3** - So when Stage 3 jumps in Deeproot de-spawns and we cant complete the PQ.

**Comment by Soulwhisper** [comment]
Same #5566

**Comment by Luth-RoR** [comment]
Thanks. Closing it then as the other one has the same info and is older.

**Comment by Soulwhisper** [comment]
Assign someone please because its like very old...and Ryan is not assigned into that one.

**Comment by Luth-RoR** [comment]
Could be that it needs scripting (which can't be done by everyone). DB devs normally grab reports by themselves. 
I only assign reports when i'm 100% sure that the person can handle/solve it and its the right person; otherwise they have to decide by themselves. 
e.g. abilities or gamebreaking exploits = azarael

**Comment by Soulwhisper** [comment]
Yeah i told you that because it was working in the past flawlessly..but it broke through some patches.So yeah it can be fixed :D I dont remember who fixed it though.Let me check.
