### ISSUE TITLE
Troll country / Brenard the Alchemist

### ISSUE THREAD

**Issue by emperorKane** [WarEmu/WarBugs#6985]
Its not able to  give him the items "Intact Troll Stomach" and "Bat Wing" to reward a Titel

**Comment by poutpoutt** [comment]
For destruction, giving the "intact troll stomach" to Voxanna the Transmuter doesn't give the unlock either (Uneasy stomach).

Troll, Stone (Stormblight Dolt/Brute) - Uneasy Stomach
"The Boulderbane"
(D) & (O)
TROLL COUNTRY @ 12, 31. Kill this mob. Collect multiple Intact Troll Stomachs. Confirmed return at 5 stomachs, official number may be less.
(D) Deliver to Voxanna the Transmuter in Felde @ 11, 60.
(O) Deliver to Brenard the Alchemist in Felde Castle @ 27, 82.

**Comment by Lheana** [comment]
Workaround possible maybe ?

**Comment by Ryanfawkez** [comment]
Work-around made. Collect 5 Intact Troll Stomachs and bring them to the library assistants in the capitol.

**Comment by Lheana** [comment]
Work-around correctly works, but it does not provide the unlock, only the title (intended). Moreover, killing 'Stormblight Brute' and 'Stormblight Dolt' does not provide the unlock. In real interacting with 'Voxanna the Transmuter' provides the unlock. I think the unlock should be linked to these trolls, instead of Voxanna.

**Comment by Lheana** [comment]
Fixed: Voxanna won't trigger the unlock anymore ; kill Stormblight Brute/Stormblight Dolt for the unlock.

**Comment by Lheana** [comment]
Stormblight Brute will now also drop 'Intact Troll Stomach'.

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Lheana [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UBTOYDHMID2QCLCUQGMOQIFVCXMADMEG3QGLACKFV3AXWLBRBTFFCVFFEKMZWJMAZUVLYJUIONQVWNIQTTGM2TIUMLKSVELYYDQMYJCFVQWYBACUUQKIAOUAOOAEXAAXQAFYAV4MNP4AE3AB5QATRSHYBG4CVBCCYQCIAAEA======@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 08:23:21 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp g16si1642539ybh.325 - gsmtp:
    retry timeout exceeded
