### ISSUE TITLE
Hide detection

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#6993]
Bolstered players have a almost 100% chance to detect players in hide, incognito, shadow prowler.

**Comment by Lileldys** [comment]
Stealth detection on RoR works on Initiative + Proximity/Distance, the closer you are to players, the higher chance of them seeing you.(This was due to staff not knowing the live formula for stealth checks)

Are you sure you aren't being too close to people for a long period of time? 

Over-bolstered players may have slightly more initiative than most, but I can't imagine 10-20 extra initiative being a game changer.

**Comment by tlitschye** [comment]
Im on my WE inside orderkeeps almost my whole onlinetime. With full Annihilator gear, so around 350 INI. Lvl 40 full equipped players dont see me as easy as low lvl bolstered people. I always have to make huge turns around those low lvls so they dont detect me. Something dsnt seem right.

**Comment by ozarmidrashim** [comment]
Totally subjective.
