### ISSUE TITLE
Oppression [Chosen Skill] activates only on block, not on parry

### ISSUE THREAD

**Issue by Ritzlas** [WarEmu/WarBugs#7078]
Hi...Today i found the skill from Chosen dont work anymore.
The skill dont start or when Hit someone (very very rare..1/100) ther proc Armor buff dont stack.
It's only my issue or someone have the same problem?

**Comment by Luth-RoR** [comment]
I just tested this on the devserver: the ability works perfectly like described in the tooltip. 
Stat buffs nerver stack. 
How did you notice this? Over a longer period or is this based on some 1vs1 experience?
Because: when an ability with a buff/debuff component is blocked/parried by the enemy, the buff/debuff is not applied.

**Comment by Ritzlas** [comment]
This problem start today,I respec my chosen and i start in PvE to farm the Jewels set,
I tasted all the time today,all the time I parried an attack and the skill is active I try to use but dont work)dont hit dont start 20 sec CD...nothing) but when sometime this skill start my armor still the same and the proc dont stack.

**Comment by Luth-RoR** [comment]
Ok, i tested it again and the ability only activates on the server when the chosen blocks a hit, not when he parries.

**Comment by ozarmidrashim** [comment]
Incorrectly required shield. Fixed.
