### ISSUE TITLE
Engineer Ability Redeploy Does Not Work at Close Range to Turret

### ISSUE THREAD

**Issue by LordTercept** [WarEmu/WarBugs#7118]
As stated in title I noticed that Redeploy doesn't appear to be working at close range to my turret.  I noticed this in Warzones in Tier 1.  When attempting to redeploy my turret if I'm within the range of the "Improvised Upgrades" buff the ability goes off but the turret remains at it's original location.   See the video below:
https://youtu.be/wC85ny5Q8sA

Just an additional note that the same issue is present whether I enable or disable all addons.  

Thanks!

**Comment by Soulwhisper** [comment]
This persists even now after 8/8/2016 Changelog.

**Comment by Luth-RoR** [comment]
The packets used for pet-ability communication with the client are still not completely reverse-engineered afaik.

**Comment by Soulwhisper** [comment]
This one used to work afair.There are no restrictions of Feet that you can redeploy.

**Comment by Luth-RoR** [comment]
I think atm it doesn't work exactly like on the mythic server, as iirc the use of different pet addons can bug "redeploy" (e.g. loyalpet).

**Comment by LordTercept** [comment]
In my original post I outlined that I've tried with both all addons enabled and all disabled with the same result.

**Comment by Luth-RoR** [comment]
This was just for informational reasons; i already read that you tested it without addons.
I just meant that: if addons can bug the pet behaviour, it is an indicator that it doesn't work 100% like on the mythic server atm; i guess some workaround because of the lack knowledge about the packet structure between the server and the client _atm_.
The devs are constantly trying to analyse the structure, but mythics communication between server and client is a mess and it can very often take a while until more knowlege is gathered.

**Comment by LordTercept** [comment]
I see what you mean.  Thanks for all your work on these issues.  It's very encouraging to see such dedicated development for this game.

**Comment by geezereur** [comment]
And also when I use Redeploy on my Engineer the Turret dont attack my Enemy automatically, like it does when I summon it normally, I have to use the turret attack manually after Redeploy.

**Comment by ozarmidrashim** [comment]
Fixed thanks to Londo's assistance.
