### ISSUE TITLE
Auto Attack toggle issues

### ISSUE THREAD

**Issue by kdm666** [WarEmu/WarBugs#7194]
The auto attack toggle is not working from the abilities menu. When placing the ability auto attack from the abilities menu on the action bar, you are not able to toggle it on or off so that you can start combat with an ability instead of a standard attack.  Example using a long activation Squig Herder ability, you target a monster and start to use a long cast time ability and it fires a standard arrow causing the target to start running immediately.  This causes immobilizing abilities to not work correctly.

**Comment by Luth-RoR** [comment]
The AA ability doesn't work like a toggle and it never did afaik. It just starts the "AA cicle" without the use of any real ability.

Though channeling/buildup abilities should block AA completely and i guess if you start the fight with one, on the mythic server the first AA was executed _after_ the attack.

**Comment by Zealote** [comment]
Regarding the AA ability, I remember it as Luth does: it couldn't be toggled on and off afaik.

> Example using a long activation Squig Herder ability, you target a monster and start to use a long cast time ability and it fires a standard arrow causing the target to start running immediately. This causes immobilizing abilities to not work correctly. [- kdm666]
.....
>Though channeling/buildup abilities should block AA completely and i guess if you start the fight with one, on the mythic server the first AA was executed after the attack. [- Luth]

I just tried targeting both orange/red monsters and using Eagle Eye: the AA didn't go off until after EE had hit (~20 attempts). It's possible though that the AA does automatically trigger during flight time --before the ability hits-- and my weap just isn't firing fast enough to show it, since I _was_ able to AA during EE's flight time by manually pressing it. It certainly doesn't seem to AA while you're building up an ability (which is how I understood the OP), but is the above what was meant?

**Comment by ozarmidrashim** [comment]
Closing as apparently false report
