### ISSUE TITLE
Mara Mutation

### ISSUE THREAD

**Issue by pootie14** [WarEmu/WarBugs#720]
If I release the mutation it disappears but it wont let me get another mutation. It says that I have the mutation but the graphics aren't there. I have to log out then back in for it to reappear and correct itself.

**Comment by Gnashspike** [comment]
Hey Pootie,
iirc, Dana/Horsegirl (could've been Azarael or Sigmarpriest, idr) said the mutation is released client side, but not server side. Have you tried using a different mutation after releasing? That's always worked for me. However, I still use the "old rule of thumb" that was posted on live forums a few years back; to paraphrase,'always release mutation before flying or zoning anywhere; this includes entering and exiting SCs and City Sieges, including each instance within a City Siege, and this should be done with pet classes as well: as with mara mutations, kill/dismiss pet before zoning or flying anywhere.' And since I use all mara mutations when context requires, I have them hotkeyed to avoid 'mis-click' frustration.

For the life of me I can't remember what doing this remedied on live servers (crashing upon zone entry, I believe), but on RoR it takes care of the Mara "appearance bug" (where your face, scar and tatoo models randomly change upon zone entry) as well as losing/never gaining control of pathing pets and turret pets not responding to attack/disengage commands and not being able to put either type of  pet on passive/follow so YOU control the pet (not the AI)and to prevent them from attacking/following guards.

Hope this helps.
Good Hunting!
-Gnashspike Rhaylphist
