### ISSUE TITLE
Energy of Vaul/Fury of Da Green

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#7206]
These abillties doesn't burn career mechanic points on use. Intentded or bug???

![hewlin_001](https://cloud.githubusercontent.com/assets/16356956/17622420/94477184-609a-11e6-9f56-2542970e7a18.jpg)
![hewlin_000](https://cloud.githubusercontent.com/assets/16356956/17622419/94419b1a-609a-11e6-8bdf-e98d29ba8787.jpg)

**Comment by footpatrol2** [comment]
By the way I can't remeber on the mythic servers if they spent mechanic points. 

Does anyone have confirmation on how it was on the mythic servers. ideally video.

**Comment by Luth-RoR** [comment]
Tooltip description says "Tranquility reduces casttime".

**Comment by footpatrol2** [comment]
This bug report is a continued conversation I've been having with roadkillrobin via private messages which got to the point of making a bug report. Which is why i am commenting on it.

Please note: Energy of Vaul and Fury of da Green do not have to face their target to use in its current state. Meaning, in its current status you can use these abilities while kiting and still maintain your mechanic level of 5. I am unsure that this is intentional or a bug. I am unsure if this was how it was on the mythic servers. I can see how it would be intentional design by mythic or RoR modification and I can also see how it is a bug and was overlooked by RoR. It would be nice if someone had video of it on the mythic servers.

If you take balanced mending tactic/Gork fix'd it tactic along with energy of vaul/Fury of da green. You can make a healing spec that is viable. You supplement your Isha/da Green healing with instant cast energy of vaul/Fury of da green that doesn't burn mechanic. You still constantly heal via isha/mork abilities but now have a random potentially large instant heal with vamp healing every 5 sec's that can be used on the move without facing your target and without burning your mechanic.. As mentioned before Energy of Vaul/Fury of da green do not spend class mechanic points.

This means you can get 2 instant casts with back to back gcd's. 
Example: instant cast fury of da green, instant cast i'll take that to burn mechanic.

This is extremely viable. Stat value's need to be played around with to find the sweet spot.

Spec looks like this as the minimal requirement. 
http://waronlinebuilder.org/#career=sha;5;0;13;3:5:;;13:;;0:0:0:0:
http://waronlinebuilder.org/#career=am;5;0;13;3:5:;;13:;;0:0:0:0:

I don't know if this is a bug or not. But due to the unpopular nature of vaul and da green spec lines, I believe this is good for the class overall. 

In addition: There is some very nasty synergy with these abilities if you use a Double whisper wind group coming from 2 SM's or Chop Faster coming from a choppa. I believe this is by design from mythic. You are basically creating a at distance action point Bomb group with those classes since energy of vaul/fury of da green becomes spammable due to not burning the mechanic. 

If geared and spec'd for it energy of vaul/Fury of da green CAN hit like trucks. 

It requires organization/coordination that mythic in my opinion loved to reward, so I can see how this would be by design. This also indirectly buff's SM's.

**Comment by ozarmidrashim** [comment]
Was resolved some time ago
