### ISSUE TITLE
Black ork bugs

### ISSUE THREAD

**Issue by powazappa** [WarEmu/WarBugs#7279]
Hey just wanted to let you know some bugs on the black ork you might wanna know:

-The skill savin me hide doesnt seem to apply the 4 second buff that reduces magic damage by 20%, atleast i dont see it on the buffbar(if its hidden then nevermind this one).

-The skill right in da jibblies doesnt interrupt channels

-It might be the same for taunt tho i havent really confirmed this

-Changing da plan bugs out frequently. using it after using a skill will quite often put it on cooldown and still not change the plan. This happens more often when theres alot of players in the area.

-Hold the line cant be interrupted by pressing the skill(minor annoyance really but annoying nonetheless)

-Warbellow doesnt stick after you log out (this one doesnt really matter aswell)

-Morale keeps building after death and stays after res

im still a lowbie so i havent really had a look at all the skills yet but ill let you know if i find anything else. keep up the good work!

**Comment by Luth-RoR** [comment]
1. https://github.com/WarEmu/WarBugs/issues/7142
2. https://github.com/WarEmu/WarBugs/issues/922
3. Please only tested bugs on the tracker
4. The crappy BO/SM class mechanic had always problems with server/client lag, even on the mythic server(s); maybe this can be fixed one day
5. https://github.com/WarEmu/WarBugs/issues/2350
6. Not implemented yet
7. https://github.com/WarEmu/WarBugs/issues/7084

Please use the search function and only one bug per report; otherwise reports can't be closed when bugs are fixed and i have to assign 10+ labels and/or devs for the different problems. Thanks.
