### ISSUE TITLE
Run Away SH ability works incorrect

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#7331]
on live : If pet taunts enemy, enemy can hit pet 100% damage and  another targets 50% damage in 10 sec 
And gives 30% mov speed

ROR: gives only mov speed

**Comment by Nfkillz** [comment]
https://www.youtube.com/watch?v=OifqOiGPKKQ

**Comment by Lileldys** [comment]
Taunts don't work because PvE agro system isn't implemented. 

I'm guessing you'll have to give some proof of the 50% damage reduction, as it's not in the tooltips.

**Comment by Nfkillz** [comment]
here https://youtu.be/FfilDuLX-40?t=6m19s
look at damage of sudden accusation when SH uses run away

**Comment by Silentguard** [comment]
vid above 6:23 - WH is dead, taunt gone, SH getting normal damage of Sudden Accusation.

**Comment by ozarmidrashim** [comment]
Run Away is implemented as Challenge, but with a 50% reduction factor and the caster as the Squig pet. It works identically to Challenge in all respects.

**Comment by Silentguard** [comment]
What do you mean SA not affected? It's video (not meaning op post vid) from Live server which proving that Run Away have -50% damage effect to any affected enemy. Even if not said in ability tooltip.

PS
SA on live has direct damage flag, means any tic can trigger any matching procs (odjira etc).

**Comment by ozarmidrashim** [comment]
Then the bug is in SA / ES and not in Run Away.

**Comment by Silentguard** [comment]
Ok. Let's try again. RoR Run Away debuff don't apply damage reduction effect as it should. So OP made a video which show this, he getting same damage from mob. And also how debuff vanishing after mob hit him, instead of vanishing after mob hitting pet. 
So as writed above was not proved by tooltip and looks dubious i found a video from war live which proving that Run Away has damage reduction effect.

**Comment by ozarmidrashim** [comment]
Both issues dealt with.
