### ISSUE TITLE
Dreamshade Forest - Public Quest Destruction Dark Elf Chapter 3

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7405]
- [x] Stage 1 doesnt work.
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_003](https://cloud.githubusercontent.com/assets/16864486/17911219/1c9caa74-6995-11e6-998c-e1497d47640f.jpg)

**Comment by Yellowpillow** [comment]
#5504

**Comment by Soulwhisper** [comment]
PQ working fine.But there is already a Shadow Walker Lalia in the PQ area all the time.I dont know though if its independent from PQ because she doesnt respawn/removed upon completion.
**(The right one in screenshot)**
![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/21467139/27a8eac4-c9ec-11e6-8219-9b8a65bd00a8.jpg)

**Comment by wargrimnir** [comment]
Fixed in next
