### ISSUE TITLE
Gon'Seraph - Public Quest Destruction Dark Elf Chapter 3

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7412]
- [x] Stage 1 doesnt work.
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17912031/bbc2cef4-6999-11e6-9044-ea34ad3caf53.jpg)

**Comment by Yellowpillow** [comment]
#5504

**Comment by Soulwhisper** [comment]
- [ ] These mobs are untargetable.Posting here because they are inside of the PQ.
![warhammer online age of reckoning 12 24 2016 - 16 45 53 78](https://cloud.githubusercontent.com/assets/16864486/21467489/a56946fa-c9f8-11e6-8436-08304ed555eb.png)
![warhammer online age of reckoning 12 24 2016 - 16 46 19 79](https://cloud.githubusercontent.com/assets/16864486/21467490/a56ce53a-c9f8-11e6-8117-84a3ba54c9fa.png)

**Comment by Lheana** [comment]
NPCs fixed with next patch.
About the chest I had no problem so I guess it has been fixed.

**Comment by sioding** [comment]
Fixed with patch from 28.10.2017
