### ISSUE TITLE
SW's/SH's "Whirling Pin" incorrectly works.

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#745]
SW/SH can to jump away without enemy. It is incorrectly.
On live server "Whirling Pin" worked so:
1. Target must be within 30 ft from you (without target you couldn't jump away).
2. Snare-effect was applied.( Should not be effects of resolute defence or immunity to snare on enemy otherwise SW doesn't snares enemy and doesn't jumps away).
3.SW jumps away from enemy.
Else. "Whirling Pin" snare effect stacked with "Takedown" snare effect. Total: 40%+40%=80% reduced enemy's speed.

**Comment by ozarmidrashim** [comment]
Is the distance to the player's offensive target checked, or does the skill instead check for any enemy target within 30ft?

**Comment by Thorgatin** [comment]
Iirc it was a check against the nearest target and the backjump direction is calculated from this target. The aoe snare is applied to every target in range if the backjump is succesful.
The ability behaviour was pretty unique imo.

On snare stacking: as the ability was introduced/altered very late in the game and because there are no other stacking snares, i believe this was a bug.

**Comment by ozarmidrashim** [comment]
Looks like I'll need a dedicated handler for it then. Will fix.

**Comment by murmelon** [comment]
in another "Whirling pin" is similar to any tank's root
1. can to be parried/blocked
2. Сooldown is running if you used "Whirling pin" but targets, within 30 ft from you, was not.

**Comment by gittoaster** [comment]
i like how the direction is handled currently, and so far I see it as better for the class IMO.  My 2c.

**Comment by Evildoor** [comment]
Punt no longer occurs with no enemies in range. Closing.
