### ISSUE TITLE
Choosen bugged aura Discordant Fluctuation

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#748]
Hello, i am playing Bright Wizard and i have some issues with Discordant Fluctuation aura of the chosen. When i use Fiery Blast on my BW that aura damage me for every target i hit. So if there are 10+ targets in small area (And at least 1 chosen with such aura running)  i die instantly. From 1660 HP to 0 just with 1 skill use. Thats not right. I am not sure if that happen to sorcerer as well. I remember in off server aura was hitting me only from 1 target that i hit, and not half warband like now.

**Comment by ozarmidrashim** [comment]
Probably should have a retrigger interval?

**Comment by DUSKANGEL** [comment]
Well if only main target  that i hit will trigger aura response no need intervals:D

**Comment by Radiantknight** [comment]
http://warhammeronline.wikia.com/wiki/Discordant_Fluctuation
I'll just leave it here, everything is said in the description. No real proof from that BW, just words. With gimping this aura's effect it becomes totally useless. I remember reading forum thread where people said that it procs only once per 3 seconds, which is also BS, otherwise it would have been reflected in aura description. And auras affect only party members, not warband, so 10+ ppl and 1 chosen is BS.
