### ISSUE TITLE
registration doesnot works please help

### ISSUE THREAD

**Issue by kosutadesu** [WarEmu/WarBugs#7524]
![untitled](https://cloud.githubusercontent.com/assets/21297942/18037349/76ad4d1a-6d92-11e6-990a-faa3ab9038fe.png)
cant register to the game it is telling me i am marked as a hacker or spamer - directly IP is marked, the fact is you can check the log files and system, i entered the webpage just today first time, 28/08/2016. i would relaly love to play this game once again, since official is gone i found this game can anyone please help me? (asking devs) since i am neither hacker or spamer or scamer or something like that including the fact i entered the webpage first time today. i really do hope anyone will answer me and fix this issue with registration. regards.

**Comment by Luth-RoR** [comment]
1. the bugtracker is only for bugs
2. for support use the support forum please
3. someone else who owned your IP before you was a registered spammer; most private users have dynamic IP adresses, which means you get a new one every now and then: http://whatismyipaddress.com/dynamic-static
You can restart your router to high likely get a new one, or better request a new one in the router UI if possible. 
If you can only restart it to get a new address: I don't recommend restarting your router too frequently in a short timeframe, because for the DSL hardware on the other side it could look like the connection is unstable and it may reduce your speed for more stability.
