### ISSUE TITLE
Ch 20 Dark Elf - Woodsong manor PQ

### ISSUE THREAD

**Issue by NorKalli** [WarEmu/WarBugs#7553]
Loyal Songblade mobs give no credit towards completion of stage 1

**Comment by Soulwhisper** [comment]
#7459

**Comment by Yellowpillow** [comment]
#5504

**Comment by Luth-RoR** [comment]
I was told that Db devs basically look at the forum thread and have different resources to gather info for PQs. They will fix every PQ one by one if possible, but some just can't be fixed yet.

**Comment by NorKalli** [comment]
Want me to stop reporting them?

**Comment by Luth-RoR** [comment]
DB-devs say so. They are aware of the issues, so the non-working PQs are not a lack of knowledge.
All other issues should be reported ofc.

**Comment by Soulwhisper** [comment]
@NorKalli Stop reporting those who dont work at all.For example if Stage 1 doesnt work and you cant proceed then dont report it.

**Comment by NorKalli** [comment]
got it, was only trying to help

**Comment by Luth-RoR** [comment]
Yes ofc, thanks. I didn't think about it earlier, but it makes sense from a dev perspective.

Once the PQs have been implemented and then you encounter bugs it is completely different though.
If a PQ has been implemented and parts of it are not working after going live, please report any issues, so that devs can finetune/fix them.
