### ISSUE TITLE
Dps Formula

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#7589]
When I talked to a Developer ingame a couple months back he/she kinda explained that toughness that surpases any dps bonus will chug away flat base damage of abillities aswell as the base damage from AA. However I claimed that any toughness that surpases the dps bonuses are simply void of effect since that how i learned toughness work when I played live. But if I ever found proof of my claim i should provide it. This isn't really hard evidence since the source link to the old WAR board isn't working but I see no reason for the site to missqoute the Dev of mythic that helped him. I however think its evidence enough to maybe question the RoR dps formula.

http://www.unigamesity.com/how-do-warhammer-online-stats-work/

**Comment by Yellowpillow** [comment]
I am fully confirm written. Damage per second being given by, for example, the strength offset by the same amount of toughness. On live If the attacker had 500 strength (which is equal 100 DPS bonus on 80rr) and the defender 250 toughness (50 DPS decrease from attacker's DPS) the striker got an attack bonus of 50 DPS, which is equal to 250 strength (or 200 melee power).

**Comment by ozarmidrashim** [comment]
Absolutely nothing here contradicts what is in the emulator.

**Comment by roadkillrobin** [comment]
The article clearly mention dps bonus, not dps.

**Comment by ozarmidrashim** [comment]
Take it up with Annaise or Bruglir. They know far more about the combat formulas than anyone else and they know it from live. The bugtracker is for CONFIRMED issues ONLY.

**Comment by roadkillrobin** [comment]
Talked to Bruglir and he confirms my point. 

[quote="Bruglir"]Hello!

from what i remember, the damage formula works by simply subtracting toughness from str/int/bal to give you the damage bonus. Stephen and Keaven both confirmed to me that "An abilitys final damage can never fall below it's base value". which indicates to me that the formula should probably be something like:

Max(0,(atkstat - toughness)) * blah...[/quote]

**Comment by Luth-RoR** [comment]
I'm not saying that thoughness calculation is wrong atm (combat formulas from theory crafters could be also wrong and have been in the past iirc), but even if:
I remember that Keaven also posted that any modification on the combat formulas was strictly forbidden by the management. So he or any other dev never had the chance to change anything on the formulas, even if they realized that something is not balanced,

As this seems to be a controversial topic:
Any balance discussions on the forum please, so that others can discuss/contribute to the topic as well.
The bugtracker is not very well-frequented by the playerbase and generally the wrong place for this.
