### ISSUE TITLE
Only NPCs 'Grim Wolf Cub' should be friendly, but 'Grim Wolf' are too, and shouldn't 

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7620]

**Comment by unrealmack** [comment]
Same here, unable to complete quest "Da Perfect Bone" (Kill Grim Wolf - 0/5) as all of the grim wolves are set to friendly instead of aggressive and unable to be attacked.

**Comment by gschouweiler** [comment]
Confirmation with screen.
Quest impossible to complete because NPC is "allied".

![screen bug](https://cloud.githubusercontent.com/assets/22920863/19770670/6ec7f99a-9c60-11e6-9f9a-89bdc5aa2bf5.PNG)

![quest](https://cloud.githubusercontent.com/assets/22920863/19770677/77376318-9c60-11e6-830a-9dbd5cf9b216.PNG)

**Comment by Soulwhisper** [comment]
This is patched.Can you check it again if it works?

**Comment by gschouweiler** [comment]
Fixed.
Nice works.

![correction](https://cloud.githubusercontent.com/assets/22920863/20302457/b162f4a0-ab27-11e6-860d-89488751bcb4.PNG)
![end](https://cloud.githubusercontent.com/assets/22920863/20302749/d568bd2a-ab28-11e6-91ee-f8e6bf993c77.PNG)

**Comment by Soulwhisper** [comment]
@Luth-RoR :)
