### ISSUE TITLE
bunny hopping / triggering out of range

### ISSUE THREAD

**Issue by Karast** [WarEmu/WarBugs#7645]
I noticed a lot more people bunny hopping than before so I did a little testing in duels and with guild mates.

When you bunny hop it seems to increase the frequency of getting "target out of range", and it also seems to cause a bit of warping on the map. 

Part of this also seems to be latency connected but even with lower latency it still seems to have a noticeable impact, which is probably why a lot of people have gone back to bunny hopping recently. I had thought there was a bug report about this issue up, but I didn't see it after searching. If it's a double post sorry about wasting your time!

**Comment by Luth-RoR** [comment]
That's known. 
There was a temporary fix to somewhat compensate for that: jumping while in combat gives you a short movement speed debuff; the debuff is only applied if you repeatedly jump and it stacks; the first jump doesn't count (no debuff). This is continously being worked on and will (hopefully) be fixed one day, so that this bandaid-fix won't be needed anymore.

As some players consider _lag-jumping/bunnyhopping_ as a _legit defense mechanic_, the forums basement is still a bit wet from the day this temp fix was pushed on the server.
