### ISSUE TITLE
Guild taverns crashing the game

### ISSUE THREAD

**Issue by Nasharan** [WarEmu/WarBugs#7649]
Upon entering the Viper's Pit via scroll, the game crashed. When trying to log into the Viper's Pit, the game either crashes immediately or within 5 seconds after logging in. It took me about 15 game starts to get out of there.

**Comment by Luth-RoR** [comment]
Needs confirmation if others have the same problems.

**Comment by Teefz** [comment]
This might actually be the explanation to me constant crashing upon logging in. I was in Viper's as well.

**Comment by GnFlala** [comment]
This bug is confirmed by me also. Using guild scroll makes the client crash with a rate of 60 to 70%. 
After that every time you try to login to the character that is in the viper pit makes client crash.

That happens sometimes when i go to viper pit and go near the flight master in it.

Solution is at login screen to write fast /stuck press Enter and again /stuck even if you do not see the interface or the chat. You will be transported to norsca.
If that does not work try it again. Press login and at the login screen /stuck,Enter,/stuck.

**Comment by Nizdizzle** [comment]
Also can confirm, CTD 4 times today, all 4 were inside Viper Pit.

**Comment by Luth-RoR** [comment]
Same with both guild taverns: https://github.com/WarEmu/WarBugs/issues/7789
