### ISSUE TITLE
Flag tier 1 bugged

### ISSUE THREAD

**Issue by sbronzo** [WarEmu/WarBugs#7705]
I am practically three days that the BO (flag) of the tier 1 are bugged in part ... virtually prendibili only by order. Now I do not know if it is desired as something ... but this will surely bring benefit to order that continue to gain renown.
I personally have sent 1 ticket per day for about all of this , but no one answered so I post this thread in case someone will deign to read it.

**Comment by Soulwhisper** [comment]
#7644
Please always check if it has already been reported.

**Comment by ozarmidrashim** [comment]
Hai già letto le regole di questo sito? È scritto che non serve aprire multipli racconti dello stesso soggetto. I problemi saranno sistemato solo quando avrò aggiornato il server. Non voglio aggiornarlo adesso perché non ho finito qualche novità.

Chiuso.

--

Did you read the bugtracker rules? We don't need multiple reports on the same subject. It'll be fixed when I patch, which I won't do yet because I'm not finished with some stuff.

Closed.
