### ISSUE TITLE
Riposte can trigger Tantrum\Deadly Determination

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#7754]
And probably some other onAttack abilities.

**Comment by Luth-RoR** [comment]
Do you made a screenshot showing it?

**Comment by Silentguard** [comment]
I'm not playing. Got report from mate. He was pretty happy about this bug.

**Comment by Luth-RoR** [comment]
Ok, i just tested it and it works with riposte.
![luthslayer_001_crop](https://cloud.githubusercontent.com/assets/8567481/18562636/d94b5246-7b84-11e6-87fd-5c709c1eeb58.jpg)

**Comment by Luth-RoR** [comment]
I suspected it to work with other procs too then and it also procs "reckless gamble"; Seems like riposte is generally bugged atm and can proc everything.
![luthslayer_003_crop](https://cloud.githubusercontent.com/assets/8567481/18562770/73d6eb22-7b85-11e6-88e0-66f6d15af14b.jpg)

**Comment by Luth-RoR** [comment]
According to https://github.com/WarEmu/WarBugs/issues/7788 it seems like all tactics that do damage can proc everything.

**Comment by Daniellita** [comment]
Afaik prayers/covenants, bw/sorc buffs didn't have internal cd's on live. However their interactions with tactics are not working correctly and Enfeebling Strike/Sudden Accusation are definitely not working correctly atm nor is Touch of Palsy. So it seems like there is a tactics issue and an onMovement issue with procs, but it should not be confused with an internal cooldown being where it was not.

**Comment by ozarmidrashim** [comment]
Changed to proc damage.

**Comment by Karast** [comment]
Since this topic was about damage procs, I hope this is not out of place.

As an additional observation the BW proc, flames of rhuin seems to be able to double proc off phosphorus shells on Engi. It is a little hard to tell with combat log clutter, but it seems to be able to proc on the direct damage portion, and then on the dot application. I seem to recall it working like that back on live, as many used it as a way to proc the crit damage buff. But I am not 100% sure.
