### ISSUE TITLE
Enfeebling Strike/Touch of Palsy  - proccing dok covenants 100% of time upon movement

### ISSUE THREAD

**Issue by ItsJustJono** [WarEmu/WarBugs#7848]
Tested this extensively with several guildies:

If you have 2 doks - both of whom are running the tactic that increases proc chance by 15% (Potent Covenants) and both using different covs - and have a Chosen apply Touch of Palsy on the target, the target will take proc damage whenever they move - regardless of proc chance (it becomes 100%).

The same applies when a witch elf applies Enfeebling Strike on a target: whenever the target moves, they take the normal enfeebling damage PLUS covenant damage/any other procs (I believe Sorcerer's proc also applies)

We tested this with a Sorcerer running the Frozen Fury tactic, also, and that also applied along with the covenants.

Literally farming through groups in a matter of seconds - both normal scenarios and 6v6 caledor woods - without thought given to playing properly (healdebuffs/punts/etc/challenge): just simply spamming aoe and relying on procs to overwhelm.

Heymate/Katarn - Peterthepan3

**Comment by Luth-RoR** [comment]
Probably related to this issue: https://github.com/WarEmu/WarBugs/issues/7754

**Comment by ItsJustJono** [comment]
Alright mate, happy to help.

**Comment by Daniellita** [comment]
First of all, enfeebling strike, sudden accusation and touch of palsy shouldn't trigger procs, just like tactics do not - because of the idea that procs shouldn't proc procs (which makes perfects sense). However, the rest of the information in this bugreport is factually wrong. I've tested this on my slayer against a group with 2 DoKs running potent covenants and a sorcerer with the 75% proc tactic.

Combat logs:

Convenatns only:
http://imgur.com/a/O3ctp (not a 100%)

Covenants and Frozen Touch 

http://imgur.com/a/K5sCC (Covenants not a 100%, Frozen Touch seems about 75% - correct with the tactic, definitely not a 100%)

However, as mentioned above these abilities should not be triggering these procs in the first place.

**Comment by ItsJustJono** [comment]
Maybe not 100% but each proc seemed to trigger all the time upon movement. We're streaming now so happy to show.

**Comment by Yellowpillow** [comment]
First - 35% (max chance of covenant to proc with tactic equipped) is not too much. Even with 2 doks it not gonna be like 35+35=70%, it don't work that way.
Second - if it not suppose to be this way you should proof it, because it not obvious thing. Most of the time devs require proofs from live.
Third - about that "procs shouldn't proc procs" : Touch of Palsy is ability with direct damage, it can trigger procs, why shouldn't it?

**Comment by Daniellita** [comment]
I think the procs are working at the correct percentage rate as you mentioned Yellowpillow.

As per Touch of Palsy, Sudden Accusation and Enfeebling Strikes afaik these didn't trigger (I didn't play with a proc on a Chosen/WH/WE on live) on live, friends who did tell me it didn't proc that way. I know how it was on live is not good enough justification for how it should work here so let me elaborate:

Yes, you are correct they are direct damage, but so are proc tactics. The reason they shouldn't and didn't proc tactics on live is that they themselves hit very often and are in an of themselves triggered on every movement, therefore proc'd by a movement (ie.: in a way a proc). The reason procs shouldn't proc procs is because it results in ridiculous damage during a low time window for classes that could stack these procing tactics/abilities. If you run with a Touch of Palsy on yourself against 2 DoKs with potent covenants and a Sorc with the proc tactic, it will do about 4-5k damage. That is a bit over the top wouldn't you agree? Of course it isn't THAT much of an issue because these abilities are easily counterplayable by not moving, but I still don't believe they should deal this much damage.

**Comment by Ktaan** [comment]
Covenants/prayers/procs should have internal CD, otherwise they too much overperforming and they make 2 doks/wp and sorc/bw is an absolute must in grp because just from this procs you get 35%-50% damage (and even more on def tanks) boost according to enemy addon combat statistic.

**Comment by MKorin** [comment]
Enfeebling Strike proc Shield of The Sun too

**Comment by Silentguard** [comment]
On live if DAMAGING proc has no cooldown in description mostly means 1 sec internal cd.

**Comment by ozarmidrashim** [comment]
These abilities are now proc damage.
