### ISSUE TITLE
Quest: Desperate Gambit - Answer to Prayer

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7878]
Realm: Order - Empire
Region: West Praag
Target Coordinates: 50k/60k
Subject: Send Penitent Knights to pray & Speak with Griffon First Knight

Problem: Quest marker for target area on the map is missing

![1 desperategambit-answertoprayer](https://cloud.githubusercontent.com/assets/18719012/18808486/694b5950-8264-11e6-8ea7-b05d21d99c57.jpg)

![2 desperategambit-answertoprayer](https://cloud.githubusercontent.com/assets/18719012/18808489/756ae87c-8264-11e6-8e0c-ca586d329646.jpg)

![3 desperategambit-answertoprayer](https://cloud.githubusercontent.com/assets/18719012/18808491/7baae9c6-8264-11e6-866a-ddc170e7e68a.jpg)

![4 desperategambit-answertoprayer](https://cloud.githubusercontent.com/assets/18719012/18808493/81774642-8264-11e6-81da-5c6fae725809.jpg)

**Comment by Ezella** [comment]
Had the same issue after taking the quest like Soulwhisper ( #7875 ), but the 'completed'-questsign disappears as it should after turning the quest.

**Comment by Gakvar** [comment]
Checked. Map markers still missing, just like every other quest for West Praag.

**Comment by lennip** [comment]
Checked too. Apart from still missing quest marker, I found another error: quest requirements are incorrect. The correct quest requirements should be :
*Speak with Griffon First Knight 0 of 1
*Send Penitent Knights to pray 0 of 5
It currently asks you to speak 5 times with Griffon First Knight instead of just once, which makes no sense.

**Comment by Razielhell** [comment]
Fixed in next. Corrected quest markers.
