### ISSUE TITLE
Resolute defense ability

### ISSUE THREAD

**Issue by porkstar** [WarEmu/WarBugs#7925]
I purchased Resolute Defense and I am unable to place it on my hot bar. If I log out, resolute defense disappears from my abilities window. It is also not available in the renown purchase abilities. I am basically not able to place resolute defense on my hot bar. My login name is Porkstar

**Comment by Luth-RoR** [comment]
I tested this on the dev server with RD I, II and III; the ability stays under the "career" tab in the abilities window after logout and is saved on all my hotbars.

**Comment by porkstar** [comment]
Do I need to be a certain level? i am level 18. Apologies if this is the case.

**Comment by Luth-RoR** [comment]
10 renown points should be enough for RD I.

**Comment by milosxe** [comment]
Iirc it doesn't work prior to r20rr20, Neither does Cleansing Wind.

**Comment by Luth-RoR** [comment]
I just tested it again: all the implemented _active_ renown abilities require a minimum renown rank of 20.
If you reset your renown points, you shouldn't be able to take the abilities again until RR20 (didn't work for me). 
If your RR is 20 already, you need level 20 too, as the renown points are bound to your level since some patch (for the server you have only RR18 atm, until you reach level 20).
