### ISSUE TITLE
T4 Order: Unmasking the Enemy Quest

### ISSUE THREAD

**Issue by Zardonic** [WarEmu/WarBugs#7931]
In caledor on the quest ''Unmasking the Enemy'' there is a part where you need to kill 7 helglaive raider. However they are not targetable, So you can't kill the npc's to continue with the questline.

**Comment by Yoreik** [comment]
I've done this quest yesterday. The issue is real, anyway, you can do it like that : 
- Do not take any target (defensive or offensive)
- Get in mob aggro range, let you being hit by the npc
- You will get him as a target, your abilities will still displayed as unavailable, but you can clic them as they are "red".

Tips 2 : bring aoe toons with you.
You're welcome.
