### ISSUE TITLE
The bug with the bag.

### ISSUE THREAD

**Issue by z0tt** [WarEmu/WarBugs#7996]
03/10/2016
Happened a bug with the backpack. On the third tab (craft) appeared fourth division, I moved to things and they become inactive. After relog the fourth tab is missing along with things.
Nick in game Zottza (destruction)

**Comment by Luth-RoR** [comment]
You high likely clicked on of the colored bags at the side of your inventory.

**Comment by Krazis** [comment]
This happens all the time with crafting bags, I should know, I am apothecary and cultivator. Then best thing you can do to minimize this issue is to firstly, move stacks of items into all the empty spots to find your missing items. Secondly, once found, do not use the lower 2 crafting bags. Thirdly, store as much as you can in your bank vault and in your main bag and you will not come into this issue. 
Yes it sucks but this has been a crafting issue since the beginning of time.

**Comment by Luth-RoR** [comment]
I'm a apo/culti with my RP too and never had this problem so far; maybe related only to newer accounts?

**Comment by Kaelang** [comment]
This is no longer happening as of later patches. Please re-open this issue if you are still playing and find this issue persists.
