### ISSUE TITLE
[shamman][tactic] Hurts, Don't It?

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#8012]
In tooltip 240 toughness debuff, on target only 216 . (11 points in path of gork).

**Comment by Luth-RoR** [comment]
>on target

How was this checked?

**Comment by MKorin** [comment]
Only in buffs / debuffs

**Comment by Luth-RoR** [comment]
I just tested it, it indeed only debuffs 216 thoughness. The debuff value should probably be bigger too, depending on how many mastery points have been inested into the tree (240 is the base level 40 value i guess)
Base thoughness of the NPC:

![stinkinmorf_000_crop](https://cloud.githubusercontent.com/assets/8567481/19114680/420e4d08-8b0f-11e6-8b77-31dee5f8f17d.jpg)

With debuff:

![stinkinmorf_001_crop](https://cloud.githubusercontent.com/assets/8567481/19114752/9bedcaba-8b0f-11e6-9138-c0210472a69d.jpg)

**Comment by Evildoor** [comment]
Hmm, is it a tooltip problem? If i understand correctly, debuff scales at 6 toughness per level. If this assumption is correct, then tactic should:

- debuff for 24 on my lvl 4 shammy: 4 * 6 = 24
- debuff for 150 on lvl 40 with no mastery points in Gork tree: 25 * 6 = 150
- debuff for 216 on lvl 40 with 11 points in Gork tree: (25 + 11) *  6 = 36 * 6 = 216
- debuff for 240 on lvl 40 with 15 points in Gork tree: (25 + 15) * 6 = 40 * 6 = 240
- debuff for 246, 252 and so on with renown above 80 (my memory about live agrees with these numbers)

Of course you cannot test in first two cases because you cannot get the tactic, but you can check the values in training window.
![hdi](https://cloud.githubusercontent.com/assets/11015074/20175589/9dc8f088-a754-11e6-9968-fa4e9a9a47ac.jpg)
So, this tooltip looks correct to me. Sorry, can't check tooltip in other cases myself since i don't have a lvl 40 shaman.

**Comment by dalen** [comment]
This works as intended. It debuffs 6 toughness per ability level. So 240 toughness on ability lvl 40
