### ISSUE TITLE
sc debuff apply randomly

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#8014]
sometimes when exiting from sc i get quitter debuff

**Comment by Luth-RoR** [comment]
I guess _exing_ means exiting:

_- Leaving a scenario through an exit portal or another teleportation method._

https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=17377#p188798

**Comment by Tesq** [comment]
no luth, leaving a sc after you had finish it apply randomly the debuff. not with other not correct method, re open the issue please

**Comment by Luth-RoR** [comment]
People can still post in most of the closed reports; the problem i have is: 
I can't leave every report that looks like something is wrongly reported open, to wait for an answer; the bugtracker functionality is actually pretty bad and lacks a _calendar/schedule_ feature.
It's far easier to close/re-open reports that look questionable than to leave everything open and ask every week again for some reply and/or evidence.

**Comment by Tesq** [comment]
luth, did i ever take more than few hours to answer anything? but k then i suppose.

**Comment by Luth-RoR** [comment]
It's not about you personally, but the bugtracker as a whole; with over 1700 open issues, i can't keep every open issue in my mind.

To avoid any misunderstanding, it's always a good idea to write reports as complete as possible with proper wording and a minimum of typos (this makes also report searching easier). 
But even then i could read it wrongly, as 
a) i'm a human
b) english is not my first language
Therefore i rarely lock reports (except when people abuse the bugtracker) so that the communication can still go on. The open/close button is just a switch.

**Comment by Tesq** [comment]
no worry i said in fact "k then i suppose" for these reasons.

**Comment by Tesq** [comment]
i also add:
- somethimes when you are loggin into sc and you crash/soft disconnect when you relog you also get the debuff.
-sometimes (very rare) client bug when you press to join sc and the pop menu vanish at the end of the countdown to enter you also get the debuff
