### ISSUE TITLE
Chosen aura animation spreads to other players

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#8042]
The Chosen aura animation when gained by a party member looks as if they themselves have an aura, the animation on live was that of a "aura echo" with accompanying sound effect letting you know you entered/exited the chosen aura range.

**Comment by Yellowpillow** [comment]
As far as I remember the aura effect applied to all members of the group. I had a dok that was in a premade with two choosens, and the aura effect was always on me, but the smaller size of it, as the model of dok is smaller than the model of chosen, that because it was less noticeable. Perhaps this is the reason why you do not remember the effect.

**Comment by sioding** [comment]
This was fixed long ago
