### ISSUE TITLE
WH/WE Attacking from Stealth

### ISSUE THREAD

**Issue by WAR-Tyr** [WarEmu/WarBugs#8058]
Sometimes combopoints are spend immidiately if you attack from Stealth. This happens if you using a skill from the stealth actionbar which generates two combopoints (accusations) and a consumer skill (like BAL) is bound on the same slot:

Normal Action Bar Slot 1: BAL
Stealth Action Bar Slot 1: Burn Armor

It seems that activating Burn Armor (or a stealth skill in general) doesn't trigger the gcd so BAL will get fired too.

As a side note: I'm not using NerfedButtons or anything.

**Comment by diablight** [comment]
Enfeebling strike, vehement blades, treacherous assault, fanatical zeal, sudden accusation and burn armor never had an gcd. If you use any other attack at the same time its pretty clear that it get fired too. Since youre not using nerfed buttons, just put your consumer ability to another slot in the action bar, this should help.

**Comment by Luth-RoR** [comment]
As i read it, he only uses _one_ ability from his stealth bar and _another_ ability in the same slot of his normal bar (which isn't in place at this time) is used immediately too.

**Comment by Torquemadra** [comment]
and so it would be, as the opener has no GCD
