### ISSUE TITLE
Entering a scenario while falling can cause you to fall through the map upon return

### ISSUE THREAD

**Issue by Deathborn-RoR** [WarEmu/WarBugs#8115]
Entering a scenario while falling can cause you to fall through the map and circumvent death when you return from a scenario.

I entered a scenario twice today while airborne in the Inevitable City. In one of these instances, I was about to fall to my death but I decided to accept the call to battle for a scenario in order to save myself from dying. When I returned, I continued to fall into the abyss surrounding the Inevitable City and eventually landed on some sort of invisible ground far beneath the IC.

In the second scenario, I leaped off of a ramp to jump onto another piece of land and accepted the call to a scenario while I was airborne. When I returned, I spawned ever so slightly beneath the Inevitable City and began to fall into the abyss once again until I landed on the invisible ground far below and survived.

**Comment by Ryanfawkez** [comment]
You don't die from falling into IC's depths, period. The damage calculation done during fall time is different from live, and there is no killzone implemented on the void's 'floor' yet. The fact you're set to fall after returning from a scenario is because your position is stored upon accepting the Scenario, which stopped you in mid-air in the second jump and led to a descent.
