### ISSUE TITLE
Abilities moving on hotbar after zoning into scenarios

### ISSUE THREAD

**Issue by Alteren** [WarEmu/WarBugs#818]
Abilities are moving on the hotbar after zoning into scenarios. Some hotkeys jump around, some disappear, and some are duplicated into other slots. This has occurred approximately 50% of the time I zone into a scenario.

**Comment by Evildoor** [comment]
If i understand this correctly then it was a common problem which caused lvl 1 abilities (throw axe, for example) to place themselves onto panels as if you just created a character, and this problem was fixed, so i'm closing this. However, if i'm mistaken and this is a different problem which still persists, feel free to say so and i'll reopen this issue.
