### ISSUE TITLE
Turning in Halloween Quests - Destro

### ISSUE THREAD

**Issue by trastamara** [WarEmu/WarBugs#8209]
Hey guys!

This is more of a nuisance bug more than anything else, but when I turn in 'some' of the Halloween quests in T2-destro, I am no longer able to interact with the world around me.  I can run around, but I can't talk to anyone, I can't type /camp, I can't do anything.  

To fix this, all I do is go to the desktop and force-close the game.  After waiting a minute or two, I can log back in and everything is working fine.  After logging in, the quest HAS been turned in already.

This has happened a few times now.

Hope this helps.

Justin

**Comment by Malvius** [comment]
This happened to me every time I turned in the quests where you have to collect zombie hands and skeleton bones. Same issue on Order side.
The game will actually resume working if you just wait it out (takes quite a while), at least for me it did. It behaves like the server does not communicate with my client. No interaction possible, NPCs and players disappear after a while. Then everything is back.
The bigger problem (imo) is that after everything resumes I still have all the hands and bones in my inventory (I think it used to work before they were made uncommon rarity in order to roll for them in group, doesn't any more since then) but the quest is gone and I receive neither the quest xp nor the event currency for it.
