### ISSUE TITLE
Dropped supplies twice!

### ISSUE THREAD

**Issue by gke96** [WarEmu/WarBugs#8236]
Its as it says check the screenshots pls. I carried supply to base i dropped it but supply stil remained on me after first drop. then did it again..

![horsewhisperer_033](https://cloud.githubusercontent.com/assets/11146551/19877085/a85d7e46-9fe4-11e6-915f-67cf098e64e2.jpg)
![horsewhisperer_032](https://cloud.githubusercontent.com/assets/11146551/19877086/aa4bcc6c-9fe4-11e6-896d-ee1369e03228.jpg)

**Comment by Luth-RoR** [comment]
Maybe related to https://github.com/WarEmu/WarBugs/issues/8213

**Comment by Tholkienn** [comment]
Think relate on #8235

**Comment by Blaqwar** [comment]
I think being able to drop supplies off unlimited amount of times has something to do with capturing the enemy supplies after they've been picked up. 

I killed a Sorc transporting the supplies in Barak Varr today, I picked them up, ran to the keep and was able to return it unlimited times. (Unfortunately I did it three times, second one was to verify that it indeed is unlimited returns and the third to take some screenshots for the bug report since I didn't think of it sooner, sorry destro!).

You can see that I'm returning resource after I've already gotten a reward for returning resource.

![enses_001](https://cloud.githubusercontent.com/assets/5108812/19898268/a4cc4bf0-a05b-11e6-9c07-bc8d8ddcf468.jpg)

**Comment by sioding** [comment]
Since you can´t carry any resources anymore i close this issue now. Thanks for the report.
