### ISSUE TITLE
Broken distribution of bags in T1

### ISSUE THREAD

**Issue by RogovArtem** [WarEmu/WarBugs#8311]
The longer you are in an open quest, than the award biger (with the siege was about the same).
https://youtu.be/JlGpCvR85h8?t=1m4s

**Comment by Soulwhisper** [comment]
Both times you had the lowest contribution which is correct because you didnt participate at all.
Roll on the other hand is random.Where is the bug?

**Comment by Luth-RoR** [comment]
I think the impact of the random component is still very big and mythic-like (really not sure bit iirc 1/3 contribution and 2/3 randomness).

**Comment by Luth-RoR** [comment]
As it works like on the mythic server, it's indeed no bug; but feel free to create a suggestion to change that here: https://www.returnofreckoning.com/forum/viewforum.php?f=15

**Comment by Luth-RoR** [comment]
Ok, as it seems the large impact of the random factor is intended, so that AOE classes don't get the biggest contribution.

**Comment by Luth-RoR** [comment]
Reopening as the contribution should be only 1 if one stands only around in the area; though this seems to be a T1 issue only.

**Comment by RogovArtem** [comment]
> Both times you had the lowest contribution which is correct because you didnt participate at all.
Roll on the other hand is random.Where is the bug?

it happens all the time.

**Comment by RogovArtem** [comment]
i understand, its not bug,but...what is it? One hit=top 1(see chat).
![image](https://cloud.githubusercontent.com/assets/12447382/20242478/5d4175b0-a940-11e6-8a46-2a8a300d7f56.png)

**Comment by Blaqwar** [comment]
Since there were only 5 people participating in total the last few on contribution still got some added values for contribution (something like 200-250, can't remember the exact number). The person must have then rolled over 900 with the other top contributor rolling low (lower than 500). It sucks but it happens and this is how the PQ system works. A lucky person who didn't contribute much will win over an unlucky top contributor.
