### ISSUE TITLE
Potential bug related to WB / interacting with vendors = Disconnection

### ISSUE THREAD

**Issue by Tyrul** [WarEmu/WarBugs#8321]
I've been experiencing frequent disconnects when being in a WB and talking to a vendor such as the Emblem Quartermaster's in IC , Once i leave the WB however it does not occur and it is not only these vendors but any Quartermaster i've interacted with it has been happening on all of my characters aswell.

**Comment by Luth-RoR** [comment]
I have sometimes a similar issue, but without being in a warband; so far i only encountered it when on my knight and as far as i can tell only at some days, so that it could happen on certain chars only.
For me it happend usually when i had the mouse arrow over items in the inventory, mails attachements or vendors.
