### ISSUE TITLE
scenarios party frame disapearing

### ISSUE THREAD

**Issue by Tellmar** [WarEmu/WarBugs#8376]
Sometimes when i join scenario there is no partyframes and party management ui. /reloadui helps but it freeze game client so hard so i get DC and "quitter". 2nd part probably coz my week hardware, but if 1st part will be fixed somehow it will be good. Seen topic #992 but it closed and fixed. My isn't.

**Comment by Natherul** [comment]
This might be related to: https://github.com/WarEmu/WarBugs/issues/8059 ?

**Comment by Luth-RoR** [comment]
I think this one is different; i had this bug fairly often a few months ago and iirc it was because of scenario groups not working correctly. 
The quitter is just because he disconnected from the scenario, but not because the server doesn't realize he is actually in the scenario. In https://github.com/WarEmu/WarBugs/issues/8059 /rel doesn't help to temp fix the problem.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
