### ISSUE TITLE
Being able to use "Requires Disrupt" ability after disrupting (parrying) Wrath of Hoeth.

### ISSUE THREAD

**Issue by Blaqwar** [WarEmu/WarBugs#8377]
As far as I'm aware Wrath of Hoeth and Gusting Wind (Swordmaster) melee abilities get checked against parry/block for defence, as that is the defense effective against them. If they do get blocked/parried the client incorrectly displays Disrupt, which I assumed was a bug in the vein of WH executions displaying Dodge when they get Parried/Blocked.

All fine and well but should a Mara be able to use Mutated Energy after parrying one of your attacks (which would show up as disrupt in the combat log).

![bug](https://cloud.githubusercontent.com/assets/5108812/20450736/0d5f3318-adf3-11e6-857f-7de5834aea99.jpg)

(The only present players were me, a Mara and a DoK, he couldn't not have been disrupting someone else's attack).

**Comment by Luth-RoR** [comment]
My guess is that the client (combat log) doesn't know that it wasn't a disrupt and activates the ability (also handled by the client). So a temporary solution could be that the server blocks it even if it's activated by the client, but that would likely lead to other reports of mara players because they would think the ability is bugged (activates but can't be used). 
Though if it is true what i wrote, the current handling gives the class even more utility.
