### ISSUE TITLE
Cast interrupting when stopping to cast

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#843]
If you start casting an ability, strafe a step breaking the cast and try to cast something again, then the next ability cast is interrupted immediately on start. 

Letting the first ability build up to about 80% before moving to cancel results in the next ability being cast normally.

**Comment by Silentguard** [comment]
Its should not be a bug. When you start casting anything client send ability use to server and server set you to 1.5 sec GCD so if you interrupt ability while GCD duration you still not be able to use any ability. Otherwise any cast interrupted over 1.5 sec do not block you abilities by obvious reason.

**Comment by ozarmidrashim** [comment]
This is a visual issue. The cancellation packet we send incorrectly resets the GCD, but it is correctly triggered on the server.

**Comment by Evildoor** [comment]
Tested, seems to be fixed.
