### ISSUE TITLE
ToK 'Nina'

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8439]
Kill collector in Trovolek, does not provide unlock
![image](https://cloud.githubusercontent.com/assets/23622177/20516180/86d589be-b095-11e6-943d-4eb4d9d3e5a6.png)
(Side note, I know it must suck to tag all my reports. Hope they'll be useful in the future though! <3)

**Comment by Luth-RoR** [comment]
>(Side note, I know it must suck to tag all my reports. Hope they'll be useful in the future though! <3)

It's ok, thanks for reporting. 😃 
I just talked with the DB devs; atm proximity unlocks are issues that can't be fixed yet because there is additional code from core devs needed. I will close the reports and tag them with a milestone, so that DB devs can view all of them in one place and reopen them later once they can be solved.

**Comment by Lheana** [comment]
This is not a proximity unlock : need to talk to the kill collector Nina to provide his Noteworthy Persons unlock. So think it's fixable now :)
