### ISSUE TITLE
[Combat Mechanic] Armor not mitigating damage with the new patch

### ISSUE THREAD

**Issue by Karast** [WarEmu/WarBugs#8529]
As the title says in the new patch today armor is not working. It offers no mitigation for direct damage abilities and autoattack. It still seems to work for dots however. Toughness mitigation still works however.

**Comment by Pxl555** [comment]
I can confirm what Karast said , and i'd like to add that it also seems to affect resistances.

**Comment by Blaqwar** [comment]
The small difference in damage I took is due to the toughness I lost from unequipping the armor.

![armorbug](https://cloud.githubusercontent.com/assets/5108812/20860360/9d27b19e-b976-11e6-96c9-5e4dae38f6cc.png)
![armorbug1](https://cloud.githubusercontent.com/assets/5108812/20860361/a0661e4a-b976-11e6-91b4-e06b1dee56a2.png)

**Comment by SunsetCNTK** [comment]
![starlight_000 croped](https://cloud.githubusercontent.com/assets/16652212/20860449/dd9e9876-b978-11e6-9e80-4cf7004dcc3f.jpg)
![starlight_001 croped](https://cloud.githubusercontent.com/assets/16652212/20860450/df5f44da-b978-11e6-8b28-194752822816.jpg)

No difference between having or not having Focused offence slotted [aka 1k armor diff, no other stats affected]

**Comment by cimator** [comment]
Its not only armor btw, resists also dont mitigate but somehow any dot, physical or not, gets mitigated.

**Comment by ozarmidrashim** [comment]
fixed.
