### ISSUE TITLE
The proof is in the paws - Quest

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8626]
This is under Screaming Cat tavern(basement) but portal doesnt work.
I dont know where exactly it should port you.
There is no questmarker either.

**Comment by Luth-RoR** [comment]
The portal is one of the entries to the skaven tunnels dungeon to get the boots of the sentinel set. http://warhammeronline.wikia.com/wiki/Warpblade_Tunnels
The quest probably leads the player to the dungeon entry.

Closing this for the moment, because it can't be fixed until the dungeon tool is ready.
