### ISSUE TITLE
[T1] people able to snipe inside wc

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#8680]
![antenisca_017](https://cloud.githubusercontent.com/assets/17765890/21427827/155f69c4-c857-11e6-8d4d-6430271b4e80.jpg)
after recent improvements the Eng marked on top right as able to snipe the mara operating the cannon located inside destro's wc

**Comment by Luth-RoR** [comment]
Both players were flagged as in combat and the Engineer killed the enemy with his increased range buff from his gun turret (same as a Magus).

**Comment by Luth-RoR** [comment]
Reopening this as maybe DB devs will place a guard there.

**Comment by Evildoor** [comment]
Looks like #5126 to me.

**Comment by Luth-RoR** [comment]
Yes, DB devs have to decide, if they want to/can fix it or close it as intended/not important.

**Comment by Smokeras** [comment]
If you are using a cannon then you rvr flagged.if you rvr flagged that means that you want to fight players in pvp.The guys that try to rank up renown by hiding behind cannons and expect that they will shot people  from distance without the other person counter him is exploit.There is a guard there that do his job if you get close.If you want to safe logout etc you dont want to be close to cannon.The max distance of range abilitys in both destro and orders in t1 are 140ft.There players that abuse wc cannons especialy artillery because they thing that the other side can't attack them so they stay for hours there pressing 1 button.If these players want this high reward, there must be a risk of obtain it.Solutions exist already from destro side that they try to lure low players in the guards above just to emote them with lol and trash talk them.This game has rvr mechanics you want order or destro leave the spot just team up and go from back road to kill them.Also you can use the further artillery to cover the camping spot.Solutions exists already i mention 2 of them.Again if you want to logout safe just go further to rally master dont stay close to outside guards of the wc.The order can still hit you if they manageto push close to your rvr ramp.

**Comment by zak68** [comment]
if you say that order's artilliers can be attacked too i'll be fine with that.

**Comment by Luth-RoR** [comment]
Any discussion have to take place on the forum; the bugtracker is only for bugs.

**Comment by Smokeras** [comment]
Zak68 yes 2 st cannons and artilerry on order side can be shot down also and the players that are using them are also killable.

**Comment by Torquemadra** [comment]
not important, if players want to use siege they are part of the fight
