### ISSUE TITLE
WL pet ability Shred

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#887]
The effect of ability Shred (War lion Armor Debuff) doesn't match to value on tooltip.

**Comment by Zealote** [comment]
Fairly ancient report now but this only seems to be the case in PvP; I guess due to Bolster?

In pic below, top line shows the ability tooltip, and the bottom shows the debuff icon tooltip thingy: 

![wl shred](https://cloud.githubusercontent.com/assets/10598420/17476617/ceb3d5d2-5d58-11e6-851c-417a0bcdfb9b.png)

**Comment by Nfkillz** [comment]
now works correct
