### ISSUE TITLE
ToK unlock "Who Let That Thing Out?"

### ISSUE THREAD

**Issue by Xanics** [WarEmu/WarBugs#8939]
Reffering to issue: ToK unlock "Who Let That Thing Out?" [#8072](https://github.com/WarEmu/WarBugs/issues/8072)

Killed the Hysra in Caledor, but did not grant the Titel: "Hydra Tamer", altough it says this has been fixed.

![image](https://cloud.githubusercontent.com/assets/14800906/22069071/78ecc81a-dd97-11e6-99ad-b7979e8e10fd.png)

**Comment by Ryanfawkez** [comment]
Surely love how there's a Griffon named Deathclaw and a Hydra called Deathclaw Hydra. Fixing properly now.

**Comment by Xanics** [comment]
Haha :) Thanks Ryan

**Comment by Blaqwar** [comment]
While on the subject of Hydra's since this doesn't warrant a separate report, the Hydra's that spawn in the second stage of the Order PQ in Eataine "The Tower of Lysean" have a typo in their name. They're called "Hyra" instead of "Hydra".

So minor that I wouldn't even mention it if you weren't fixing Hydra's already. :P

**Comment by Ryanfawkez** [comment]
That'll be fixed as well for the next patch. The first of many typos to be fixed...
