### ISSUE TITLE
Taking The Inevitable City Quest

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#8973]
There is a quest available from General Albrecht who is located in Karl Franz's throne room. The quest is to go to the Inevitable city and win. similar to a "take this keep" type quest. not sure if this is suppose to happen but upon taking the quest, you can immediately hand it back in with out doing the requirements.
any questions IGN: Sybella. Forum name: carmine3161.

**Comment by Luth-RoR** [comment]
What's he name of the quest?

**Comment by carmine3161** [comment]
Capture The Enemy Lair!

**Comment by carmine3161** [comment]
I got my friend to try and recreate this, but it didnt work.

**Comment by carmine3161** [comment]
In order to hand in the quest you just right click on General Albrecht and it somehow counts as taking the Inevitable City?

**Comment by Blaqwar** [comment]
I've noticed a few other quests behave in the same way in the throne room:

Strategic Control (immediately completed upon talking to Karl Franz)
Not Forgotten (immediately completed upon talking to General Albrecht)

These 3 actually have "Speak to NPC 0/1" as objectives eventhough the quest text clearly directs you to capturing a keep in a T4 zone and getting a scrap from the banner (I'm guessing that's why they were changed?):

Finding the Strength (immediately completed upon talking to Phoenix King Finubar)
Constant Vigilance (immediately completed upon talking to Phoenix King Finubar)
Honor's Guard (immediately completed upon talking to Phoenix King Finubar)
Clean It Out (immediately completed upon talking to High King Thorgrim Grudgebearer)
Green Menace (immediately completed upon talking to High King Thorgrim Grudgebearer)
To Arms (immediately completed upon talking to High King Thorgrim Grudgebearer)

**Comment by Ryanfawkez** [comment]
Will disable these quests unless their actual objectives can be set.
