### ISSUE TITLE
Cannot join scenario while in combat

### ISSUE THREAD

**Issue by SparkyTheOld** [WarEmu/WarBugs#9044]
I wasn't able to join scenario because I was "in combat" while not fighting anything.

**Comment by Razielhell** [comment]
type .u

**Comment by Tyramissoux** [comment]
Very old, known bug but nobody knows what causes it.

**Comment by SparkyTheOld** [comment]
Tried .u, didn't help.

**Comment by Luth-RoR** [comment]
>Very old, known bug but nobody knows what causes it.

Iirc according to devs, the bug existed on WAR too, but Londo found out that mythic had just coded an automatic workaround, which was the same as the .u or .unlock selfpunt instead of fixing the bug. Maybe with client access it can be really fixed.

Nevertheless getting out of combat while stuck in combat _for no reason_ by typing .u or .unlock into the chat window works for me; maye try the /s chatinstead of a specific one. Closing.
