### ISSUE TITLE
Time Played in ToK is highly influxuated

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#9096]
This is my only character with this issue
![lilskittlez_000](https://cloud.githubusercontent.com/assets/19709971/22690109/eea30fb4-ece8-11e6-91a8-dffd9820dbcf.jpg)

**Comment by Afterlife92** [comment]
This happens when you get a random client crash during loading character screen or disconnect and from that your quest log wipes (all your quests reset and you can do them again). I have been told that this bug is releated to client control and should be fixed with client patcher. If you get the quests wipe you can wait for server restart to get them back. It's releated also to #2001 

Character without the bug

![welch_000](https://user-images.githubusercontent.com/18471440/36640882-7166ee4a-1a27-11e8-9704-c3b545a844ff.jpg)

Character with the bug

![welchz_000](https://user-images.githubusercontent.com/18471440/36640883-7186c1de-1a27-11e8-8127-01cdc3a7cf7d.jpg)
