### ISSUE TITLE
the Fall of Konrad Schultz - Order Troll country quest

### ISSUE THREAD

**Issue by Krazis** [WarEmu/WarBugs#910]
Konrad does not trigger to attack-able, thus not able to be killed, (invalid target) so you are unable to complete the quest due to not being able to read the notes he "drops".

**Comment by Evildoor** [comment]
According to @ozarmidrashim in #1951: "This quest shouldn't exist. Konrad Schultz, in the original game, was a WH who appeared in every tier, offering quests along a storyline. His appearance (possessed / shaking) should be used in Tier 4, at the end, when he is killed - otherwise he appears as a normal WH in Sentinel armor."

**Comment by erkislev** [comment]
Found TWO Konrad Schultz copies in one location. It is not a bug (so restart didn't help), it is a real copy. 

Location: Entrance to Empire Chapter 13
Location of first copy: 61080, 5549
Location of second copy: 61342, 7646

Screenshots available. Another copy can be seen from the position of first and vice versa.
![konrad_schultz_2](https://cloud.githubusercontent.com/assets/16850861/12529807/f9d548e0-c1d6-11e5-8e4b-6264c0df72b3.jpg)
![konrad_schultz_1](https://cloud.githubusercontent.com/assets/16850861/12529808/f9d583a0-c1d6-11e5-9e6e-94ba0c83a074.jpg)

**Comment by Gakvar** [comment]
Is it possible to spawn a hostile version of Konrad Schultz so we can kill him and complete the quest?

**Comment by lennip** [comment]
I recently found this page about the quest "The Fall of Konrad Schultz", it's an old blog by some japanese player who used to log all the info of the quests he did, so it has some useful info about original WAR quests:
[http://marrek.blog113.fc2.com/blog-entry-967.html](http://marrek.blog113.fc2.com/blog-entry-967.html). 

Currently in RoR, Konrad Schultz gives this quest at several spots along the Empire storyline : in chapt 6 in Troll Country, chapt 13 in Talabecland, and somewhere in Chaos Wastes (not sure where exactly, my empire char hasn't reached that part yet). According to Evildoor's comment and what the quest dialog says, it seems that Konrad should indeed appear in all tiers, but he should only give this quest in Tier 4 (Chaos Wastes), and then become killable so that it can be completed. IMHO that would make much more sense that way...
