### ISSUE TITLE
Wont get Set Bonus

### ISSUE THREAD

**Issue by SweNinja** [WarEmu/WarBugs#9172]
Hi i just got full Mercenary set but it says i am missing the Boots... As seen on Picture.... 

![swe_025](https://cloud.githubusercontent.com/assets/25357451/23091488/8c82b3de-f5b7-11e6-92ca-3c039dcb80fb.jpg)

get back to me as soon as possible... thanks
Swe Ninja BG 40
NinjaSwe  WE 40

**Comment by Luth-RoR** [comment]
High likely because of a namechange for the knight boots from "dark greaves" to "greaves"; on the dev server "greaves" are renamed to "sabatons" and the other sets have the same issue.
It's only a visual problem as .getstats confirms that the set bonus works on the server, though maybe it prevents tome title unlocks for completing a set.
