### ISSUE TITLE
Black orc right in da jibblies

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#922]
If target doesn't have punt/root CC immunity skill should bump players in the air 1-2ft and interrupt any skills being cast. Skill didn't give any CC immunity.

Can see the bump at around 1.35 mins in here   https://www.youtube.com/watch?v=1854xeSxEeA

**Comment by ozarmidrashim** [comment]
Since this has been brought up recently - the skill used a different mechanism than F_KNOCKBACK to accomplish this effect, but we don't know what it was. Sorry.

**Comment by Tesq** [comment]
kobs have and interrupt too differently by the taunt maybe that coudl help?, and instead of jump it could be apply a 1 sec stun eff with no immunity related.
The result sould be the same.

**Comment by MadMask** [comment]
A workaround like Tesq suggested would be nice, Black Orcs don't have the buff planned on the last PTS, it would be nice to not disadvantage them too much.

**Comment by Evildoor** [comment]
I think that at least cast interruption can be added for now.
1 sec stun - i'm not sure that small knockup from RidJ affected instant skills in any way on live, only movement and cast, while stun will definitely affect them.

**Comment by Tesq** [comment]
If the skill on live interrupt and maybe gave to target a global coldow the eff would be the same , while in air you cannot start new cast but only finish those sltedu started, So apply 1 sec stun would be k

**Comment by Evildoor** [comment]
I still vote against stun. BO/SM need some love, but not, IMO, a stun which gives no immunity on 10 sec cd. One of the reasons why i prefer WAR over any other MMO is a reasonable CC system which prevents the game from turning into stunlockfest while keeping CC important, reliable and satisfying to use.

**Comment by Tesq** [comment]
1 sec is a resonable interrupt, could anyway ask to ppl how that worked, anyway it wasn't so much gamebreaking , it would have been seen in game during live orherwise.
By the way not like is a balance thread, if there is the  chance to make it the more near to lave that should be take in consideration.

**Comment by Silvertusk** [comment]
Status? plans of a workaround like tesq's proposal or just make it a normal interrupt?

**Comment by Gobtar** [comment]
I was going to post a bug but did a search and found this, RitJ was mostly used as an interrupt, though the stalling effect was nice against kiters. I would prefer that the ability to interrupt be added over a stun, if I recall correctly the KB upwards was similar to the SHs Kaboom self KB up, except not as far movement on the Z access.

**Comment by Evildoor** [comment]
By the way... @Tesq, why have you suggested 1 sec stun instead of 1 sec root? RidJ was interrupting and knocking up, this knock up had no effect on your abilities, it was only preventing you from running - pretty much like small root.
Anyway, stun or root or nothing or whatever is a balance discussion about how to apply a temporary fix while live behavior is unavailable - but we all agree that skill should interrupt, so maybe it is time to implement it? @ozarmidrashim ?

**Comment by bozzax** [comment]
Sad to see this one not working as it was one of the better BO tools. Couldn't the Choppa GTTC pull be used with a really short pull until a better solution is found?

**Comment by Tesq** [comment]
Suggested 1 sec stun as with root you can cast, but maybe interrupt x 1 sec root could work better

**Comment by Tesq** [comment]
But if i remember correctly the knock up was short in time like between 0.5- 1 sec. Due the time server need to apply/remove  stag it could be more similar with stag rather than root. With rior tou can also cast which make it more a root + interrupt than i terrupt + being unable to use skill which was the knock up eff . Maybe if sone video coul be found and duretion be check. Instead root or stag you could apply root,silence disarm  to reproducd the  eff better. I just giving sone random idea nothing well thinked about.

**Comment by Tesq** [comment]
Sy for error im on phone and cannot corret it

**Comment by Tesq** [comment]
Maybe what boxx said about pull could work even better.... apply mara pull, make it parry able* range 5feet + interrupt; more or less the visual experience  should be the same.

**Comment by Tesq** [comment]
Anyway seems the knock up is something like 0.5 sec. So you culd just apply : interrupt + root + global coldown refresh .
This way target would not move and could'not cast anything in 0,5 due to global cd ( unbreakable root)

**Comment by Tesq** [comment]
This last solution seema better than my old one

**Comment by Gobtar** [comment]
Any news on an Interrupt band-aid solution?
