### ISSUE TITLE
Disconnet /DC dont allow you to see the bag roll [visual]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#9293]
Disconnect ( due to internet issue) before the bag roll make you loose the contribution for the roll (and no access to it but you do not loose the contribution for the renown rewarded for lock the zone. Don't know if it's intended or not.

**Comment by Daniellita** [comment]
I disconnected yesterday in Dragonwake and still won a gold bag, which means this issue is either inconsistent, or non-existent. I didn't even manage to log back in before the zone locked (Crashed before lock; didn't come back online before zone was over). Would be interesting if someone is in a zone from start to end, within a party that has one of the highest amount of kills and can actually confirm losing out on a roll because of a disconnect.

**Comment by Tesq** [comment]
Well i had 7 k renown on max of 10k for the lock so the kill count of my group wasn't low. Tough i instead relogged before the lock. It could also be visual to just not show the bags roll mini interface or part visual and part true bug.

**Comment by Tesq** [comment]
i have an update: i was able to win a bag even if the roll didn't show and other as well seems visual only, the strange thing is it also happen if the client is closed and re open anew and not only after a soft disconnection.

**Comment by Luth-RoR** [comment]
Closing then; UI issues with PQs are already known.
