### ISSUE TITLE
[White Lion] Lion pet

### ISSUE THREAD

**Issue by Tyrean** [WarEmu/WarBugs#934]
More work to do on lion pet :

When i use charge the lion dont charge whit me
When we running the lion need to be near me on the right not behind so far
Sometimes the lion disappear for no reason 
When you leave TC and come OST on rvr area the lion leave and disappear

It's a really disadvantage for us because whitout our lion close to us on fight our dps is really decreased and we are allways waiting our pet to begin a fight .

Please try to fix the lion ! Thanks

**Comment by MrAngel0** [comment]
My two cents. I remember there was at least two main stages of movement:

1. If pet is close enough to the player and "following" (not in action), the game client starts calculation of position of the pet. Basically pet attached to the player's position and server should not make extra calculation;
2. Once pet got's into action (attack, chasing, etc). server starts sending commands - enemy target position and etc.

I believe at this moment (and in order to follow the player) server regularly sends a new position of the player to the pet. Not really effective as it costs extra network traffic - a possible lag issue?

**Comment by Tyrean** [comment]
Woooaaa it's really complicated but in fight whit addon loyal pet the pet is sometime good but it's really for following its real problem !

**Comment by ozarmidrashim** [comment]
All of this has been posted already. Please don't make duplicate reports.
