### ISSUE TITLE
Will of the Warboss - Missing Moonfang Stickpointa

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#9352]
The stickpointa's required for Will of the Warboss progression are missing again. Server reset didn't fix this. The stickpointa's are the ranged variety. They are usually scattered throughout the camp but none exist at the moment.

Location: Greenskin Chapter 11 Badlands - PQ: Revoltin' Gobbos

**Comment by wargrimnir** [comment]
These may be in the second stage of the PQ

**Comment by Zoggof** [comment]
Going from previous records/bug reports, stage 1 of the PQ is kill 100 Stickpointa Goblins. I tried killing the other sort (Moonfang Headhitta) but that didn't do anything.

The PQ itself doesn't appear either as being active (no PQ title popup when you enter the PQ area). You don't receive INF either for killing any of the current mobs around the PQ.

**Comment by Torquemadra** [comment]
The issue is this

The mobs are tied to the PQ, someone has to enter into the PQ area to start the pq off. However currently it seems all badlands for destro are borked which prevents them from starting and the associated mobs from spawning.

A workaround until it is fixed is to take an order character to that PQ it will start the the cycle and the mobs will spawn

**Comment by Zoggof** [comment]
Thanks, will try the order character workaround in the meantime.

**Comment by wargrimnir** [comment]
Spawned a small cabal of these well outside the PQ area near the canyon.
![image](https://cloud.githubusercontent.com/assets/12942408/24574923/0457a894-1668-11e7-8877-1ff49398109b.png)
