### ISSUE TITLE
Dance after knock down

### ISSUE THREAD

**Issue by jebca** [WarEmu/WarBugs#9360]
Hello
After WH knock down, prey start "dance", and positioning face to face. Hi now Start parry block ect.
After KD i think hi should not use any action

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/2053

**Comment by jebca** [comment]
Dont link me old topic only repair this Bug.

**Comment by Luth-RoR** [comment]
1. You don't tell the developers what to fix and what not.
2. If you kindly read the linked report:
https://github.com/WarEmu/WarBugs/issues/2053#issuecomment-190161403
and 
https://github.com/WarEmu/WarBugs/issues/2053#issuecomment-220529787
Which means that player models only turn around on the client, not the server.
Due to the messy server-client packet structure, which was apropos created by **mythic entertainment**, it is atm unknown how to fix this bug. 
3. Thanks in advance for using the bugtracker search function next time.
