### ISSUE TITLE
Lileath's Arrow with Expert Skirmisher

### ISSUE THREAD

**Issue by k0ut4l1** [WarEmu/WarBugs#9409]
Looks like the "Lileath's Arrow" skill gets the defensive target for the "Expert Skirmisher" tactic to work instead of the offensive one. Skills that require target work fine. Don't know if "Shoot Thru Ya" has the same issue.

https://youtu.be/jaZpzGuXv4Y

**Comment by Ghatisgob** [comment]
there is some strange things that happens in duel. Try to test it again with a destru. 
We can try it together : whisp Ghatisgob

**Comment by k0ut4l1** [comment]
i tested it on rvr too, i can post video if i have too.

**Comment by cimator** [comment]
iirc its intentional since the ability is self cast and doesnt require any target, and it will still reduce it by %50 even if you have a defensive target and its away, the 2s cast in the video is visual bug, you can spam the button as if its 1sec cast to test if you like. And its the same with shoot thru ya, summon squig, summon daemons/turret for magus/engi and rift/magnet of engi.

**Comment by Luth-RoR** [comment]
It is high likely not intentional that abilities get a reduced cast time from afar (more than 20 feet away) with that tactic slotted.

**Comment by Luth-RoR** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/9320
