### ISSUE TITLE
Influence Reward Bug

### ISSUE THREAD

**Issue by ka3vas** [WarEmu/WarBugs#9438]
Hello !

I was participating in fights in Dragonwake (I was there for the whole duration - 4h - fighting, caping BO and so on) and after the zone locked I didnt get the right amount of influence in my book/bar. The game showd that I got +5618 but in my book it only added about +449. I noted it because just before the zonelock I got my first zone reward (the belt), which is 17970. So I should end with about 23000 infuence points in my book, but its only 18000.

![blekitna_017](https://cloud.githubusercontent.com/assets/25376843/24681949/a0a296e6-1997-11e7-8c88-cbc38717da2c.jpg)

I tryed reloading game and changin zones it still didnt updatet
![blekitna_018](https://cloud.githubusercontent.com/assets/25376843/24681971/be4b066a-1997-11e7-9ce7-9a665117d714.jpg)

RR and bag roll worked fine (got my gold bag ^^), im missing only my influence.

**Comment by Sciezka** [comment]
One more thing that i should add. In that time there was 1 full warband game crash and I also DC once, but after relog I was at the same place I DCd.

**Comment by wargrimnir** [comment]
When a new zone is started, check your influence. Screenshot.
After the zone flip notification comes along, check your influence. Compare to previous screenshot. I wonder if that would make up for the discrepancy and there's something odd about the flip ticks being reported.

Or there might just be something attributing to the wrong faction. Did you get a big tick for Dark Elf RvR?

**Comment by Sciezka** [comment]
You could check at what time I got Wraith's Girdment, thats the point I hit the 17970 influence points (bought it right away). Destro was at our warcamp at that point, so I couldnt do more than 100 infuence at thoes destro/order wave pushes. So after "zone flip" I got smthing like 300 infuence. 

So if You are able to get the timing when I got that item you can eassily see how much IP I got after the flip (thats why I started this post, because it seems very wrong for me). This would give You a clear point of my influence BEFORE zone lock and AFTER.

And is 5k IP to much for someone that was in zone from the start till the end? 4 hours of active play, not afk in warcamp after fliping 2 BO. I got multi BO and supplys - smuggled even some in last second to save a 5% door. Not to add killing destro solo and in group, wiping whole WB and ofcourse dying a fair amount in the battles. "Been there, done it all." And if its 300 IP "reward" in the end.... Then yeah.

And to the last thing I got similar IP rewards on my RP in the same zone, so dunno if its about race.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9631

>it was message about 7200 inf and 29k renown. got the rp but not influence
![argusha_004](https://cloud.githubusercontent.com/assets/28632635/25964205/bbfbfefc-368c-11e7-970b-132e120cfccb.jpg)

**Comment by geolyk** [comment]
today i got the lock on Praag .5min before the lock i took the first reward, at lock i got 5k reward and no added.i relog also
![gouga_006](https://cloud.githubusercontent.com/assets/26933999/26429732/4e721f64-40f1-11e7-8041-d42351679b8a.jpg)
![gouga_007](https://cloud.githubusercontent.com/assets/26933999/26429734/5141480a-40f1-11e7-8b8e-d3f8f47baf64.jpg)

**Comment by dbddhkpuka** [comment]
Hi,
I experienced the following: When participating in one zone and switching to another one BEFORE the first zone locks, I got the influence reward for the zone i switched to (the one I am in when the lock occurs), not the one i came from.
I can reproduce this at least in T1, didn't try in T2+ already, but assume it's the same.
cya

**Comment by gszczepanski** [comment]
Elf t1: Playing Order I got first influence reward for 1320 influence points. After that I entered battlefield, fought, got killed. I respawned and immediately (while being in camp) zone locked for Destro. Message said i got about 800 influence points. I checked and saw i had 1423 T1 influence - seems I got only about 100 points or nothing (these 100 may be for figting in zone before last death).
