### ISSUE TITLE
Caledor LOCKREWARD 9. April 2017

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#9448]
Hey,

Caledor locked today 9. April 2017 at around 17:00.
Contributionwindow showed me on 1st place with +750, then i rolled the lovely dices and rolled a number higher than 500.
At that point i was certain to have a golden Bag, since the next few places rolled lower than me, but hey suddenly i was 2nd place and my final roll was 1180, something is not correct there.
a contribution of +750 and a roll over 500 dsnt give 1180 but more like 1250 and that was around the numbers the one that won goldbag got, goldbag went to player dirtyrag that i wasnt able to reach over PM.

Can you please explain those things?

Thank you very much.

Greets

**Comment by Luth-RoR** [comment]
What is going on on the server is not always shown on the client, as the client can't be modified yet and the RoR server code is sometimes different from the mythic server code (intendedly or because there is absolutely no knowledge about mythics server code). 
Furthermore questions go to the support subforum.
