### ISSUE TITLE
pet proc damage

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#9467]
![proc bug](https://cloud.githubusercontent.com/assets/8299081/25044375/4035d9ba-211e-11e7-85f7-8c400cf734ab.png)

Shining blade should proc just once instead of multiple times, bug happens only from pet attacks not players.

**Comment by Pxl555** [comment]
This is not a pet related issue. It is related to the interaction of Shining Blade and its Chosen Mirror ,Tooth of Tzeentch, towards multi hit abilities that land in the same frame.

To demonstrate , i have used the other few multihit abilities i know off, Rend Wind from magus (3hits 1 cast),Finisher's from WE  in this case puncture to demonstrate (2hits 1 cast) , Squig Herder Ability Git Em (2 hits for both the user and the pet for 1 cast) and WL coordinated Strike (2 hits for both the user and the pet for 1 cast) - the last 2 show what happens when both pet and user cast a multi hit ability.The Particular Ability in Morf's screenshot Fang and Claw is a multihit ability (2 hits 1 cast) that works in the same way as WE puncture and the pet itsself casts it. 

Relevant Screenshots:
![proc s1](https://cloud.githubusercontent.com/assets/17297910/25687995/3f3191be-307b-11e7-9c4c-0b67347575ff.png)
![proc s3](https://cloud.githubusercontent.com/assets/17297910/25687997/42925b22-307b-11e7-894b-0c900447519e.png)
![proc s2](https://cloud.githubusercontent.com/assets/17297910/25687996/40a4c7b4-307b-11e7-8a55-6268acd08c84.png)
![proc s4](https://cloud.githubusercontent.com/assets/17297910/25687999/43f4efac-307b-11e7-9bb2-b5b71a2308a0.png)


I tried other proc abilities such as Shaman 'Ere we go and WL pack assault , and i could not get them to multihit with abilities above their intended amount of times. As such i presume it is an issue entirely related to Shining Blade (Kotbs) and Tooth of Tzeentch (Chosen)

**Comment by Luth-RoR** [comment]
Thanks; maybe an internal cooldown would help here.

**Comment by Torquemadra** [comment]
fixed
