### ISSUE TITLE
Disrupt Rate not being calculated correctly for DoTs.

### ISSUE THREAD

**Issue by Daniellita** [WarEmu/WarBugs#9522]
It seems like intelligence isn't getting correctly calculated into the disrupt formula when using DoT abilities. Disrupt rate on DoTs is much higher than it should be, given intelligence and willpower values and significantly higher than on direct damage abilities.

BW and AM in same spec hitting my RP in same spec with DoTs and DD abilities: 

http://imgur.com/a/WAEDF

**Comment by Torquemadra** [comment]
you have a selection of abilities of such low counts as to be worthless, we have no idea what you were facing be is squishies for dd or tanks for dots.

**Comment by Zumos** [comment]
"we have no idea what you were facing be is squishies for dd or tanks for dots."

"BW and AM in same spec hitting my RP in same spec with DoTs and DD abilities:"

Did you even read?

And 32 fireballs with 22% disrupt versus 37 ignites with 50% disrupt rate has a veeery low chance of not representing a difference between the abilities.

**Comment by wargrimnir** [comment]
Provide a larger selection of data and we will review further. Also, be more specific with your testing methodology. It wasn't clear you were dueling, nor is it clear whether those abilities were in that combat log before testing. Was the RP doing anything aside from healing? Were your abilities affected by tactics or buffs? Did your armor/weapon/jewelry selection have any procs attached to it? The combat system is very complex, you need to eliminate a dozen factors to get to a good base for testing, and then do a sufficient amount of repetition to eliminate false positives. Try 100 casts for each ability you're looking into.

This isn't closed because there isn't a problem, it's closed because there's insufficient data and the testing methodolgy is unknown.

**Comment by Zumos** [comment]
Do you expect us to write a full scientific report for every bug report? If the methodology wasn't clear you could have simply asked whether we controlled for all other variables instead of immediatly closing the issue. Meanwhile you could expect that the test wasn't done by retards and we did control for all other variables. Also I'm quite interested how a BW and an AM can attack a RP when not dueling?

And I don't understand how you can keep saying this is insufficient data. So to prove my point I did the Chi-Square test: 
![statistical testing disrupt rate](https://cloud.githubusercontent.com/assets/19267650/25521537/4c9a26d8-2c00-11e7-93ee-368f62ec2eaf.png)

With a p-value of 0.011 the conclusion is that there indeed is a significant difference between the disrupt rate of fireball and of ignite.
