### ISSUE TITLE
Malachia attacking and getting killed by invisible NPC

### ISSUE THREAD

**Issue by lawfol** [WarEmu/WarBugs#9529]
Three times in a row now Malachia gets into combat with some NPC hidden in the ground (at least it lookslike it,the wyvern attacking something in the ground). Malachia gets killed pretty easy,but the quest is still unfullfilled.

**Comment by Lheana** [comment]
In real Malachia is killing himself, I don't know how exactly but he does and it is not possible to loot him and he does not give the kill for the quest. I think he is doing auto-damage during the fight, that's why we can't loot and have the kill. Here is a ss that shows he is killing himself.
![anaehll_361](https://cloud.githubusercontent.com/assets/11537611/25591656/b14780be-2eb5-11e7-8122-1b4e3c03e659.jpg)
The ss is in french but 'Malachia a tué Malachia' means 'Malachia has killed Malachia'.

**Comment by Torquemadra** [comment]
try now, as in from this time onwards, not last week or 5 minutes ago

**Comment by Tesq** [comment]
malachian killed himself again 3 times today

**Comment by Torquemadra** [comment]
fixed
