### ISSUE TITLE
Double quests Nordland RvR Camp

### ISSUE THREAD

**Issue by Aloysiusr** [WarEmu/WarBugs#963]
Hello guys,

Now, I'll have to excuse myself, because I don't have many informations about my bug : the thing is, it is related to a quest whose name I cannot neither remember nor find in game.

I know that this quest is one of the, for the moment, simple ones that only needs you to speak to a person, so basically you say "accept quest" and instantaly speak again with the giver and the quest is completed. I think I remember that those quests where originally about scouting places or taking over RvR objectives.

Now I came across one of those quests, given by one of the giver on the left when you enter Nordland Camp from the non-RvR zone, near that big repetition canon and the rally master. There is a lady and another man, on the left, who gives this kind of quests. I cannot remember which one of them gave me two times the same quest.

I know that they both, or so, gives several quests which are actually completed in the same way as we're in Alpha, but still there was a doubled. So I just wanted to point it out to you.

Sorry for being so long, I hope I presented it the right way and as comprehensible as possible.

Abridged version : quest giver on the left of non-RvR entrance of Nordland camp gives two times the exact same quest.

Thanks for your job men

**Comment by Evildoor** [comment]
If i understand correctly, this is about quest named "Faces of War". There were 3 instances of this quest: two of them were repeatable: kill 1 Destro player, third one was to go and use an object in Nordland RVR. First one and third one were given by same NPC. At some point in the past first and second quests were removed to normalize amount of kill quests between Order and Destruction. Dunno about the third one, but that quest alone should be fine, since others with same name were removed. Closing unless someone points out that i've mistaken.
