### ISSUE TITLE
[Ironbreaker][Abilities] Tactic Furios Reprisal

### ISSUE THREAD

**Issue by joschika77** [WarEmu/WarBugs#9708]
Hi guys, is it possibile that the tactic "Fusios Reprisal", Path middle, does'nt work. Yesterday i checked this tactic in a enemy. Can you take a look? Thanks 👍

**Comment by Torquemadra** [comment]
nope, you test and report, dont have time to check everything on the offchance.

**Comment by joschika77** [comment]
Ok, i mean the tactic does'nt work. I checked this yesterday with a friend.

**Comment by Luth-RoR** [comment]
Strange, with .getstats it shows _Cooldown 5000 [(0 + 5000) x 1]_ so it should work i guess.
Didn't test it vs a player though.

**Comment by joschika77** [comment]
Hi Luth,

unfortunately I did'nt tested .getstats
Usally you should be able to see it visually, its a debuff. Tonight I will test it again with .getstats on the enemy

regards

**Comment by Luth-RoR** [comment]
It showed a 5 second debuff icon on the NPC, same as the ability icon iirc; it's not a tactic symbol.

**Comment by joschika77** [comment]
Ok?!? Its Not the same like "punishing knock"?
In this example you can see the tactic icon. Hmmm...

**Comment by Luth-RoR** [comment]
I just checked it again and "furious reprisal" has a definite bug:
When the tactic is equipped, the knockdown debuff icon changes to _5 seconds_ instead of creating a separate debuff from the tactic; this means that the immunity timer caused by the knockdown changes from 30 seconds to 50 seconds; the target is still knocked for _3 seconds_.

Without the tactic:
![20170522205733_1_crop](https://cloud.githubusercontent.com/assets/8567481/26324240/45caedc0-3f32-11e7-8361-495fa3a86646.jpg)

With the tactic:
![20170522205821_1_crop](https://cloud.githubusercontent.com/assets/8567481/26324259/5b010ada-3f32-11e7-8127-3891522012b6.jpg)

Maybe the debuff was bound to the knockdown ability icon to disallow stacking with slayer "shatter limbs"'(tactic+ability); in case it was like that, it made this mediocre* tactic useless.

*mediocre, because 3 second knockdown + 2 seconds increased cooldown duration after getting up again (in most cases).

**Comment by joschika77** [comment]
Luth,

thanks for your effort. Nice Support xD
I found this in the Original Warhammer book. Sadly in German xD "Schild des Vergeltungsschlag steigert die Abklingzeiten des Ziel für 10s um 5s"
Was the tactics already nerfed on the Live Server? It's too long ago, i don't know.

regards

**Comment by Luth-RoR** [comment]
I don't remember; the german tooltip could be also wrong.
