### ISSUE TITLE
ToK unlock 'For Once it Isn't Guano'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9712]
This bestiary unlock for Giant Bats should be triggered by collecting one 'Bat Wing' on 'Leatherwing Bats' or 'Blighted Leatherwings' in Troll Country around 15k 48k/11k 38k. Once the 'Bat Wing' collected:

- Destruction chars should talk to Voxanna the Transmuter in Felde in Troll Country (11k 60.3k).
- Order chars should talk to Brenard the Alchemist in Felde Castle in Troll Country.

These giant bats correctly drop 'Bat Wing', but talking to Voxanna or Brenard does not provide the unlock.

Note: The alternative in Marshes of Madness, consisting in killing Neborhest Bat, correctly works.

**Comment by Lheana** [comment]
Fixed

**Comment by Lheana** [comment]
Blighted Leatherwing will now also drop Bat Wing.

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Lheana [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UAHICGEFGCMMBJMRSD5ZAHQABIKMVQAM5FNYBLKUIH63ORCYRTBKBLXUKTYPT6C22EHKSQK5QG6EFXC4VTFCSC7AE4MEYFOZAGELQ2UYYSIFJAALARBQAB6AB3QATYADMAA6AC3AZXQMBPGAVTAJLGMAYLUUNJIRACAIAAEA======@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 08:25:35 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp c10si1562790ybb.320 - gsmtp:
    retry timeout exceeded
