### ISSUE TITLE
Set bonus proc chances remain after switching item set pieces via "closet goblin" addon

### ISSUE THREAD

**Issue by Kubzes** [WarEmu/WarBugs#9720]
Everything is in the Video: 

I used ClosetGoblin addon for changing the Equipment

[VIDEO](https://www.youtube.com/watch?v=Ue5PifdPzUc&feature=youtu.be)

**Comment by Torquemadra** [comment]
Write the issue out

**Comment by Luth-RoR** [comment]
Maybe related: https://github.com/WarEmu/WarBugs/issues/1636

**Comment by Torquemadra** [comment]
unable to replicate

require information including full loadouts

**Comment by Kubzes** [comment]
So UPDATE: On my chosen firstly use FULL beastlord set, which 6th bonus give me 10% to reduce enemy's armor for X value. When I switch my set to the FULL ruin, the 6th bonus from beastlord set should have disapeared. It didn't happened. It still's apply the debuff on the enemies with the same proc.

For changing of the eq i've used Closet Goblin addon.

What else do you need me to post ?
Greetings.

**Comment by Torquemadra** [comment]
rest of the loadout please

**Comment by Pxl555** [comment]
I tried this aswell on my BG, i used 5pc devastator for the taunt proc (i only had those 5 pieces in cg) and swaped back to normal set (4pc beastlord 2pc merc 3pc dominator) - taunt proc still remained.

I tried to see how extreme the bug is so i stacked 3 different set bonuses on my SW:
![buggers](https://cloud.githubusercontent.com/assets/17297910/26511443/573649be-4262-11e7-868a-8c71fe2aeae3.png)

What you see here is creeping, dominaton and marked on 1 enemy target (impossible under normal conditions)
I first swapped into 5pc conq for marked , then i used devastator for domination and i stayed in duelist for creeping) no other item's where present appart from the bow.

It was slightly inconsistent of wheater it starts working or not (also hard to get all of them to proc at the same time ) but it can be done as show'n by the screenshot
Further testing showed that only proc's seem to be affected, not stat setbonuses nor the +1 mastery ( i did this in a quick round of testing but i assume it should be consistent for other bonuses aswell). Overall it felt pretty abusable as some t3 proc's are still fairly relevant even in t4 ( cast speed proc's , slow proc's, redundancy for stat's , and conq/domi for tanks felt a little bit outrageous - there's probably some silly combination's possible)

**Comment by Luth-RoR** [comment]
Just to be 100% sure that it is not just visual (only the buff/debuff icons): do the buffs/debuufs have a real effect (e.g. in .getstats or the cast time reduction)?

**Comment by Kubzes** [comment]
Yes It does. I tryed that when Dueling with my Guildmate. It still lowers the Armor stat AFTER changing to NON-bonus set. 100% Confirmed

**Comment by Luth-RoR** [comment]
K, thanks a lot.

**Comment by Natherul** [comment]
@Kubzes could you please contact me over discord or pm on the forum? I would like to get some more information

**Comment by Natherul** [comment]
forgot to close this, its now fixed
