### ISSUE TITLE
Damage modifiers don't affect DoTs cast beforehand

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#973]
E.g. on tank if you dot someone and then taunt them, there's no change to the damage of each dot tick. Same if you dot someone then buff your strength.

Related to 3rd point in my post in this report: https://github.com/WarEmu/WarBugs/issues/936, so guess it applies to all modifiers.

Edit: Haven't tested this but it's worth checking whether it works for dmg reduction abilities as well. E.g. whether detaunt reduces dmg from DoTs that were cast on you beforehand.

**Comment by milosxe** [comment]
Detaunts don't decrease dmg from dots applied before the detaunt even though they should.

**Comment by magter3001** [comment]
Same thing goes with the Morale 2 of physical range dps, the one that increases damage by 100%. The damage is supposed to be 100% for only 7 seconds total but engineers can abuse the morale and have all their AoE dots to do 100% damage for the dots entire life cycle, like 21 seconds for one of their AoEs and 15 seconds for the other when it's only suppose to effect them for 7 seconds.

Also Taunt works incorrectly the same way.

So de-taunt, taunt, and any and every damage modifier as far as I know so that might include choppas and slayers as well with their mechanic. The modifiers are suppose to increase damage or reduce damage for every ability that is currently being used, and suppose to go back to the normal amount as soon as the modifier time ends.
