### ISSUE TITLE
Ram exploit

### ISSUE THREAD

**Issue by CoffeeForAll** [WarEmu/WarBugs#9730]
The ram can be operated outside the area of effect of oil defenses. This is being deliberately used as a "tactic" by the vast majority of players on both factions at t2/3 keeps. I do not know if the same happens in t4.

**Comment by cimator** [comment]
For destro t4, it is same at dwarf and empire keeps, iirc you cant get out of oil range on elf keeps due to towers next to door.

**Comment by wargrimnir** [comment]
This was fixed.

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "wargrimnir [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UBDNICSFY6AOZABYQGNEABKNTVEAHZGYABLLSI7NPHWBR2FPBRD2DRDJITABUAMPVEAODBMEHHYO2GMRAGJOCGNFR4ORKEBK2ESQQKZAACKIKBEARVAJYYERMCCOBALASTRAC2WAHYAC4AAXWEKRS7F4BCIABAAAQA====@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Mon, 12 Jun 2017 16:13:27 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.26]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp j3si2387039ywk.186 - gsmtp:
    retry timeout exceeded
