### ISSUE TITLE
High Elf Chapter 10 PQs bugged

### ISSUE THREAD

**Issue by MrRedKnox** [WarEmu/WarBugs#9764]
Hello,
I was doing the High Elf Ch. 10 PQs when I noticed that there were a few bugs, some more major then others. Firstly, the Slash and Burn PQ next to the entrance portal to the zone is severely bugged, as the counter does not work at all, and after the first stage nothing happens (See Slash and Burn 0, & 1). Secondly, the Rotten Embrace PQ suffers similar problems, as the counter does not work (it stays stuck on Stage 1), it does go to the other stages, but there is no reward at the end (See Rotten Embrace 0,1,2, & 3). Lastly, the Ritual of Corruption PQ counts every single kill for each category, e.i. you kill a sentinel and it counts for the sentinel, acolyte, and witch (See Ritual of Corruption). Furthermore, it has to be disclosed that I did not finish the Ritual of Corruption as I ran out of time and had to go.

I hope this was to any help, and that I put it in the right spot. Moreover, I sincerely hope this format is not confusing for the developers.

Best Regards, Asusia

Attachments
Slash and Burn 0: https://cloud.githubusercontent.com/assets/29195802/26778375/4cddc114-49e1-11e7-8451-ef28b5106d60.jpg
Slash and Burn 1: https://cloud.githubusercontent.com/assets/29195802/26778377/50685164-49e1-11e7-9234-cf01149fe58f.jpg
Rotten Embrace 0: https://cloud.githubusercontent.com/assets/29195802/26778507/d6dd7544-49e1-11e7-88d7-052c7ac93be9.jpg
Rotten Embrace 1: https://cloud.githubusercontent.com/assets/29195802/26778508/d6de9744-49e1-11e7-9fe3-529856875a92.jpg
Rotten Embrace 2: https://cloud.githubusercontent.com/assets/29195802/26778509/d6e0f796-49e1-11e7-96fb-466551f313f2.jpg
Rotten Embrace 3: https://cloud.githubusercontent.com/assets/29195802/26778510/d6e13670-49e1-11e7-8901-f46741246530.jpg
Ritual of Corruption: https://cloud.githubusercontent.com/assets/29195802/26778622/58968f26-49e2-11e7-95f3-8198fd485c4a.jpg

**Comment by Luth-RoR** [comment]
Thanks, but the stuck PQ UI is known: https://github.com/WarEmu/WarBugs/issues/6935
I post and reopen the Ritual of Corruption part here: https://github.com/WarEmu/WarBugs/issues/5599 as several bugs, or in this case PQs, per report is not useful (report need to be closed when fixed).

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "MrRedKnox [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UAHLTHKEAIYRBGDCABHIBTEBLIWBR5ICLBYVQI6FVKUEJRA2HTODBIOUACSUOZFIZABBQE2IECEGQHFNARCKDIPQZ5YYMSKWICEYBTQRZ2AACKBEVAAPIALFAEKQBLIASUAS2DGVESA6ZALMQC4NLSLAVFSHFEAQQAAIA=@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 02:44:23 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp o69si1483352ybg.330 - gsmtp:
    retry timeout exceeded

**Comment by Luth-RoR** [comment]
That's a very cool story.
