### ISSUE TITLE
Replacing a talisman to no success

### ISSUE THREAD

**Issue by GloomySam** [WarEmu/WarBugs#9765]
I tried to improve my Crimson cloak yesterday. It had a +16 str tali in it, the other slot was empty. I got a +20 wounds and a +20 str talisman, put the wounds in the empty slot and fused it OK, then put the +20 str instead of the +16 and fused, but the added strength value remained +16. I then tried to replace the strength talisman with willpower - just to see what would happen, and put a +20 WP talisman in its place - it now turned into +16 willpower.
So it seems like the slot will not go above +16 no matter what i put in there.

**Comment by Torquemadra** [comment]
works fine for me, placed a Minor Talisman of the Gladiator (lvl 16) then overwrote it with Talisman of the Gladiator (lvl 20) then overwrote that with Lesser Talisman of the Gladiator (lvl 12)

**Comment by nailinthehead** [comment]
Just wanted to write it happened to me as well. 
Beginning state: Had two +18 str and ws talis in a great hammer. 
Chain of events: 
1. Replaced one tali with armour and second one with + 18 ini. Armor got fused ok, ini did not fuse and ws one remained in the slot, although ini tali disappeared from my bag. 
2. Then I took +22 ini and attempted to replace the ws tali again. Unfortunately after fusing the ws tali turned into +18 ini and the +22 one disappeared from the bag. 
3. In order to test it further I replaced the +18 ini one with +12 wounds tali, hoping it will turn into the +22 ini I lost, but it fused ok. So I had +124 armour and +12 wounds talis in the weapon.
4. Replaced wounds tali with +18 ini and it fused ok again.

Summary: looks like there's some problem with refreshing second slot with new tali in two-slots gear after replacing both talismans at once or in a short span of time.
