### ISSUE TITLE
Backpack/Apot window

### ISSUE THREAD

**Issue by Jokerloz** [WarEmu/WarBugs#9770]
The Items in my bag I can't click or but bottles in my window to create pot's . i have /rel several times in the end i had to /q.  after the 2nd bag so bags 3 and 4.

**Comment by Luth-RoR** [comment]
Please read the bugtracker rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
Particularly these parts:
2. Verify that it's not been posted before.
8. Use the relevant keywords and spell them correctly. 
9. Ensure you can use English to a respectable standard.

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Luth [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAIZEA3ICGEMMZIIBJIAXDCIRZWUNGKAPZJHVEA5QGCYLIAMNGKVXHETRTQZWOKOLIDB2SKAAGQBDUCF2AOKBHZNJVOIJQMYGJMIXBRKBXEN6CAAWBCDAAD4ADXABHQAGYAB4AFWBSPRYC6MBLGASWM2LBMRRYCAJAAAQA====@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 08:43:20 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp z195si1573202ywa.200 - gsmtp:
    retry timeout exceeded

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Luth [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UAZYCOLACIADXAHMQBYNADQAFOMI4KNNEEJBCHQ4AIMACGNVZUFZROKI4GIRC3CN2WKYAMRZQL4MFBANHG5WCEYYIDIVPNCIXAXKBUVQBTYABFEFASAI2QE4MCIWBBHAQFQJJYQJPLAD4ABOAAL3CNJ5CWKYYAICQAAIA=@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 08:53:18 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.26]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp q72si1583843ywg.93 - gsmtp:
    retry timeout exceeded
