### ISSUE TITLE
Nerx Gutslime

### ISSUE THREAD

**Issue by zageen** [WarEmu/WarBugs#9771]
There is many problème that occure on this boss:
1- the 75% dmg réduction : The boss apply/refresh this buff on him every 15 sec , this is a blessing , but cannot be removed
2-Healing buff : The boss has a buff that make him healing each time he defend an attack , this buff simply doesn't work
3-His dmg : This boss make abnormal dmg, compared to other bosses that we down this afternoon , mix high physical (like other bosses) AND high magical dmg ( 800/tick on 50% reduction , so 1600/tick , 1 tick every 1 sec)

We did this boss with 4 ppl (2 heal , 1 dps , and me as a tank)

You can spec my stat on Zag (+shamy and chosen resist buff)

Hope it help to make pve great again !

All other bosses where really too easy ... , but that is another thing ^^

**Comment by Luth-RoR** [comment]
First issue is known: https://github.com/WarEmu/WarBugs/issues/9746
About 2. and 3.: I don't think that this boss is meant to be killed with 4 players and other groups managed to kill him.

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Luth [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAIZEAJ2KG3MADYAJZFCTRKILMIADFABXCC3NDMMATWVAIMDYIBLTTBZAA5R5DYNCKFLKSDQLAWYQVCMJ6MT4RIUBR6RGGYIOGLTLARDCDSR2CABLCEFQAHQAHKACNAAMQADIALEDE2MQD4YBWMAVUZJSVUJHOEARAAAQA====@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 13:14:27 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp y129si1633063ybf.38 - gsmtp:
    retry timeout exceeded
