### ISSUE TITLE
Eataine BO capping issue

### ISSUE THREAD

**Issue by raptrr** [WarEmu/WarBugs#9778]
You can capture the Utorin Siege Camp in Eataine with one of the Gaurds still alive.
At least a Wh just did it in front of me, as I pulled the last guard, standanding far away from flag

got it on a short video clip as well

https://youtu.be/S1Lj2S04i00

(sorry for bad quality)

**Comment by Luth-RoR** [comment]
Known and merging with https://github.com/WarEmu/WarBugs/issues/9536

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "raptrr [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UA3IZYERRDY3NTIBDQ4LAD2ACIKJLGBSEANCCFEEWCGGQTCVUFKAAASNMCMGLSK7XGQSSMZIEQMBFKBCEGXVRAPAMLYVKCBWGDEQSGCMNJEVICAVQAA5ASGQAFUAETABVQANYAFMAHOBS3CEQXMIJWEAXIICFFCUWEMYQCEAACA===@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Mon, 12 Jun 2017 17:47:48 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.26]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp p124si2399234ybb.111 - gsmtp:
    retry timeout exceeded
