### ISSUE TITLE
Cooldown Bug after zone change

### ISSUE THREAD

**Issue by raptrr** [WarEmu/WarBugs#9779]
I just flew from Eataine to Dragonwake and got this bug:

![rondul_012](https://user-images.githubusercontent.com/27915421/26857533-710792f4-4b2b-11e7-9a03-4d255aba2660.jpg)

Cannot cast any spell. Mounting works and 2 abilitys - morale affacted as well.
Others are on cooldown, which is kinda long :D

Logout not possible as well

**Comment by Luth-RoR** [comment]
Fixed: https://returnofreckoning.com/forum/viewtopic.php?t=21642&p=239445#p239421

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "raptrr [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UAJYBTEMMCKM2IKCQUNJADQMLIEXKJDLCQ3E2M2YAVSWNZIRSB6QDHA4A3KACDAPFBS5QE2JYOKRZVGEWUCVIRHBSS4MSAOEJXAIDQJADYAABVASSQALSAHRQDEYBFMARGANLBVJWKAPNAFWQBOUQZE4HDKAPBMERAAIAAEA======@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Mon, 12 Jun 2017 17:47:41 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.26]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp x66si2469114ywa.187 - gsmtp:
    retry timeout exceeded
