### ISSUE TITLE
[Orc's weapons]

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#978]
Is it correct?
![gorilla_019](https://cloud.githubusercontent.com/assets/12655727/8683852/dbe6b062-2a7d-11e5-94bf-5d5c0f3ae2b4.jpg)
![gorilla_020](https://cloud.githubusercontent.com/assets/12655727/8683861/e2a9c92a-2a7d-11e5-9654-cc02a93c6423.jpg)
![gorilla_025](https://cloud.githubusercontent.com/assets/12655727/8683867/e7106adc-2a7d-11e5-88a8-60d7846187bd.jpg)

**Comment by Evildoor** [comment]
It seems that these are a bunch of different problems.
1) Blighted Slayer should have 26 STR instead of 52 - similar weapons for Slayer and DoK, for example, only give 26 stats. The same goes for another chaos axe, Slayer of the Wicked, which gives 26 STR and 26 WS.
2) Some weapons have slightly worse stats than their analogues, like here or in this issue(dunno why it was closed, as far as i remember the stats are still wrong):
https://github.com/WarEmu/WarBugs/issues/654
3) Chosen with duals - no idea.

**Comment by wargrimnir** [comment]
Corrected stats on these
