### ISSUE TITLE
Quest - Battle for Dragonwake

### ISSUE THREAD

**Issue by Fractus1484** [WarEmu/WarBugs#9806]
New kill quests, Battle for Dragonwake, i have completed this as per screenshot, but all NPC's at the 4 different BO's in Caledor do not complete the quest.

I go very close to the NPC, right click, left click, anything, does nothing, quest is not able to be completed
![talitus_121](https://user-images.githubusercontent.com/26185873/27043954-c7a2734c-4f93-11e7-8b82-10523091a204.jpg)
,

Thanks,

**Comment by vianiznice** [comment]
For some reason you get quest credit even when being in different zones. The quest seem to complete but you can't hand it in. Also, it ruins all the other quests so you can't get progress on already active quests, nor pick new ones up.

**Comment by lawfol** [comment]
Gtoother Conqueror medalion quests completed...Iam not able to give in any. Battle for Dragonwake, Battle for Praag, Battle for Thunder Mountain, Secure Eataine.

Havent completed the other two s"secure"quests yet...The Conquer quests I completed all last 2 days and worked fine....but their end point is in altdorf.

**Comment by Oreas** [comment]
All the Conqueror Quest NPCs in the RvR-Lakes seem to be buggy.
It is not possible to obtain the Quests or turn them in
Secure Kadrin Valey/Reikland/Eataine
Battle for Thunder Mountain/Praag/Drabonwake
It is not possible to obtain the Quests from NPC (Keep Lord)
Conquest of Black Craig/Chaoswastes/Caledor 
The last three can be turned in at Altdorf Palace

As far as i noticed, these bug appeared when the buggy Thunder Mountain Quest was fixed. (The quest did not work because Order was supposed to kill Order Characters. After the fix, the quest itself worked, but could never be turned in.)

**Comment by Fractus1484** [comment]
The hand in for this quest now works after yesterdays boot/fix, tested in Caledor and Chaos Wastes, both worked, thank you!

**Comment by Oreas** [comment]
Seems to be bugged again
