### ISSUE TITLE
Scenario party bug

### ISSUE THREAD

**Issue by ShlomoSheckelberg** [WarEmu/WarBugs#992]
Cannot join any group in a scenario, can't get guard, and get group heals. Very frustrating and it seems to be random.

**Comment by Tyramissoux** [comment]
You can work around that problem by joining an empty party. All the other players are suddenly displayed and you can join a proper one. Though, be advised to be careful with parties with only one spot left as they are most likely to get you back to group bug because there's a member in this party who isn't visible so that the party is actually full.

**Comment by Radiantknight** [comment]
Actually it is better to look in the chat to see if party is full, there is a notification for that, even if you don't see anyone in party.
But it's kinda annoying bug nonetheless

**Comment by Soulwhisper** [comment]
This one is fixed.Remember that one...! @Luth-RoR
