### ISSUE TITLE
Double seal of the paragon

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#9987]
I don't know wether this is a new change or if it is intentional, but I just got 2 seals of the paragon from zonelock, then 2 in the mail right after. A total of 4 seals, I'm pretty sure it was not more than 100% AAO. 
I was in SC during zonelock, so that might be a reason; being out of zone?

**Comment by thorbolt80** [comment]
You should be in defense with aao so... it's normal.

**Comment by rekkir** [comment]
Additional aao seals don't come in mail!

**Comment by Razielhell** [comment]
Oh yes they do.

**Comment by anarchypark** [comment]
I can confirm this Seal of Paragon double bug.
![seal_bug](https://user-images.githubusercontent.com/19988772/29133819-a5e2b3b6-7d6f-11e7-8423-1d04d3eaaee6.jpg)
I missed screenshot of inside of mail. there were 2 officer medals and 1 seal of paragon.

you get seals when zone locked, no matter where you are.
it goes directly into your currency bag.
and you get exact same amount of seals from mail 
if you were in SC when timer of reward chest expired.
aao is not related to this bug. screenshot is when I won zone.

I had experienced this once and tried to reproduce this bug by joining SC when zone is almost locked.
if chest popped on your screen inside of SC but you got out of it before timer of chest expired
mail is not sent.
or mail is not sent because I didn't earn single officer medals at that time.

sry my english.
bug is you getting seal from mail and directly both, in some situation.
that situation is when you were in SC.
